/* Speak or Boom — Airport scenario: Check-in to Takeoff */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.airport = {
    id: 'airport',
    title: 'Airport',
    tagline: 'Check-in to Takeoff',
    speaker: 'AGENT',
    difficulty: 'Intermediate',
    rounds: [
      // ---------- Chapter 1: Arrival at the Terminal ----------
      { id: 'airport-001', chapter: 'Arrival at the Terminal', agent: 'Welcome to the international terminal. How can I help you today?', user: "Hi, I'm flying to Tokyo this morning.", keywords: ['tokyo', 'morning'] },
      { id: 'airport-002', chapter: 'Arrival at the Terminal', agent: 'The departure hall is on level three. Do you need directions?', user: 'Yes, please. Where is the check-in area?', keywords: ['check', 'area'] },
      { id: 'airport-003', chapter: 'Arrival at the Terminal', agent: 'Which airline are you flying with today, sir?', user: "I'm flying with Air China, flight CA 1837.", keywords: ['china', '1837'] },
      { id: 'airport-004', chapter: 'Arrival at the Terminal', agent: 'That flight departs at nine forty from gate B twelve.', user: 'My flight is CA 1837 at nine forty.', keywords: ['flight', 'forty'] },
      { id: 'airport-005', chapter: 'Arrival at the Terminal', agent: 'Your airline uses Terminal Two. This is Terminal One.', user: 'Oh no. How do I get to Terminal Two?', keywords: ['terminal', 'two'] },
      { id: 'airport-006', chapter: 'Arrival at the Terminal', agent: 'Take the free shuttle bus outside exit number four.', user: 'The shuttle bus is outside exit four, right?', keywords: ['shuttle', 'exit'] },
      { id: 'airport-007', chapter: 'Arrival at the Terminal', agent: 'Yes. It runs every ten minutes, around the clock.', user: "Great. I'll catch the next shuttle bus.", keywords: ['next', 'shuttle'] },
      { id: 'airport-008', chapter: 'Arrival at the Terminal', agent: "Do you need a luggage trolley? They're over there.", user: 'Yes, I need a trolley for my suitcase.', keywords: ['trolley', 'suitcase'] },
      { id: 'airport-009', chapter: 'Arrival at the Terminal', agent: 'Trolleys cost two dollars. Coins or card only.', user: 'Can I pay for the trolley by card?', keywords: ['trolley', 'card'] },
      { id: 'airport-010', chapter: 'Arrival at the Terminal', agent: 'Of course. Just tap your card on the reader.', user: 'Thanks. Now where is the departure board?', keywords: ['departure', 'board'] },
      { id: 'airport-011', chapter: 'Arrival at the Terminal', agent: 'The big screens are above the information desk.', user: 'I can see my flight on the screen.', keywords: ['flight', 'screen'] },
      { id: 'airport-012', chapter: 'Arrival at the Terminal', agent: 'Check-in opens three hours before your flight.', user: "I'll head to the check-in counters now.", keywords: ['check', 'counters'] },
      // ---------- Chapter 2: Check-in Counter ----------
      { id: 'airport-013', chapter: 'Check-in Counter', agent: 'Good morning. May I see your passport and booking reference?', user: 'Here you are. My booking reference is X T seven K.', keywords: ['booking', 'reference'] },
      { id: 'airport-014', chapter: 'Check-in Counter', agent: 'Thank you. Are you checking in any bags today?', user: "Yes, I'd like to check in one suitcase.", keywords: ['check', 'suitcase'] },
      { id: 'airport-015', chapter: 'Check-in Counter', agent: 'Please place your bag on the scale, screen side up.', user: "It's quite heavy. I hope it's under twenty kilos.", keywords: ['heavy', 'kilos'] },
      { id: 'airport-016', chapter: 'Check-in Counter', agent: "Twenty-three kilos. That's just over the limit.", user: 'Oh no. How much is the extra charge?', keywords: ['extra', 'charge'] },
      { id: 'airport-017', chapter: 'Check-in Counter', agent: "It's thirty dollars per extra kilo, I'm afraid.", user: "That's fine. I'll pay the extra fee.", keywords: ['pay', 'fee'] },
      { id: 'airport-018', chapter: 'Check-in Counter', agent: 'Would you like a window or an aisle seat?', user: 'A window seat, please, near the front.', keywords: ['window', 'front'] },
      { id: 'airport-019', chapter: 'Check-in Counter', agent: "I've put you in seat fourteen A. Is that okay?", user: 'Fourteen A sounds perfect. Thank you.', keywords: ['fourteen', 'perfect'] },
      { id: 'airport-020', chapter: 'Check-in Counter', agent: "Here's your boarding pass. Boarding starts at nine.", user: 'What time does boarding start, sorry?', keywords: ['boarding', 'start'] },
      { id: 'airport-021', chapter: 'Check-in Counter', agent: "Boarding starts at nine o'clock, gate B twelve.", user: 'Gate B twelve. Got it. Thank you very much.', keywords: ['gate', 'twelve'] },
      { id: 'airport-022', chapter: 'Check-in Counter', agent: "You're in boarding group three. Listen for the announcement.", user: "I'm in group three. I'll wait for the call.", keywords: ['group', 'three'] },
      { id: 'airport-023', chapter: 'Check-in Counter', agent: 'One last thing — any power banks in your hand luggage?', user: 'Yes, my power bank is in my backpack.', keywords: ['power', 'backpack'] },
      { id: 'airport-024', chapter: 'Check-in Counter', agent: "That's fine. Keep it with you, not in checked bags.", user: "Understood. I'll keep it in my backpack.", keywords: ['keep', 'backpack'] },
      // ---------- Chapter 3: Baggage Drop ----------
      { id: 'airport-025', chapter: 'Baggage Drop', agent: 'Baggage drop for Air China is at counters thirty to forty.', user: 'Where is the baggage drop for Air China?', keywords: ['baggage', 'drop'] },
      { id: 'airport-026', chapter: 'Baggage Drop', agent: "Follow the signs. It's just past the check-in hall.", user: "I can see the signs. I'll follow them.", keywords: ['signs', 'follow'] },
      { id: 'airport-027', chapter: 'Baggage Drop', agent: 'Please have your boarding pass ready for scanning.', user: 'My boarding pass is ready on my phone.', keywords: ['boarding', 'phone'] },
      { id: 'airport-028', chapter: 'Baggage Drop', agent: 'Scan it here, then put your bag on the belt.', user: "The scan worked. Now I'll lift my bag up.", keywords: ['scan', 'bag'] },
      { id: 'airport-029', chapter: 'Baggage Drop', agent: 'The tag is printing. Please attach it to the handle.', user: 'Where should I attach this luggage tag?', keywords: ['attach', 'tag'] },
      { id: 'airport-030', chapter: 'Baggage Drop', agent: 'Loop it through the top handle, nice and tight.', user: "It's attached. The tag feels secure now.", keywords: ['attached', 'secure'] },
      { id: 'airport-031', chapter: 'Baggage Drop', agent: 'Is anything fragile inside? We can add a sticker.', user: "Yes, there's a bottle of wine inside.", keywords: ['bottle', 'wine'] },
      { id: 'airport-032', chapter: 'Baggage Drop', agent: "I'll mark it fragile. It'll be handled with care.", user: 'Thank you. Please handle it with care.', keywords: ['handle', 'care'] },
      { id: 'airport-033', chapter: 'Baggage Drop', agent: 'Keep this claim receipt until you land in Tokyo.', user: "I'll keep the receipt until I land.", keywords: ['receipt', 'land'] },
      { id: 'airport-034', chapter: 'Baggage Drop', agent: 'You can track your bag in the airline app.', user: 'Can I track my bag in the app?', keywords: ['track', 'app'] },
      { id: 'airport-035', chapter: 'Baggage Drop', agent: 'Yes. Just enter the tag number on your receipt.', user: "I'll enter the tag number right now.", keywords: ['tag', 'number'] },
      { id: 'airport-036', chapter: 'Baggage Drop', agent: "All done. Your bag is on its way to Tokyo.", user: "Great. Now I'm heading to security check.", keywords: ['security', 'check'] },
      // ---------- Chapter 4: Security Check ----------
      { id: 'airport-037', chapter: 'Security Check', speaker: 'OFFICER', agent: 'Have your boarding pass and ID ready, please.', user: 'My boarding pass and passport are ready.', keywords: ['passport', 'ready'] },
      { id: 'airport-038', chapter: 'Security Check', speaker: 'OFFICER', agent: 'Place all bags and trays on the belt.', user: "I'll put my backpack in a tray.", keywords: ['backpack', 'tray'] },
      { id: 'airport-039', chapter: 'Security Check', speaker: 'OFFICER', agent: 'Laptops must go in a separate tray, lid open.', user: 'My laptop is in a separate tray now.', keywords: ['laptop', 'separate'] },
      { id: 'airport-040', chapter: 'Security Check', speaker: 'OFFICER', agent: 'Any liquids? They must be under one hundred milliliters.', user: 'I have a small bottle of hand cream.', keywords: ['bottle', 'cream'] },
      { id: 'airport-041', chapter: 'Security Check', speaker: 'OFFICER', agent: 'That needs to go in the clear plastic bag.', user: "I'll put it in the plastic bag.", keywords: ['plastic', 'bag'] },
      { id: 'airport-042', chapter: 'Security Check', speaker: 'OFFICER', agent: 'Please remove your shoes and belt as well.', user: 'My shoes and belt are off already.', keywords: ['shoes', 'belt'] },
      { id: 'airport-043', chapter: 'Security Check', speaker: 'OFFICER', agent: 'Empty your pockets into the tray, please.', user: "My pockets are empty. Phone's in the tray.", keywords: ['pockets', 'empty'] },
      { id: 'airport-044', chapter: 'Security Check', speaker: 'OFFICER', agent: 'Step into the scanner and raise your arms.', user: "I'm stepping in with my arms raised.", keywords: ['arms', 'raised'] },
      { id: 'airport-045', chapter: 'Security Check', speaker: 'OFFICER', agent: 'All clear. You can collect your things now.', user: "Thank you. I'll collect my things now.", keywords: ['collect', 'things'] },
      { id: 'airport-046', chapter: 'Security Check', speaker: 'OFFICER', agent: "Don't forget anything in the trays behind you.", user: 'Let me double-check the trays behind me.', keywords: ['double', 'trays'] },
      { id: 'airport-047', chapter: 'Security Check', speaker: 'OFFICER', agent: 'Your watch set off the alarm. Please try again.', user: 'Sorry, I forgot to take off my watch.', keywords: ['forgot', 'watch'] },
      { id: 'airport-048', chapter: 'Security Check', speaker: 'OFFICER', agent: "No problem. You're good to go now.", user: 'Thanks for your help. Have a nice day.', keywords: ['help', 'day'] },
      // ---------- Chapter 5: Passport Control ----------
      { id: 'airport-049', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'Next, please. Passport and boarding pass.', user: "Here's my passport and my boarding pass.", keywords: ['passport', 'boarding'] },
      { id: 'airport-050', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'What is the purpose of your visit?', user: "I'm visiting Tokyo for a short holiday.", keywords: ['holiday', 'tokyo'] },
      { id: 'airport-051', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'How long will you be staying?', user: "I'll be staying for five days.", keywords: ['staying', 'days'] },
      { id: 'airport-052', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'Where will you be staying in Tokyo?', user: 'At the Park Hotel near Tokyo Station.', keywords: ['hotel', 'station'] },
      { id: 'airport-053', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'Do you have a return ticket?', user: 'Yes, I fly back on Sunday morning.', keywords: ['back', 'sunday'] },
      { id: 'airport-054', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'What do you do for a living?', user: "I'm an engineer at a car company.", keywords: ['engineer', 'company'] },
      { id: 'airport-055', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'Is this your first visit to Japan?', user: "Yes, it's my first time in Japan.", keywords: ['first', 'japan'] },
      { id: 'airport-056', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'Please look at the camera for a photo.', user: "Sure. I'm looking at the camera now.", keywords: ['looking', 'camera'] },
      { id: 'airport-057', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'Place your right index finger on the scanner.', user: 'My finger is on the scanner now.', keywords: ['finger', 'scanner'] },
      { id: 'airport-058', chapter: 'Passport Control', speaker: 'OFFICER', agent: "Everything looks good. Here's your passport back.", user: 'Thank you very much, officer.', keywords: ['officer'] },
      { id: 'airport-059', chapter: 'Passport Control', speaker: 'OFFICER', agent: 'How much cash are you carrying today?', user: "I'm carrying about three hundred dollars.", keywords: ['carrying', 'dollars'] },
      { id: 'airport-060', chapter: 'Passport Control', speaker: 'OFFICER', agent: "That's fine. Enjoy your stay in Japan.", user: "Thank you. I'm really looking forward to it.", keywords: ['forward', 'thank'] },
      // ---------- Chapter 6: Finding Your Gate ----------
      { id: 'airport-061', chapter: 'Finding Your Gate', agent: 'The information desk is right behind you, miss.', user: 'Excuse me, which way is gate B twelve?', keywords: ['gate', 'twelve'] },
      { id: 'airport-062', chapter: 'Finding Your Gate', agent: 'Gates B one to twenty are in the north pier.', user: 'The north pier. How do I get there?', keywords: ['pier', 'north'] },
      { id: 'airport-063', chapter: 'Finding Your Gate', agent: 'Follow the blue line on the floor.', user: "I'll follow the blue line on the floor.", keywords: ['blue', 'line'] },
      { id: 'airport-064', chapter: 'Finding Your Gate', agent: "It's about a fifteen-minute walk from here.", user: "Fifteen minutes? I'd better hurry up.", keywords: ['hurry', 'fifteen'] },
      { id: 'airport-065', chapter: 'Finding Your Gate', agent: "Or take the shuttle train. It's much faster.", user: 'Where can I catch the shuttle train?', keywords: ['shuttle', 'train'] },
      { id: 'airport-066', chapter: 'Finding Your Gate', agent: 'Down the escalator, then turn left.', user: 'Down the escalator and turn left. Thanks.', keywords: ['escalator', 'left'] },
      { id: 'airport-067', chapter: 'Finding Your Gate', agent: 'The train leaves every three minutes.', user: "Every three minutes. That's very convenient.", keywords: ['minutes', 'convenient'] },
      { id: 'airport-068', chapter: 'Finding Your Gate', agent: 'There are shops and cafés near gate B ten.', user: "I'd like to grab a coffee first.", keywords: ['grab', 'coffee'] },
      { id: 'airport-069', chapter: 'Finding Your Gate', agent: 'The coffee shop is next to the bookstore.', user: "A latte to go, please. I'm in a hurry.", keywords: ['latte', 'hurry'] },
      { id: 'airport-070', chapter: 'Finding Your Gate', agent: 'Restrooms are on your right, past the café.', user: "I'll use the restroom before boarding.", keywords: ['restroom', 'boarding'] },
      { id: 'airport-071', chapter: 'Finding Your Gate', agent: 'Free charging stations are by the windows.', user: 'I need to charge my phone quickly.', keywords: ['charge', 'phone'] },
      { id: 'airport-072', chapter: 'Finding Your Gate', agent: 'Gate B twelve is just around the corner.', user: 'I can see gate B twelve now.', keywords: ['see', 'gate'] },
      // ---------- Chapter 7: Boarding ----------
      { id: 'airport-073', chapter: 'Boarding', agent: 'Now boarding flight CA eighteen thirty-seven to Tokyo.', user: "That's my flight. I'll join the queue.", keywords: ['flight', 'queue'] },
      { id: 'airport-074', chapter: 'Boarding', agent: 'Please have your boarding pass ready.', user: 'My boarding pass is ready in my hand.', keywords: ['boarding', 'hand'] },
      { id: 'airport-075', chapter: 'Boarding', agent: "We're now boarding group three. Group three only.", user: "I'm group three. This is my turn.", keywords: ['group', 'turn'] },
      { id: 'airport-076', chapter: 'Boarding', agent: "The scanner didn't read it. Try holding it flat.", user: 'Let me hold my phone a bit flatter.', keywords: ['hold', 'flatter'] },
      { id: 'airport-077', chapter: 'Boarding', agent: 'There we go. Seat fourteen A, enjoy your flight.', user: 'Fourteen A. Thank you very much.', keywords: ['fourteen', 'thank'] },
      { id: 'airport-078', chapter: 'Boarding', agent: 'Your bag is too big for the cabin, sir.', user: 'Oh really? Can I check it at the gate?', keywords: ['check', 'gate'] },
      { id: 'airport-079', chapter: 'Boarding', agent: "Yes, we'll tag it and check it for free.", user: "That's kind. Please tag it for me.", keywords: ['tag', 'kind'] },
      { id: 'airport-080', chapter: 'Boarding', agent: 'Families with small children board first.', user: "I'll wait until they call my group.", keywords: ['wait', 'group'] },
      { id: 'airport-081', chapter: 'Boarding', agent: 'Priority boarding is through the left lane.', user: "I'll use the regular lane, thank you.", keywords: ['regular', 'lane'] },
      { id: 'airport-082', chapter: 'Boarding', agent: "Please keep your passport out until you're seated.", user: "I'll keep my passport out until I'm seated.", keywords: ['passport', 'seated'] },
      { id: 'airport-083', chapter: 'Boarding', agent: 'Welcome aboard. Your seat is on the left.', user: "Thank you. I'm happy to be aboard.", keywords: ['happy', 'aboard'] },
      { id: 'airport-084', chapter: 'Boarding', agent: 'Please stow your bag and take your seat quickly.', user: "I'll stow my bag and sit down now.", keywords: ['stow', 'bag'] },
      // ---------- Chapter 8: On the Plane ----------
      { id: 'airport-085', chapter: 'On the Plane', speaker: 'CREW', agent: "Please fasten your seatbelt. We're about to push back.", user: "My seatbelt is fastened. I'm ready to go.", keywords: ['seatbelt', 'fastened'] },
      { id: 'airport-086', chapter: 'On the Plane', speaker: 'CREW', agent: 'Tray tables up and seats upright for takeoff.', user: 'My tray table is up and locked.', keywords: ['tray', 'locked'] },
      { id: 'airport-087', chapter: 'On the Plane', speaker: 'CREW', agent: 'Would you like something to drink?', user: 'Just a glass of water, please.', keywords: ['water', 'glass'] },
      { id: 'airport-088', chapter: 'On the Plane', speaker: 'CREW', agent: 'Chicken or beef for your main course?', user: "I'll have the chicken, please.", keywords: ['chicken', 'have'] },
      { id: 'airport-089', chapter: 'On the Plane', speaker: 'CREW', agent: 'Do you have any food allergies we should know?', user: "No allergies, but I'm vegetarian, actually.", keywords: ['vegetarian', 'allergies'] },
      { id: 'airport-090', chapter: 'On the Plane', speaker: 'CREW', agent: 'We have a vegetarian meal available for you.', user: 'The vegetarian meal would be perfect.', keywords: ['vegetarian', 'perfect'] },
      { id: 'airport-091', chapter: 'On the Plane', speaker: 'CREW', agent: "More coffee or tea? We're doing a second round.", user: 'A cup of green tea, please.', keywords: ['green', 'tea'] },
      { id: 'airport-092', chapter: 'On the Plane', speaker: 'CREW', agent: "Would you like a blanket? It's getting chilly.", user: 'Yes, please. A blanket would be lovely.', keywords: ['blanket', 'lovely'] },
      { id: 'airport-093', chapter: 'On the Plane', speaker: 'CREW', agent: 'The entertainment system is in the seatback screen.', user: 'How do I turn on the movie screen?', keywords: ['movie', 'screen'] },
      { id: 'airport-094', chapter: 'On the Plane', speaker: 'CREW', agent: 'Please raise your window shade for landing.', user: 'My window shade is up already.', keywords: ['shade', 'window'] },
      { id: 'airport-095', chapter: 'On the Plane', speaker: 'CREW', agent: "We're expecting some turbulence. Please stay seated.", user: "I'll stay seated with my belt fastened.", keywords: ['seated', 'belt'] },
      { id: 'airport-096', chapter: 'On the Plane', speaker: 'CREW', agent: 'Thank you for flying with us today.', user: 'Thank you. It was a smooth flight.', keywords: ['smooth', 'flight'] },
      // ---------- Chapter 9: Customs & Immigration ----------
      { id: 'airport-097', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'Welcome to Tokyo. Please join the foreign passports line.', user: "I'm joining the foreign passports line now.", keywords: ['foreign', 'line'] },
      { id: 'airport-098', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'Have you filled in your arrival card?', user: 'Yes, I filled it in on the plane.', keywords: ['filled', 'plane'] },
      { id: 'airport-099', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'What is the purpose of your visit?', user: "Tourism. I'm here for five days.", keywords: ['tourism', 'days'] },
      { id: 'airport-100', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'Where are you staying in Tokyo?', user: 'At the Park Hotel in Shinjuku.', keywords: ['hotel', 'shinjuku'] },
      { id: 'airport-101', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'Do you have anything to declare?', user: 'I have one bottle of wine to declare.', keywords: ['declare', 'wine'] },
      { id: 'airport-102', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'One bottle is within the duty-free limit.', user: "Good. It's a gift for my friend.", keywords: ['gift', 'friend'] },
      { id: 'airport-103', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'Are you carrying any fresh food or fruit?', user: 'No fresh food, just some chocolate.', keywords: ['chocolate', 'food'] },
      { id: 'airport-104', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'Any medicine? Some types need a permit.', user: 'Just some vitamins, nothing special.', keywords: ['vitamins', 'special'] },
      { id: 'airport-105', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'How much cash are you bringing in?', user: 'About three hundred dollars in cash.', keywords: ['dollars', 'cash'] },
      { id: 'airport-106', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'Are you bringing in any expensive electronics?', user: 'Just my laptop and my camera.', keywords: ['laptop', 'camera'] },
      { id: 'airport-107', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'Please walk through the green channel.', user: "I'll go through the green channel now.", keywords: ['green', 'channel'] },
      { id: 'airport-108', chapter: 'Customs & Immigration', speaker: 'OFFICER', agent: 'Enjoy your stay in Japan. Have a wonderful trip.', user: "Thank you. I'm excited to explore Tokyo.", keywords: ['explore', 'tokyo'] },
      // ---------- Chapter 10: Baggage Claim ----------
      { id: 'airport-109', chapter: 'Baggage Claim', agent: 'Baggage claim is downstairs, past customs.', user: 'Where do I find the baggage carousels?', keywords: ['baggage', 'carousels'] },
      { id: 'airport-110', chapter: 'Baggage Claim', agent: "Your flight's bags are on carousel seven.", user: "Carousel seven. I'll wait over there.", keywords: ['carousel', 'seven'] },
      { id: 'airport-111', chapter: 'Baggage Claim', agent: 'Bags from Tokyo flights usually take twenty minutes.', user: "Twenty minutes? I'll wait patiently then.", keywords: ['wait', 'minutes'] },
      { id: 'airport-112', chapter: 'Baggage Claim', agent: 'Is that your black suitcase going around?', user: 'No, mine has a red strap on it.', keywords: ['red', 'strap'] },
      { id: 'airport-113', chapter: 'Baggage Claim', agent: 'The carousel has stopped. Is your bag missing?', user: "Yes, my suitcase hasn't come out yet.", keywords: ['suitcase', 'come'] },
      { id: 'airport-114', chapter: 'Baggage Claim', agent: "Let's file a report. Can you describe your bag?", user: "It's a large black suitcase with wheels.", keywords: ['black', 'wheels'] },
      { id: 'airport-115', chapter: 'Baggage Claim', agent: 'Any stickers or tags to identify it?', user: "There's a red strap and a wine sticker.", keywords: ['strap', 'sticker'] },
      { id: 'airport-116', chapter: 'Baggage Claim', agent: "What's the tag number on your receipt?", user: 'The tag number is eight four two nine.', keywords: ['tag', 'number'] },
      { id: 'airport-117', chapter: 'Baggage Claim', agent: "We'll deliver it to your hotel tomorrow.", user: 'Please deliver it to the Park Hotel.', keywords: ['deliver', 'hotel'] },
      { id: 'airport-118', chapter: 'Baggage Claim', agent: "Here's some money for essentials tonight.", user: "Thank you. That's very kind of you.", keywords: ['kind', 'thank'] },
      { id: 'airport-119', chapter: 'Baggage Claim', agent: "We'll call you the moment we find it.", user: 'My phone number is on the report.', keywords: ['phone', 'report'] },
      { id: 'airport-120', chapter: 'Baggage Claim', agent: 'Good news — your bag just arrived.', user: "That's wonderful news. Thank you so much.", keywords: ['wonderful', 'news'] },
      // ---------- Chapter 11: Flight Delay ----------
      { id: 'airport-121', chapter: 'Flight Delay', agent: 'Attention: flight CA eighteen thirty-eight is delayed.', user: 'My flight is delayed? How long for?', keywords: ['delayed', 'long'] },
      { id: 'airport-122', chapter: 'Flight Delay', agent: 'About two hours, due to heavy fog.', user: 'Two hours because of fog. I see.', keywords: ['fog', 'hours'] },
      { id: 'airport-123', chapter: 'Flight Delay', agent: 'Please check the screens for updates.', user: "I'll keep an eye on the screens.", keywords: ['eye', 'screens'] },
      { id: 'airport-124', chapter: 'Flight Delay', agent: 'We can rebook you on the next flight.', user: 'Can you rebook me on the next flight?', keywords: ['rebook', 'next'] },
      { id: 'airport-125', chapter: 'Flight Delay', agent: 'The next flight leaves at four fifteen.', user: 'Four fifteen works fine for me.', keywords: ['fifteen', 'works'] },
      { id: 'airport-126', chapter: 'Flight Delay', agent: "Here's a meal voucher for the delay.", user: 'Thank you for the meal voucher.', keywords: ['meal', 'voucher'] },
      { id: 'airport-127', chapter: 'Flight Delay', agent: 'You can use it at any restaurant upstairs.', user: "I'll grab lunch upstairs, then.", keywords: ['lunch', 'upstairs'] },
      { id: 'airport-128', chapter: 'Flight Delay', agent: 'The airline lounge is open to delayed passengers.', user: 'Can I wait in the lounge instead?', keywords: ['lounge', 'wait'] },
      { id: 'airport-129', chapter: 'Flight Delay', agent: "Of course. Show your boarding pass at the door.", user: "I'll show my boarding pass at the door.", keywords: ['boarding', 'door'] },
      { id: 'airport-130', chapter: 'Flight Delay', agent: 'Boarding will now start at gate C five.', user: "Gate C five. I'll head there now.", keywords: ['gate', 'five'] },
      { id: 'airport-131', chapter: 'Flight Delay', agent: 'We apologize again for the inconvenience.', user: "These things happen. Thanks for your help.", keywords: ['happen', 'help'] },
      { id: 'airport-132', chapter: 'Flight Delay', agent: 'Your new seat is twenty-two K, window side.', user: 'Twenty-two K. I like window seats.', keywords: ['window', 'seats'] },
      // ---------- Chapter 12: Missed Connection ----------
      { id: 'airport-133', chapter: 'Missed Connection', agent: "We've landed late. You may miss your connection.", user: "I think I've missed my connecting flight.", keywords: ['missed', 'connecting'] },
      { id: 'airport-134', chapter: 'Missed Connection', agent: 'The transfer desk is near gate D two.', user: 'Where is the transfer desk, please?', keywords: ['transfer', 'desk'] },
      { id: 'airport-135', chapter: 'Missed Connection', agent: 'Let me check the next available flight for you.', user: 'Please check the next available flight.', keywords: ['check', 'flight'] },
      { id: 'airport-136', chapter: 'Missed Connection', agent: 'The next flight is tomorrow at eight.', user: "Tomorrow at eight? That's quite early.", keywords: ['tomorrow', 'early'] },
      { id: 'airport-137', chapter: 'Missed Connection', agent: "We'll put you in a hotel for the night.", user: 'A hotel for the night sounds good.', keywords: ['hotel', 'night'] },
      { id: 'airport-138', chapter: 'Missed Connection', agent: "Here's a voucher for dinner and breakfast.", user: 'Dinner and breakfast are included. Great.', keywords: ['dinner', 'breakfast'] },
      { id: 'airport-139', chapter: 'Missed Connection', agent: 'The shuttle to the hotel leaves in ten minutes.', user: "I'll catch the hotel shuttle in ten minutes.", keywords: ['shuttle', 'minutes'] },
      { id: 'airport-140', chapter: 'Missed Connection', agent: 'Your bag will go straight to the final destination.', user: 'My bag goes straight through? Perfect.', keywords: ['straight', 'perfect'] },
      { id: 'airport-141', chapter: 'Missed Connection', agent: "Here's your new boarding pass for tomorrow.", user: 'Thank you for the new boarding pass.', keywords: ['boarding', 'pass'] },
      { id: 'airport-142', chapter: 'Missed Connection', agent: 'Please be at the gate by seven fifteen.', user: "I'll be at the gate by seven fifteen.", keywords: ['gate', 'fifteen'] },
      { id: 'airport-143', chapter: 'Missed Connection', agent: 'Is there anything else I can do for you?', user: "No, you've been very helpful. Thanks.", keywords: ['helpful', 'thanks'] },
      { id: 'airport-144', chapter: 'Missed Connection', agent: 'Safe travels, and sorry for the trouble.', user: "Thanks. I'll plan longer layovers next time.", keywords: ['layovers', 'time'] }
    ]
  };
})();
