/* Speak or Boom — Airport v2 (rich, narrative) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.airport = {
    id: 'airport',
    title: 'Airport',
    tagline: 'Check-in to Takeoff',
    speaker: 'AGENT',
    difficulty: 'Intermediate',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: Arrival at the Terminal ----------
      { id: 1, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'Welcome to Terminal Three! You look like you are carrying the weight of the world today.',
        user: 'Is it that obvious? I barely slept last night thinking about this flight.',
        keywords: ['obvious', 'barely'] },
      { id: 2, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'After fifteen years here, I can spot a nervous traveler from fifty meters away.',
        user: 'Fifteen years? You must have seen every kind of airport drama imaginable.',
        keywords: ['drama', 'imaginable'] },
      { id: 3, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'Every kind, my friend. Proposals, reunions, farewells — airports hold all human emotions.',
        user: 'That is beautifully put. I never thought of airports as emotional places before.',
        keywords: ['beautifully', 'emotional'] },
      { id: 4, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'They absolutely are. I am Raj, by the way. Where is this journey taking you today?',
        user: 'Nice to meet you, Raj. I am Jordan, flying to Lisbon this morning.',
        keywords: ['jordan', 'lisbon'] },
      { id: 5, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'Lisbon! What a magnificent city. Is this a vacation, or something more permanent?',
        user: 'Something more permanent. I am moving there to start a completely new chapter.',
        keywords: ['completely', 'permanent'] },
      { id: 6, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'A new chapter — how exciting! Though I detect a hint of fear behind that brave smile.',
        user: 'You are very perceptive. I am excited, but honestly, I am terrified too.',
        keywords: ['perceptive', 'terrified'] },
      { id: 7, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'Terror and excitement are twins, Jordan. They always travel together on big life changes.',
        user: 'I like that perspective. It makes my anxiety feel almost normal and healthy.',
        keywords: ['perspective', 'anxiety'] },
      { id: 8, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'It is completely normal. Now, is this your first time flying alone internationally?',
        user: 'First time alone, yes. I have always had someone holding my hand before.',
        keywords: ['holding', 'someone'] },
      { id: 9, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'Then today you become your own guide. That is a powerful moment worth celebrating.',
        user: 'When you say it like that, it sounds empowering rather than frightening.',
        keywords: ['frightening', 'empowering'] },
      { id: 10, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'It is empowering! Now, do you have your passport and booking reference handy?',
        user: 'Passport here, booking on my phone. I checked them about ten times already.',
        keywords: ['passport', 'booking'] },
      { id: 11, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'Ten times is amateur hour. Real nervous travelers check at least twenty times minimum.',
        user: 'Then I am definitely an amateur. Maybe by Lisbon I will be a professional.',
        keywords: ['amateur', 'professional'] },
      { id: 12, chapter: 'Arrival at the Terminal', speaker: 'RAJ',
        agent: 'You will be. Come with me to the counter, and let us get this adventure properly started.',
        user: 'Lead the way, Raj. I feel I am in very good hands today.',
        keywords: ['hands', 'feel'] },
      // ---------- Chapter 2: Check-in Counter ----------
      { id: 13, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'Alright, passport please. Let us see what kind of traveler you officially are.',
        user: 'Here you go. Be kind — that photo was from a bad hair phase.',
        keywords: ['phase', 'photo'] },
      { id: 14, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'We have all been there. Mine makes me look like a startled owl, honestly.',
        user: 'A startled owl! Now I really want to see your passport photo, Raj.',
        keywords: ['passport', 'startled'] },
      { id: 15, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'That photo is classified information. Now, window or aisle for your great escape?',
        user: 'Window, definitely. I want to watch the world shrink beneath me as we climb.',
        keywords: ['definitely', 'shrink'] },
      { id: 16, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'Window seat, excellent choice. There is something magical about watching clouds from above.',
        user: 'Magical is the right word. It always makes my problems feel wonderfully small.',
        keywords: ['magical', 'wonderfully'] },
      { id: 17, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'Perspective at thirty-five thousand feet heals many things, I have always believed.',
        user: 'I hope you are right. I could use some serious healing and fresh perspective.',
        keywords: ['perspective', 'healing'] },
      { id: 18, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'You will find it. Now, any checked baggage, or are you traveling light today?',
        user: 'One checked bag. I tried to pack light, but my books refused staying behind.',
        keywords: ['checked', 'refused'] },
      { id: 19, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'Books are the hardest to leave behind. They are like loyal friends who weigh too much.',
        user: 'Exactly! Each one holds a memory. How could I possibly choose between them?',
        keywords: ['possibly', 'between'] },
      { id: 20, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'You cannot, and you should not. Memories deserve the extra baggage fee, my friend.',
        user: 'I love that philosophy. My books and I are officially worth the extra cost.',
        keywords: ['philosophy', 'officially'] },
      { id: 21, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'Speaking of Lisbon, I have a confession — I am actually flying there myself today.',
        user: 'No way! Are you working this flight, or is it a personal trip?',
        keywords: ['personal', 'working'] },
      { id: 22, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'Personal trip! My mother turns seventy tomorrow, and I have not missed a birthday yet.',
        user: 'Seventy! That is wonderful. She must be thrilled you are coming home.',
        keywords: ['wonderful', 'thrilled'] },
      { id: 23, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'She is. Fifteen years of airport birthdays missed, but never hers. Family first, always.',
        user: 'Fifteen years and never missed one? That is true dedication and love.',
        keywords: ['dedication', 'fifteen'] },
      { id: 24, chapter: 'Check-in Counter', speaker: 'RAJ',
        agent: 'Here is your boarding pass. Gate forty-two, and we might just be seatmates, Jordan.',
        user: 'Seatmates would be perfect. This day keeps getting better and better.',
        keywords: ['seatmates', 'perfect'] },
      // ---------- Chapter 3: Baggage Drop ----------
      { id: 25, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'Now the moment of truth — let us see if your loyal book friends broke the weight limit.',
        user: 'I am nervous. I tried being ruthless, but it is not really my style.',
        keywords: ['ruthless', 'nervous'] },
      { id: 26, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'On the scale it goes... oh dear. Twenty-six kilos, and the limit is twenty-three.',
        user: 'Three kilos over! Those books are heavier than my entire life choices combined.',
        keywords: ['kilos', 'combined'] },
      { id: 27, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'Three kilos is manageable. We can redistribute, or you can pay the overweight fee.',
        user: 'How much is the fee? I am stretching my budget with this big move.',
        keywords: ['stretching', 'budget'] },
      { id: 28, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'Fifty dollars per kilo. Or, we open the bag and perform emergency surgery right here.',
        user: 'Emergency surgery sounds dramatic. What would you suggest removing first?',
        keywords: ['surgery', 'dramatic'] },
      { id: 29, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'Shoes are the usual culprits. How many pairs did you pack for a fresh start?',
        user: 'Five pairs... I know, I know. A fresh start apparently needs options.',
        keywords: ['apparently', 'options'] },
      { id: 30, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'Five pairs! Are you opening a shoe store in Lisbon, or just indecisive like me?',
        user: 'Indecisive, definitely. Each pair represents a different version of my future self.',
        keywords: ['indecisive', 'represents'] },
      { id: 31, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'I love that. But your future self in Lisbon will buy new shoes, I promise you.',
        user: 'You are right. Let me remove two pairs and keep my three absolute favorites.',
        keywords: ['favorites', 'absolute'] },
      { id: 32, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'Excellent! And those books? Could two of them travel in your carry-on instead?',
        user: 'Brilliant idea! My backpack has plenty of room for my most precious stories.',
        keywords: ['brilliant', 'precious'] },
      { id: 33, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'Let us weigh again... twenty-two point five kilos! You did it, Jordan!',
        user: 'Under the limit! I just passed my first test of independent travel.',
        keywords: ['limit', 'independent'] },
      { id: 34, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'You absolutely did. Packing light is a metaphor for life — keep only what matters.',
        user: 'Keep only what matters. I will carry that wisdom all the way to Lisbon.',
        keywords: ['matters', 'lisbon'] },
      { id: 35, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'Wise words from a baggage scale. Your bag is tagged and ready for its own adventure.',
        user: 'Bon voyage, little bag. Please do not get lost in some mysterious airport basement.',
        keywords: ['mysterious', 'basement'] },
      { id: 36, chapter: 'Baggage Drop', speaker: 'RAJ',
        agent: 'It will arrive safely, I promise. Now, my shift ends here — I will meet you at security!',
        user: 'You are coming too? This is turning into the best travel buddy story ever.',
        keywords: ['turning', 'coming'] },
      // ---------- Chapter 4: Security Check ----------
      { id: 37, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'And here I am, transformed from uniform to civilian! Did you even recognize me?',
        user: 'Barely! You look completely different without the official airport attire.',
        keywords: ['completely', 'different'] },
      { id: 38, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'The uniform adds ten years and a lot of authority, my wife always says.',
        user: 'Your wife sounds wise. Is she also traveling to Lisbon for the birthday?',
        keywords: ['traveling', 'birthday'] },
      { id: 39, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'She flew yesterday with the cake. Someone had to transport the seventy candles safely.',
        user: 'Seventy candles on one cake? That sounds like a beautiful fire hazard.',
        keywords: ['beautiful', 'candles'] },
      { id: 40, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'It absolutely is, but my mother insists on every single candle, every single year.',
        user: 'I admire that tradition. Seventy candles for seventy years of wonderful life.',
        keywords: ['tradition', 'wonderful'] },
      { id: 41, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'Now, security tips from a fifteen-year veteran: laptop out, shoes off, smile ready.',
        user: 'Laptop out, shoes off, smile ready. I feel like a soldier preparing for inspection.',
        keywords: ['inspection', 'preparing'] },
      { id: 42, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'Exactly the right attitude! And remember — the bins are not your personal storage units.',
        user: 'Noted. I will try not to leave my dignity in the plastic bin today.',
        keywords: ['dignity', 'plastic'] },
      { id: 43, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'Dignity is the first thing security takes. But they usually return it after screening.',
        user: 'Good to know. I feared flying to Lisbon without any dignity.',
        keywords: ['dignity', 'without'] },
      { id: 44, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'You are through! See? Painless. Now collect your belongings and reclaim your dignity.',
        user: 'That was surprisingly smooth. Your veteran tips really made all the difference.',
        keywords: ['surprisingly', 'difference'] },
      { id: 45, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'Fifteen years of watching helps. Now, passport control awaits — the final boss battle.',
        user: 'Final boss battle? You make border control sound like a video game quest.',
        keywords: ['control', 'battle'] },
      { id: 46, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'It kind of is. You need the right documents, the right answers, and a little luck.',
        user: 'I have the documents. The right answers might be trickier under pressure.',
        keywords: ['documents', 'trickier'] },
      { id: 47, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'Just be honest and calm. Officers can smell fear, but they respect quiet confidence.',
        user: 'Quiet confidence. I will channel my inner diplomat and breathe deeply.',
        keywords: ['diplomat', 'breathe'] },
      { id: 48, chapter: 'Security Check', speaker: 'RAJ',
        agent: 'Perfect. Follow me — I know a shortcut to the shorter queue, a staff secret.',
        user: 'A staff secret! I feel like I have a VIP guide in this airport.',
        keywords: ['airport', 'secret'] },
      // ---------- Chapter 5: Passport Control ----------
      { id: 49, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'This shortcut saved us twenty minutes. The regular line stretches around the corner.',
        user: 'Twenty minutes! You are worth your weight in gold, Raj. Seriously.',
        keywords: ['seriously', 'minutes'] },
      { id: 50, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'Flattery will get you everywhere. Now, have your passport open to the photo page.',
        user: 'Open to the photo page. I feel like I am preparing for an exam.',
        keywords: ['preparing', 'photo'] },
      { id: 51, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'It is an exam, in a way. The subject is "Are you who you claim to be?"',
        user: 'I am Jordan, I promise. Though after this morning, I am not entirely sure.',
        keywords: ['entirely', 'morning'] },
      { id: 52, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'Identity crisis at passport control — that is a new one, even for me.',
        user: 'Moving abroad does strange things to your sense of self, I am discovering.',
        keywords: ['discovering', 'strange'] },
      { id: 53, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'It does. But every stamp in that passport is a chapter of your becoming.',
        user: 'A chapter of my becoming — the most beautiful thing I have heard today.',
        keywords: ['beautiful', 'becoming'] },
      { id: 54, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'I have had fifteen years to practice my passport philosophy. It is my party trick.',
        user: 'It is a wonderful party trick. You should write a book of airport wisdom.',
        keywords: ['wonderful', 'airport'] },
      { id: 55, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'Maybe I will, once I retire. Chapter one: "The Art of the Calm Queue."',
        user: 'I would buy that book. Chapter two could be about dramatic baggage rescues.',
        keywords: ['dramatic', 'baggage'] },
      { id: 56, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'You are our turn! Remember — quiet confidence, honest answers, friendly smile.',
        user: 'Quiet confidence, honest answers. Here goes nothing, wish me luck.',
        keywords: ['honest', 'luck'] },
      { id: 57, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'Purpose of visit? "Starting a new life" might be too honest for the form.',
        user: 'I will say work and new beginnings. That is honest without being overwhelming.',
        keywords: ['overwhelming', 'beginnings'] },
      { id: 58, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'Perfect answer. Short, true, and just mysterious enough to be interesting.',
        user: 'Stamped! He barely looked at me. All that anxiety for absolutely nothing.',
        keywords: ['absolutely', 'anxiety'] },
      { id: 59, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'Ninety percent of travel anxiety is exactly that — fear of absolutely nothing.',
        user: 'Ninety percent! I wish someone had told me that statistic years ago.',
        keywords: ['statistic', 'ninety'] },
      { id: 60, chapter: 'Passport Control', speaker: 'RAJ',
        agent: 'Now you know. Officially stamped and approved — Lisbon is getting closer, Jordan.',
        user: 'Closer with every step. I can almost taste the pastéis de nata already.',
        keywords: ['almost', 'closer'] },
      // ---------- Chapter 6: Finding Your Gate ----------
      { id: 61, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'Gate forty-two is quite a trek. Follow me — I know all the secret shortcuts here.',
        user: 'Another secret shortcut? You are like the airport whisperer, Raj.',
        keywords: ['whisperer', 'shortcut'] },
      { id: 62, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'Airport whisperer — I like that title. Fifteen years earns you these hidden paths.',
        user: 'Hidden paths and hidden wisdom. What else are you hiding from me?',
        keywords: ['hidden', 'hiding'] },
      { id: 63, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'Only my terrible singing voice, which you will thankfully never have to hear.',
        user: 'Now I am genuinely curious. Terrible singing voices are always entertaining.',
        keywords: ['entertaining', 'genuinely'] },
      { id: 64, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'Entertaining for everyone except the singer. Some talents are better kept private.',
        user: 'Fair enough. I will protect your secret, though I am slightly disappointed.',
        keywords: ['disappointed', 'slightly'] },
      { id: 65, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'Look at this terminal — it is a small city with its own rhythms and stories.',
        user: 'It really is. Every face here is heading toward a completely different destiny.',
        keywords: ['completely', 'different'] },
      { id: 66, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'Exactly! That couple is honeymooning, that man is fleeing something, she is chasing dreams.',
        user: 'You read people like novels. What story do you think my face is telling?',
        keywords: ['telling', 'novels'] },
      { id: 67, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'Yours says "brave beginning." A little scared, but walking forward anyway. That is courage.',
        user: 'Brave beginning... I might cry. That is the kindest thing anyone has said today.',
        keywords: ['beginning', 'kindest'] },
      { id: 68, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'No tears at gate forty-two! Save them for the beautiful Lisbon sunset tonight.',
        user: 'Sunset tonight! I had almost forgotten that Lisbon is waiting for me.',
        keywords: ['sunset', 'forgotten'] },
      { id: 69, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'It is waiting, and it is patient. Now, coffee before boarding? My treat, naturally.',
        user: 'Your treat? After all your help, I insist on buying this round, Raj.',
        keywords: ['buying', 'insist'] },
      { id: 70, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'I never argue with insistence. But I am choosing the place — I know the best spot.',
        user: 'Of course you do. Lead me to the legendary best airport coffee spot.',
        keywords: ['legendary', 'airport'] },
      { id: 71, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'Here we are. This tiny kiosk makes better espresso than most fancy downtown cafés.',
        user: 'Tiny kiosk, big flavor. Airports are full of these wonderful hidden surprises.',
        keywords: ['kiosk', 'wonderful'] },
      { id: 72, chapter: 'Finding Your Gate', speaker: 'RAJ',
        agent: 'They are. Now let us find our gate and settle in. Our adventure continues shortly.',
        user: 'Settle in and wait. I am getting quite good at this traveling business.',
        keywords: ['settle', 'business'] },
      // ---------- Chapter 7: Flight Delay ----------
      { id: 73, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'Oh no. That announcement does not sound good. Listen carefully, Jordan.',
        user: 'What did they say? I could not hear over the coffee machine noise.',
        keywords: ['machine', 'coffee'] },
      { id: 74, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'Our flight is delayed three hours. Mechanical issue — they need to inspect something.',
        user: 'Three hours! But your mother’s birthday dinner is tonight, Raj!',
        keywords: ['birthday', 'mothers'] },
      { id: 75, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'I know, I know. Fifteen years, and I still cannot control the airplanes themselves.',
        user: 'You cannot control everything, even with all your airport whisperer powers.',
        keywords: ['control', 'powers'] },
      { id: 76, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'Sadly true. But I can control how we spend these three unexpected hours together.',
        user: 'Unexpected hours... you always find a positive angle, do you not?',
        keywords: ['unexpected', 'positive'] },
      { id: 77, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'It is a survival skill in my profession. Now, first things first — call your Lisbon contact.',
        user: 'Good thinking. My new landlord is expecting me this evening. He will understand.',
        keywords: ['understand', 'expecting'] },
      { id: 78, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'He will. And I will call my wife — she will keep my mother distracted with cake.',
        user: 'Distracted with cake is the best kind of distraction. Seventy candles need attention.',
        keywords: ['distracted', 'attention'] },
      { id: 79, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'Exactly. Now, what do you say we explore the terminal like proper tourists?',
        user: 'Proper tourists with boarding passes! I love this spontaneous adventure mindset.',
        keywords: ['tourists', 'spontaneous'] },
      { id: 80, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'That is the spirit! There is an observation deck upstairs with incredible runway views.',
        user: 'An observation deck! I have always wanted to watch planes take off up close.',
        keywords: ['observation', 'planes'] },
      { id: 81, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'Then today is your lucky day. Sometimes delays are just disguised opportunities.',
        user: 'Disguised opportunities... I am starting to see delays in a whole new light.',
        keywords: ['disguised', 'opportunities'] },
      { id: 82, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'Look at them go! Each plane carries a thousand stories into that beautiful sky.',
        user: 'A thousand stories... and now ours is one of them, paused but not canceled.',
        keywords: ['thousand', 'paused'] },
      { id: 83, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'Paused but not canceled — I love that. You have a poet’s heart, Jordan.',
        user: 'A poet’s heart and a teacher’s mind. Maybe Lisbon will unlock both fully.',
        keywords: ['teachers', 'lisbon'] },
      { id: 84, chapter: 'Flight Delay', speaker: 'RAJ',
        agent: 'It will. Now, I just got a text — let me check if there is any update.',
        user: 'Any good news? Please tell me those three hours just became two.',
        keywords: ['became', 'please'] },
      // ---------- Chapter 8: Missed Connection ----------
      { id: 85, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'Bad news, I am afraid. The delay means we will miss our Madrid connection completely.',
        user: 'Miss our connection! But Madrid was the whole point of this route, Raj.',
        keywords: ['connection', 'madrid'] },
      { id: 86, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'Do not panic yet — I have ideas and a few old colleagues to call.',
        user: 'Old colleagues to the rescue! Your fifteen years are finally paying off.',
        keywords: ['colleagues', 'rescue'] },
      { id: 87, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'They are. Give me ten minutes and my phone. This is what I do best.',
        user: 'Ten minutes. I will try not to spiral into despair while you work magic.',
        keywords: ['spiral', 'despair'] },
      { id: 88, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'No spiraling allowed! Go get us more coffee while I negotiate with the airline gods.',
        user: 'Coffee duty, on it. Black for you, like Mrs. Chen would approve, right?',
        keywords: ['approve', 'coffee'] },
      { id: 89, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'Ha! You remembered. Black, no nonsense — just like life should be sometimes.',
        user: 'Sometimes being the key word. Most days I prefer my life with oat milk.',
        keywords: ['sometimes', 'prefer'] },
      { id: 90, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'And... done! I have news, and you are not going to believe how good it is.',
        user: 'That was fast! Did your airport magic actually work? Tell me everything!',
        keywords: ['everything', 'actually'] },
      { id: 91, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'They rebooked us on a direct flight to Lisbon! No Madrid, no connection, no stress.',
        user: 'Direct to Lisbon! That is actually better than our original plan, Raj!',
        keywords: ['direct', 'original'] },
      { id: 92, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'It is! Sometimes when plans fall apart, the universe hands you something better.',
        user: 'The universe works in mysterious ways. I am learning to trust the detours.',
        keywords: ['universe', 'mysterious'] },
      { id: 93, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'Trust the detours — that should be printed on every boarding pass ever issued.',
        user: 'I would buy that boarding pass. Detours have led to my best life moments.',
        keywords: ['detours', 'moments'] },
      { id: 94, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'Mine too. And the direct flight leaves in one hour — we should head to the gate.',
        user: 'One hour! From despair to direct flight in ten minutes. You are incredible.',
        keywords: ['incredible', 'despair'] },
      { id: 95, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'Just doing my job, even off duty. Now, new gate — forty-seven, other side of the terminal.',
        user: 'Other side! Good thing I have a professional airport guide leading the way.',
        keywords: ['professional', 'guide'] },
      { id: 96, chapter: 'Missed Connection', speaker: 'RAJ',
        agent: 'Professional guide, at your service. And Jordan — thank you for trusting me today.',
        user: 'Thank you for being trustworthy. Not everyone earns that in a single morning.',
        keywords: ['trustworthy', 'single'] },
      // ---------- Chapter 9: Boarding ----------
      { id: 97, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'Gate forty-seven, and look — they are already calling our boarding group! Perfect timing.',
        user: 'Perfect timing indeed. After this morning, I was starting to lose hope.',
        keywords: ['starting', 'morning'] },
      { id: 98, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'Never lose hope at an airport. Hope is the unofficial currency of all terminals.',
        user: 'Unofficial currency! You should definitely write that book of airport wisdom.',
        keywords: ['currency', 'unofficial'] },
      { id: 99, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'I am seriously considering it now. Chapter three: "Hope and Other Boarding Essentials."',
        user: 'Chapter three sounds perfect. I will write the foreword as your grateful student.',
        keywords: ['foreword', 'grateful'] },
      { id: 100, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'Deal! Now, have your boarding pass ready — the scanner awaits your grand entrance.',
        user: 'Grand entrance, coming right up. I feel like a celebrity walking the red carpet.',
        keywords: ['celebrity', 'entrance'] },
      { id: 101, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'Work it, Jordan! And... beep! You are officially on your way to Lisbon.',
        user: 'Officially on my way! That beep was the sweetest sound I have heard today.',
        keywords: ['officially', 'sweetest'] },
      { id: 102, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'Sweeter than my passport philosophy? I am genuinely honored, my friend.',
        user: 'Almost as sweet. Your philosophy will be hard to top, I must admit.',
        keywords: ['philosophy', 'almost'] },
      { id: 103, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'I will take "almost." Now down the jet bridge — the plane is waiting for us.',
        user: 'The jet bridge feels like a tunnel between my old life and new one.',
        keywords: ['tunnel', 'between'] },
      { id: 104, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'What a beautiful way to see it. Every step forward is a step toward Lisbon.',
        user: 'Toward Lisbon, toward new beginnings, toward the person I am becoming.',
        keywords: ['toward', 'beginnings'] },
      { id: 105, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'And guess what? My standby cleared — we are seatmates! Twenty-three A and B.',
        user: 'Seatmates! The universe really is looking out for us today, Raj.',
        keywords: ['seatmates', 'universe'] },
      { id: 106, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'It really is. Window for you, as promised. I will take the middle like a gentleman.',
        user: 'A gentleman indeed. Though I feel guilty taking the best seat again.',
        keywords: ['gentleman', 'guilty'] },
      { id: 107, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'No guilt allowed! Today you are the guest of honor on this journey.',
        user: 'Guest of honor... I could get used to this kind of special treatment.',
        keywords: ['honor', 'treatment'] },
      { id: 108, chapter: 'Boarding', speaker: 'RAJ',
        agent: 'Get used to it. Lisbon treats its newcomers well — you will see very soon.',
        user: 'I cannot wait. Buckled up, tray table up, ready for takeoff!',
        keywords: ['buckled', 'takeoff'] },
      // ---------- Chapter 10: On the Plane ----------
      { id: 109, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'Here we go! The engines are roaring. Squeeze my arm if you need to, Jordan.',
        user: 'I might take you up on that. Takeoff is my least favorite part.',
        keywords: ['favorite', 'takeoff'] },
      { id: 110, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'Mine too, honestly. Even after hundreds of flights, my stomach still drops a little.',
        user: 'Hundreds of flights and still nervous? That actually makes me feel much better.',
        keywords: ['actually', 'hundreds'] },
      { id: 111, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'Nervous means you are alive and aware. Only the reckless feel nothing at all.',
        user: 'Alive and aware — I will hold onto that thought until we level off.',
        keywords: ['thought', 'alive'] },
      { id: 112, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'And... we are up! Look out your window — the city is shrinking beneath us.',
        user: 'It is beautiful. All my worries look so tiny from thirty-five thousand feet.',
        keywords: ['thirtyfive', 'beautiful'] },
      { id: 113, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'That is the magic I promised. Now, tell me — why Lisbon? What called you there?',
        user: 'Honestly? Burnout. I was teaching, exhausted, and needed a completely fresh start.',
        keywords: ['burnout', 'exhausted'] },
      { id: 114, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'Burnout is real, and brave people admit it. What will you teach in Lisbon?',
        user: 'English, ironically. Teaching my own language in a country where it is foreign.',
        keywords: ['ironically', 'foreign'] },
      { id: 115, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'Not ironic — poetic. You will help others find their voice, just as you found yours.',
        user: 'Poetic... I never thought of it that way. Maybe this move is exactly right.',
        keywords: ['exactly', 'thought'] },
      { id: 116, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'It is. And what about me? Fifteen years of airports — what have I learned, you ask?',
        user: 'I am asking! What has fifteen years of hellos and goodbyes taught you, Raj?',
        keywords: ['hellos', 'goodbyes'] },
      { id: 117, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'That every ending is a beginning in disguise. Every goodbye holds a future hello.',
        user: 'Every goodbye holds a future hello... Raj, that belongs in your book, definitely.',
        keywords: ['definitely', 'belongs'] },
      { id: 118, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'It does. Oh, feel that? A little turbulence — just the sky reminding us who is boss.',
        user: 'Who is boss, indeed. I will just breathe deeply and trust the pilots completely.',
        keywords: ['completely', 'breathe'] },
      { id: 119, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'That is the spirit. And look — it is already passing. Smooth skies ahead, my friend.',
        user: 'Smooth skies ahead. I like the sound of that, both literally and metaphorically.',
        keywords: ['smooth', 'metaphorically'] },
      { id: 120, chapter: 'On the Plane', speaker: 'RAJ',
        agent: 'Metaphorically is where I live. Now rest — Lisbon will be here before you know it.',
        user: 'Rest with a poet beside me. This has been the most meaningful flight ever.',
        keywords: ['meaningful', 'beside'] },
      // ---------- Chapter 11: Customs & Immigration ----------
      { id: 121, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'Ladies and gentlemen, we have landed in Lisbon! Welcome to your new home, Jordan.',
        user: 'My new home! Those words still sound surreal, but wonderfully exciting.',
        keywords: ['wonderfully', 'exciting'] },
      { id: 122, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'Surreal is the perfect word. Now, follow the signs to passport control — last hurdle.',
        user: 'Last hurdle! I feel like an athlete approaching the finish line right now.',
        keywords: ['hurdle', 'athlete'] },
      { id: 123, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'You are! And remember our mantra — quiet confidence, honest answers, friendly smile.',
        user: 'Quiet confidence, honest answers. Your mantra has served me well all day.',
        keywords: ['mantra', 'served'] },
      { id: 124, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'It has never failed me. The officer looks strict, but that is just professional focus.',
        user: 'Professional focus, got it. I will not mistake seriousness for unfriendliness.',
        keywords: ['unfriendliness', 'professional'] },
      { id: 125, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'Exactly right. Purpose of visit? "New life" is true, but "work" is simpler.',
        user: 'Work and new beginnings — my tried and true answer from this morning.',
        keywords: ['beginnings', 'morning'] },
      { id: 126, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'Tried and true indeed. How long will you stay? "Indefinitely" sounds romantic but risky.',
        user: 'I will say one year, renewable. Honest, practical, and leaves room for dreams.',
        keywords: ['practical', 'renewable'] },
      { id: 127, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'Perfect balance of practical and dreamy. You are learning the art of borders.',
        user: 'The art of borders... every country has its own entry poetry, does it not?',
        keywords: ['borders', 'country'] },
      { id: 128, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'It does. Stamped! Welcome to Portugal, Jordan. You are officially a resident dreamer.',
        user: 'Resident dreamer! I love that title. It sounds so much better than expatriate.',
        keywords: ['resident', 'expatriate'] },
      { id: 129, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'Much better. Now, one more adventure awaits — the legendary baggage carousel.',
        user: 'Legendary indeed. Please let my bag be there, safe and sound and on time.',
        keywords: ['legendary', 'indeed'] },
      { id: 130, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'It will be. And my mother is waiting outside — I can already smell her cooking.',
        user: 'Her cooking! After seventy candles, I bet she makes an incredible birthday feast.',
        keywords: ['incredible', 'birthday'] },
      { id: 131, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'She does. Bacalhau, pastéis, enough food for a small army. You should join us.',
        user: 'Join your family birthday? I would not want to intrude on this special day.',
        keywords: ['birthday', 'intrude'] },
      { id: 132, chapter: 'Customs & Immigration', speaker: 'RAJ',
        agent: 'Nonsense! In my family, strangers are just friends who have not eaten together yet.',
        user: 'That is the most welcoming thing anyone has said to me. I am touched.',
        keywords: ['welcoming', 'touched'] },
      // ---------- Chapter 12: Baggage Claim ----------
      { id: 133, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'Here we are — the carousel of hope and anxiety. Every traveler knows this feeling.',
        user: 'Hope and anxiety, perfectly described. I am scanning every bag like a detective.',
        keywords: ['described', 'detective'] },
      { id: 134, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'Detective Jordan on the case! What does your bag look like? Describe it precisely.',
        user: 'Big, blue, covered in stickers from every place I have ever dreamed of visiting.',
        keywords: ['stickers', 'visiting'] },
      { id: 135, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'Stickers from dream destinations — now it carries you to a real one. Poetic, no?',
        user: 'Poetic indeed. Those stickers were promises, and now one is finally coming true.',
        keywords: ['promises', 'stickers'] },
      { id: 136, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'There it is! The blue dream machine! Grab it before someone else claims your life.',
        user: 'Got it! My whole new life in one slightly battered blue suitcase. Incredible.',
        keywords: ['battered', 'suitcase'] },
      { id: 137, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'Incredible indeed. Now where is mine... hmm, this is taking unusually long, actually.',
        user: 'Unusually long? Do not tell me the baggage expert’s bag is actually missing.',
        keywords: ['unusually', 'actually'] },
      { id: 138, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'It appears so! The irony is not lost on me — fifteen years, and my bag vanishes.',
        user: 'The irony is delicious. Even the master is humbled by the carousel gods.',
        keywords: ['irony', 'humbled'] },
      { id: 139, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'Humbled indeed. But I know exactly what to do — file the claim, stay calm, trust the system.',
        user: 'Trust the system, just like you taught me. The student becomes the teacher today.',
        keywords: ['system', 'student'] },
      { id: 140, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'The student becomes the teacher — I love it. My work here is officially done.',
        user: 'Your work? Raj, your friendship is just beginning. Lisbon is our next chapter.',
        keywords: ['friendship', 'beginning'] },
      { id: 141, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'Our next chapter... I like the sound of that. Coffee tomorrow? I know a place.',
        user: 'Coffee tomorrow! You know all the best places, wherever in the world we are.',
        keywords: ['tomorrow', 'wherever'] },
      { id: 142, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'Wherever we are, indeed. Now go — your landlord, your new life, Lisbon awaits you.',
        user: 'Lisbon awaits! Thank you, Raj, for turning a scary day into a beautiful adventure.',
        keywords: ['awaits', 'beautiful'] },
      { id: 143, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'Thank you for reminding me why I love airports — the brave beginnings, every single day.',
        user: 'Brave beginnings... I will carry those words with me, always. Goodbye for now.',
        keywords: ['brave', 'always'] },
      { id: 144, chapter: 'Baggage Claim', speaker: 'RAJ',
        agent: 'Not goodbye — até logo! In Portugal, we say "until soon." Until soon, Jordan.',
        user: 'Até logo, Raj! Until soon, my friend. My Lisbon story starts right now.',
        keywords: ['logo', 'story'] }
    ]
  };
})();
