/* Speak or Boom — Hotel v2 (rich, narrative)
   Characters: NORA (receptionist, 8 yrs at Grand Plaza, warm/dry wit) x
   DANIEL REYES (guest, architecture photographer, here for sister Lily's wedding).
   Arc: reservation call -> arrival -> room -> AC trouble -> housekeeping ->
   breakfast with Mr. Abernathy -> rooftop sunset -> printer crisis & speech ->
   extended stay -> checkout -> lost lens -> polite complaint as love letter.
   Threads: Lily's wedding/toast, arctic AC, room 312 novelist, rooftop lights,
   grandfather's film camera, Rosa's towel swans, biscotti. */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.hotel = {
    id: 'hotel',
    title: 'Hotel',
    tagline: 'A Night Away From Home',
    speaker: 'RECEPTION',
    difficulty: 'Intermediate',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: Making a Reservation ----------
      { id: 1, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'Good evening, Grand Plaza Hotel. This is Nora speaking. How may I help you tonight?',
        user: 'Good evening! I need a room for three nights, starting this Friday, please.',
        keywords: ['nights', 'friday'] },
      { id: 2, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'Three nights starting Friday — lovely. May I ask what brings you to our city?',
        user: 'My sister Lily is getting married here. I would not miss it.',
        keywords: ['sister', 'married'] },
      { id: 3, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'A wedding! How wonderful. Are you giving a speech, or just enjoying the champagne?',
        user: 'I am the best man, unfortunately. Public speaking terrifies me more than flying.',
        keywords: ['terrifies', 'flying'] },
      { id: 4, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'Best man duties and a fear of microphones — we will make sure you rest well beforehand.',
        user: 'Rest would be amazing. I have barely slept thinking about that speech all week.',
        keywords: ['barely', 'speech'] },
      { id: 5, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'Then you need our quietest room. The courtyard side is peaceful, even on weekends.',
        user: 'Quiet sounds perfect. Is there a big price difference between the room types?',
        keywords: ['difference', 'types'] },
      { id: 6, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'Not at all for wedding guests. I can offer you our old-town view at standard rate.',
        user: 'Old-town view? That sounds lovely. What exactly would I be looking at?',
        keywords: ['exactly', 'looking'] },
      { id: 7, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'Cobbled streets, the cathedral spire, and rooftops that glow gold at sunset. Pure magic.',
        user: 'You paint quite a picture. I am also a photographer, so that view matters.',
        keywords: ['photographer', 'matters'] },
      { id: 8, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'A photographer! Then you will adore the light here. Mornings are especially beautiful.',
        user: 'Now I am genuinely excited. How do I secure this magical room, Nora?',
        keywords: ['genuinely', 'secure'] },
      { id: 9, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'Just your name and a card to hold it. No charge until you actually check in.',
        user: 'Daniel Reyes. And the wedding is Saturday, so Friday to Monday works perfectly.',
        keywords: ['reyes', 'saturday'] },
      { id: 10, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'Daniel Reyes, Friday to Monday, old-town view. Shall I note any special requests?',
        user: 'Extra pillows, please. I sleep like a log when my neck is properly supported.',
        keywords: ['pillows', 'supported'] },
      { id: 11, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'Extra pillows, noted with pleasure. Anything else — early check-in, perhaps?',
        user: 'My flight lands at noon. Could I possibly check in a little bit early?',
        keywords: ['flight', 'lands'] },
      { id: 12, chapter: 'Making a Reservation', speaker: 'NORA',
        agent: 'For a best man with camera gear and nerves, early check-in is absolutely guaranteed.',
        user: 'Nora, you are a lifesaver. I already feel better about this whole trip.',
        keywords: ['lifesaver', 'trip'] },
      // ---------- Chapter 2: Arrival & Check-in ----------
      { id: 13, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'Welcome to the Grand Plaza! You must be Daniel — I recognize the nervous best man voice.',
        user: 'You remembered! I am impressed. The flight was delayed, so I am running late.',
        keywords: ['remembered', 'delayed'] },
      { id: 14, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'Delayed flights are the worst. Let me get you checked in quickly so you can rest.',
        user: 'Thank you. The lobby looks beautiful, by the way. Very grand, very welcoming.',
        keywords: ['beautiful', 'welcoming'] },
      { id: 15, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'Thank you! The building dates back to nineteen twenty-eight. It has wonderful bones.',
        user: 'Nineteen twenty-eight? This place has nearly a century of stories in its walls.',
        keywords: ['century', 'walls'] },
      { id: 16, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'A famous novelist wrote an entire book in room three twelve, fueled by our coffee.',
        user: 'Now I want room three twelve! Though I suppose it is probably always booked.',
        keywords: ['probably', 'suppose'] },
      { id: 17, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'Always booked, sadly. But your room has the same sunset view, I promise you.',
        user: 'The sunset view will do nicely. May I have the key cards, please?',
        keywords: ['sunset', 'cards'] },
      { id: 18, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'Two key cards, extra pillows already placed, and early check-in honored as promised.',
        user: 'You thought of everything. This is already the smoothest check-in I have experienced.',
        keywords: ['smoothest', 'experienced'] },
      { id: 19, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'We aim to please. The wedding is tomorrow — are the nerves any better today?',
        user: 'Marginally better. Your calm voice on the phone helped more than you know.',
        keywords: ['marginally', 'calm'] },
      { id: 20, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'That is kind of you to say. I have worked here eight years; nervous guests are my specialty.',
        user: 'Eight years! You must have witnessed hundreds of weddings from this very desk.',
        keywords: ['witnessed', 'hundreds'] },
      { id: 21, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'Hundreds, at least. And every best man survives the speech. Every single one.',
        user: 'Every single one? That is statistically reassuring, I suppose. I will trust you.',
        keywords: ['statistically', 'reassuring'] },
      { id: 22, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'Trust the statistics. Now — the rooftop opens at six. Do not miss that golden light.',
        user: 'The photographer in me is already excited. Is the rooftop open to all guests?',
        keywords: ['photographer', 'excited'] },
      { id: 23, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'All guests, every evening. And the bakery across the street opens ridiculously early.',
        user: 'Ridiculously early is my favorite kind of early. I will remember that bakery.',
        keywords: ['ridiculously', 'bakery'] },
      { id: 24, chapter: 'Arrival & Check-in', speaker: 'NORA',
        agent: 'Room four twelve, elevator on the right. Sleep well, Daniel. Tomorrow is the big day.',
        user: 'Thank you, Nora. Talking to you feels like arriving home, strangely enough.',
        keywords: ['strangely', 'arriving'] },
      // ---------- Chapter 3: Room Requests ----------
      { id: 25, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'Front desk, Nora speaking. Is everything alright with room four twelve, Daniel?',
        user: 'Everything is wonderful! The view is even better than you described it.',
        keywords: ['wonderful', 'described'] },
      { id: 26, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'I am so glad! The cathedral spire looks magnificent when the afternoon light hits it.',
        user: 'It really does. Quick question — do you have an iron I could borrow?',
        keywords: ['question', 'borrow'] },
      { id: 27, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'Of course! I will send one up right away. Wedding suits need to look absolutely sharp.',
        user: 'You are a mind reader. My suit sat folded in a suitcase for hours.',
        keywords: ['reader', 'suitcase'] },
      { id: 28, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'Six hours in a suitcase is a crime against tailoring. The iron will be there shortly.',
        user: 'While I have you — could I get a couple of extra towels, please?',
        keywords: ['towels', 'couple'] },
      { id: 29, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'Extra towels, absolutely. Anything else to make your stay more comfortable tonight?',
        user: 'Actually, what time does the noise usually die down? I am a light sleeper.',
        keywords: ['usually', 'sleeper'] },
      { id: 30, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'The courtyard side goes completely silent by ten. You picked the perfect room for sleeping.',
        user: 'Perfect. One more thing — is the minibar as terrifyingly expensive as everyone says?',
        keywords: ['terrifyingly', 'expensive'] },
      { id: 31, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'Terrifyingly expensive is accurate, I am afraid. The bakery across the street is far kinder.',
        user: 'Honest advice. I like that. I will stick to the bakery for midnight snacks.',
        keywords: ['honest', 'midnight'] },
      { id: 32, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'Wise choice. Now, is there anything else I can do for our favorite best man?',
        user: 'Tell me about that novelist. Which book did she write in room three twelve?',
        keywords: ['which', 'book'] },
      { id: 33, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'The Salt Meridian — a sweeping saga about lighthouse keepers and lost love. Have you read it?',
        user: 'Not yet, but I am intrigued. A novel born in this building — amazing.',
        keywords: ['intrigued', 'amazing'] },
      { id: 34, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'She stayed three months. Claimed the foggy mornings gave her the perfect melancholy mood.',
        user: 'Foggy mornings and melancholy. I see why a writer would fall for this place.',
        keywords: ['foggy', 'melancholy'] },
      { id: 35, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'Writers, photographers, nervous best men — this old hotel collects interesting souls.',
        user: 'I am honored to be collected. Though I hope my story ends more happily.',
        keywords: ['honored', 'collected'] },
      { id: 36, chapter: 'Room Requests', speaker: 'NORA',
        agent: 'With a sister who loves you and a sunset view, I would say the odds are excellent.',
        user: 'When you put it that way, I almost believe everything will turn out fine.',
        keywords: ['almost', 'believe'] },
      // ---------- Chapter 4: Room Problems ----------
      { id: 37, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'Front desk, Nora here. Daniel, is something wrong? You sound a little chilly.',
        user: 'The air conditioning is blasting like an arctic wind. I cannot feel my toes.',
        keywords: ['blasting', 'arctic'] },
      { id: 38, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'Arctic winds in April are definitely not our intention. Let me walk you through the thermostat.',
        user: 'I would appreciate that. Technology and I have never been close friends, honestly.',
        keywords: ['technology', 'honestly'] },
      { id: 39, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'No shame in that. See the small dial on the right? Turn it gently toward the sun symbol.',
        user: 'The sun symbol... found it! Turning now. Oh, that already feels much better.',
        keywords: ['symbol', 'turning'] },
      { id: 40, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'Wonderful! But I will still send maintenance to check it properly first thing tomorrow.',
        user: 'That would be great. I do not want to wake up like a popsicle.',
        keywords: ['popsicle', 'wake'] },
      { id: 41, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'No popsicles on my watch. Would you like an extra blanket, just in case tonight?',
        user: 'An extra blanket sounds heavenly. You really think of every little detail.',
        keywords: ['heavenly', 'detail'] },
      { id: 42, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'Eight years teaches you that little details are actually the big things in hospitality.',
        user: 'That is a lovely philosophy. Is that why you have stayed here so long?',
        keywords: ['philosophy', 'stayed'] },
      { id: 43, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'Partly. Mostly I stay for the people — every guest brings a whole new world.',
        user: 'A whole new world... that is exactly why I became a photographer, you know.',
        keywords: ['exactly', 'photographer'] },
      { id: 44, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'Tell me more. What made you pick up a camera in the first place, Daniel?',
        user: 'My grandfather gave me his old film camera when I turned sixteen years old.',
        keywords: ['grandfather', 'sixteen'] },
      { id: 45, chapter: 'Room Problems', speaker: 'NORA',
        agent: "A grandfather's camera — what a beautiful inheritance. Do you still carry it with you?",
        user: 'Always. It is in my bag now. Film feels more honest than digital somehow.',
        keywords: ['digital', 'somehow'] },
      { id: 46, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'More honest — I love that. There is the knock! Maintenance is at your door now.',
        user: 'That was fast! Your team really does not waste any time around here.',
        keywords: ['waste', 'team'] },
      { id: 47, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'We try our best. I will let you get back to your evening, Daniel. Sleep warm!',
        user: 'Goodnight, Nora. Thanks for turning an arctic disaster into a pleasant conversation.',
        keywords: ['disaster', 'pleasant'] },
      { id: 48, chapter: 'Room Problems', speaker: 'NORA',
        agent: 'Anytime. And Daniel — your sister is lucky to have a brother who cares this much.',
        user: 'That means a lot, truly. Goodnight, and thanks for everything tonight.',
        keywords: ['truly', 'means'] },
      // ---------- Chapter 5: Housekeeping ----------
      { id: 49, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'Good morning, Daniel! Did the arctic winds stay away last night, or should I worry?',
        user: 'I slept like a baby! Your blanket advice was absolutely spot on, thank you.',
        keywords: ['advice', 'spot'] },
      { id: 50, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'Spot on is my middle name. I see your do-not-disturb sign is still hanging proudly.',
        user: 'Up late rehearsing my speech in the mirror. It still needs serious work.',
        keywords: ['rehearsing', 'mirror'] },
      { id: 51, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'Rehearsing in the mirror is a classic technique. How did the mirror react to it?',
        user: 'The mirror was very supportive, but mirrors are notoriously bad critics, unfortunately.',
        keywords: ['notoriously', 'critics'] },
      { id: 52, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'Notoriously bad critics indeed. When you are ready, Rosa will work her housekeeping magic.',
        user: 'Rosa? Is she the one who folded my towels into that elegant swan shape?',
        keywords: ['elegant', 'swan'] },
      { id: 53, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'The very same! Rosa has been folding towel swans for fifteen years without repeating a design.',
        user: 'Fifteen years of swans! That is dedication to an art most people never notice.',
        keywords: ['dedication', 'notice'] },
      { id: 54, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'She notices, and that is what matters. Shall I send her up in about an hour?',
        user: 'An hour is perfect. Actually, could she also press my shirt for the wedding?',
        keywords: ['press', 'shirt'] },
      { id: 55, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'Pressed shirt, coming up. Rosa handles wedding emergencies like a seasoned general.',
        user: 'A seasoned general of housekeeping. I feel safer knowing she is in charge.',
        keywords: ['seasoned', 'general'] },
      { id: 56, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'You are in excellent hands. Is there anything else before I let you go?',
        user: 'Just one thing — what is the proper way to tip housekeeping these days?',
        keywords: ['housekeeping', 'proper'] },
      { id: 57, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'What a thoughtful question! An envelope on the pillow is the classic, gracious way.',
        user: 'Envelope on the pillow, got it. Rosa deserves something extra for the swan alone.',
        keywords: ['envelope', 'deserves'] },
      { id: 58, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'She will be thrilled. Small kindnesses are the currency of this old hotel, Daniel.',
        user: 'Currency of kindness — I like that. This place runs on something truly special.',
        keywords: ['currency', 'special'] },
      { id: 59, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'It really does. Now go enjoy your morning — the wedding is only hours away now!',
        user: 'Hours away! My stomach just did a somersault hearing you say that out loud.',
        keywords: ['somersault', 'stomach'] },
      { id: 60, chapter: 'Housekeeping', speaker: 'NORA',
        agent: 'Somersaults are normal. Breathe deeply, trust your words, and remember to smile.',
        user: 'Breathe, trust, smile. I am writing that on my hand so I never forget.',
        keywords: ['writing', 'forget'] },
      // ---------- Chapter 6: Breakfast ----------
      { id: 61, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'The breakfast room is through the archway. Might I recommend the shakshuka? It is legendary.',
        user: 'Legendary shakshuka? You have convinced me. I will take your recommendation gladly.',
        keywords: ['convinced', 'gladly'] },
      { id: 62, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'Excellent choice! Sit by the window if you can — the morning light is pure poetry.',
        user: 'Pure poetry and poached eggs. What a wonderful way to start a wedding day.',
        keywords: ['poached', 'wonderful'] },
      { id: 63, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'Oh, I see Mr. Abernathy is already holding court at his usual corner table.',
        user: 'Holding court? He sounds like a character. Should I be nervous sitting near him?',
        keywords: ['character', 'nervous'] },
      { id: 64, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'Nervous? Never. He is eighty-two, travels alone, and collects stories like precious souvenirs.',
        user: 'Eighty-two and traveling alone! That is the kind of future I aspire to, honestly.',
        keywords: ['aspire', 'honestly'] },
      { id: 65, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'He just waved you over. Consider yourself officially invited to the court of Abernathy.',
        user: 'Officially invited! I feel honored. Excuse me while I join his royal breakfast court.',
        keywords: ['officially', 'honored'] },
      { id: 66, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'Enjoy! And Daniel — he gives excellent advice. Better than any wedding planner, truly.',
        user: 'Better than a wedding planner? Now I am genuinely curious what he will say.',
        keywords: ['genuinely', 'curious'] },
      { id: 67, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'He is telling you about his own wedding, I bet. Fifty-eight years ago, in this very city.',
        user: 'Fifty-eight years! He just told me the secret is laughing together every single day.',
        keywords: ['secret', 'laughing'] },
      { id: 68, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'Laughing every day — simple wisdom from someone who has actually lived it fully.',
        user: 'It hit me hard. I want that kind of love story for Lily too.',
        keywords: ['story', 'hit'] },
      { id: 69, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'Lily will have it. And your toast tonight will be part of her beautiful beginning.',
        user: 'My toast... I am still terrified, but somehow less than I was yesterday.',
        keywords: ['terrified', 'somehow'] },
      { id: 70, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'Less terrified is real progress! What did Mr. Abernathy say about public speaking?',
        user: 'He said speak from the heart, and the words will take care of themselves.',
        keywords: ['heart', 'themselves'] },
      { id: 71, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'From the heart — he is absolutely right. Audiences forgive everything except insincerity.',
        user: 'I will remember that. My love for Lily is the sincerest thing I know.',
        keywords: ['sincerest', 'remember'] },
      { id: 72, chapter: 'Breakfast', speaker: 'NORA',
        agent: 'Then you have nothing to fear. Now finish that legendary shakshuka before it gets cold!',
        user: 'Finishing now! Thank you, Nora — for breakfast, for Abernathy, for absolutely everything.',
        keywords: ['finishing', 'absolutely'] },
      // ---------- Chapter 7: Hotel Facilities ----------
      { id: 73, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Feeling brave after breakfast? Our pool is heated, and the gym is surprisingly well equipped.',
        user: 'A heated pool sounds perfect. I need to burn off this nervous energy.',
        keywords: ['heated', 'nervous'] },
      { id: 74, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Burn it off! The pool is on the second floor, towels are provided, no excuses allowed.',
        user: 'No excuses! I like your coaching style. What are the pool hours today?',
        keywords: ['coaching', 'hours'] },
      { id: 75, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Seven to ten daily. And afterward, the rooftop at sunset is practically mandatory for photographers.',
        user: 'Mandatory rooftop sunset — consider it done. What time does the light get good?',
        keywords: ['mandatory', 'light'] },
      { id: 76, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Around seven thirty. The whole old town turns amber, and the cathedral glows like embers.',
        user: 'Amber and embers... you describe light the way poets describe their beloved muses.',
        keywords: ['amber', 'poets'] },
      { id: 77, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Eight years of sunsets will turn anyone into a poet, Daniel. Go see for yourself.',
        user: 'I will! But first, twenty laps to earn that sunset. Talk later, Nora.',
        keywords: ['laps', 'earn'] },
      { id: 78, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Twenty laps! Ambitious. I will expect a full report on the water temperature later.',
        user: 'Full report incoming. If I survive twenty laps, that is. Wish me luck!',
        keywords: ['incoming', 'survive'] },
      { id: 79, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Front desk, Nora here. Is that you calling from the rooftop, Daniel? How is the view?',
        user: 'Nora, it is unreal! The whole city looks like it is gently on fire.',
        keywords: ['unreal', 'gently'] },
      { id: 80, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Gently on fire — that is exactly it! Are you getting good shots with the camera?',
        user: "Incredible shots. My grandfather's film camera is earning its keep tonight, truly.",
        keywords: ['incredible', 'earning'] },
      { id: 81, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'He would be proud, watching you capture this city with his beloved old camera.',
        user: 'I think so. He always said light is the true subject of every photograph.',
        keywords: ['subject', 'photograph'] },
      { id: 82, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Wise grandfather. You know, during the war, this hotel kept its rooftop lights burning.',
        user: 'Really? Keeping the lights on during wartime must have meant something powerful.',
        keywords: ['wartime', 'powerful'] },
      { id: 83, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'It meant hope. People said if the Grand Plaza glows, the city is still standing strong.',
        user: 'If the Grand Plaza glows, that gives me chills. What a beautiful legacy!',
        keywords: ['chills', 'legacy'] },
      { id: 84, chapter: 'Hotel Facilities', speaker: 'NORA',
        agent: 'Eighty years of glowing strong. Enjoy every minute up there, Daniel. It is special.',
        user: 'It really is. Thank you for sending me up. This moment is pure magic.',
        keywords: ['sending', 'magic'] },
      // ---------- Chapter 8: Business Services ----------
      { id: 85, chapter: 'Business Services', speaker: 'NORA',
        agent: 'Back from the rooftop already? You look like someone with an urgent mission, Daniel.',
        user: 'Urgent mission. I need to print my wedding speech, but the printer jammed.',
        keywords: ['mission', 'jammed'] },
      { id: 86, chapter: 'Business Services', speaker: 'NORA',
        agent: 'A jammed printer before a wedding speech is a classic crisis. I am coming up myself.',
        user: 'Coming up? Nora, you do not have to leave the front desk for me.',
        keywords: ['coming', 'front'] },
      { id: 87, chapter: 'Business Services', speaker: 'NORA',
        agent: "Nonsense. A best man's speech emergency outranks everything. Business center, two minutes.",
        user: 'You are incredible. I will meet you there with my laptop and my panic.',
        keywords: ['incredible', 'panic'] },
      { id: 88, chapter: 'Business Services', speaker: 'NORA',
        agent: 'Panic is optional; the printer is mandatory. Let us see what this beast has swallowed.',
        user: 'It swallowed page two, I think. The most emotional paragraph, of course it did.',
        keywords: ['swallowed', 'emotional'] },
      { id: 89, chapter: 'Business Services', speaker: 'NORA',
        agent: 'Of course it did — printers have a cruel sense of humor. Ah, there is the culprit!',
        user: 'You found it! How do you know so much about printers, thermostats, everything?',
        keywords: ['thermostats', 'everything'] },
      { id: 90, chapter: 'Business Services', speaker: 'NORA',
        agent: 'Eight years, remember? I have unjammed printers, calmed brides, and relocated several spiders.',
        user: 'Relocated spiders! Now I have heard everything. You are a true hotel superhero.',
        keywords: ['relocated', 'superhero'] },
      { id: 91, chapter: 'Business Services', speaker: 'NORA',
        agent: 'Superhero is a stretch, but I will take it. And... printing! Your speech lives again.',
        user: 'It lives! Thank you. Would you mind reading it? I need one honest opinion.',
        keywords: ['lives', 'opinion'] },
      { id: 92, chapter: 'Business Services', speaker: 'NORA',
        agent: 'One honest opinion, coming right up. Hand it over, best man. I am all ears.',
        user: 'Be brutal, please. Lily deserves the best words I can possibly give her.',
        keywords: ['brutal', 'deserves'] },
      { id: 93, chapter: 'Business Services', speaker: 'NORA',
        agent: 'Brutal? Daniel, this is beautiful. The part about her laugh made my eyes water.',
        user: 'Your eyes watered? That is the best review I could have hoped for, honestly.',
        keywords: ['watered', 'review'] },
      { id: 94, chapter: 'Business Services', speaker: 'NORA',
        agent: 'Truly watered. You wrote from the heart, exactly like Mr. Abernathy advised you.',
        user: 'From the heart... I finally understand what he meant. It just poured out.',
        keywords: ['poured', 'understand'] },
      { id: 95, chapter: 'Business Services', speaker: 'NORA',
        agent: 'That is how you know it is real. Lily is going to cry, and so will everyone else.',
        user: 'Happy tears, I hope. Not the awkward silence kind I have been dreading.',
        keywords: ['dreading', 'awkward'] },
      { id: 96, chapter: 'Business Services', speaker: 'NORA',
        agent: 'Happy tears, guaranteed. Now go get dressed — the wedding is in two hours, superstar!',
        user: 'Two hours! Deep breaths. Thank you, Nora — for the printer, the tears, everything.',
        keywords: ['everything', 'breaths'] },
      // ---------- Chapter 9: Extending Your Stay ----------
      { id: 97, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'Well, well — if it is not the famous best man! How did the speech go last night?',
        user: 'Nora! It was perfect! Happy tears everywhere, just like you predicted it would be.',
        keywords: ['predicted', 'perfect'] },
      { id: 98, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'Predicted and delivered! I am so proud of you, Daniel. How is the happy couple?',
        user: 'Radiant. Lily cried, I cried, even the photographer cried. It was beautiful chaos.',
        keywords: ['radiant', 'chaos'] },
      { id: 99, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'Beautiful chaos is the best kind. So, are you checking out today, or...?',
        user: 'That is what I wanted to discuss. Could I extend for one more night?',
        keywords: ['discuss', 'extend'] },
      { id: 100, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'Extend? I thought you could not wait to get home! What changed your mind, Daniel?',
        user: 'This city changed my mind. I have not finished photographing it, not even close.',
        keywords: ['changed', 'close'] },
      { id: 101, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'The city has that effect on people. Let me check what we have for tonight, then.',
        user: 'Take your time. No hurry now — the wedding pressure is completely gone.',
        keywords: ['hurry', 'pressure'] },
      { id: 102, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'No pressure, just pleasure. Good news — room four twelve is yours for another night!',
        user: 'Room four twelve again! It feels like my own little sanctuary in this city.',
        keywords: ['sanctuary', 'little'] },
      { id: 103, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'Sanctuary is a lovely word for it. What will you do with your bonus day, photographer?',
        user: "Wander with no map. Get gloriously lost in the old town's winding streets.",
        keywords: ['wander', 'gloriously'] },
      { id: 104, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'Gloriously lost is the only way to truly see a city. Can I suggest the riverside market?',
        user: 'The riverside market sounds perfect. What makes it special, in your expert opinion?',
        keywords: ['riverside', 'expert'] },
      { id: 105, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: "Painters, spice merchants, and the best street food. It is the city's beating heart, honestly.",
        user: 'Beating heart... I love how you talk about this place. It is your home.',
        keywords: ['beating', 'heart'] },
      { id: 106, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'It is home. Though home, I have learned, is more about people than places, really.',
        user: 'People, not places... you are right. This hotel feels like home because of you.',
        keywords: ['people', 'places'] },
      { id: 107, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'Careful, Daniel — flattery like that might earn you another complimentary biscotti.',
        user: 'Flattery for biscotti is a trade I will happily make any day.',
        keywords: ['flattery', 'trade'] },
      { id: 108, chapter: 'Extending Your Stay', speaker: 'NORA',
        agent: 'Deal! One biscotti, coming right up. Enjoy your bonus day, Daniel. You earned it.',
        user: 'Earned it and loving it. Thank you for making this trip utterly unforgettable, Nora.',
        keywords: ['utterly', 'unforgettable'] },
      // ---------- Chapter 10: Checkout ----------
      { id: 109, chapter: 'Checkout', speaker: 'NORA',
        agent: 'Checkout day already? I feel like you just arrived with your nervous best man energy.',
        user: 'It feels like ages ago. I arrived nervous and now leave transformed, somehow.',
        keywords: ['transformed', 'arrived'] },
      { id: 110, chapter: 'Checkout', speaker: 'NORA',
        agent: 'Transformed! From terrified speaker to wedding hero in just four days. Remarkable growth.',
        user: 'Four days that felt like a month. In the best way, I should add.',
        keywords: ['month', 'best'] },
      { id: 111, chapter: 'Checkout', speaker: 'NORA',
        agent: 'The best possible way is the only way we do things here. Shall we settle the bill?',
        user: 'Let us settle it. Though I am half tempted to just move in permanently.',
        keywords: ['tempted', 'permanently'] },
      { id: 112, chapter: 'Checkout', speaker: 'NORA',
        agent: 'Permanently? Room four twelve is available next month, just saying. No pressure, of course.',
        user: 'Tempting offer! But my plants would die without me. They are very demanding.',
        keywords: ['plants', 'demanding'] },
      { id: 113, chapter: 'Checkout', speaker: 'NORA',
        agent: 'Demanding plants — a valid reason to go home. Your total comes to four hundred twenty.',
        user: 'Four hundred twenty for four days of magic? That feels like an absolute bargain.',
        keywords: ['bargain', 'absolute'] },
      { id: 114, chapter: 'Checkout', speaker: 'NORA',
        agent: 'An absolute bargain, agreed. And the memories? Those are entirely free of charge, Daniel.',
        user: 'Free yet priceless at the same time. That is quite a business model.',
        keywords: ['priceless', 'model'] },
      { id: 115, chapter: 'Checkout', speaker: 'NORA',
        agent: 'Our business model is simple: happy guests become lifelong friends. It works surprisingly well.',
        user: 'Lifelong friends... I like that sound. Can I send you my rooftop photos?',
        keywords: ['lifelong', 'sound'] },
      { id: 116, chapter: 'Checkout', speaker: 'NORA',
        agent: 'Please do! I would love to see the city through your talented photographer eyes.',
        user: 'Through my eyes... I will send the sunset series. The amber light was unreal.',
        keywords: ['series', 'unreal'] },
      { id: 117, chapter: 'Checkout', speaker: 'NORA',
        agent: 'I cannot wait. And here — a pastry from the bakery, for the journey home.',
        user: 'A pastry for the journey! You remember everything I love about this city.',
        keywords: ['pastry', 'journey'] },
      { id: 118, chapter: 'Checkout', speaker: 'NORA',
        agent: 'It is my job to remember. Safe travels, Daniel. And give Lily our warmest congratulations.',
        user: 'I will. Thanks, Nora — for the room, the printer, the wisdom, the friendship.',
        keywords: ['wisdom', 'friendship'] },
      { id: 119, chapter: 'Checkout', speaker: 'NORA',
        agent: 'The friendship was mutual, I assure you. Now go — before we both get embarrassingly sentimental.',
        user: 'Too late for me! One quick hug? Or is that against hotel policy, Nora?',
        keywords: ['against', 'policy'] },
      { id: 120, chapter: 'Checkout', speaker: 'NORA',
        agent: 'Against policy? Never. Come here, you big softie. Travel safe, Daniel Reyes.',
        user: 'I will, Nora. This stay became a cherished life chapter.',
        keywords: ['cherished', 'chapter'] },
      // ---------- Chapter 11: Lost & Found ----------
      { id: 121, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'Front desk, Nora speaking. Daniel? You sound panicked — what happened, are you alright?',
        user: "Nora, disaster! I left my camera lens in the room! My grandfather's precious lens!",
        keywords: ['disaster', 'precious'] },
      { id: 122, chapter: 'Lost & Found', speaker: 'NORA',
        agent: "Breathe, Daniel. Which lens — the one from your grandfather's beloved film camera?",
        user: 'Yes, that one! Irreplaceable. I am at the airport and my flight boards soon.',
        keywords: ['irreplaceable', 'boards'] },
      { id: 123, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'Irreplaceable is my least favorite word, but do not worry. I will check right now.',
        user: "Please hurry! I cannot lose the one thing connecting me to my grandfather's memory.",
        keywords: ['connecting', 'memory'] },
      { id: 124, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'I understand completely. Hold the line — I am sending Rosa up to four twelve immediately.',
        user: 'Rosa to the rescue again! She is becoming my personal guardian angel, honestly.',
        keywords: ['rescue', 'angel'] },
      { id: 125, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'Guardian angel Rosa reports: found it! It was hiding under the bed, the sneaky thing.',
        user: 'Found it! Oh, thank goodness! I could hug Rosa through the phone right now.',
        keywords: ['goodness', 'hug'] },
      { id: 126, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'She would like that. Now — I can courier it to you today. What is your home address?',
        user: 'Courier today would be amazing. I will text you my address after this call.',
        keywords: ['courier', 'text'] },
      { id: 127, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'Text it over, and I will personally pack it with enough bubble wrap for a royal treasure.',
        user: 'Royal treasure treatment — perfect. It survived my grandfather, it will survive shipping.',
        keywords: ['royal', 'treasure'] },
      { id: 128, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'It will arrive safe and sound, I promise. Now go catch that flight, Daniel!',
        user: 'Catching it now! Nora, you have saved me twice this trip. You are unbelievable.',
        keywords: ['catching', 'unbelievable'] },
      { id: 129, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'Twice? Let me count: thermostat, printer, lens... that is three times, actually.',
        user: 'Three times! Keeping score? I suppose I owe you a lifetime of biscotti.',
        keywords: ['score', 'lifetime'] },
      { id: 130, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'A lifetime of biscotti sounds fair. Though I would settle for those rooftop photos, too.',
        user: 'Photos and biscotti, both promised. You drive a hard bargain, Nora Lindqvist.',
        keywords: ['promised', 'bargain'] },
      { id: 131, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'Nora Lindqvist drives only the hardest bargains. Go! Your flight will not wait forever.',
        user: 'Going, going! Thank you a million times, Nora. You are simply the best.',
        keywords: ['million', 'simply'] },
      { id: 132, chapter: 'Lost & Found', speaker: 'NORA',
        agent: 'Simply the best — I will put that on my business cards. Fly safe, Daniel!',
        user: 'Fly safe, Nora! This hotel will always have a special place in my heart.',
        keywords: ['special', 'heart'] },
      // ---------- Chapter 12: Polite Complaints ----------
      { id: 133, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Grand Plaza, Nora speaking. Daniel! Is that really you calling a week later?',
        user: 'The one and only! Calling with an important update and one tiny complaint.',
        keywords: ['update', 'tiny'] },
      { id: 134, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'An update and a complaint? This sounds serious. Should I sit down for this, Daniel?',
        user: 'Definitely sit down. First, the update: the lens arrived perfectly safe and sound.',
        keywords: ['definitely', 'perfectly'] },
      { id: 135, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Perfectly safe! Wonderful news. Rosa and I were both holding our breath all week.',
        user: "You can breathe now. It is back on my grandfather's camera, where it belongs.",
        keywords: ['breathe', 'belongs'] },
      { id: 136, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Where it belongs — I love that. Now, what is this tiny complaint you mentioned?',
        user: 'Well... the air conditioning in four twelve was a bit enthusiastic, shall we say?',
        keywords: ['enthusiastic', 'shall'] },
      { id: 137, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Enthusiastic! That is certainly a polite way to describe an arctic wind, Daniel.',
        user: 'I am practicing my polite complaint skills. How am I doing so far, honestly?',
        keywords: ['practicing', 'skills'] },
      { id: 138, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Top marks for politeness! And I promise the thermostat is already scheduled for replacement.',
        user: 'Scheduled for replacement? See, this is why I love this hotel. You actually listen.',
        keywords: ['scheduled', 'listen'] },
      { id: 139, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'We always listen. Now, is there anything else — praise, perhaps, to balance the complaint?',
        user: "Praise? Where do I begin? The sunset, the swan towels, Abernathy's wisdom, your kindness...",
        keywords: ['begin', 'kindness'] },
      { id: 140, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Stop, you are making me blush! Though please continue — I am taking notes for my manager.',
        user: 'Tell your manager that Nora Lindqvist is the reason guests become lifelong friends.',
        keywords: ['manager', 'reason'] },
      { id: 141, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Lifelong friends... you remembered our business model! I am genuinely touched, Daniel.',
        user: 'How could I forget? Printed on my heart now, right next to the sunset.',
        keywords: ['printed', 'heart'] },
      { id: 142, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Printed on your heart — that belongs in a novel. Maybe room three twelve is free?',
        user: 'A novel! Do not tempt me. I might return just to photograph the hotel.',
        keywords: ['tempt', 'photograph'] },
      { id: 143, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Come back to photograph us? We would be honored! The Grand Plaza loves the spotlight.',
        user: 'Then it is settled. Same room, same view, same brilliant receptionist. See you soon.',
        keywords: ['settled', 'brilliant'] },
      { id: 144, chapter: 'Polite Complaints', speaker: 'NORA',
        agent: 'Same everything, Daniel. The Grand Plaza will be right here, glowing strong, waiting for you.',
        user: 'Glowing strong... I love that. Goodbye for now, Nora. Until the next adventure.',
        keywords: ['glowing', 'adventure'] }
    ]
  };
})();
