/* Speak or Boom — Hotel scenario */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.hotel = {
    id: 'hotel',
    title: 'Hotel',
    tagline: 'A Night Away From Home',
    speaker: 'RECEPTION',
    difficulty: 'Beginner',
    rounds: [
      // Chapter 1: Making a Reservation
      { id: 'hotel-001', chapter: 'Making a Reservation',
        agent: 'Good morning, Grand Plaza Hotel. How may I help you?',
        user: 'Good morning. I would like to book a room.',
        keywords: ['book', 'room'] },
      { id: 'hotel-002', chapter: 'Making a Reservation',
        agent: 'Of course. What dates are you planning to stay?',
        user: 'From Friday to Sunday, two nights.',
        keywords: ['friday', 'nights'] },
      { id: 'hotel-003', chapter: 'Making a Reservation',
        agent: 'And what type of room would you prefer?',
        user: 'A double room, please.',
        keywords: ['double', 'room'] },
      { id: 'hotel-004', chapter: 'Making a Reservation',
        agent: 'Would you prefer a smoking or non-smoking room?',
        user: 'A non-smoking room, please.',
        keywords: ['room'] },
      { id: 'hotel-005', chapter: 'Making a Reservation',
        agent: 'May I have your full name, please?',
        user: 'My name is Li Zhengfang.',
        keywords: ['name'] },
      { id: 'hotel-006', chapter: 'Making a Reservation',
        agent: 'And a phone number where we can reach you?',
        user: 'My mobile number is 555-0134.',
        keywords: ['number'] },
      { id: 'hotel-007', chapter: 'Making a Reservation',
        agent: 'Do you need breakfast included in your rate?',
        user: 'Yes, please include breakfast.',
        keywords: ['breakfast'] },
      { id: 'hotel-008', chapter: 'Making a Reservation',
        agent: 'We have a sea view room for a little extra.',
        user: 'That sounds nice. I will take it.',
        keywords: ['sounds', 'take'] },
      { id: 'hotel-009', chapter: 'Making a Reservation',
        agent: 'What time do you expect to arrive?',
        user: 'I will arrive around six in the evening.',
        keywords: ['arrive', 'evening'] },
      { id: 'hotel-010', chapter: 'Making a Reservation',
        agent: 'Would you like a quiet room on a high floor?',
        user: 'Yes, a high floor would be great.',
        keywords: ['high', 'floor'] },
      { id: 'hotel-011', chapter: 'Making a Reservation',
        agent: 'Is there anything else I can do for you?',
        user: 'No, thank you. That is everything.',
        keywords: ['thank'] },
      { id: 'hotel-012', chapter: 'Making a Reservation',
        agent: 'Your reservation is confirmed. See you soon!',
        user: 'Thank you very much. Goodbye!',
        keywords: ['thank', 'goodbye'] },
      // Chapter 2: Arrival & Check-in
      { id: 'hotel-013', chapter: 'Arrival & Check-in',
        agent: 'Welcome to the Grand Plaza Hotel!',
        user: 'Hello! I have a reservation.',
        keywords: ['reservation'] },
      { id: 'hotel-014', chapter: 'Arrival & Check-in',
        agent: 'May I have your name, please?',
        user: 'It is Li Zhengfang. I booked online.',
        keywords: ['booked'] },
      { id: 'hotel-015', chapter: 'Arrival & Check-in',
        agent: 'Could I see your passport or ID, please?',
        user: 'Sure, here is my passport.',
        keywords: ['passport'] },
      { id: 'hotel-016', chapter: 'Arrival & Check-in',
        agent: 'How long will you be staying with us?',
        user: 'Just two nights, until Sunday.',
        keywords: ['nights', 'sunday'] },
      { id: 'hotel-017', chapter: 'Arrival & Check-in',
        agent: 'Your room is 1208, on the twelfth floor.',
        user: 'Great. Where is the elevator?',
        keywords: ['elevator'] },
      { id: 'hotel-018', chapter: 'Arrival & Check-in',
        agent: 'The elevators are just past the lobby.',
        user: 'Thank you. What time is checkout?',
        keywords: ['checkout'] },
      { id: 'hotel-019', chapter: 'Arrival & Check-in',
        agent: 'Checkout time is at twelve noon.',
        user: 'Is late checkout possible?',
        keywords: ['late', 'checkout'] },
      { id: 'hotel-020', chapter: 'Arrival & Check-in',
        agent: 'Yes, until two o\'clock for free.',
        user: 'Perfect, thank you very much.',
        keywords: ['perfect', 'thank'] },
      { id: 'hotel-021', chapter: 'Arrival & Check-in',
        agent: 'Here is your key card. Enjoy your stay!',
        user: 'Thanks! Is Wi-Fi free here?',
        keywords: ['wifi'] },
      { id: 'hotel-022', chapter: 'Arrival & Check-in',
        agent: 'The password is on the card sleeve.',
        user: 'Could you help me with my bags?',
        keywords: ['bags'] },
      { id: 'hotel-023', chapter: 'Arrival & Check-in',
        agent: 'Of course, the bellboy will assist you.',
        user: 'That would be wonderful, thanks.',
        keywords: ['wonderful'] },
      { id: 'hotel-024', chapter: 'Arrival & Check-in',
        agent: 'Is there anything else you need right now?',
        user: 'No, I am all set. Thanks!',
        keywords: ['set'] },
      // Chapter 3: Room Requests
      { id: 'hotel-025', chapter: 'Room Requests',
        agent: 'Hello, front desk. How can I help you?',
        user: 'Hi, could I get some extra towels?',
        keywords: ['extra', 'towels'] },
      { id: 'hotel-026', chapter: 'Room Requests',
        agent: 'Of course. How many would you like?',
        user: 'Two more towels, please.',
        keywords: ['towels'] },
      { id: 'hotel-027', chapter: 'Room Requests',
        agent: 'Is there anything else for your room?',
        user: 'Could I also have an extra pillow?',
        keywords: ['pillow'] },
      { id: 'hotel-028', chapter: 'Room Requests',
        agent: 'Certainly. We will bring them right up.',
        user: 'Thank you so much for your help.',
        keywords: ['thank'] },
      { id: 'hotel-029', chapter: 'Room Requests',
        agent: 'Would you like a room with a bathtub?',
        user: 'Yes, a bathtub would be lovely.',
        keywords: ['bathtub'] },
      { id: 'hotel-030', chapter: 'Room Requests',
        agent: 'Do you need a crib for the baby?',
        user: 'No baby, but thanks for asking.',
        keywords: ['thanks'] },
      { id: 'hotel-031', chapter: 'Room Requests',
        agent: 'We can send up an iron and board.',
        user: 'That would be very helpful.',
        keywords: ['helpful'] },
      { id: 'hotel-032', chapter: 'Room Requests',
        agent: 'Would you prefer a quieter room?',
        user: 'Yes, away from the elevator, please.',
        keywords: ['elevator'] },
      { id: 'hotel-033', chapter: 'Room Requests',
        agent: 'I can move you to the garden side.',
        user: 'That sounds perfect. Thank you.',
        keywords: ['perfect'] },
      { id: 'hotel-034', chapter: 'Room Requests',
        agent: 'Do you need a wake-up call tomorrow?',
        user: 'Yes, please call me at seven.',
        keywords: ['seven'] },
      { id: 'hotel-035', chapter: 'Room Requests',
        agent: 'Seven AM sharp. Is there anything else?',
        user: 'Could I get a city map, too?',
        keywords: ['map'] },
      { id: 'hotel-036', chapter: 'Room Requests',
        agent: 'We will leave one at your door.',
        user: 'Great, I really appreciate it.',
        keywords: ['appreciate'] },
      // Chapter 4: Room Problems
      { id: 'hotel-037', chapter: 'Room Problems',
        agent: 'Front desk, what seems to be the problem?',
        user: 'The air conditioner is not working.',
        keywords: ['conditioner'] },
      { id: 'hotel-038', chapter: 'Room Problems',
        agent: 'I am sorry to hear that. Which room?',
        user: 'Room 1208, on the twelfth floor.',
        keywords: ['1208'] },
      { id: 'hotel-039', chapter: 'Room Problems',
        agent: 'I will send maintenance up right away.',
        user: 'Thank you. How long will it take?',
        keywords: ['long'] },
      { id: 'hotel-040', chapter: 'Room Problems',
        agent: 'About fifteen minutes, I would say.',
        user: 'That is fine. I will wait in the room.',
        keywords: ['wait'] },
      { id: 'hotel-041', chapter: 'Room Problems',
        agent: 'Is the TV in your room working properly?',
        user: 'Actually, the TV has no signal.',
        keywords: ['signal'] },
      { id: 'hotel-042', chapter: 'Room Problems',
        agent: 'Have you tried the remote control?',
        user: 'Yes, but nothing happens at all.',
        keywords: ['happens'] },
      { id: 'hotel-043', chapter: 'Room Problems',
        agent: 'The shower water is too hot, you said?',
        user: 'Yes, I can not adjust the temperature.',
        keywords: ['temperature'] },
      { id: 'hotel-044', chapter: 'Room Problems',
        agent: 'We will fix it within the hour.',
        user: 'Could I change rooms instead?',
        keywords: ['change', 'rooms'] },
      { id: 'hotel-045', chapter: 'Room Problems',
        agent: 'Let me check what is available.',
        user: 'I would prefer a room upstairs, please.',
        keywords: ['upstairs'] },
      { id: 'hotel-046', chapter: 'Room Problems',
        agent: 'You mentioned a strange noise, correct?',
        user: 'Yes, the room next door is noisy.',
        keywords: ['noisy'] },
      { id: 'hotel-047', chapter: 'Room Problems',
        agent: 'I sincerely apologize for the disturbance.',
        user: 'It is okay, just please fix it.',
        keywords: ['fix'] },
      { id: 'hotel-048', chapter: 'Room Problems',
        agent: 'We have moved you to room 1502.',
        user: 'Thank you for handling this quickly.',
        keywords: ['quickly'] },
      // Chapter 5: Housekeeping
      { id: 'hotel-049', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'Housekeeping! May I come in, please?',
        user: 'Yes, come in, please.',
        keywords: ['come'] },
      { id: 'hotel-050', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'Would you like your room cleaned now?',
        user: 'Yes, please clean the room now.',
        keywords: ['clean'] },
      { id: 'hotel-051', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'Should I change the bedsheets too?',
        user: 'Yes, fresh sheets would be nice.',
        keywords: ['sheets'] },
      { id: 'hotel-052', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'Do you need the minibar restocked?',
        user: 'Just two bottles of water, please.',
        keywords: ['water'] },
      { id: 'hotel-053', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'I will replace the towels as well.',
        user: 'Thank you, that would be great.',
        keywords: ['thank'] },
      { id: 'hotel-054', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'What time should I come back?',
        user: 'Please come back after lunch.',
        keywords: ['lunch'] },
      { id: 'hotel-055', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'I will leave fresh soap in the bathroom.',
        user: 'Could you bring more shampoo, too?',
        keywords: ['shampoo'] },
      { id: 'hotel-056', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'Is the room temperature comfortable for you?',
        user: 'It is a little cold, actually.',
        keywords: ['cold'] },
      { id: 'hotel-057', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'I will turn the heating up for you.',
        user: 'Thanks, I appreciate your help.',
        keywords: ['appreciate'] },
      { id: 'hotel-058', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'Would you like turndown service tonight?',
        user: 'What time is turndown service?',
        keywords: ['turndown'] },
      { id: 'hotel-059', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'We come around eight in the evening.',
        user: 'Eight o\'clock works for me.',
        keywords: ['eight'] },
      { id: 'hotel-060', chapter: 'Housekeeping', speaker: 'HOUSEKEEPING',
        agent: 'Your room is all done. Enjoy!',
        user: 'Thank you! It looks wonderful.',
        keywords: ['wonderful'] },
      // Chapter 6: Breakfast
      { id: 'hotel-061', chapter: 'Breakfast',
        agent: 'Good morning! Table for how many?',
        user: 'Just one person, please.',
        keywords: ['person'] },
      { id: 'hotel-062', chapter: 'Breakfast',
        agent: 'Breakfast is served until ten thirty.',
        user: 'What time does it start?',
        keywords: ['start'] },
      { id: 'hotel-063', chapter: 'Breakfast',
        agent: 'We start at six thirty AM.',
        user: 'Is breakfast included in my room?',
        keywords: ['included'] },
      { id: 'hotel-064', chapter: 'Breakfast',
        agent: 'Yes, it is included in your rate.',
        user: 'Wonderful. Where should I sit?',
        keywords: ['sit'] },
      { id: 'hotel-065', chapter: 'Breakfast',
        agent: 'Anywhere you like by the window.',
        user: 'Could I have some coffee, please?',
        keywords: ['coffee'] },
      { id: 'hotel-066', chapter: 'Breakfast',
        agent: 'Would you like eggs or pancakes?',
        user: 'Scrambled eggs would be lovely.',
        keywords: ['eggs'] },
      { id: 'hotel-067', chapter: 'Breakfast',
        agent: 'Would you like white toast or whole wheat?',
        user: 'Whole wheat toast, please.',
        keywords: ['wheat'] },
      { id: 'hotel-068', chapter: 'Breakfast',
        agent: 'Would you like some fresh orange juice?',
        user: 'Yes, orange juice sounds great.',
        keywords: ['juice'] },
      { id: 'hotel-069', chapter: 'Breakfast',
        agent: 'Can I get you anything else?',
        user: 'Some more coffee, please.',
        keywords: ['coffee'] },
      { id: 'hotel-070', chapter: 'Breakfast',
        agent: 'How was your breakfast this morning?',
        user: 'It was delicious, thank you.',
        keywords: ['delicious'] },
      { id: 'hotel-071', chapter: 'Breakfast',
        agent: 'Would you like the bill now?',
        user: 'It is included, is it not?',
        keywords: ['included'] },
      { id: 'hotel-072', chapter: 'Breakfast',
        agent: 'Yes, all set. Have a great day!',
        user: 'You too! See you tomorrow.',
        keywords: ['tomorrow'] },
      // Chapter 7: Hotel Facilities
      { id: 'hotel-073', chapter: 'Hotel Facilities',
        agent: 'The pool is on the third floor.',
        user: 'What are the pool hours?',
        keywords: ['pool', 'hours'] },
      { id: 'hotel-074', chapter: 'Hotel Facilities',
        agent: 'From seven AM to ten PM.',
        user: 'Do I need to bring a towel?',
        keywords: ['towel'] },
      { id: 'hotel-075', chapter: 'Hotel Facilities',
        agent: 'Towels are provided at the pool.',
        user: 'Is there a gym as well?',
        keywords: ['gym'] },
      { id: 'hotel-076', chapter: 'Hotel Facilities',
        agent: 'Yes, the gym is open all day.',
        user: 'What time does it close?',
        keywords: ['close'] },
      { id: 'hotel-077', chapter: 'Hotel Facilities',
        agent: 'It closes at eleven at night.',
        user: 'Great, I will go this evening.',
        keywords: ['evening'] },
      { id: 'hotel-078', chapter: 'Hotel Facilities',
        agent: 'The spa offers massages from noon.',
        user: 'How do I book a massage?',
        keywords: ['book', 'massage'] },
      { id: 'hotel-079', chapter: 'Hotel Facilities',
        agent: 'I can book one for you now.',
        user: 'That would be lovely, thank you.',
        keywords: ['lovely'] },
      { id: 'hotel-080', chapter: 'Hotel Facilities',
        agent: 'There is free parking in the basement.',
        user: 'Where is the parking entrance?',
        keywords: ['parking'] },
      { id: 'hotel-081', chapter: 'Hotel Facilities',
        agent: 'Just around the corner, past reception.',
        user: 'Is the parking free for guests?',
        keywords: ['free'] },
      { id: 'hotel-082', chapter: 'Hotel Facilities',
        agent: 'Yes, just show your room key.',
        user: 'Perfect. Is there a business center?',
        keywords: ['business'] },
      { id: 'hotel-083', chapter: 'Hotel Facilities',
        agent: 'On the second floor, open 24 hours.',
        user: 'Can I print something there?',
        keywords: ['print'] },
      { id: 'hotel-084', chapter: 'Hotel Facilities',
        agent: 'Of course, it is free for guests.',
        user: 'Thank you for all your help.',
        keywords: ['thank'] },
      // Chapter 8: Business Services
      { id: 'hotel-085', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'How can the business center help you?',
        user: 'I need to print some documents.',
        keywords: ['print', 'documents'] },
      { id: 'hotel-086', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'You can email them to our printer.',
        user: 'What is the email address?',
        keywords: ['email'] },
      { id: 'hotel-087', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'It is print at grandplaza dot com.',
        user: 'Could you spell that for me?',
        keywords: ['spell'] },
      { id: 'hotel-088', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'P-R-I-N-T at grandplaza dot com, all lowercase.',
        user: 'Got it, thank you very much.',
        keywords: ['got'] },
      { id: 'hotel-089', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'Do you need to send a fax?',
        user: 'No, but I need to scan something.',
        keywords: ['scan'] },
      { id: 'hotel-090', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'The scanner is next to the printer.',
        user: 'Could you show me how it works?',
        keywords: ['works'] },
      { id: 'hotel-091', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'We also have meeting rooms available.',
        user: 'How much is a small meeting room?',
        keywords: ['much'] },
      { id: 'hotel-092', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'Two hundred dollars per half day.',
        user: 'That is a bit expensive for me.',
        keywords: ['expensive'] },
      { id: 'hotel-093', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'We offer ten percent off for our guests.',
        user: 'Wonderful! I would like to book it.',
        keywords: ['book'] },
      { id: 'hotel-094', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'Would you like to book it now?',
        user: 'Let me think about it first.',
        keywords: ['think'] },
      { id: 'hotel-095', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'Here is my card if you need anything.',
        user: 'Thank you, I will be in touch.',
        keywords: ['touch'] },
      { id: 'hotel-096', chapter: 'Business Services', speaker: 'BUSINESS CENTER',
        agent: 'Good luck with your meeting today!',
        user: 'Thanks! I hope it goes well.',
        keywords: ['hope'] },
      // Chapter 9: Extending Your Stay
      { id: 'hotel-097', chapter: 'Extending Your Stay',
        agent: 'Front desk, how may I help you?',
        user: 'I would like to extend my stay.',
        keywords: ['extend', 'stay'] },
      { id: 'hotel-098', chapter: 'Extending Your Stay',
        agent: 'For how many extra nights, please?',
        user: 'Just one more night, please.',
        keywords: ['night'] },
      { id: 'hotel-099', chapter: 'Extending Your Stay',
        agent: 'Let me check the room availability now.',
        user: 'I hope my room is free.',
        keywords: ['hope', 'free'] },
      { id: 'hotel-100', chapter: 'Extending Your Stay',
        agent: 'Good news, you can stay in 1208.',
        user: 'That is great, thank you.',
        keywords: ['great'] },
      { id: 'hotel-101', chapter: 'Extending Your Stay',
        agent: 'The rate is the same as before.',
        user: 'Perfect. Please extend it.',
        keywords: ['extend'] },
      { id: 'hotel-102', chapter: 'Extending Your Stay',
        agent: 'Would you like late checkout instead?',
        user: 'Both would be ideal, actually.',
        keywords: ['ideal'] },
      { id: 'hotel-103', chapter: 'Extending Your Stay',
        agent: 'I can offer checkout at two PM.',
        user: 'Two o\'clock is perfect for me.',
        keywords: ['perfect'] },
      { id: 'hotel-104', chapter: 'Extending Your Stay',
        agent: 'Shall I update your reservation now?',
        user: 'Yes, please go ahead.',
        keywords: ['ahead'] },
      { id: 'hotel-105', chapter: 'Extending Your Stay',
        agent: 'All done. Is there anything else?',
        user: 'Could I get a new key card?',
        keywords: ['card'] },
      { id: 'hotel-106', chapter: 'Extending Your Stay',
        agent: 'Your old card will still work.',
        user: 'Good to know, thanks.',
        keywords: ['know'] },
      { id: 'hotel-107', chapter: 'Extending Your Stay',
        agent: 'Enjoy the rest of your stay!',
        user: 'Thank you, I will.',
        keywords: ['will'] },
      { id: 'hotel-108', chapter: 'Extending Your Stay',
        agent: 'We really appreciate you choosing our hotel.',
        user: 'It is a lovely hotel, honestly.',
        keywords: ['lovely'] },
      // Chapter 10: Checkout
      { id: 'hotel-109', chapter: 'Checkout',
        agent: 'Good morning! Are you checking out today?',
        user: 'Yes, I am checking out now.',
        keywords: ['checking'] },
      { id: 'hotel-110', chapter: 'Checkout',
        agent: 'May I have your room number?',
        user: 'I am in room 1208.',
        keywords: ['1208'] },
      { id: 'hotel-111', chapter: 'Checkout',
        agent: 'Did you use anything from the minibar?',
        user: 'Just a bottle of water.',
        keywords: ['water'] },
      { id: 'hotel-112', chapter: 'Checkout',
        agent: 'I will add that to your bill.',
        user: 'Could I see the bill, please?',
        keywords: ['bill'] },
      { id: 'hotel-113', chapter: 'Checkout',
        agent: 'Here is your itemized bill, sir.',
        user: 'Everything looks correct, thank you.',
        keywords: ['correct'] },
      { id: 'hotel-114', chapter: 'Checkout',
        agent: 'How would you like to pay?',
        user: 'By credit card, please.',
        keywords: ['credit'] },
      { id: 'hotel-115', chapter: 'Checkout',
        agent: 'Could I see the card, please?',
        user: 'Here you are, thank you.',
        keywords: ['here'] },
      { id: 'hotel-116', chapter: 'Checkout',
        agent: 'Please sign your name right here.',
        user: 'Sure, where do I sign?',
        keywords: ['sign'] },
      { id: 'hotel-117', chapter: 'Checkout',
        agent: 'Would you like a receipt for your stay?',
        user: 'Yes, please email it to me.',
        keywords: ['email'] },
      { id: 'hotel-118', chapter: 'Checkout',
        agent: 'Can I call you a taxi?',
        user: 'Yes, to the airport, please.',
        keywords: ['airport'] },
      { id: 'hotel-119', chapter: 'Checkout',
        agent: 'The taxi will be here soon.',
        user: 'Thank you for everything.',
        keywords: ['thank'] },
      { id: 'hotel-120', chapter: 'Checkout',
        agent: 'We hope to see you again!',
        user: 'I had a wonderful stay, goodbye!',
        keywords: ['wonderful', 'goodbye'] },
      // Chapter 11: Lost & Found
      { id: 'hotel-121', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'Lost and found, how can I help?',
        user: 'I think I left something behind.',
        keywords: ['left'] },
      { id: 'hotel-122', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'What exactly did you lose, sir?',
        user: 'My black umbrella, I believe.',
        keywords: ['umbrella'] },
      { id: 'hotel-123', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'Where did you last see it?',
        user: 'Probably in the restaurant.',
        keywords: ['restaurant'] },
      { id: 'hotel-124', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'What does the item look like?',
        user: 'It is black with a wooden handle.',
        keywords: ['handle'] },
      { id: 'hotel-125', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'Let me check our storage room.',
        user: 'Thank you, I will hold on.',
        keywords: ['hold'] },
      { id: 'hotel-126', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'Yes, we found a black umbrella!',
        user: 'That is wonderful news, thank you.',
        keywords: ['wonderful'] },
      { id: 'hotel-127', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'Can you describe it once more?',
        user: 'Black, with a curved wooden handle.',
        keywords: ['curved'] },
      { id: 'hotel-128', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'That matches. When can you collect it?',
        user: 'I will pick it up this evening.',
        keywords: ['evening'] },
      { id: 'hotel-129', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'It is at the front desk now.',
        user: 'Perfect, I will stop by soon.',
        keywords: ['soon'] },
      { id: 'hotel-130', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'Please bring some ID with you.',
        user: 'Of course, no problem at all.',
        keywords: ['problem'] },
      { id: 'hotel-131', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'We are glad we could help you.',
        user: 'Thank you for finding it.',
        keywords: ['finding'] },
      { id: 'hotel-132', chapter: 'Lost & Found', speaker: 'LOST & FOUND',
        agent: 'Have a very safe trip home!',
        user: 'Thanks, goodbye and take care!',
        keywords: ['care'] },
      // Chapter 12: Polite Complaints
      { id: 'hotel-133', chapter: 'Polite Complaints',
        agent: 'Front desk. How can I help you?',
        user: 'I am afraid my room is too noisy.',
        keywords: ['noisy'] },
      { id: 'hotel-134', chapter: 'Polite Complaints',
        agent: 'I am very sorry to hear that.',
        user: 'There is loud music next door.',
        keywords: ['music'] },
      { id: 'hotel-135', chapter: 'Polite Complaints',
        agent: 'I will speak to those guests now.',
        user: 'Thank you, I would appreciate that.',
        keywords: ['appreciate'] },
      { id: 'hotel-136', chapter: 'Polite Complaints',
        agent: 'You mentioned the hallway lights, correct?',
        user: 'Yes, they are too bright at night.',
        keywords: ['bright'] },
      { id: 'hotel-137', chapter: 'Polite Complaints',
        agent: 'I sincerely apologize for this inconvenience.',
        user: 'Could I move to another room?',
        keywords: ['move'] },
      { id: 'hotel-138', chapter: 'Polite Complaints',
        agent: 'Let me see what is available.',
        user: 'A quieter room would be ideal.',
        keywords: ['quieter'] },
      { id: 'hotel-139', chapter: 'Polite Complaints',
        agent: 'The Wi-Fi seems slow, you said?',
        user: 'Yes, it keeps disconnecting.',
        keywords: ['disconnecting'] },
      { id: 'hotel-140', chapter: 'Polite Complaints',
        agent: 'We will reset the router right away.',
        user: 'Thank you for your quick response.',
        keywords: ['response'] },
      { id: 'hotel-141', chapter: 'Polite Complaints',
        agent: 'Is the breakfast area too crowded?',
        user: 'A little, but the food is great.',
        keywords: ['food', 'great'] },
      { id: 'hotel-142', chapter: 'Polite Complaints',
        agent: 'Your feedback is very valuable to us.',
        user: 'I am glad you take it seriously.',
        keywords: ['seriously'] },
      { id: 'hotel-143', chapter: 'Polite Complaints',
        agent: 'We would like to offer you dessert.',
        user: 'That is very kind of you.',
        keywords: ['kind'] },
      { id: 'hotel-144', chapter: 'Polite Complaints',
        agent: 'Thank you very much for your patience.',
        user: 'Thank you for listening to me.',
        keywords: ['listening'] }
    ]
  };
})();
