/* Speak or Boom — Job Interview v2 (rich, narrative) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.interview = {
    id: 'interview',
    title: 'Job Interview',
    tagline: 'Land the Offer',
    speaker: 'INTERVIEWER',
    difficulty: 'Advanced',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: Welcome & Small Talk ----------
      { id: 1, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'David! Welcome in. I am Helen, VP of Product. Please, make yourself comfortable.',
        user: 'Thank you, Helen. It is wonderful to finally meet you in person today.',
        keywords: ['wonderful', 'finally'] },
      { id: 2, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'Can I get you some water or coffee before we dive into the conversation?',
        user: 'A glass of water would be perfect, thank you. I am feeling quite energized.',
        keywords: ['perfect', 'energized'] },
      { id: 3, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'You arrived early, I noticed. Punctuality is a rare virtue in this chaotic city.',
        user: 'I always plan for the worst traffic. Better early and calm than rushed.',
        keywords: ['traffic', 'better'] },
      { id: 4, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'Wise policy. Did the rain cause you any trouble on the way over here?',
        user: 'Not at all. I brought an umbrella and actually enjoyed the quiet, rainy streets.',
        keywords: ['umbrella', 'enjoyed'] },
      { id: 5, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'A rainy-day optimist! I like that. What do you think of our office so far?',
        user: 'It feels warm and alive. The plants everywhere make it feel less corporate.',
        keywords: ['alive', 'corporate'] },
      { id: 6, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'The plants were my doing. A little greenery keeps everyone sane during long sprints.',
        user: 'It clearly works. I can already sense a thoughtful culture just walking through.',
        keywords: ['thoughtful', 'clearly'] },
      { id: 7, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'Thoughtful is exactly what we aim for. So, how are the nerves holding up?',
        user: 'Honestly, I am more excited than nervous. I have looked forward to this conversation.',
        keywords: ['excited', 'conversation'] },
      { id: 8, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'Excitement beats nerves every time. We had a lovely phone chat last week, by the way.',
        user: 'I enjoyed it too. It left me even more curious about the team.',
        keywords: ['curious', 'enjoyed'] },
      { id: 9, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'Curiosity is a great sign. Before we begin, is there anything you need right now?',
        user: 'I am all set. Shall we dive right in whenever you are ready, Helen?',
        keywords: ['ready'] },
      { id: 10, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'Let me grab my notes. I read your portfolio twice — it genuinely impressed me.',
        user: 'That means a great deal. I poured my heart into those case studies, honestly.',
        keywords: ['honestly', 'studies'] },
      { id: 11, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'It showed. One more thing — this is a conversation, not an interrogation, alright?',
        user: 'I appreciate that. The best interviews always feel like genuine human exchanges.',
        keywords: ['appreciate', 'interviews'] },
      { id: 12, chapter: 'Welcome & Small Talk', speaker: 'HELEN',
        agent: 'Exactly my philosophy. Alright, let us start at the beginning of your story.',
        user: 'Perfect. Where would you like me to begin — childhood dreams or career pivots?',
        keywords: ['childhood', 'pivots'] },
      // ---------- Chapter 2: Tell Me About Yourself ----------
      { id: 13, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'Let us start with childhood dreams. What did little David want to become?',
        user: 'An architect, actually. I was obsessed with building tiny cities from cardboard boxes.',
        keywords: ['architect', 'obsessed'] },
      { id: 14, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'From cardboard cities to digital products — that is quite an architectural evolution.',
        user: 'The medium changed, but the impulse stayed the same: shaping spaces people inhabit.',
        keywords: ['impulse', 'inhabit'] },
      { id: 15, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'Shaping spaces people inhabit — that is a beautiful way to describe product design.',
        user: 'Thank you. I truly believe interfaces are the architecture of modern daily life.',
        keywords: ['interfaces', 'architecture'] },
      { id: 16, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'So how did you travel from architecture dreams to actual product design work?',
        user: 'I studied engineering first, then realized I cared more about humans than structures.',
        keywords: ['engineering', 'structures'] },
      { id: 17, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'Humans over structures — many great designers share that exact turning point.',
        user: 'It felt like coming home. Suddenly every problem was about empathy, not equations.',
        keywords: ['empathy', 'equations'] },
      { id: 18, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'Was there a single moment when you knew design was your true calling?',
        user: 'I watched my grandmother struggle with a banking app, furious at its cruelty.',
        keywords: ['grandmother', 'cruelty'] },
      { id: 19, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'Cruelty is a strong word for bad design, but I completely understand the fury.',
        user: 'It was cruel — tiny text, confusing flows. She deserved dignity, not frustration.',
        keywords: ['confusing', 'dignity'] },
      { id: 20, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'Dignity through design. That experience clearly still fuels your work today, does it not?',
        user: 'I keep her photo near my desk as a reminder of who I serve.',
        keywords: ['reminder', 'serve'] },
      { id: 21, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'That is profoundly moving. So you taught yourself design — how did that journey unfold?',
        user: 'Nights and weekends for two years. Online courses, mentors, and countless rejected concepts.',
        keywords: ['mentors', 'rejected'] },
      { id: 22, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'Two years of nights and weekends shows remarkable discipline. What kept you going?',
        user: 'The moment a real user smiled at my work. That feeling is utterly addictive.',
        keywords: ['utterly', 'addictive'] },
      { id: 23, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'Utterly addictive indeed. And now, six years in — how would you describe your design philosophy?',
        user: 'Clarity is kindness. Every pixel should reduce confusion, never add to it.',
        keywords: ['clarity', 'kindness'] },
      { id: 24, chapter: 'Tell Me About Yourself', speaker: 'HELEN',
        agent: 'Clarity is kindness — I am writing that down. Let us talk about where you applied it.',
        user: 'My favorite example is a healthcare project. It tested everything I believed in.',
        keywords: ['healthcare', 'believed'] },
      // ---------- Chapter 3: Work Experience ----------
      { id: 25, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'A healthcare project sounds meaningful. Tell me the story from the very beginning.',
        user: 'We were redesigning a medication app for elderly patients managing multiple prescriptions daily.',
        keywords: ['medication', 'prescriptions'] },
      { id: 26, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'Elderly patients with multiple prescriptions — the stakes there could not be higher.',
        user: 'Exactly. A confusing interface was not just annoying; it was genuinely dangerous for them.',
        keywords: ['dangerous', 'genuinely'] },
      { id: 27, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'How did you begin? Research with elderly users must present unique challenges.',
        user: 'We visited their homes, watched them struggle, and listened without interrupting or judging.',
        keywords: ['interrupting', 'judging'] },
      { id: 28, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'Listening without judging — harder than it sounds. What surprised you most during research?',
        user: 'Their fear. They were terrified of making mistakes, so they avoided the app entirely.',
        keywords: ['terrified', 'avoided'] },
      { id: 29, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'Fear of mistakes paralyzing users — that reframes the entire design challenge, does it not?',
        user: 'Completely. We stopped optimizing for efficiency and started designing for reassurance instead.',
        keywords: ['reassurance', 'completely'] },
      { id: 30, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'Designing for reassurance rather than efficiency — that is a profound shift in priorities.',
        user: 'We added gentle confirmations, huge touch targets, and a prominent call-nurse button.',
        keywords: ['confirmations', 'prominent'] },
      { id: 31, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'A call-nurse button — brilliant. Sometimes the best interface admits its own limitations.',
        user: 'Precisely. Technology should know when to step aside and let humans help humans.',
        keywords: ['technology', 'precisely'] },
      { id: 32, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'Humans helping humans — I love that principle. What were the measurable results?',
        user: 'Medication errors dropped forty percent, and daily active usage tripled within three months.',
        keywords: ['tripled', 'months'] },
      { id: 33, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'Forty percent fewer errors is not a metric — that is lives genuinely improved, David.',
        user: 'That kept me going through hard weeks. Impact felt in my bones.',
        keywords: ['impact', 'bones'] },
      { id: 34, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'What was the hardest decision you had to make during that entire project?',
        user: 'Killing a beautiful animation system that confused users. It hurt, but clarity won.',
        keywords: ['animation', 'clarity'] },
      { id: 35, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'Killing your darlings for clarity — the mark of a mature designer, honestly.',
        user: 'It taught me ego has no place in design. The user decides.',
        keywords: ['taught', 'decides'] },
      { id: 36, chapter: 'Work Experience', speaker: 'HELEN',
        agent: 'The user is always the final judge — I could not agree more. Let us shift gears slightly.',
        user: 'Of course. I am curious where you want to take this conversation next, Helen.',
        keywords: ['conversation', 'curious'] },
      // ---------- Chapter 4: Your Strengths ----------
      { id: 37, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'Let us talk strengths now. But skip the buzzwords — show me through real stories.',
        user: 'Fair enough. My greatest strength is translating ambiguity into clear, actionable direction.',
        keywords: ['translating', 'ambiguity'] },
      { id: 38, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'Translating ambiguity into direction — every product team desperately needs that skill.',
        user: 'I once inherited a project with no brief, no research, just a vague mandate.',
        keywords: ['inherited', 'mandate'] },
      { id: 39, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'No brief, no research, just vibes from above — every designer’s nightmare scenario.',
        user: 'Instead of panicking, I interviewed twenty stakeholders in my first two weeks there.',
        keywords: ['stakeholders', 'panicking'] },
      { id: 40, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'Twenty stakeholder interviews in two weeks — that is serious detective work, David.',
        user: 'By week three, I had mapped the real problem. The mandate was completely wrong.',
        keywords: ['completely', 'mandate'] },
      { id: 41, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'The mandate was wrong? That takes courage to tell leadership, does it not?',
        user: 'It was terrifying. But data beats hierarchy, so I presented the evidence respectfully.',
        keywords: ['terrifying', 'hierarchy'] },
      { id: 42, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'Data beats hierarchy — I am adding that to my notebook too. What happened next?',
        user: 'They pivoted the entire roadmap. The product launched successfully six months later.',
        keywords: ['pivoted', 'roadmap'] },
      { id: 43, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'From vague mandate to successful launch — that is systems thinking in action, truly.',
        user: 'My second strength is mentoring. Helping juniors grow gives me enormous satisfaction.',
        keywords: ['mentoring', 'satisfaction'] },
      { id: 44, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'Mentoring others while delivering yourself — how do you balance those competing demands?',
        user: 'I treat mentoring as multiplication. Their growth amplifies the entire team’s output.',
        keywords: ['multiplication', 'amplifies'] },
      { id: 45, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'Mentoring as multiplication — what a lovely reframe of what many see as a burden.',
        user: 'One mentee now leads her own team. Watching her succeed beat any promotion.',
        keywords: ['mentee', 'promotion'] },
      { id: 46, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'Better than any promotion — that tells me everything about your values, honestly.',
        user: 'Titles fade, but the people you lift up carry your influence forward forever.',
        keywords: ['influence', 'forever'] },
      { id: 47, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'Beautifully said. Is there a third strength you would add to this picture?',
        user: 'Calm under fire. Chaos sharpens my focus instead of scattering it, strangely enough.',
        keywords: ['scattering', 'strangely'] },
      { id: 48, chapter: 'Your Strengths', speaker: 'HELEN',
        agent: 'Chaos sharpens rather than scatters — we will definitely test that claim later, David.',
        user: 'I welcome the test. Pressure has always brought out my clearest thinking.',
        keywords: ['welcome', 'clearest'] },
      // ---------- Chapter 5: Your Weaknesses ----------
      { id: 49, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Now the dreaded question. And please — no "I work too hard" nonsense, alright?',
        user: 'Agreed, that answer insults everyone’s intelligence. Here is my honest one instead.',
        keywords: ['insults', 'intelligence'] },
      { id: 50, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Honest answers only — I appreciate the ground rules. What is the real weakness?',
        user: 'I used to over-polish everything, endlessly refining details nobody would ever notice.',
        keywords: ['everything', 'overpolish'] },
      { id: 51, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Endless refinement of invisible details — the classic designer perfectionism trap.',
        user: 'It delayed launches and exhausted my team. My manager finally confronted me directly.',
        keywords: ['confronted', 'exhausted'] },
      { id: 52, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Being confronted about it must have stung. How did you respond in that moment?',
        user: 'Defensively at first, honestly. Then I realized she was absolutely right about me.',
        keywords: ['defensively', 'realized'] },
      { id: 53, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Defensive first, reflective later — that is a very human sequence, I respect the honesty.',
        user: 'Now I set hard ship dates and treat polish as luxury, not a requirement.',
        keywords: ['luxury', 'requirement'] },
      { id: 54, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Polish as luxury, not requirement — how do you decide what deserves the extra effort?',
        user: 'I ask: will users notice? If not, I ship it and move on.',
        keywords: ['notice', 'users'] },
      { id: 55, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'A practical filter. Tell me about a genuine failure — something that truly humbled you.',
        user: 'We launched a social feature nobody wanted. Three months of work, zero engagement afterward.',
        keywords: ['engagement', 'afterward'] },
      { id: 56, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Three months of work with zero engagement — that must have been crushing to witness.',
        user: 'We had fallen in love with our solution instead of the actual problem.',
        keywords: ['solution', 'instead'] },
      { id: 57, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Falling in love with solutions instead of problems — the most expensive mistake in product.',
        user: 'Now I kill my favorite ideas weekly. Attachment is the enemy of good judgment.',
        keywords: ['attachment', 'judgment'] },
      { id: 58, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Killing favorites weekly — brutal discipline. What did that failure change about your process?',
        user: 'We now validate with users before building anything. No exceptions, no matter how exciting.',
        keywords: ['validate', 'exceptions'] },
      { id: 59, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'No exceptions — I like the firmness. Is there a weakness you are still actively working on?',
        user: 'Saying no. I still overcommit sometimes, then scramble to deliver everything I promised.',
        keywords: ['overcommit', 'scramble'] },
      { id: 60, chapter: 'Your Weaknesses', speaker: 'HELEN',
        agent: 'Overcommitting then scrambling — how are you training yourself to say no gracefully?',
        user: 'I pause before answering now. A thoughtful no beats a resentful yes every time.',
        keywords: ['resentful', 'thoughtful'] },
      // ---------- Chapter 6: Teamwork Stories ----------
      { id: 61, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'Let us explore teamwork. Tell me about a real conflict you navigated with a colleague.',
        user: 'An engineer and I clashed over scope. He wanted cuts I deemed essential.',
        keywords: ['clashed', 'essential'] },
      { id: 62, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'Designer versus engineer over scope — the eternal product tug-of-war, I know it well.',
        user: 'Instead of arguing, I asked him to walk me through his technical constraints patiently.',
        keywords: ['constraints', 'patiently'] },
      { id: 63, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'Asking him to teach you his constraints — disarming and smart. What did you learn?',
        user: 'His concerns were completely valid. The timeline was genuinely impossible, not just difficult.',
        keywords: ['completely', 'impossible'] },
      { id: 64, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'Valid concerns, impossible timeline — so how did you two find a path forward together?',
        user: 'We redesigned the scope together. He became my strongest ally instead of my opponent.',
        keywords: ['ally', 'opponent'] },
      { id: 65, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'From opponent to strongest ally — that transformation required real humility from you.',
        user: 'It taught me that listening is more powerful than the most brilliant argument.',
        keywords: ['brilliant', 'listening'] },
      { id: 66, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'Listening beats brilliance — another notebook entry. How do you handle giving credit?',
        user: 'I over-credit, deliberately. Success has many parents, and I name every single one.',
        keywords: ['deliberately', 'parents'] },
      { id: 67, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'Over-crediting deliberately — that is generous leadership. Does it ever backfire on you?',
        user: 'Someone once took credit for my work. It stung, but the team knew.',
        keywords: ['someone', 'credit'] },
      { id: 68, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'The team knew the truth — reputation is the quiet reward of consistent generosity.',
        user: 'Exactly. Short-term credit games never beat long-term trust and respect.',
        keywords: ['shortterm', 'longterm'] },
      { id: 69, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'Long-term trust over short-term credit — wise beyond your years, David, truly.',
        user: 'Tell me about collaboration here — how do designers and engineers work together?',
        keywords: ['collaboration', 'together'] },
      { id: 70, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'We pair them from day one. No throwing designs over the wall — they build together.',
        user: 'That is music to my ears. The wall-toss model has frustrated me for years.',
        keywords: ['music', 'frustrated'] },
      { id: 71, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'Music to my ears too. What about mentoring — you mentioned it as a strength earlier?',
        user: 'I run a monthly critique circle. Juniors present work, seniors give kind, honest feedback.',
        keywords: ['critique', 'honest'] },
      { id: 72, chapter: 'Teamwork Stories', speaker: 'HELEN',
        agent: 'Kind, honest feedback in a safe circle — that is how cultures of excellence are built.',
        user: 'It has transformed our juniors. Two earned promotions within a single year.',
        keywords: ['transformed', 'promotions'] },
      // ---------- Chapter 7: Handling Pressure ----------
      { id: 73, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Earlier you claimed chaos sharpens your focus. Time to prove it — tell me about a crisis.',
        user: 'Two years ago, our app crashed for forty thousand users on launch day.',
        keywords: ['crashed', 'thousand'] },
      { id: 74, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Forty thousand users locked out on launch day — my stomach just dropped hearing that.',
        user: 'Mine did too, in the war room. Panic helps nobody, so I stayed calm.',
        keywords: ['nobody', 'calm'] },
      { id: 75, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Staying calm while forty thousand users rage — what did you actually do first?',
        user: 'I sketched a fallback screen on paper in ten minutes. Simple, honest, human.',
        keywords: ['fallback', 'sketched'] },
      { id: 76, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Paper sketches in a war room while engineers fight fires — that is composure, truly.',
        user: 'Someone had to think about the users while everyone else battled the servers.',
        keywords: ['everyone', 'battled'] },
      { id: 77, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Thinking of users amid technical chaos — that is exactly the instinct we need here.',
        user: 'The fallback went live in an hour: apology, status updates, and humor.',
        keywords: ['apology', 'humor'] },
      { id: 78, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Apology plus humor during an outage — bold tone choice. How did users react?',
        user: 'Surprisingly well. Our app store rating actually rose that week, incredibly enough.',
        keywords: ['surprisingly', 'rating'] },
      { id: 79, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Ratings rose during an outage — that is the power of honest communication, David.',
        user: 'People forgive failures. What they never forgive is silence and corporate evasiveness.',
        keywords: ['forgive', 'evasiveness'] },
      { id: 80, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Silence is unforgivable — I will remember that. What did the crisis teach you personally?',
        user: 'That I do my best thinking when stakes are highest. Pressure clarifies everything.',
        keywords: ['stakes', 'clarifies'] },
      { id: 81, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Pressure clarifies everything — do you actively seek high-stakes situations now?',
        user: 'Not recklessly. But I no longer fear them, which changes my approach.',
        keywords: ['recklessly', 'approach'] },
      { id: 82, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'Fearless about big bets — useful trait for a startup-minded company like ours.',
        user: 'What keeps you up at night here? I have long meant to ask.',
        keywords: ['night', 'meant'] },
      { id: 83, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'What keeps me up? Whether we are moving fast enough without breaking what matters most.',
        user: 'Speed versus soul — the eternal tension. How do you personally navigate that balance?',
        keywords: ['tension', 'navigate'] },
      { id: 84, chapter: 'Handling Pressure', speaker: 'HELEN',
        agent: 'By asking exactly the kind of question you just asked, repeatedly, until it hurts.',
        user: 'Then we will get along splendidly. I never stop asking uncomfortable questions.',
        keywords: ['splendidly', 'uncomfortable'] },
      // ---------- Chapter 8: Why This Company ----------
      { id: 85, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Let us turn to motivation. Why us — and please, no flattery about our beautiful office.',
        user: 'Honestly? Your accessibility report last year. It was brave, transparent, and genuinely rare.',
        keywords: ['accessibility', 'transparent'] },
      { id: 86, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Our accessibility report! Most candidates never mention it. What struck you about it?',
        user: 'You published your failures openly. Most companies bury their shortcomings in footnotes.',
        keywords: ['failures', 'shortcomings'] },
      { id: 87, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Publishing failures openly — it was terrifying, but it built extraordinary trust with users.',
        user: 'That courage is why I am here. Values you can verify beat slogans.',
        keywords: ['courage', 'verify'] },
      { id: 88, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Verifiable values over slogans — you did your homework, I can tell. What else?',
        user: 'Your decision to remove dark patterns, even though it cost short-term revenue.',
        keywords: ['patterns', 'revenue'] },
      { id: 89, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Removing dark patterns cost us real money. Do you think that decision was actually wise?',
        user: 'Completely. Trust compounds over time, while tricks only work until users notice.',
        keywords: ['compounds', 'tricks'] },
      { id: 90, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Trust compounds, tricks expire — you understand our philosophy better than some employees.',
        user: 'I have followed your product evolution closely for nearly two years now, Helen.',
        keywords: ['evolution', 'closely'] },
      { id: 91, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Two years of following us — what product decision impressed you most during that time?',
        user: 'Simplifying onboarding from twelve steps to three. Ruthless focus, beautifully executed.',
        keywords: ['ruthless', 'executed'] },
      { id: 92, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Twelve steps to three — that project nearly broke the team, but it was worth it.',
        user: 'I can imagine. Cutting features is always harder than adding them, paradoxically.',
        keywords: ['paradoxically', 'cutting'] },
      { id: 93, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Harder than adding — paradoxically true. Where do you see yourself contributing here?',
        user: 'Your mobile experience needs the clarity-is-kindness treatment I have spent years refining.',
        keywords: ['treatment', 'refining'] },
      { id: 94, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Our mobile experience does need love. What would you tackle in your first ninety days?',
        user: 'I would listen first — users, engineers, support tickets — before proposing anything dramatic.',
        keywords: ['tickets', 'dramatic'] },
      { id: 95, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Listen first, propose later — the humility to learn before acting. I respect that deeply.',
        user: 'Every company has invisible wisdom. Rushing in with answers disrespects the people already here.',
        keywords: ['invisible', 'disrespects'] },
      { id: 96, chapter: 'Why This Company', speaker: 'HELEN',
        agent: 'Invisible wisdom — lovely phrase. Alright, let us discuss the practical matters next.',
        user: 'Of course. I appreciate how naturally this conversation has flowed so far, Helen.',
        keywords: ['conversation', 'appreciate'] },
      // ---------- Chapter 9: Salary Expectations ----------
      { id: 97, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'Let us talk compensation openly. What range are you considering for this role?',
        user: 'Based on my research, I am looking between one forty and one sixty annually.',
        keywords: ['research', 'annually'] },
      { id: 98, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'One forty to one sixty — that aligns well with our band for this level, actually.',
        user: 'Glad to hear it. I did extensive benchmarking before arriving at those numbers.',
        keywords: ['benchmarking', 'extensive'] },
      { id: 99, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'Extensive benchmarking shows professionalism. Beyond salary, what matters most to you?',
        user: 'Growth trajectory and meaningful work. Money without purpose feels hollow after a while.',
        keywords: ['trajectory', 'hollow'] },
      { id: 100, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'Money without purpose feels hollow — I have seen too many people learn that too late.',
        user: 'I learned it early, thankfully. Fulfillment compounds just like interest, I have found.',
        keywords: ['thankfully', 'fulfillment'] },
      { id: 101, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'Fulfillment compounds — you have a gift for memorable phrases, David, I must say.',
        user: 'Thank you. How do you think about equity versus base salary for this position?',
        keywords: ['equity', 'position'] },
      { id: 102, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'Great question. We are generous with equity because we want true ownership mentality.',
        user: 'Ownership resonates deeply. I want to feel like a builder, not a hired hand.',
        keywords: ['ownership', 'builder'] },
      { id: 103, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'A builder, not a hired hand — that is precisely the mindset that thrives here.',
        user: 'What about flexibility? I do my deepest thinking in quiet morning hours, honestly.',
        keywords: ['flexibility', 'deepest'] },
      { id: 104, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'We care about output, not office hours. Many of us do our best work before nine.',
        user: 'That is refreshing. My creativity peaks early, then I collaborate better in afternoons.',
        keywords: ['refreshing', 'collaborate'] },
      { id: 105, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'Mornings for depth, afternoons for collaboration — a rhythm I completely understand.',
        user: 'It sounds like the culture here genuinely supports different working styles, then.',
        keywords: ['different', 'genuinely'] },
      { id: 106, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'Different working styles, same high standards — that is the deal we offer everyone.',
        user: 'High standards with humanity — that combination is rarer than it should be, honestly.',
        keywords: ['humanity', 'combination'] },
      { id: 107, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'Rarer than it should be — sadly true. Shall we move to your questions for us?',
        user: 'Absolutely. I have been saving my most curious questions for this exact moment.',
        keywords: ['saving', 'curious'] },
      { id: 108, chapter: 'Salary Expectations', speaker: 'HELEN',
        agent: 'Saved-up curious questions — my favorite part. Ask me anything, truly anything.',
        user: 'Challenge accepted. I hope you are ready for some uncomfortable honesty, Helen.',
        keywords: ['challenge', 'accepted'] },
      // ---------- Chapter 10: Your Questions for Us ----------
      { id: 109, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'Alright, uncomfortable honesty accepted. What is your first sharp question for me?',
        user: 'How do decisions actually get made here — through debate, data, or executive decree?',
        keywords: ['debate', 'decree'] },
      { id: 110, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'Debate, then data, then commitment. We argue fiercely, then unite behind the decision completely.',
        user: 'Fierce debate followed by full commitment — that takes remarkable cultural maturity, honestly.',
        keywords: ['commitment', 'remarkable'] },
      { id: 111, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'It took years to build. What else are you curious about — do not hold back now.',
        user: 'What does failure look like here? Is it punished, hidden, or genuinely learned from?',
        keywords: ['punished', 'genuinely'] },
      { id: 112, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'Genuinely learned from — we hold blameless postmortems and share them company-wide, actually.',
        user: 'Company-wide postmortems? That level of transparency is extraordinarily rare and brave.',
        keywords: ['postmortems', 'extraordinarily'] },
      { id: 113, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'Brave and occasionally painful, but it prevents the same mistakes from repeating silently.',
        user: 'Painful transparency beats comfortable silence. I have seen silence kill good teams.',
        keywords: ['transparency', 'comfortable'] },
      { id: 114, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'Silence kills teams — I have witnessed that tragedy too. Next question, please.',
        user: 'What would make someone fail in this role within the first six months?',
        keywords: ['fail', 'within'] },
      { id: 115, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'Brilliant question. Waiting to be told what to do, instead of discovering what needs doing.',
        user: 'Proactive discovery over passive waiting — noted. That suits my temperament perfectly, actually.',
        keywords: ['proactive', 'temperament'] },
      { id: 116, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'It clearly does. What about our team rituals — anything you want to know?',
        user: 'Do you have any rituals that protect creativity from the crush of endless meetings?',
        keywords: ['rituals', 'crush'] },
      { id: 117, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'Wednesday mornings are sacred — no meetings, just deep work. We guard it fiercely.',
        user: 'Sacred deep-work time — you are speaking my language now, Helen, truly.',
        keywords: ['sacred', 'language'] },
      { id: 118, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'I thought that might resonate. One more question before we move to deeper waters?',
        user: 'What is the biggest unsolved design challenge your team is wrestling with right now?',
        keywords: ['unsolved', 'wrestling'] },
      { id: 119, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'Personalization without creepiness — helpful but never surveillance-like. It haunts us daily.',
        user: 'Helpful without creepy — that is the defining design puzzle of our entire era.',
        keywords: ['defining', 'helpful'] },
      { id: 120, chapter: 'Your Questions for Us', speaker: 'HELEN',
        agent: 'The defining puzzle of our era — exactly. Now, are you ready for my toughest questions?',
        user: 'Bring them on. I have waited for the real test since we sat down.',
        keywords: ['waited', 'bring'] },
      // ---------- Chapter 11: The Deep Dive ----------
      { id: 121, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Here is a curveball: teach me something completely unrelated to design in two minutes.',
        user: 'Sourdough. The starter is alive — feed it, nurture it, and it rewards patience.',
        keywords: ['sourdough', 'nurture'] },
      { id: 122, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Sourdough as a metaphor for patience — I was not expecting baking wisdom today, David.',
        user: 'Everything teaches design if you look closely. Fermentation taught me to respect slow processes.',
        keywords: ['fermentation', 'respect'] },
      { id: 123, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Respect for slow processes — noted. Now, what is a popular design opinion you disagree with?',
        user: 'That minimalism is always better. Sometimes richness serves users more honestly than starkness.',
        keywords: ['minimalism', 'starkness'] },
      { id: 124, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Minimalism is not always better — that is heresy in some design circles, you know.',
        user: 'Heresy I will defend. Hospital apps should feel warm, not like empty galleries.',
        keywords: ['heresy', 'galleries'] },
      { id: 125, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Warm over empty — I actually agree. What would you change about our product tomorrow?',
        user: 'Your settings bury privacy controls. I would surface them proudly on the first screen.',
        keywords: ['controls', 'settings'] },
      { id: 126, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Burying privacy controls — ouch, but fair. You noticed that from outside, impressively.',
        user: 'It stood out immediately. Privacy should be a feature you showcase, not hide.',
        keywords: ['showcase', 'immediately'] },
      { id: 127, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Showcase, not hide — I am bringing that exact phrase to our next roadmap review.',
        user: 'I would be honored. Though I hope I keep my job after bold criticism.',
        keywords: ['honored', 'criticism'] },
      { id: 128, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Bold criticism backed by reasoning is exactly what we pay people for here, David.',
        user: 'That is reassuring. I would rather be honest than comfortable, every single time.',
        keywords: ['reassuring', 'comfortable'] },
      { id: 129, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Honest over comfortable — consistent with everything you have shown me today, truly.',
        user: 'Consistency matters to me. I would rather be predictably principled than charmingly vague.',
        keywords: ['predictably', 'principled'] },
      { id: 130, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Predictably principled beats charmingly vague — that might be my favorite line today.',
        user: 'Glad it resonated. Shall we talk about what happens next in this process?',
        keywords: ['resonated', 'process'] },
      { id: 131, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'We shall. But first — one final scenario. Your manager asks you to ship something unethical.',
        user: 'I would refuse clearly, document my concerns, and escalate through proper channels immediately.',
        keywords: ['immediately', 'channels'] },
      { id: 132, chapter: 'The Deep Dive', speaker: 'HELEN',
        agent: 'Refuse, document, escalate — even if it cost you the job? Be completely honest now.',
        user: 'Even then. Some lines cannot be crossed, no matter how attractive the compensation.',
        keywords: ['crossed', 'compensation'] },
      // ---------- Chapter 12: Closing the Interview ----------
      { id: 133, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Some lines cannot be crossed — that is precisely the answer I was hoping to hear.',
        user: 'I am relieved. Integrity should never be a trick question in any interview.',
        keywords: ['relieved', 'integrity'] },
      { id: 134, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Never a trick question — just the most important one. David, I have been genuinely impressed.',
        user: 'That means the world, Helen. This conversation has been a highlight of my year.',
        keywords: ['conversation', 'highlight'] },
      { id: 135, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'A highlight of my year as well, honestly. Let me be transparent about next steps now.',
        user: 'Please do. I appreciate directness far more than vague promises about timelines.',
        keywords: ['appreciate', 'directness'] },
      { id: 136, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Directness it is: team interviews next week, decision within ten days after that.',
        user: 'Ten days is refreshingly fast. I have waited months elsewhere with zero communication.',
        keywords: ['refreshingly', 'communication'] },
      { id: 137, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Months of silence is disrespectful. Candidates deserve the same clarity we ask of them.',
        user: 'That principle alone tells me volumes about how you treat people here, Helen.',
        keywords: ['principle', 'volumes'] },
      { id: 138, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'How we treat candidates reveals how we treat everyone — I believe that deeply.',
        user: 'I will remember this experience regardless of the outcome, truly. Thank you.',
        keywords: ['experience', 'regardless'] },
      { id: 139, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Regardless of outcome — though between us, I am already advocating strongly for you.',
        user: 'That is incredibly kind. I will try not to refresh my email obsessively now.',
        keywords: ['obsessively', 'incredibly'] },
      { id: 140, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Try not to obsess — but a little hopeful anticipation never hurt anyone, David.',
        user: 'Hopeful anticipation it is. Is there anything else you need from me today?',
        keywords: ['anticipation', 'hopeful'] },
      { id: 141, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Just one thing: keep that photo of your grandmother near your desk, wherever you land.',
        user: 'I promise. She is the reason I do this work with such conviction.',
        keywords: ['conviction', 'promise'] },
      { id: 142, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Conviction rooted in love — the rarest fuel in our industry. Walk me out, shall we?',
        user: 'With pleasure. This office feels a little less intimidating on the way out.',
        keywords: ['intimidating', 'pleasure'] },
      { id: 143, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Less intimidating already — a good sign. The rain has stopped, look at that sunshine.',
        user: 'Sunshine after rain — rather poetic for the end of an interview, no?',
        keywords: ['poetic', 'sunshine'] },
      { id: 144, chapter: 'Closing the Interview', speaker: 'HELEN',
        agent: 'Poetic indeed. Goodbye for now, David — and remember, clarity is kindness, always.',
        user: 'Goodbye, Helen. And clarity is kindness — I will carry those words with me.',
        keywords: ['clarity', 'carry'] }
    ]
  };
})();
