/* Speak or Boom — Job Interview scenario */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.interview = {
    id: 'interview',
    title: 'Job Interview',
    tagline: 'Land the Offer',
    speaker: 'INTERVIEWER',
    difficulty: 'Advanced',
    rounds: [
      /* ---------- Chapter 1: Welcome & Small Talk ---------- */
      { id: 'interview-001', chapter: 'Welcome & Small Talk',
        agent: 'Hi, welcome in! I\'m Sarah, the hiring manager.',
        user: 'Hi Sarah, great to meet you. Thanks for having me.',
        keywords: ['meet', 'having'] },
      { id: 'interview-002', chapter: 'Welcome & Small Talk',
        agent: 'Did you find the office alright?',
        user: 'Yes, your directions were very clear. No trouble at all.',
        keywords: ['directions', 'trouble'] },
      { id: 'interview-003', chapter: 'Welcome & Small Talk',
        agent: 'Can I get you some water or coffee?',
        user: 'A glass of water would be great, thank you.',
        keywords: ['water', 'great'] },
      { id: 'interview-004', chapter: 'Welcome & Small Talk',
        agent: 'How was your trip over here today?',
        user: 'Pretty smooth. The subway was faster than I expected.',
        keywords: ['smooth', 'subway'] },
      { id: 'interview-005', chapter: 'Welcome & Small Talk',
        agent: 'Traffic can be terrible around this area.',
        user: 'I left early just in case, so I arrived relaxed.',
        keywords: ['early', 'relaxed'] },
      { id: 'interview-006', chapter: 'Welcome & Small Talk',
        agent: 'I see you brought a copy of your resume.',
        user: 'Yes, I printed a few copies for the team.',
        keywords: ['copies', 'team'] },
      { id: 'interview-007', chapter: 'Welcome & Small Talk',
        agent: 'So, how are you feeling today?',
        user: 'Excited, honestly. I\'ve been looking forward to this conversation.',
        keywords: ['excited', 'forward'] },
      { id: 'interview-008', chapter: 'Welcome & Small Talk',
        agent: 'Great office, isn\'t it? We moved in last spring.',
        user: 'It\'s lovely. The open space feels really welcoming.',
        keywords: ['lovely', 'welcoming'] },
      { id: 'interview-009', chapter: 'Welcome & Small Talk',
        agent: 'Before we start, anything you need?',
        user: 'I\'m all set. Shall we dive right in?',
        keywords: ['set', 'dive'] },
      { id: 'interview-010', chapter: 'Welcome & Small Talk',
        agent: 'I enjoyed our phone chat last week.',
        user: 'Me too. It got me even more interested in the role.',
        keywords: ['interested', 'role'] },
      { id: 'interview-011', chapter: 'Welcome & Small Talk',
        agent: 'Let me grab my notes, one second.',
        user: 'Of course, take your time. I\'m in no rush.',
        keywords: ['time', 'rush'] },
      { id: 'interview-012', chapter: 'Welcome & Small Talk',
        agent: 'Alright, let\'s get started, shall we?',
        user: 'Absolutely. I\'m ready whenever you are.',
        keywords: ['ready', 'whenever'] },
      /* ---------- Chapter 2: Tell Me About Yourself ---------- */
      { id: 'interview-013', chapter: 'Tell Me About Yourself',
        agent: 'So, tell me a little about yourself.',
        user: 'Sure. I\'m a quality engineer with eight years of experience.',
        keywords: ['quality', 'experience'] },
      { id: 'interview-014', chapter: 'Tell Me About Yourself',
        agent: 'Walk me through your background, please.',
        user: 'I started as a process engineer, then moved into quality management.',
        keywords: ['process', 'management'] },
      { id: 'interview-015', chapter: 'Tell Me About Yourself',
        agent: 'What does your current role involve?',
        user: 'I lead supplier quality for three major automotive programs.',
        keywords: ['supplier', 'programs'] },
      { id: 'interview-016', chapter: 'Tell Me About Yourself',
        agent: 'What got you into this field?',
        user: 'I\'ve always loved solving problems that affect real products.',
        keywords: ['solving', 'products'] },
      { id: 'interview-017', chapter: 'Tell Me About Yourself',
        agent: 'Summarize your biggest achievement for me.',
        user: 'I cut our defect rate by forty percent in one year.',
        keywords: ['defect', 'percent'] },
      { id: 'interview-018', chapter: 'Tell Me About Yourself',
        agent: 'Where did you do your studies?',
        user: 'I earned my engineering degree at a technical university in Shenzhen.',
        keywords: ['engineering', 'shenzhen'] },
      { id: 'interview-019', chapter: 'Tell Me About Yourself',
        agent: 'Do you hold any certifications worth mentioning?',
        user: 'I\'m a certified Six Sigma Black Belt, and I speak three languages.',
        keywords: ['sigma', 'languages'] },
      { id: 'interview-020', chapter: 'Tell Me About Yourself',
        agent: 'What are you doing right now?',
        user: 'Currently I manage a team of five quality engineers.',
        keywords: ['manage', 'engineers'] },
      { id: 'interview-021', chapter: 'Tell Me About Yourself',
        agent: 'Why are you looking to move on?',
        user: 'I\'m ready for a bigger challenge and broader responsibility.',
        keywords: ['challenge', 'responsibility'] },
      { id: 'interview-022', chapter: 'Tell Me About Yourself',
        agent: 'Give me the short version of your career.',
        user: 'Eight years, three companies, one clear focus: building reliable products.',
        keywords: ['companies', 'reliable'] },
      { id: 'interview-023', chapter: 'Tell Me About Yourself',
        agent: 'What should I remember about you?',
        user: 'That I turn quality problems into measurable business results.',
        keywords: ['measurable', 'results'] },
      { id: 'interview-024', chapter: 'Tell Me About Yourself',
        agent: 'Anything else before we move on?',
        user: 'Just that I\'m genuinely excited about this opportunity.',
        keywords: ['genuinely', 'opportunity'] },
      /* ---------- Chapter 3: Work Experience ---------- */
      { id: 'interview-025', chapter: 'Work Experience',
        agent: 'Describe your most recent project for me.',
        user: 'I led the launch quality plan for a new electric vehicle platform.',
        keywords: ['launch', 'platform'] },
      { id: 'interview-026', chapter: 'Work Experience',
        agent: 'What was your exact responsibility there?',
        user: 'I owned the supplier audit schedule and the containment process.',
        keywords: ['audit', 'containment'] },
      { id: 'interview-027', chapter: 'Work Experience',
        agent: 'Tell me about a problem you solved.',
        user: 'A key supplier kept shipping parts with surface defects.',
        keywords: ['supplier', 'defects'] },
      { id: 'interview-028', chapter: 'Work Experience',
        agent: 'What action did you take exactly?',
        user: 'I visited their plant and redesigned the inspection checklist with them.',
        keywords: ['plant', 'checklist'] },
      { id: 'interview-029', chapter: 'Work Experience',
        agent: 'And what was the final result?',
        user: 'Defects dropped to nearly zero within two months.',
        keywords: ['dropped', 'months'] },
      { id: 'interview-030', chapter: 'Work Experience',
        agent: 'Give me another example with numbers.',
        user: 'I reduced warranty claims by twenty-five percent across two product lines.',
        keywords: ['warranty', 'percent'] },
      { id: 'interview-031', chapter: 'Work Experience',
        agent: 'How big were the teams you led?',
        user: 'Usually five to eight people, plus external supplier teams.',
        keywords: ['eight', 'external'] },
      { id: 'interview-032', chapter: 'Work Experience',
        agent: 'What tools do you use daily?',
        user: 'Mostly data dashboards, 8D reports, and statistical process control charts.',
        keywords: ['dashboards', 'charts'] },
      { id: 'interview-033', chapter: 'Work Experience',
        agent: 'Have you ever been promoted at work?',
        user: 'Twice. Both times after delivering major cost-saving projects.',
        keywords: ['twice', 'cost'] },
      { id: 'interview-034', chapter: 'Work Experience',
        agent: 'What\'s the hardest project you\'ve handled?',
        user: 'A recall investigation with a forty-eight-hour deadline from management.',
        keywords: ['recall', 'deadline'] },
      { id: 'interview-035', chapter: 'Work Experience',
        agent: 'How did you manage that pressure?',
        user: 'I broke the work into shifts and kept everyone updated hourly.',
        keywords: ['shifts', 'hourly'] },
      { id: 'interview-036', chapter: 'Work Experience',
        agent: 'What did you learn from it?',
        user: 'That clear communication matters more than perfect analysis.',
        keywords: ['communication', 'analysis'] },
      /* ---------- Chapter 4: Your Strengths ---------- */
      { id: 'interview-037', chapter: 'Your Strengths',
        agent: 'What would you say are your strengths?',
        user: 'I\'m analytical, persistent, and calm under pressure.',
        keywords: ['analytical', 'persistent'] },
      { id: 'interview-038', chapter: 'Your Strengths',
        agent: 'Give me an example of your analytical thinking.',
        user: 'I traced a recurring failure to one faulty sensor batch.',
        keywords: ['traced', 'sensor'] },
      { id: 'interview-039', chapter: 'Your Strengths',
        agent: 'What do colleagues praise you for?',
        user: 'They say I explain complex issues in simple terms.',
        keywords: ['explain', 'simple'] },
      { id: 'interview-040', chapter: 'Your Strengths',
        agent: 'What makes you different from other candidates?',
        user: 'I combine shop-floor experience with strong data skills.',
        keywords: ['shop', 'data'] },
      { id: 'interview-041', chapter: 'Your Strengths',
        agent: 'Are you more of a leader or a doer?',
        user: 'Both. I lead the strategy, then roll up my sleeves.',
        keywords: ['strategy', 'sleeves'] },
      { id: 'interview-042', chapter: 'Your Strengths',
        agent: 'How would you rate your communication skills?',
        user: 'Strong. I present to executives and operators with equal ease.',
        keywords: ['executives', 'ease'] },
      { id: 'interview-043', chapter: 'Your Strengths',
        agent: 'Can you give a leadership example?',
        user: 'I mentored two junior engineers who both earned promotions.',
        keywords: ['mentored', 'promotions'] },
      { id: 'interview-044', chapter: 'Your Strengths',
        agent: 'How do you handle data in your work?',
        user: 'I turn raw numbers into decisions people can act on.',
        keywords: ['decisions', 'act'] },
      { id: 'interview-045', chapter: 'Your Strengths',
        agent: 'What about creativity in problem solving?',
        user: 'I find practical fixes, not just textbook solutions.',
        keywords: ['practical', 'textbook'] },
      { id: 'interview-046', chapter: 'Your Strengths',
        agent: 'Would you describe yourself as detail-oriented?',
        user: 'Very. I catch issues in drawings that others miss.',
        keywords: ['catch', 'drawings'] },
      { id: 'interview-047', chapter: 'Your Strengths',
        agent: 'How quickly do you usually learn new things?',
        user: 'Fast. I mastered our new QMS software in two weeks.',
        keywords: ['mastered', 'software'] },
      { id: 'interview-048', chapter: 'Your Strengths',
        agent: 'Sum up your strengths in one sentence.',
        user: 'I solve real problems fast and bring people with me.',
        keywords: ['solve', 'people'] },
      /* ---------- Chapter 5: Your Weaknesses ---------- */
      { id: 'interview-049', chapter: 'Your Weaknesses',
        agent: 'Now the classic one: your weaknesses?',
        user: 'I used to over-prepare for every single meeting.',
        keywords: ['prepare', 'meeting'] },
      { id: 'interview-050', chapter: 'Your Weaknesses',
        agent: 'How did you address that weakness?',
        user: 'I learned to trust my preparation and stay flexible.',
        keywords: ['trust', 'flexible'] },
      { id: 'interview-051', chapter: 'Your Weaknesses',
        agent: 'Is there an area you\'re actively improving now?',
        user: 'Public speaking. I joined a Toastmasters club last year.',
        keywords: ['speaking', 'toastmasters'] },
      { id: 'interview-052', chapter: 'Your Weaknesses',
        agent: 'Has any feedback ever surprised you?',
        user: 'Once. My manager said I should delegate more often.',
        keywords: ['delegate', 'often'] },
      { id: 'interview-053', chapter: 'Your Weaknesses',
        agent: 'What did you do about it?',
        user: 'I started coaching my team instead of doing everything myself.',
        keywords: ['coaching', 'myself'] },
      { id: 'interview-054', chapter: 'Your Weaknesses',
        agent: 'Tell me about a mistake you made.',
        user: 'I approved a supplier change without full testing.',
        keywords: ['approved', 'testing'] },
      { id: 'interview-055', chapter: 'Your Weaknesses',
        agent: 'What happened after that big mistake?',
        user: 'We caught it early, but it taught me to slow down.',
        keywords: ['caught', 'slow'] },
      { id: 'interview-056', chapter: 'Your Weaknesses',
        agent: 'What skill do you still want to build?',
        user: 'I\'d like to strengthen my financial modeling skills.',
        keywords: ['strengthen', 'modeling'] },
      { id: 'interview-057', chapter: 'Your Weaknesses',
        agent: 'How do you usually handle criticism?',
        user: 'I listen first, then decide what to change.',
        keywords: ['listen', 'change'] },
      { id: 'interview-058', chapter: 'Your Weaknesses',
        agent: 'Do you ever struggle with work-life balance?',
        user: 'Sometimes, so I now block evenings for family time.',
        keywords: ['block', 'family'] },
      { id: 'interview-059', chapter: 'Your Weaknesses',
        agent: 'What\'s your biggest development goal this year?',
        user: 'To become a better coach for my team members.',
        keywords: ['coach', 'members'] },
      { id: 'interview-060', chapter: 'Your Weaknesses',
        agent: 'Anything you wish you\'d learned earlier?',
        user: 'To ask for help sooner instead of struggling alone.',
        keywords: ['sooner', 'alone'] },
      /* ---------- Chapter 6: Teamwork Stories ---------- */
      { id: 'interview-061', chapter: 'Teamwork Stories',
        agent: 'Tell me about a great team you worked in.',
        user: 'Our launch team hit every milestone for eighteen months straight.',
        keywords: ['milestone', 'straight'] },
      { id: 'interview-062', chapter: 'Teamwork Stories',
        agent: 'What was your role in it?',
        user: 'I coordinated quality gates between engineering and manufacturing.',
        keywords: ['coordinated', 'gates'] },
      { id: 'interview-063', chapter: 'Teamwork Stories',
        agent: 'Ever had a conflict with a colleague?',
        user: 'Yes. A designer and I disagreed on a tolerance spec.',
        keywords: ['disagreed', 'tolerance'] },
      { id: 'interview-064', chapter: 'Teamwork Stories',
        agent: 'How did you resolve that conflict?',
        user: 'We tested both options and let the data decide.',
        keywords: ['tested', 'decide'] },
      { id: 'interview-065', chapter: 'Teamwork Stories',
        agent: 'Tell me about helping a struggling teammate.',
        user: 'I spent two weeks coaching a new hire through his first audit.',
        keywords: ['coaching', 'audit'] },
      { id: 'interview-066', chapter: 'Teamwork Stories',
        agent: 'How do you work with difficult people?',
        user: 'I focus on shared goals, not personal differences.',
        keywords: ['shared', 'differences'] },
      { id: 'interview-067', chapter: 'Teamwork Stories',
        agent: 'Describe a cross-functional project you joined.',
        user: 'I partnered with purchasing and R&D on a supplier switch.',
        keywords: ['partnered', 'switch'] },
      { id: 'interview-068', chapter: 'Teamwork Stories',
        agent: 'How do you build trust in a new team?',
        user: 'By delivering on small promises, consistently, from day one.',
        keywords: ['promises', 'consistently'] },
      { id: 'interview-069', chapter: 'Teamwork Stories',
        agent: 'Have you led a team through change?',
        user: 'Yes. I guided my team through a full system migration.',
        keywords: ['guided', 'migration'] },
      { id: 'interview-070', chapter: 'Teamwork Stories',
        agent: 'What does good teamwork look like to you?',
        user: 'Honest debate in the room, full commitment outside it.',
        keywords: ['debate', 'commitment'] },
      { id: 'interview-071', chapter: 'Teamwork Stories',
        agent: 'How do you celebrate team wins?',
        user: 'I always credit the team publicly before mentioning myself.',
        keywords: ['credit', 'publicly'] },
      { id: 'interview-072', chapter: 'Teamwork Stories',
        agent: 'What would your team say about you?',
        user: 'That I\'m demanding but fair, and I have their backs.',
        keywords: ['demanding', 'fair'] },
      /* ---------- Chapter 7: Handling Pressure ---------- */
      { id: 'interview-073', chapter: 'Handling Pressure',
        agent: 'How do you handle tight deadlines?',
        user: 'I prioritize ruthlessly and communicate progress every day.',
        keywords: ['prioritize', 'progress'] },
      { id: 'interview-074', chapter: 'Handling Pressure',
        agent: 'Describe a high-pressure situation you faced.',
        user: 'A customer escalation arrived the night before a major audit.',
        keywords: ['escalation', 'audit'] },
      { id: 'interview-075', chapter: 'Handling Pressure',
        agent: 'What did you do first in that situation?',
        user: 'I gathered the facts before reacting or assigning blame.',
        keywords: ['facts', 'blame'] },
      { id: 'interview-076', chapter: 'Handling Pressure',
        agent: 'How do you stay calm under pressure?',
        user: 'I focus on the next concrete step, not the whole mountain.',
        keywords: ['concrete', 'mountain'] },
      { id: 'interview-077', chapter: 'Handling Pressure',
        agent: 'Tell me about a time you failed.',
        user: 'I missed a cost target on my first big project.',
        keywords: ['missed', 'target'] },
      { id: 'interview-078', chapter: 'Handling Pressure',
        agent: 'How did you recover from that failure?',
        user: 'I presented a recovery plan and delivered it ahead of schedule.',
        keywords: ['recovery', 'schedule'] },
      { id: 'interview-079', chapter: 'Handling Pressure',
        agent: 'What if everything goes wrong at once?',
        user: 'I triage like a doctor: stop the bleeding first.',
        keywords: ['triage', 'bleeding'] },
      { id: 'interview-080', chapter: 'Handling Pressure',
        agent: 'How do you prioritize competing tasks?',
        user: 'Impact first, urgency second, everything else gets scheduled.',
        keywords: ['impact', 'urgency'] },
      { id: 'interview-081', chapter: 'Handling Pressure',
        agent: 'Ever disagreed with your boss under pressure?',
        user: 'Yes. I presented the risks clearly, then followed the decision.',
        keywords: ['risks', 'decision'] },
      { id: 'interview-082', chapter: 'Handling Pressure',
        agent: 'How do you avoid burnout in busy periods?',
        user: 'I protect my sleep and take real weekends off.',
        keywords: ['protect', 'weekends'] },
      { id: 'interview-083', chapter: 'Handling Pressure',
        agent: 'What keeps you motivated in tough times?',
        user: 'Seeing a fix I designed working on the production line.',
        keywords: ['designed', 'production'] },
      { id: 'interview-084', chapter: 'Handling Pressure',
        agent: 'Sum up your approach to pressure.',
        user: 'Stay calm, get the facts, act fast, learn always.',
        keywords: ['calm', 'learn'] },
      /* ---------- Chapter 8: Salary Expectations ---------- */
      { id: 'interview-085', chapter: 'Salary Expectations',
        agent: 'What are your salary expectations for this role?',
        user: 'I\'m looking for a base in the ninety to one-hundred-ten range.',
        keywords: ['base', 'range'] },
      { id: 'interview-086', chapter: 'Salary Expectations',
        agent: 'That\'s above our initial budget. Thoughts?',
        user: 'I understand budgets matter. Let\'s discuss the full package.',
        keywords: ['budgets', 'package'] },
      { id: 'interview-087', chapter: 'Salary Expectations',
        agent: 'What matters most to you in compensation?',
        user: 'Fair base pay, plus growth tied to clear results.',
        keywords: ['fair', 'results'] },
      { id: 'interview-088', chapter: 'Salary Expectations',
        agent: 'Would you consider a lower base with bonus?',
        user: 'Yes, if the targets are realistic and clearly defined.',
        keywords: ['targets', 'defined'] },
      { id: 'interview-089', chapter: 'Salary Expectations',
        agent: 'What benefits matter most to you?',
        user: 'Health coverage and learning budget matter a lot to me.',
        keywords: ['coverage', 'learning'] },
      { id: 'interview-090', chapter: 'Salary Expectations',
        agent: 'Is there flexibility on your number?',
        user: 'Some, for the right role and the right team.',
        keywords: ['right', 'team'] },
      { id: 'interview-091', chapter: 'Salary Expectations',
        agent: 'What does your current package look like?',
        user: 'I\'d rather focus on the value I\'ll bring here.',
        keywords: ['value', 'bring'] },
      { id: 'interview-092', chapter: 'Salary Expectations',
        agent: 'We need a number to move forward.',
        user: 'Then let\'s use my range as a starting point for discussion.',
        keywords: ['starting', 'discussion'] },
      { id: 'interview-093', chapter: 'Salary Expectations',
        agent: 'How do you feel about equity or stock?',
        user: 'I like it. It shows we\'re building something together.',
        keywords: ['building', 'together'] },
      { id: 'interview-094', chapter: 'Salary Expectations',
        agent: 'What if we can\'t meet your expectation?',
        user: 'Then I\'ll need to weigh it against my other options.',
        keywords: ['weigh', 'options'] },
      { id: 'interview-095', chapter: 'Salary Expectations',
        agent: 'Are you interviewing with other companies too?',
        user: 'Yes, but this role is my top choice so far.',
        keywords: ['top', 'choice'] },
      { id: 'interview-096', chapter: 'Salary Expectations',
        agent: 'Anything else you\'d like to add on compensation?',
        user: 'Just that I\'m confident we can find a fair middle ground.',
        keywords: ['confident', 'ground'] },
      /* ---------- Chapter 9: Your Questions for Us ---------- */
      { id: 'interview-097', chapter: 'Your Questions for Us',
        agent: 'What questions do you have for us?',
        user: 'What does success look like in the first six months?',
        keywords: ['success', 'months'] },
      { id: 'interview-098', chapter: 'Your Questions for Us',
        agent: 'Good question. What else is on your mind?',
        user: 'How would you describe the team culture here?',
        keywords: ['describe', 'culture'] },
      { id: 'interview-099', chapter: 'Your Questions for Us',
        agent: 'Anything you\'d like to ask about the role itself?',
        user: 'What are the biggest challenges facing this team right now?',
        keywords: ['challenges', 'right'] },
      { id: 'interview-100', chapter: 'Your Questions for Us',
        agent: 'That\'s a good one. Please go on.',
        user: 'How is performance measured and reviewed in this role?',
        keywords: ['performance', 'reviewed'] },
      { id: 'interview-101', chapter: 'Your Questions for Us',
        agent: 'What else would you like to know?',
        user: 'What opportunities exist for professional growth and learning?',
        keywords: ['growth', 'learning'] },
      { id: 'interview-102', chapter: 'Your Questions for Us',
        agent: 'Sure thing. What\'s your next question?',
        user: 'Why did the previous person in this role leave?',
        keywords: ['previous', 'leave'] },
      { id: 'interview-103', chapter: 'Your Questions for Us',
        agent: 'Fair question. Anything else you\'d like to ask?',
        user: 'How does the company support work-life balance in practice?',
        keywords: ['support', 'practice'] },
      { id: 'interview-104', chapter: 'Your Questions for Us',
        agent: 'Good ones. Keep the questions coming.',
        user: 'What\'s the most exciting project on the roadmap this year?',
        keywords: ['exciting', 'roadmap'] },
      { id: 'interview-105', chapter: 'Your Questions for Us',
        agent: 'What about the team structure here?',
        user: 'Who would I report to, and who reports to me?',
        keywords: ['report', 'reports'] },
      { id: 'interview-106', chapter: 'Your Questions for Us',
        agent: 'Anything you\'d like to know about our future plans?',
        user: 'Where do you see the company heading in five years?',
        keywords: ['heading', 'years'] },
      { id: 'interview-107', chapter: 'Your Questions for Us',
        agent: 'Do you have one last question for us?',
        user: 'What are the next steps in your hiring process?',
        keywords: ['steps', 'process'] },
      { id: 'interview-108', chapter: 'Your Questions for Us',
        agent: 'We\'ll be in touch within a week.',
        user: 'Perfect. I really appreciate your time today.',
        keywords: ['appreciate', 'today'] },
      /* ---------- Chapter 10: Phone Screening ---------- */
      { id: 'interview-109', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'Hi, is this a good time to talk?',
        user: 'Yes, perfect timing. I have about thirty minutes.',
        keywords: ['timing', 'minutes'] },
      { id: 'interview-110', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'Great. Why are you interested in us?',
        user: 'Your reputation for innovation really stands out in the industry.',
        keywords: ['reputation', 'innovation'] },
      { id: 'interview-111', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'What\'s your notice period at your current job?',
        user: 'Thirty days, though I can sometimes negotiate it shorter.',
        keywords: ['thirty', 'negotiate'] },
      { id: 'interview-112', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'Would you be open to relocating for this role?',
        user: 'Yes. I\'ve already discussed it with my family.',
        keywords: ['discussed', 'family'] },
      { id: 'interview-113', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'This role is hybrid. Does that work?',
        user: 'Absolutely. I work well both remotely and on-site.',
        keywords: ['remotely', 'site'] },
      { id: 'interview-114', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'Would you need visa sponsorship from us?',
        user: 'No, I\'m fully authorized to work here.',
        keywords: ['authorized', 'work'] },
      { id: 'interview-115', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'Can you share your current salary band?',
        user: 'I\'d prefer to discuss that later in the process.',
        keywords: ['discuss', 'process'] },
      { id: 'interview-116', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'Why are you leaving your current job?',
        user: 'I\'ve grown as far as I can in my current role.',
        keywords: ['grown', 'role'] },
      { id: 'interview-117', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'When would you be able to start?',
        user: 'Early next quarter would be ideal for me.',
        keywords: ['quarter', 'ideal'] },
      { id: 'interview-118', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'Any questions for me at this stage?',
        user: 'What\'s the timeline for the next interview rounds?',
        keywords: ['timeline', 'rounds'] },
      { id: 'interview-119', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'We\'ll schedule the panel for next week.',
        user: 'That works for me. I\'ll keep my calendar open.',
        keywords: ['calendar', 'open'] },
      { id: 'interview-120', chapter: 'Phone Screening', speaker: 'RECRUITER',
        agent: 'Thanks so much for your time today.',
        user: 'Thank you. I\'m looking forward to the next steps.',
        keywords: ['forward', 'steps'] },
      /* ---------- Chapter 11: Second Interview ---------- */
      { id: 'interview-121', chapter: 'Second Interview',
        agent: 'Welcome back. Ready for round two?',
        user: 'Definitely. I\'ve been thinking about our last conversation.',
        keywords: ['thinking', 'conversation'] },
      { id: 'interview-122', chapter: 'Second Interview',
        agent: 'Why do you want to work here specifically?',
        user: 'Your quality-first culture matches how I already work.',
        keywords: ['culture', 'matches'] },
      { id: 'interview-123', chapter: 'Second Interview',
        agent: 'Where do you see yourself in five years?',
        user: 'Leading a quality organization and mentoring future leaders.',
        keywords: ['leading', 'mentoring'] },
      { id: 'interview-124', chapter: 'Second Interview',
        agent: 'How would you handle our biggest challenge?',
        user: 'First I\'d listen to the team, then map the real bottlenecks.',
        keywords: ['listen', 'bottlenecks'] },
      { id: 'interview-125', chapter: 'Second Interview',
        agent: 'Walk me through a tough technical decision.',
        user: 'I chose a slower supplier with far better process controls.',
        keywords: ['slower', 'controls'] },
      { id: 'interview-126', chapter: 'Second Interview',
        agent: 'What would your first ninety days look like?',
        user: 'Listen, learn the systems, then deliver one quick win.',
        keywords: ['learn', 'win'] },
      { id: 'interview-127', chapter: 'Second Interview',
        agent: 'How do you feel about our company values?',
        user: 'They resonate with me, especially the focus on integrity.',
        keywords: ['resonate', 'integrity'] },
      { id: 'interview-128', chapter: 'Second Interview',
        agent: 'What questions do you have for the panel?',
        user: 'How do teams here typically resolve disagreements on priorities?',
        keywords: ['resolve', 'priorities'] },
      { id: 'interview-129', chapter: 'Second Interview',
        agent: 'Do you have any concerns about this role?',
        user: 'Only that I want to make sure expectations are realistic.',
        keywords: ['expectations', 'realistic'] },
      { id: 'interview-130', chapter: 'Second Interview',
        agent: 'How do you keep your skills current?',
        user: 'I take courses, attend conferences, and learn from mentors.',
        keywords: ['courses', 'mentors'] },
      { id: 'interview-131', chapter: 'Second Interview',
        agent: 'Why should we choose you over other candidates?',
        user: 'Because I deliver results and make the people around me better.',
        keywords: ['deliver', 'better'] },
      { id: 'interview-132', chapter: 'Second Interview',
        agent: 'We\'ll discuss and get back to you.',
        user: 'Sounds good. This has been a great experience overall.',
        keywords: ['experience', 'overall'] },
      /* ---------- Chapter 12: Closing the Interview ---------- */
      { id: 'interview-133', chapter: 'Closing the Interview',
        agent: 'We\'re almost done here. Any final thoughts?',
        user: 'This conversation confirmed my strong interest in the role.',
        keywords: ['confirmed', 'interest'] },
      { id: 'interview-134', chapter: 'Closing the Interview',
        agent: 'Is there anything we didn\'t cover today?',
        user: 'I\'d love to share references from two former managers.',
        keywords: ['references', 'managers'] },
      { id: 'interview-135', chapter: 'Closing the Interview',
        agent: 'That would be very helpful, thank you.',
        user: 'I\'ll send their contact details by tomorrow morning.',
        keywords: ['contact', 'morning'] },
      { id: 'interview-136', chapter: 'Closing the Interview',
        agent: 'When is the best time to reach you?',
        user: 'Any weekday after six works best for me.',
        keywords: ['weekday', 'works'] },
      { id: 'interview-137', chapter: 'Closing the Interview',
        agent: 'Thanks for coming in to see us today.',
        user: 'Thank you for the thoughtful questions and your time.',
        keywords: ['thoughtful', 'time'] },
      { id: 'interview-138', chapter: 'Closing the Interview',
        agent: 'We\'ll be in touch very soon.',
        user: 'I look forward to hearing from you.',
        keywords: ['forward', 'hearing'] },
      { id: 'interview-139', chapter: 'Closing the Interview',
        agent: 'Do you want a tour of the office?',
        user: 'I\'d love one. It helps me picture working here.',
        keywords: ['picture', 'working'] },
      { id: 'interview-140', chapter: 'Closing the Interview',
        agent: 'Here\'s the production floor where it all happens.',
        user: 'Impressive setup. The workflow looks very well organized.',
        keywords: ['impressive', 'organized'] },
      { id: 'interview-141', chapter: 'Closing the Interview',
        agent: 'And this is where your team would sit.',
        user: 'Great location. I can already see myself collaborating here.',
        keywords: ['location', 'collaborating'] },
      { id: 'interview-142', chapter: 'Closing the Interview',
        agent: 'Have a safe trip back home today.',
        user: 'Thanks again. I\'ll follow up with a thank-you email tonight.',
        keywords: ['follow', 'tonight'] },
      { id: 'interview-143', chapter: 'Closing the Interview',
        agent: 'We really appreciate your enthusiasm today.',
        user: 'The feeling is mutual. This feels like the right fit.',
        keywords: ['mutual', 'fit'] },
      { id: 'interview-144', chapter: 'Closing the Interview',
        agent: 'Goodbye for now, and good luck!',
        user: 'Goodbye! I hope we get to work together soon.',
        keywords: ['hope', 'together'] }
    ]
  };
})();
