/* Speak or Boom — "Ship It!" Ep.1: Demo Day Disaster (ORIGINAL series) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.movies = {
    id: 'movies',
    title: 'Ship It!',
    tagline: 'Ep.1: Demo Day Disaster',
    speaker: 'OFFICE',
    difficulty: 'Intermediate',
    ordered: true,
    rounds: [
      // ---------- Scene 1: Morning Meltdown ----------
      { id: 'movies-001', chapter: 'Morning Meltdown', speaker: 'JAKE',
        agent: 'Morning, Mia! You look like you slept a full eight hours.',
        user: "I did. You look like you didn't sleep at all.",
        keywords: ['didnt', 'sleep'] },
      { id: 'movies-002', chapter: 'Morning Meltdown', speaker: 'JAKE',
        agent: 'I was up all night fixing the demo. It works now.',
        user: 'It better. Mr. Chen arrives tomorrow at ten.',
        keywords: ['better', 'tomorrow'] },
      { id: 'movies-003', chapter: 'Morning Meltdown', speaker: 'LUCY',
        agent: 'Good morning! I brought my famous oatmeal cookies.',
        user: "They smell amazing, Lucy. But I'm too nervous to eat.",
        keywords: ['smell', 'nervous'] },
      { id: 'movies-004', chapter: 'Morning Meltdown', speaker: 'JAKE',
        agent: 'Nervous? The demo is tomorrow. We have plenty of time.',
        user: 'Famous last words. Did you test the new build?',
        keywords: ['test', 'build'] },
      { id: 'movies-005', chapter: 'Morning Meltdown', speaker: 'JAKE',
        agent: 'Test? I wrote it at two in the morning. It is perfect.',
        user: "Jake, two in the morning is not a good sign.",
        keywords: ['morning', 'sign'] },
      { id: 'movies-006', chapter: 'Morning Meltdown', speaker: 'LUCY',
        agent: 'Has anyone tried the coffee machine? It sounds weird.',
        user: 'Not again. Jake, did you touch the coffee machine?',
        keywords: ['again', 'touch'] },
      { id: 'movies-007', chapter: 'Morning Meltdown', speaker: 'JAKE',
        agent: 'I just tried to make it faster. Now it makes no coffee.',
        user: 'You broke it? On demo week? Are you serious?',
        keywords: ['broke', 'serious'] },
      { id: 'movies-008', chapter: 'Morning Meltdown', speaker: 'LUCY',
        agent: 'Relax. I will fix it after the demo. Priorities, people.',
        user: "You're right. Demo first, coffee later. I can survive.",
        keywords: ['demo', 'survive'] },
      { id: 'movies-009', chapter: 'Morning Meltdown', speaker: 'JAKE',
        agent: 'So the plan is simple. Mia pitches, I click, Lucy smiles.',
        user: 'And what could possibly go wrong with that plan?',
        keywords: ['possibly', 'wrong'] },
      { id: 'movies-010', chapter: 'Morning Meltdown', speaker: 'LUCY',
        agent: 'Do not jinx it, Mia. Last time the projector died.',
        user: 'Okay, okay. Positive thinking. The demo will be perfect.',
        keywords: ['positive', 'perfect'] },
      { id: 'movies-011', chapter: 'Morning Meltdown', speaker: 'JAKE',
        agent: 'Now, who wants to see my amazing new animation feature?',
        user: 'New feature? Jake, we froze the code last Friday!',
        keywords: ['froze', 'code'] },
      { id: 'movies-012', chapter: 'Morning Meltdown', speaker: 'JAKE',
        agent: 'Relax, it is just a small animation. Watch this.',
        user: "No! Don't touch anything until after the demo!",
        keywords: ['touch', 'demo'] },
      { id: 'movies-013', chapter: 'Morning Meltdown', speaker: 'LUCY',
        agent: "That's Mr. Chen's office calling. This cannot be good.",
        user: 'Answer it, Lucy. Put it on speaker.',
        keywords: ['answer', 'speaker'] },
      { id: 'movies-014', chapter: 'Morning Meltdown', speaker: 'LUCY',
        agent: 'That was his assistant. The demo moved to today at three.',
        user: "Today? At three? That's in four hours!",
        keywords: ['today', 'hours'] },
      // ---------- Scene 2: Damage Control ----------
      { id: 'movies-015', chapter: 'Damage Control', speaker: 'JAKE',
        agent: 'Four hours? I need four days! My code needs four days!',
        user: "Breathe, Jake. We'll make a plan and stick to it.",
        keywords: ['breathe', 'plan'] },
      { id: 'movies-016', chapter: 'Damage Control', speaker: 'LUCY',
        agent: "Mia's right. Panic never fixed a single bug.",
        user: 'Okay. First, we test the demo right now.',
        keywords: ['test', 'now'] },
      { id: 'movies-017', chapter: 'Damage Control', speaker: 'JAKE',
        agent: 'Fine. Opening the app... and... oh no.',
        user: 'Oh no what? Jake, what does oh no mean?',
        keywords: ['mean'] },
      { id: 'movies-018', chapter: 'Damage Control', speaker: 'JAKE',
        agent: 'The scan button freezes. The whole app just freezes.',
        user: "The two in the morning update broke it, didn't it?",
        keywords: ['broke'] },
      { id: 'movies-019', chapter: 'Damage Control', speaker: 'JAKE',
        agent: 'Maybe a little. But my animation is beautiful!',
        user: "I don't care about beautiful. I need working!",
        keywords: ['working'] },
      { id: 'movies-020', chapter: 'Damage Control', speaker: 'LUCY',
        agent: "Jake, did you save yesterday's version anywhere safe?",
        user: 'Please say yes. Please, please say yes.',
        keywords: ['say', 'yes'] },
      { id: 'movies-021', chapter: 'Damage Control', speaker: 'JAKE',
        agent: "Of course! It's on my lucky thumb drive.",
        user: 'Great! Where is your lucky thumb drive?',
        keywords: ['where', 'drive'] },
      { id: 'movies-022', chapter: 'Damage Control', speaker: 'JAKE',
        agent: 'It is... hmm. It was in my backpack. Or my desk.',
        user: 'Jake! The backup is missing hours before demo?',
        keywords: ['missing'] },
      { id: 'movies-023', chapter: 'Damage Control', speaker: 'LUCY',
        agent: "Everyone stay calm. We'll search the office together.",
        user: "Good idea. Jake, you check your desk drawers.",
        keywords: ['check', 'drawers'] },
      { id: 'movies-024', chapter: 'Damage Control', speaker: 'JAKE',
        agent: 'My desk has a system! It is called organized chaos.',
        user: 'Your system lost our backup. Start searching now.',
        keywords: ['lost', 'searching'] },
      { id: 'movies-025', chapter: 'Damage Control', speaker: 'LUCY',
        agent: 'I will check the meeting room. Mia, check the kitchen.',
        user: 'On it. And Jake, no more brilliant ideas today.',
        keywords: ['brilliant', 'ideas'] },
      { id: 'movies-026', chapter: 'Damage Control', speaker: 'JAKE',
        agent: 'I found an old sandwich! Does that count as backup?',
        user: 'A sandwich is not a backup drive, Jake.',
        keywords: ['sandwich', 'drive'] },
      { id: 'movies-027', chapter: 'Damage Control', speaker: 'LUCY',
        agent: 'Nothing in the meeting room. Jake, think harder.',
        user: 'When did you last see the thumb drive?',
        keywords: ['last', 'see'] },
      { id: 'movies-028', chapter: 'Damage Control', speaker: 'JAKE',
        agent: 'Yesterday... I was showing it to Captain Quackers.',
        user: 'Who is Captain Quackers? And why?',
        keywords: ['who', 'why'] },
      // ---------- Scene 3: The Duck and the Drive ----------
      { id: 'movies-029', chapter: 'The Duck and the Drive', speaker: 'JAKE',
        agent: 'Captain Quackers is my rubber duck. I debug with him.',
        user: 'You talk to a rubber duck about code?',
        keywords: ['talk', 'duck'] },
      { id: 'movies-030', chapter: 'The Duck and the Drive', speaker: 'JAKE',
        agent: 'Every great developer does! The duck never judges.',
        user: 'Focus, Jake. Where did you last have the drive?',
        keywords: ['focus', 'drive'] },
      { id: 'movies-031', chapter: 'The Duck and the Drive', speaker: 'JAKE',
        agent: 'I was near the coffee machine... trying to fix it...',
        user: 'The coffee machine? Why was the drive near there?',
        keywords: ['why'] },
      { id: 'movies-032', chapter: 'The Duck and the Drive', speaker: 'LUCY',
        agent: "Jake, please tell me you didn't put it inside the machine.",
        user: "He did, didn't he? I can see it on his face.",
        keywords: ['see', 'face'] },
      { id: 'movies-033', chapter: 'The Duck and the Drive', speaker: 'JAKE',
        agent: 'It was the safest spot! No one looks in a coffee machine!',
        user: 'Nobody puts a thumb drive in a coffee machine, Jake!',
        keywords: ['nobody', 'puts'] },
      { id: 'movies-034', chapter: 'The Duck and the Drive', speaker: 'LUCY',
        agent: "I'll get my tools. Mia, unplug that machine right now.",
        user: "Unplugged. Jake, you're buying the next coffee machine.",
        keywords: ['buying', 'machine'] },
      { id: 'movies-035', chapter: 'The Duck and the Drive', speaker: 'JAKE',
        agent: "Got it! It's a little wet, but it's here!",
        user: "Wet? Jake, water and electronics don't mix!",
        keywords: ['water', 'mix'] },
      { id: 'movies-036', chapter: 'The Duck and the Drive', speaker: 'LUCY',
        agent: "Let me see... Mia, I'm afraid this drive is dead.",
        user: 'Dead? As in completely, totally dead?',
        keywords: ['completely', 'dead'] },
      { id: 'movies-037', chapter: 'The Duck and the Drive', speaker: 'JAKE',
        agent: 'Maybe if we put it in rice? Rice fixes everything!',
        user: 'Rice fixes phones, not our demo, not today.',
        keywords: ['rice', 'today'] },
      { id: 'movies-038', chapter: 'The Duck and the Drive', speaker: 'LUCY',
        agent: 'The drive is gone. We need a new plan, fast.',
        user: 'You are right. Panicking wastes time. Think, Mia, think.',
        keywords: ['wastes', 'think'] },
      { id: 'movies-039', chapter: 'The Duck and the Drive', speaker: 'JAKE',
        agent: 'I could rebuild the demo! I just need... six hours.',
        user: 'We have three. And you need sleep, not more coding.',
        keywords: ['sleep', 'coding'] },
      { id: 'movies-040', chapter: 'The Duck and the Drive', speaker: 'LUCY',
        agent: "What about the screenshots from last week's test?",
        user: "Screenshots? Lucy, that's actually not crazy.",
        keywords: ['actually', 'crazy'] },
      { id: 'movies-041', chapter: 'The Duck and the Drive', speaker: 'LUCY',
        agent: 'I printed every screen. Old school, but it works.',
        user: "You printed them? Lucy, you're a genius!",
        keywords: ['printed', 'genius'] },
      { id: 'movies-042', chapter: 'The Duck and the Drive', speaker: 'JAKE',
        agent: "Paper screenshots? That's like using a paper map today!",
        user: 'Maps still work when the GPS dies, Jake.',
        keywords: ['maps', 'dies'] },
      // ---------- Scene 4: Plan B ----------
      { id: 'movies-043', chapter: 'Plan B', speaker: 'LUCY',
        agent: 'I have forty screenshots, in order, from login to checkout.',
        user: 'Forty? When did you even print all these?',
        keywords: ['when', 'print'] },
      { id: 'movies-044', chapter: 'Plan B', speaker: 'LUCY',
        agent: "Last Friday. I never trust Jake's midnight coding.",
        user: 'Smartest decision anyone made this week.',
        keywords: ['smartest', 'decision'] },
      { id: 'movies-045', chapter: 'Plan B', speaker: 'JAKE',
        agent: 'Hey! My midnight coding is inspired! Mostly.',
        user: 'Inspired chaos. Now help us sort these pages.',
        keywords: ['chaos', 'sort'] },
      { id: 'movies-046', chapter: 'Plan B', speaker: 'JAKE',
        agent: 'What if we just tell Mr. Chen the app is... invisible?',
        user: 'No. We are not lying to an investor, Jake.',
        keywords: ['lying', 'investor'] },
      { id: 'movies-047', chapter: 'Plan B', speaker: 'JAKE',
        agent: "What if I do a live drawing of the app? I'm artistic!",
        user: 'Your stick figures are not investor-ready.',
        keywords: ['stick', 'figures'] },
      { id: 'movies-048', chapter: 'Plan B', speaker: 'LUCY',
        agent: 'Enough. Mia, you pitch with my screenshots. Jake, you assist.',
        user: "Assist how? He breaks everything he touches.",
        keywords: ['breaks', 'touches'] },
      { id: 'movies-049', chapter: 'Plan B', speaker: 'LUCY',
        agent: "He'll handle questions. Honest answers, Jake. No jokes.",
        user: "No jokes? That's like asking fish not to swim.",
        keywords: ['fish', 'swim'] },
      { id: 'movies-050', chapter: 'Plan B', speaker: 'JAKE',
        agent: 'I can be serious! Watch: I am serious now.',
        user: "You're smiling. That's not a serious face.",
        keywords: ['smiling', 'face'] },
      { id: 'movies-051', chapter: 'Plan B', speaker: 'LUCY',
        agent: 'Jake, log into the company account. We need the slides.',
        user: 'Please tell me the password is not password one two three four.',
        keywords: ['password'] },
      { id: 'movies-052', chapter: 'Plan B', speaker: 'JAKE',
        agent: "It's... password one two three four. I added numbers.",
        user: "That's not security, Jake! Change it tonight!",
        keywords: ['security', 'change'] },
      { id: 'movies-053', chapter: 'Plan B', speaker: 'LUCY',
        agent: "Slides are up. Mia, let's practice your pitch.",
        user: 'Practice? With three hours left? Absolutely.',
        keywords: ['practice', 'absolutely'] },
      { id: 'movies-054', chapter: 'Plan B', speaker: 'JAKE',
        agent: "Can Captain Quackers watch? He's great moral support.",
        user: 'Fine. The duck can stay. No talking, duck.',
        keywords: ['stay', 'duck'] },
      { id: 'movies-055', chapter: 'Plan B', speaker: 'LUCY',
        agent: "Remember: smile, breathe, and don't rush the ending.",
        user: "Smile, breathe, don't rush. Got it, Lucy.",
        keywords: ['smile', 'breathe'] },
      { id: 'movies-056', chapter: 'Plan B', speaker: 'JAKE',
        agent: "And if all else fails, I'll do my robot dance.",
        user: "If all else fails, we're already doomed.",
        keywords: ['fails', 'doomed'] },
      // ---------- Scene 5: Pitch Practice ----------
      { id: 'movies-057', chapter: 'Pitch Practice', speaker: 'JAKE',
        agent: "Okay, superstar. Pitch to us like we're Mr. Chen.",
        user: 'BrightBox is the smart lunchbox that thinks for you.',
        keywords: ['smart', 'thinks'] },
      { id: 'movies-058', chapter: 'Pitch Practice', speaker: 'LUCY',
        agent: "Good start! But slow down. You're racing the words.",
        user: 'Sorry. BrightBox... is the smart lunchbox...',
        keywords: ['sorry', 'lunchbox'] },
      { id: 'movies-059', chapter: 'Pitch Practice', speaker: 'JAKE',
        agent: "You sound like a robot! Where's the passion?",
        user: "Passion? I'm running on fear and no coffee.",
        keywords: ['fear', 'coffee'] },
      { id: 'movies-060', chapter: 'Pitch Practice', speaker: 'LUCY',
        agent: "Pretend you're telling a friend. Just talk to us.",
        user: 'Okay... Imagine never guessing what is for lunch.',
        keywords: ['imagine', 'guessing'] },
      { id: 'movies-061', chapter: 'Pitch Practice', speaker: 'JAKE',
        agent: 'Better! Now sell me the dream! Sell it!',
        user: 'Our app scans your food in two seconds flat!',
        keywords: ['scans', 'seconds'] },
      { id: 'movies-062', chapter: 'Pitch Practice', speaker: 'LUCY',
        agent: 'Lovely! And what does the app do next?',
        user: 'It tracks nutrition and suggests healthier swaps.',
        keywords: ['tracks', 'swaps'] },
      { id: 'movies-063', chapter: 'Pitch Practice', speaker: 'JAKE',
        agent: 'Now with feeling! Like it is the best thing ever!',
        user: "It's like a nutritionist living in your lunchbox!",
        keywords: ['nutritionist', 'living'] },
      { id: 'movies-064', chapter: 'Pitch Practice', speaker: 'LUCY',
        agent: "That's the one! Say that exact line to Mr. Chen.",
        user: "I will. I think I'm actually ready.",
        keywords: ['actually', 'ready'] },
      { id: 'movies-065', chapter: 'Pitch Practice', speaker: 'JAKE',
        agent: "One more time, but I'll heckle like an investor.",
        user: 'Bring it on. I can handle your heckling.',
        keywords: ['handle', 'heckling'] },
      { id: 'movies-066', chapter: 'Pitch Practice', speaker: 'JAKE',
        agent: 'Why should I invest? Convince me in one sentence!',
        user: 'Because everyone eats, and everyone wants to eat smarter.',
        keywords: ['eats', 'smarter'] },
      { id: 'movies-067', chapter: 'Pitch Practice', speaker: 'LUCY',
        agent: 'Brilliant answer! Quick, confident, no rambling.',
        user: 'Thanks, Lucy. My stomach is growling, though.',
        keywords: ['stomach', 'growling'] },
      { id: 'movies-068', chapter: 'Pitch Practice', speaker: 'LUCY',
        agent: 'Oatmeal cookie? I saved you one from this morning.',
        user: 'Yes, please! Nerves are gone, hunger is back.',
        keywords: ['nerves', 'hunger'] },
      { id: 'movies-069', chapter: 'Pitch Practice', speaker: 'JAKE',
        agent: "Hey! Where's my cookie? I was nervous too!",
        user: 'You were never nervous. You were just hungry.',
        keywords: ['never', 'hungry'] },
      { id: 'movies-070', chapter: 'Pitch Practice', speaker: 'LUCY',
        agent: "There's plenty for everyone. Eat up, team.",
        user: "Best cookie ever. Okay, I'm ready for Mr. Chen.",
        keywords: ['best', 'ready'] },
      // ---------- Scene 6: The Investor Arrives Early ----------
      { id: 'movies-071', chapter: 'The Investor Arrives Early', speaker: 'JAKE',
        agent: "Was that the door? Please tell me that's not the door.",
        user: "It's two o'clock. He's an hour early!",
        keywords: ['early'] },
      { id: 'movies-072', chapter: 'The Investor Arrives Early', speaker: 'LUCY',
        agent: 'Everyone look busy! Jake, hide the sandwich!',
        user: "Hide the sandwich? That's your priority?",
        keywords: ['priority'] },
      { id: 'movies-073', chapter: 'The Investor Arrives Early', speaker: 'JAKE',
        agent: 'The sandwich is gone! I ate it during practice!',
        user: 'Of course you did. Just smile and look professional.',
        keywords: ['smile', 'professional'] },
      { id: 'movies-074', chapter: 'The Investor Arrives Early', speaker: 'LUCY',
        agent: "Mr. Chen! Welcome! We're so glad you're early.",
        user: 'Yes, welcome! Please come in and sit down.',
        keywords: ['welcome', 'down'] },
      { id: 'movies-075', chapter: 'The Investor Arrives Early', speaker: 'JAKE',
        agent: "Mr. Chen, I'm Jake. I built the app. Mostly.",
        user: "He built all of it. He's being modest.",
        keywords: ['built', 'modest'] },
      { id: 'movies-076', chapter: 'The Investor Arrives Early', speaker: 'LUCY',
        agent: 'Can I get you coffee? Oh... our machine is resting today.',
        user: "Resting? Lucy, it's broken. Jake broke it.",
        keywords: ['resting', 'broke'] },
      { id: 'movies-077', chapter: 'The Investor Arrives Early', speaker: 'JAKE',
        agent: 'I prefer to say I gave it an early retirement.',
        user: 'Mr. Chen, please excuse our... creative team.',
        keywords: ['excuse', 'creative'] },
      { id: 'movies-078', chapter: 'The Investor Arrives Early', speaker: 'LUCY',
        agent: 'So, Mr. Chen, what brings you to startups like ours?',
        user: "Yes, we'd love to hear what caught your eye.",
        keywords: ['love', 'caught'] },
      { id: 'movies-079', chapter: 'The Investor Arrives Early', speaker: 'JAKE',
        agent: 'He probably saw our amazing website. I made it!',
        user: 'The website is great. But our product is better.',
        keywords: ['website', 'better'] },
      { id: 'movies-080', chapter: 'The Investor Arrives Early', speaker: 'LUCY',
        agent: "Mia, why don't you show Mr. Chen what BrightBox does?",
        user: "I'd love to. Mr. Chen, have you seen a smart lunchbox?",
        keywords: ['seen', 'lunchbox'] },
      { id: 'movies-081', chapter: 'The Investor Arrives Early', speaker: 'JAKE',
        agent: "It's not just a box! It's a revolution in a box!",
        user: 'Jake, let me pitch. You handle the questions later.',
        keywords: ['pitch', 'later'] },
      { id: 'movies-082', chapter: 'The Investor Arrives Early', speaker: 'LUCY',
        agent: 'Take your time, Mia. Remember: smile and breathe.',
        user: 'Smile and breathe. Here we go, team.',
        keywords: ['here', 'team'] },
      { id: 'movies-083', chapter: 'The Investor Arrives Early', speaker: 'JAKE',
        agent: "You've got this, Mia! We're right behind you!",
        user: 'Here goes. Wish me luck, everyone.',
        keywords: ['luck'] },
      { id: 'movies-084', chapter: 'The Investor Arrives Early', speaker: 'LUCY',
        agent: "No luck needed. You've done the work.",
        user: 'Okay. Mr. Chen, let me tell you about BrightBox.',
        keywords: ['tell', 'about'] },
      // ---------- Scene 7: The Pitch ----------
      { id: 'movies-085', chapter: 'The Pitch', speaker: 'JAKE',
        agent: "She's starting! Everyone act natural and professional!",
        user: 'Mr. Chen, meet BrightBox: lunch, upgraded.',
        keywords: ['meet', 'upgraded'] },
      { id: 'movies-086', chapter: 'The Pitch', speaker: 'LUCY',
        agent: "She's showing the screenshots now. Looking good.",
        user: 'Our app scans any meal in two seconds flat.',
        keywords: ['scans', 'meal'] },
      { id: 'movies-087', chapter: 'The Pitch', speaker: 'JAKE',
        agent: "Two seconds! I timed it! It's really fast!",
        user: 'Then it builds your nutrition profile automatically.',
        keywords: ['builds', 'automatically'] },
      { id: 'movies-088', chapter: 'The Pitch', speaker: 'LUCY',
        agent: 'Mr. Chen is nodding. Keep going, Mia.',
        user: 'No more guessing. No more boring food diaries.',
        keywords: ['guessing', 'diaries'] },
      { id: 'movies-089', chapter: 'The Pitch', speaker: 'JAKE',
        agent: 'Come on, one live demo! The investors love live demos!',
        user: 'Fine. One quick scan. Jake, make it work.',
        keywords: ['quick', 'work'] },
      { id: 'movies-090', chapter: 'The Pitch', speaker: 'JAKE',
        agent: 'Scanning... scanning... come on... frozen. Classic.',
        user: "And that's why we brought screenshots, Mr. Chen!",
        keywords: ['brought'] },
      { id: 'movies-091', chapter: 'The Pitch', speaker: 'LUCY',
        agent: "Smooth recovery, Mia! He's actually smiling!",
        user: "Honesty works. Our app crashed, our team didn't.",
        keywords: ['honesty', 'crashed'] },
      { id: 'movies-092', chapter: 'The Pitch', speaker: 'JAKE',
        agent: "Mr. Chen wants to know about our competitors.",
        user: "Good question. We're cheaper and much simpler to use.",
        keywords: ['cheaper', 'simpler'] },
      { id: 'movies-093', chapter: 'The Pitch', speaker: 'LUCY',
        agent: "He's asking about your background, Mia. Tell him.",
        user: 'I managed food apps for five years before BrightBox.',
        keywords: ['managed', 'years'] },
      { id: 'movies-094', chapter: 'The Pitch', speaker: 'JAKE',
        agent: "He's pointing at Captain Quackers! He wants to know!",
        user: "That's Jake's debugging duck. Don't ask.",
        keywords: ['debugging', 'ask'] },
      { id: 'movies-095', chapter: 'The Pitch', speaker: 'JAKE',
        agent: 'The duck finds bugs! I explain code to him!',
        user: "And somehow it works. Don't question the duck.",
        keywords: ['question', 'works'] },
      { id: 'movies-096', chapter: 'The Pitch', speaker: 'LUCY',
        agent: 'Mr. Chen is laughing! He loves the duck story!',
        user: "See? Honesty and a duck. That's our strategy.",
        keywords: ['strategy'] },
      { id: 'movies-097', chapter: 'The Pitch', speaker: 'JAKE',
        agent: "He's asking the big one: why will you win?",
        user: 'Because we solve a real problem real people have.',
        keywords: ['solve', 'real'] },
      { id: 'movies-098', chapter: 'The Pitch', speaker: 'LUCY',
        agent: 'Pitch complete! Mia, you were wonderful!',
        user: 'Thank you. Now the hard part: his decision.',
        keywords: ['hard', 'decision'] },
      // ---------- Scene 8: The Twist ----------
      { id: 'movies-099', chapter: 'The Twist', speaker: 'JAKE',
        agent: "He's quiet. Quiet is bad. Quiet is very bad.",
        user: "Quiet just means he's thinking, Jake.",
        keywords: ['thinking'] },
      { id: 'movies-100', chapter: 'The Twist', speaker: 'LUCY',
        agent: "He's asking to speak with you alone, Mia.",
        user: 'Alone? Okay. Guys, wish me luck.',
        keywords: ['alone', 'luck'] },
      { id: 'movies-101', chapter: 'The Twist', speaker: 'JAKE',
        agent: "We'll be right outside! With the duck for support!",
        user: 'Mr. Chen, what did you want to discuss?',
        keywords: ['discuss'] },
      { id: 'movies-102', chapter: 'The Twist', speaker: 'LUCY',
        agent: "Take your time in there. We'll keep busy out here.",
        user: "So, Mr. Chen, what are your thoughts so far?",
        keywords: ['thoughts'] },
      { id: 'movies-103', chapter: 'The Twist', speaker: 'JAKE',
        agent: "He stepped out to take a call. What happened in there?",
        user: 'He told me about his daughter. She has diabetes.',
        keywords: ['daughter', 'diabetes'] },
      { id: 'movies-104', chapter: 'The Twist', speaker: 'LUCY',
        agent: 'Oh, the poor man. That explains his interest.',
        user: 'He tracks her meals by hand every single day.',
        keywords: ['tracks', 'hand'] },
      { id: 'movies-105', chapter: 'The Twist', speaker: 'JAKE',
        agent: "So this isn't just business for him. It's personal.",
        user: 'Exactly. He wants BrightBox to help families like his.',
        keywords: ['families'] },
      { id: 'movies-106', chapter: 'The Twist', speaker: 'LUCY',
        agent: "But what did he decide? Don't keep us waiting.",
        user: 'He has not decided. He moved the meeting to test us.',
        keywords: ['test'] },
      { id: 'movies-107', chapter: 'The Twist', speaker: 'JAKE',
        agent: 'Test us? That early meeting was a test?',
        user: 'He wanted to see us under pressure. Sneaky, right?',
        keywords: ['pressure', 'sneaky'] },
      { id: 'movies-108', chapter: 'The Twist', speaker: 'LUCY',
        agent: 'And did we pass his little test, do you think?',
        user: "He smiled at the duck. I'd call that passing.",
        keywords: ['smiled', 'passing'] },
      { id: 'movies-109', chapter: 'The Twist', speaker: 'JAKE',
        agent: "Captain Quackers saves the day again! He's a hero!",
        user: 'The duck helped. But our honesty won him over.',
        keywords: ['honesty', 'over'] },
      { id: 'movies-110', chapter: 'The Twist', speaker: 'LUCY',
        agent: "He's coming back. Everyone look calm and confident.",
        user: 'Calm and confident. I can do calm and confident.',
        keywords: ['calm', 'confident'] },
      { id: 'movies-111', chapter: 'The Twist', speaker: 'JAKE',
        agent: "He's shaking your hand! That's a good sign!",
        user: "He's offering us the investment, team!",
        keywords: ['offering', 'investment'] },
      { id: 'movies-112', chapter: 'The Twist', speaker: 'LUCY',
        agent: 'I knew it! Did he mention the terms?',
        user: "One condition: a kids' version within a year.",
        keywords: ['condition', 'kids'] },
      // ---------- Scene 9: The Deal ----------
      { id: 'movies-113', chapter: 'The Deal', speaker: 'JAKE',
        agent: "A kids' version? We can totally do that!",
        user: "Totally. BrightBox Junior. I love it already.",
        keywords: ['junior', 'love'] },
      { id: 'movies-114', chapter: 'The Deal', speaker: 'LUCY',
        agent: "Did you agree? Tell me you didn't agree too fast.",
        user: "I said we'd love to discuss it properly.",
        keywords: ['discuss', 'properly'] },
      { id: 'movies-115', chapter: 'The Deal', speaker: 'JAKE',
        agent: 'Properly? Mia, he offered us money! Say yes!',
        user: 'Smart founders read the terms first, Jake.',
        keywords: ['smart', 'terms'] },
      { id: 'movies-116', chapter: 'The Deal', speaker: 'LUCY',
        agent: "She's right. Excitement now, lawyers tomorrow.",
        user: "Exactly. But between us... I'm thrilled.",
        keywords: ['thrilled'] },
      { id: 'movies-117', chapter: 'The Deal', speaker: 'JAKE',
        agent: 'Can we celebrate now? Please? Just a little?',
        user: 'A little. But no robot dance yet.',
        keywords: ['little', 'dance'] },
      { id: 'movies-118', chapter: 'The Deal', speaker: 'LUCY',
        agent: "Mr. Chen is leaving. Let's walk him out properly.",
        user: 'Thank you for believing in us, Mr. Chen.',
        keywords: ['believing'] },
      { id: 'movies-119', chapter: 'The Deal', speaker: 'JAKE',
        agent: 'He waved at the duck! The duck gets a wave!',
        user: "Everyone loves Captain Quackers. It's science.",
        keywords: ['science'] },
      { id: 'movies-120', chapter: 'The Deal', speaker: 'LUCY',
        agent: 'Term sheet tomorrow, he said. Then we celebrate.',
        user: 'Tomorrow. Today, we breathe and clean up.',
        keywords: ['breathe', 'clean'] },
      { id: 'movies-121', chapter: 'The Deal', speaker: 'JAKE',
        agent: "I can't believe we survived! We actually did it!",
        user: 'We did. Paper screenshots and all.',
        keywords: ['paper'] },
      { id: 'movies-122', chapter: 'The Deal', speaker: 'LUCY',
        agent: 'Never underestimate old school methods, my dears.',
        user: "Lesson learned, Lucy. I'll never doubt the printouts.",
        keywords: ['lesson', 'printouts'] },
      { id: 'movies-123', chapter: 'The Deal', speaker: 'JAKE',
        agent: 'So... can I do the robot dance now?',
        user: "Fine. One robot dance. You've earned it.",
        keywords: ['earned'] },
      { id: 'movies-124', chapter: 'The Deal', speaker: 'LUCY',
        agent: "I'll allow it. Just don't break anything else.",
        user: 'The coffee machine is already broken. Go wild.',
        keywords: ['wild'] },
      { id: 'movies-125', chapter: 'The Deal', speaker: 'JAKE',
        agent: 'Best day ever! Ship it! Ship it! Ship it!',
        user: "Ship it! Okay, team, let's clean this office.",
        keywords: ['ship', 'clean'] },
      { id: 'movies-126', chapter: 'The Deal', speaker: 'LUCY',
        agent: "I'll start with Jake's desk. It scares me.",
        user: "Good luck. You'll need a map and snacks.",
        keywords: ['map', 'snacks'] },
      // ---------- Scene 10: Aftermath ----------
      { id: 'movies-127', chapter: 'Aftermath', speaker: 'LUCY',
        agent: 'Mia, hand me that paperclip. Watch a master.',
        user: "A paperclip? You're fixing it with a paperclip?",
        keywords: ['paperclip'] },
      { id: 'movies-128', chapter: 'Aftermath', speaker: 'JAKE',
        agent: 'No way. That machine is dead forever.',
        user: 'Lucy fixed the printer with a hairpin once.',
        keywords: ['hairpin'] },
      { id: 'movies-129', chapter: 'Aftermath', speaker: 'LUCY',
        agent: 'And... there! Listen to that beautiful sound!',
        user: "It's working! Lucy, you're a miracle worker!",
        keywords: ['miracle', 'worker'] },
      { id: 'movies-130', chapter: 'Aftermath', speaker: 'JAKE',
        agent: "I take back everything. You're a genius, Lucy!",
        user: 'To Lucy: keeper of screenshots, fixer of machines.',
        keywords: ['keeper', 'fixer'] },
      { id: 'movies-131', chapter: 'Aftermath', speaker: 'LUCY',
        agent: 'To the team: the bravest startup in town.',
        user: "To BrightBox! And to Captain Quackers!",
        keywords: ['brightbox'] },
      { id: 'movies-132', chapter: 'Aftermath', speaker: 'JAKE',
        agent: 'Best team ever! Now, about my password...',
        user: 'Change it tonight. Password one two three four is weak.',
        keywords: ['change', 'weak'] },
      { id: 'movies-133', chapter: 'Aftermath', speaker: 'LUCY',
        agent: 'Speaking of tonight, check your email, Mia.',
        user: "Email? At six? Can't it wait till morning?",
        keywords: ['wait', 'morning'] },
      { id: 'movies-134', chapter: 'Aftermath', speaker: 'JAKE',
        agent: 'Is it the term sheet? Already? That was fast!',
        user: "Not the term sheet. It's... oh no.",
        keywords: ['term', 'sheet'] },
      { id: 'movies-135', chapter: 'Aftermath', speaker: 'LUCY',
        agent: 'Oh no what? Mia, what does oh no mean?',
        user: "It's from LunchTech. Our biggest competitor.",
        keywords: ['competitor'] },
      { id: 'movies-136', chapter: 'Aftermath', speaker: 'JAKE',
        agent: 'LunchTech? What do they want from us?',
        user: 'They want to meet. Tomorrow. About a partnership.',
        keywords: ['partnership'] },
      { id: 'movies-137', chapter: 'Aftermath', speaker: 'LUCY',
        agent: 'A partnership? Or are they scared of us?',
        user: 'Probably scared. We just got funded, after all.',
        keywords: ['scared', 'funded'] },
      { id: 'movies-138', chapter: 'Aftermath', speaker: 'JAKE',
        agent: 'Tomorrow? I need sleep! Real sleep this time!',
        user: 'Sleep fast, Jake. Tomorrow we meet the competition.',
        keywords: ['fast', 'competition'] },
      { id: 'movies-139', chapter: 'Aftermath', speaker: 'LUCY',
        agent: "Same time tomorrow, team. Bring your A-game.",
        user: 'And Jake? No more midnight coding tonight.',
        keywords: ['midnight', 'coding'] },
      { id: 'movies-140', chapter: 'Aftermath', speaker: 'JAKE',
        agent: 'No promises! But first... SHIP IT!',
        user: "Ship it! See you tomorrow, team.",
        keywords: ['ship', 'tomorrow'] }
    ]
  };
})();
