/* Speak or Boom — Classic Movies scenario: Speak Like a Star */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.movies = {
    id: 'movies',
    title: 'Classic Movies',
    tagline: 'Speak Like a Star',
    speaker: 'SCENE',
    difficulty: 'Intermediate',
    rounds: [
      // ---------- Chapter 1: Forrest Gump ----------
      { id: 'movies-001', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Forrest sits on the bench and offers you chocolate. Say his famous line.',
        user: 'Life is like a box of chocolates.',
        keywords: ['box', 'chocolates'] },
      { id: 'movies-002', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Forrest finishes the chocolate saying. Say the second half now.',
        user: "You never know what you're gonna get.",
        keywords: ['never', 'gonna'] },
      { id: 'movies-003', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'A stranger calls Forrest stupid. Repeat his clever answer.',
        user: 'Stupid is as stupid does.',
        keywords: ['stupid'] },
      { id: 'movies-004', chapter: 'Forrest Gump', speaker: 'JENNY',
        agent: "Young Forrest can't run well. Jenny shouts at him. Shout her line.",
        user: 'Run, Forrest, run!',
        keywords: ['run', 'forrest'] },
      { id: 'movies-005', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Forrest introduces himself to a stranger. Say it like he does.',
        user: "My name's Forrest Gump.",
        keywords: ['forrest', 'gump'] },
      { id: 'movies-006', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Forrest finishes telling his long story. Close it his way.',
        user: "That's all I have to say about that.",
        keywords: ['say', 'about'] },
      { id: 'movies-007', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Forrest describes his friendship with Jenny. Use his words.',
        user: 'Jenny and me was like peas and carrots.',
        keywords: ['peas', 'carrots'] },
      { id: 'movies-008', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Forrest talks about loving Jenny all his life. Say his honest line.',
        user: "I'm not a smart man, but I know what love is.",
        keywords: ['smart', 'love'] },
      { id: 'movies-009', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Forrest shares good news about Lieutenant Dan. Say his happy line.',
        user: 'Lieutenant Dan got new legs.',
        keywords: ['lieutenant', 'legs'] },
      { id: 'movies-010', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'After running for three years, Forrest suddenly stops. Say his quiet line.',
        user: "I'm pretty tired. I think I'll go home now.",
        keywords: ['tired', 'home'] },
      { id: 'movies-011', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Forrest remembers his friend Bubba in Vietnam. Say his sad line.',
        user: 'Bubba was my best good friend.',
        keywords: ['bubba', 'friend'] },
      { id: 'movies-012', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: "Forrest quotes his mama's best advice. Say her wise words.",
        user: 'Do the best with what God gave you.',
        keywords: ['best', 'god'] },
      { id: 'movies-013', chapter: 'Forrest Gump', speaker: 'JENNY',
        agent: 'Forrest asks Jenny to marry him. Answer him gently as Jenny.',
        user: 'Yes, Forrest. I will marry you.',
        keywords: ['marry'] },
      { id: 'movies-014', chapter: 'Forrest Gump', speaker: 'MAMA',
        agent: 'Forrest asks about his destiny. Answer him as his mama.',
        user: "You're gonna have to figure that out yourself.",
        keywords: ['figure', 'yourself'] },
      { id: 'movies-015', chapter: 'Forrest Gump', speaker: 'DAN',
        agent: 'You are Lieutenant Dan. Forrest asks about shrimping. Encourage him.',
        user: 'Take that boat and find your shrimp, Gump.',
        keywords: ['boat', 'shrimp'] },
      { id: 'movies-016', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'A reporter asks why Forrest started running. Answer simply.',
        user: 'I just felt like running that day.',
        keywords: ['felt', 'running'] },
      { id: 'movies-017', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Jenny asks if Forrest is afraid. Answer her honestly.',
        user: "I'm not afraid, Jenny. Not anymore.",
        keywords: ['afraid'] },
      { id: 'movies-018', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: 'Someone asks Forrest about Vietnam. Keep your answer short and calm.',
        user: 'It rained a lot over there.',
        keywords: ['rained'] },
      { id: 'movies-019', chapter: 'Forrest Gump', speaker: 'MAMA',
        agent: 'Forrest is sad about school. Comfort him as his mama.',
        user: "You're no different from anyone else, Forrest.",
        keywords: ['different'] },
      { id: 'movies-020', chapter: 'Forrest Gump', speaker: 'GUMP',
        agent: "Forrest says goodbye at Jenny's grave. Speak from your heart.",
        user: "I miss you, Jenny. I'll always miss you.",
        keywords: ['miss', 'jenny'] },
      // ---------- Chapter 2: Titanic ----------
      { id: 'movies-021', chapter: 'Titanic', speaker: 'JACK',
        agent: "Jack stands at the ship's bow, arms wide. Shout his famous line.",
        user: "I'm the king of the world!",
        keywords: ['king', 'world'] },
      { id: 'movies-022', chapter: 'Titanic', speaker: 'JACK',
        agent: 'Jack promises to follow Rose anywhere. Say his romantic line.',
        user: 'You jump, I jump, remember?',
        keywords: ['jump'] },
      { id: 'movies-023', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Rose holds Jack in the freezing water. Say her tearful promise.',
        user: "I'll never let go, Jack.",
        keywords: ['never', 'jack'] },
      { id: 'movies-024', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Rose asks Jack to draw her. Say her bold request.',
        user: 'Draw me like one of your French girls.',
        keywords: ['draw', 'french'] },
      { id: 'movies-025', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Old Rose begins her story about the ship. Say her poetic line.',
        user: "A woman's heart is a deep ocean of secrets.",
        keywords: ['heart', 'ocean'] },
      { id: 'movies-026', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Rose begs Jack to survive the cold water. Say her desperate line.',
        user: 'You must do me this honor.',
        keywords: ['honor'] },
      { id: 'movies-027', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Rose keeps begging Jack. Make him promise to live.',
        user: "Promise me you'll survive, Jack.",
        keywords: ['promise', 'survive'] },
      { id: 'movies-028', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Jack asks if Rose trusts him. Answer him softly.',
        user: 'I trust you, Jack. I really do.',
        keywords: ['trust'] },
      { id: 'movies-029', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Jack asks how it feels at the bow. Answer with joy.',
        user: "I'm flying! This feels amazing!",
        keywords: ['flying'] },
      { id: 'movies-030', chapter: 'Titanic', speaker: 'JACK',
        agent: 'Jack asks Rose to close her eyes. Tell her as Jack.',
        user: 'Close your eyes, Rose. Trust me now.',
        keywords: ['eyes'] },
      { id: 'movies-031', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Rose decides to leave her rich fiance. Tell Jack your plan.',
        user: "I'm leaving with you, Jack. Tonight.",
        keywords: ['leaving'] },
      { id: 'movies-032', chapter: 'Titanic', speaker: 'JACK',
        agent: 'Jack just won two ship tickets. Shout the good news.',
        user: "We won the tickets! We're going!",
        keywords: ['tickets'] },
      { id: 'movies-033', chapter: 'Titanic', speaker: 'ROSE',
        agent: "Rose meets Jack's artist friends. Introduce yourself warmly.",
        user: "I'm Rose. It's nice to meet you.",
        keywords: ['rose'] },
      { id: 'movies-034', chapter: 'Titanic', speaker: 'JACK',
        agent: 'Jack asks Rose to come to a real party. Invite her below deck.',
        user: 'Come to a real party with me.',
        keywords: ['party'] },
      { id: 'movies-035', chapter: 'Titanic', speaker: 'CAL',
        agent: 'You are Cal. Rose is missing again. Call out for her angrily.',
        user: 'Rose! Where have you been all night?',
        keywords: ['rose', 'night'] },
      { id: 'movies-036', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Cal asks where Rose was. Answer him coldly.',
        user: "I was with Jack. I won't lie.",
        keywords: ['jack'] },
      { id: 'movies-037', chapter: 'Titanic', speaker: 'JACK',
        agent: 'The ship is sinking. Tell Rose to stay calm.',
        user: "Stay calm, Rose. We'll get out.",
        keywords: ['calm'] },
      { id: 'movies-038', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'An officer asks if women and children go first. Answer quickly.',
        user: 'Yes! Women and children first, please!',
        keywords: ['women', 'children'] },
      { id: 'movies-039', chapter: 'Titanic', speaker: 'ROSE',
        agent: 'Jack asks Rose to promise something. Give him your word.',
        user: "I promise. I'll never let go.",
        keywords: ['promise'] },
      { id: 'movies-040', chapter: 'Titanic', speaker: 'JACK',
        agent: 'Say goodbye to Rose as the ship goes down. Be brave.',
        user: 'Go on, Rose. Live your life.',
        keywords: ['live'] },
      // ---------- Chapter 3: The Shawshank Redemption ----------
      { id: 'movies-041', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy explains his life philosophy to Red. Say his famous line.',
        user: 'Get busy living, or get busy dying.',
        keywords: ['living', 'dying'] },
      { id: 'movies-042', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy talks about hope in prison. Say the first half.',
        user: 'Hope is a good thing.',
        keywords: ['hope'] },
      { id: 'movies-043', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy finishes his thought about hope. Say the second half.',
        user: 'Maybe the best of things.',
        keywords: ['best'] },
      { id: 'movies-044', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy contrasts fear and hope. Say the first half.',
        user: 'Fear can hold you prisoner.',
        keywords: ['fear', 'prisoner'] },
      { id: 'movies-045', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy finishes the contrast. Say the hopeful half.',
        user: 'Hope can set you free.',
        keywords: ['free'] },
      { id: 'movies-046', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy writes a secret letter to the warden. Read the opening line.',
        user: 'Dear Warden, you were right.',
        keywords: ['warden'] },
      { id: 'movies-047', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy dreams of the Pacific Ocean. Say his dreamy line.',
        user: 'I hope the Pacific is as blue as in my dreams.',
        keywords: ['pacific', 'dreams'] },
      { id: 'movies-048', chapter: 'The Shawshank Redemption', speaker: 'RED',
        agent: "Red describes Andy's free spirit. Say his thoughtful line.",
        user: "Some birds aren't meant to be caged.",
        keywords: ['birds', 'caged'] },
      { id: 'movies-049', chapter: 'The Shawshank Redemption', speaker: 'RED',
        agent: "The parole board asks Red if he's rehabilitated. Answer honestly.",
        user: "I don't have any idea what that means.",
        keywords: ['idea'] },
      { id: 'movies-050', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy tells Red his plan for Mexico. Describe your dream.',
        user: "I'll open a small hotel there.",
        keywords: ['hotel'] },
      { id: 'movies-051', chapter: 'The Shawshank Redemption', speaker: 'RED',
        agent: 'Andy asks Red for a rock hammer. Reply like a smuggler.',
        user: "I can get it. It'll cost you.",
        keywords: ['cost'] },
      { id: 'movies-052', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Red asks why Andy loves the library. Explain it simply.',
        user: 'Books help us forget these walls.',
        keywords: ['books', 'walls'] },
      { id: 'movies-053', chapter: 'The Shawshank Redemption', speaker: 'RED',
        agent: "Andy asks if Red thinks he's innocent. Answer carefully.",
        user: "Everyone in here claims they're innocent.",
        keywords: ['innocent'] },
      { id: 'movies-054', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'The warden asks Andy to do his taxes. Agree politely.',
        user: "I'd be glad to help you, sir.",
        keywords: ['glad'] },
      { id: 'movies-055', chapter: 'The Shawshank Redemption', speaker: 'RED',
        agent: 'Red warns Andy about hope in prison. Give your warning.',
        user: 'Hope is dangerous in this place.',
        keywords: ['dangerous'] },
      { id: 'movies-056', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy plays music over the speakers. Describe how it feels.',
        user: 'For a moment, we all felt free.',
        keywords: ['free'] },
      { id: 'movies-057', chapter: 'The Shawshank Redemption', speaker: 'RED',
        agent: 'Red meets Andy on the beach at last. Greet your old friend.',
        user: 'Andy! You made it, my friend!',
        keywords: ['andy', 'friend'] },
      { id: 'movies-058', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Red asks how Andy escaped. Keep it mysterious.',
        user: "Let's just say I got lucky.",
        keywords: ['lucky'] },
      { id: 'movies-059', chapter: 'The Shawshank Redemption', speaker: 'RED',
        agent: "The board asks about Red's future plans. Answer with hope.",
        user: 'I hope to see my friend again.',
        keywords: ['hope', 'friend'] },
      { id: 'movies-060', chapter: 'The Shawshank Redemption', speaker: 'ANDY',
        agent: 'Andy gives Red final advice about hope. Say his gentle line.',
        user: 'Remember, Red: hope is a good thing.',
        keywords: ['remember', 'hope'] },
      // ---------- Chapter 4: The Godfather ----------
      { id: 'movies-061', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'The Don promises to solve a problem. Say his chilling line.',
        user: "I'm gonna make him an offer he can't refuse.",
        keywords: ['offer', 'refuse'] },
      { id: 'movies-062', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'Michael explains a hard decision. Say his cold line.',
        user: "It's not personal. It's strictly business.",
        keywords: ['personal', 'business'] },
      { id: 'movies-063', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'After the job, the Don gives an order. Say it calmly.',
        user: 'Leave the gun. Take the cannoli.',
        keywords: ['gun', 'cannoli'] },
      { id: 'movies-064', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'Michael shares his strategy about enemies. Say his wise line.',
        user: 'Keep your friends close, but your enemies closer.',
        keywords: ['friends', 'enemies'] },
      { id: 'movies-065', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'The Don talks about family values. Say the first half.',
        user: "A man who doesn't spend time with his family",
        keywords: ['family'] },
      { id: 'movies-066', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'The Don finishes his thought. Say the second half.',
        user: 'can never be a real man.',
        keywords: ['real'] },
      { id: 'movies-067', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'The Don dislikes unnecessary violence. Tell Tom your view.',
        user: "I don't like violence, Tom.",
        keywords: ['violence'] },
      { id: 'movies-068', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'Michael warns about hatred and judgment. Say his sharp line.',
        user: 'Never hate your enemies. It affects your judgment.',
        keywords: ['hate', 'judgment'] },
      { id: 'movies-069', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'Michael feels trapped by the family business. Say his sad line.',
        user: 'Just when I thought I was out, they pull me back in.',
        keywords: ['out'] },
      { id: 'movies-070', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'A man asks the Don for a favor. Grant it graciously.',
        user: "I'll do this favor for you.",
        keywords: ['favor'] },
      { id: 'movies-071', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'Kay asks if Michael ordered the hit. Deny it firmly.',
        user: "Don't ask me about my business, Kay.",
        keywords: ['business'] },
      { id: 'movies-072', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'The Don welcomes a guest warmly. Offer him kindness.',
        user: "Come, sit down. Let's talk together.",
        keywords: ['talk'] },
      { id: 'movies-073', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'At the baptism, the priest asks a question. Answer as Michael.',
        user: 'I do renounce him.',
        keywords: ['renounce'] },
      { id: 'movies-074', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'Tom asks if the Don is worried. Answer with calm power.',
        user: "There's nothing to worry about.",
        keywords: ['worry'] },
      { id: 'movies-075', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'Fredo betrayed the family. Confront him coldly.',
        user: 'I know it was you, Fredo.',
        keywords: ['fredo'] },
      { id: 'movies-076', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'Michael tells Fredo how he feels. Say the painful half.',
        user: 'You broke my heart, Fredo.',
        keywords: ['broke', 'heart'] },
      { id: 'movies-077', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'The Don advises Michael about life. Share your wisdom.',
        user: "Never tell anyone what you're thinking.",
        keywords: ['thinking'] },
      { id: 'movies-078', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'Michael takes charge of the family. Announce your decision.',
        user: "From now on, I'm in charge.",
        keywords: ['charge'] },
      { id: 'movies-079', chapter: 'The Godfather', speaker: 'VITO',
        agent: 'A friend fears for his shop. Reassure him strongly.',
        user: 'No one will touch your shop.',
        keywords: ['shop'] },
      { id: 'movies-080', chapter: 'The Godfather', speaker: 'MICHAEL',
        agent: 'Michael closes a dangerous meeting. End it with power.',
        user: "We're finished here. Thank you all.",
        keywords: ['finished'] },
      // ---------- Chapter 5: Harry Potter ----------
      { id: 'movies-081', chapter: 'Harry Potter', speaker: 'HAGRID',
        agent: 'Hagrid reveals the big secret to Harry. Say his famous line.',
        user: "You're a wizard, Harry.",
        keywords: ['wizard'] },
      { id: 'movies-082', chapter: 'Harry Potter', speaker: 'HARRY',
        agent: "Harry opens the Marauder's Map. Say the magic words.",
        user: 'I solemnly swear that I am up to no good.',
        keywords: ['swear'] },
      { id: 'movies-083', chapter: 'Harry Potter', speaker: 'HERMIONE',
        agent: "Hermione corrects Ron's spell pronunciation. Say it proudly.",
        user: "It's leviOsa, not leviosA.",
        keywords: ['leviosa'] },
      { id: 'movies-084', chapter: 'Harry Potter', speaker: 'DUMBLEDORE',
        agent: 'Dumbledore warns Harry about the Mirror of Erised. Say his wise line.',
        user: 'It does not do to dwell on dreams and forget to live.',
        keywords: ['dreams', 'live'] },
      { id: 'movies-085', chapter: 'Harry Potter', speaker: 'OLLIVANDER',
        agent: 'The wand maker explains his craft. Say his mysterious line.',
        user: 'The wand chooses the wizard, Mr. Potter.',
        keywords: ['wand', 'wizard'] },
      { id: 'movies-086', chapter: 'Harry Potter', speaker: 'DUMBLEDORE',
        agent: "Dumbledore talks about Voldemort's name. Say his brave line.",
        user: 'Fear of a name increases fear of the thing itself.',
        keywords: ['fear', 'name'] },
      { id: 'movies-087', chapter: 'Harry Potter', speaker: 'HAGRID',
        agent: 'Hagrid defends who he is. Say his proud line.',
        user: "I am what I am, an' I'm not ashamed.",
        keywords: ['ashamed'] },
      { id: 'movies-088', chapter: 'Harry Potter', speaker: 'DUMBLEDORE',
        agent: 'Dumbledore comforts Harry about dark times. Say his hopeful line.',
        user: 'Happiness can be found even in the darkest of times.',
        keywords: ['happiness', 'darkest'] },
      { id: 'movies-089', chapter: 'Harry Potter', speaker: 'HERMIONE',
        agent: 'Hermione scolds Harry and Ron. Say her funny line.',
        user: 'We could all have been killed, or worse, expelled.',
        keywords: ['killed', 'expelled'] },
      { id: 'movies-090', chapter: 'Harry Potter', speaker: 'SNAPE',
        agent: 'Dumbledore asks if you still love Lily. Answer as Snape.',
        user: 'Always. I have always loved her.',
        keywords: ['always', 'loved'] },
      { id: 'movies-091', chapter: 'Harry Potter', speaker: 'DUMBLEDORE',
        agent: 'Dumbledore praises standing up to enemies. Say the first half.',
        user: 'It takes bravery to stand up to enemies,',
        keywords: ['bravery'] },
      { id: 'movies-092', chapter: 'Harry Potter', speaker: 'DUMBLEDORE',
        agent: 'Dumbledore finishes the thought. Say the second half.',
        user: 'but more to stand up to friends.',
        keywords: ['friends'] },
      { id: 'movies-093', chapter: 'Harry Potter', speaker: 'HARRY',
        agent: 'Hagrid asks if Harry knows the truth. Answer as Harry.',
        user: "I'm just Harry. Only Harry.",
        keywords: ['harry'] },
      { id: 'movies-094', chapter: 'Harry Potter', speaker: 'HARRY',
        agent: 'Ron asks to share your compartment. Welcome him aboard.',
        user: "Come in! I'm Harry, by the way.",
        keywords: ['harry'] },
      { id: 'movies-095', chapter: 'Harry Potter', speaker: 'HERMIONE',
        agent: 'Ron is stuck on the spell again. Correct him sharply.',
        user: 'Wingardium Leviosa! Say it right!',
        keywords: ['right'] },
      { id: 'movies-096', chapter: 'Harry Potter', speaker: 'RON',
        agent: 'Harry asks about your family. Answer as Ron.',
        user: "I've got five older brothers, Harry.",
        keywords: ['brothers'] },
      { id: 'movies-097', chapter: 'Harry Potter', speaker: 'HARRY',
        agent: 'Dumbledore asks if Harry is afraid. Answer bravely.',
        user: 'A little, but I will be brave.',
        keywords: ['brave'] },
      { id: 'movies-098', chapter: 'Harry Potter', speaker: 'HAGRID',
        agent: 'Harry asks about his parents. Answer him gently.',
        user: 'They were brave and kind, Harry.',
        keywords: ['brave', 'kind'] },
      { id: 'movies-099', chapter: 'Harry Potter', speaker: 'HERMIONE',
        agent: 'Harry asks for help with homework. Reply like Hermione.',
        user: "Read the book! It's all in there.",
        keywords: ['book'] },
      { id: 'movies-100', chapter: 'Harry Potter', speaker: 'HARRY',
        agent: 'Voldemort demands the stone. Refuse him firmly.',
        user: "You'll never get it from me.",
        keywords: ['never'] },
      // ---------- Chapter 6: The Lion King ----------
      { id: 'movies-101', chapter: 'The Lion King', speaker: 'TIMON',
        agent: 'Timon teaches his life motto. Sing his famous line.',
        user: 'Hakuna Matata! It means no worries!',
        keywords: ['hakuna', 'matata'] },
      { id: 'movies-102', chapter: 'The Lion King', speaker: 'TIMON',
        agent: 'Timon finishes the song. Sing the second line.',
        user: 'For the rest of your days.',
        keywords: ['rest', 'days'] },
      { id: 'movies-103', chapter: 'The Lion King', speaker: 'MUFASA',
        agent: "Mufasa's ghost appears in the sky. Speak his powerful line.",
        user: 'Remember who you are.',
        keywords: ['remember'] },
      { id: 'movies-104', chapter: 'The Lion King', speaker: 'MUFASA',
        agent: 'Mufasa shows Simba the kingdom. Say his proud line.',
        user: 'Everything the light touches is our kingdom.',
        keywords: ['light', 'kingdom'] },
      { id: 'movies-105', chapter: 'The Lion King', speaker: 'SIMBA',
        agent: 'Simba boasts to Nala about bravery. Say his bold line.',
        user: 'I laugh in the face of danger.',
        keywords: ['laugh', 'danger'] },
      { id: 'movies-106', chapter: 'The Lion King', speaker: 'SIMBA',
        agent: 'Young Simba dreams of ruling. Sing his excited line.',
        user: "Oh, I just can't wait to be king.",
        keywords: ['wait', 'king'] },
      { id: 'movies-107', chapter: 'The Lion King', speaker: 'SCAR',
        agent: 'Scar betrays Mufasa at the cliff. Whisper his cold line.',
        user: 'Long live the king.',
        keywords: ['live', 'king'] },
      { id: 'movies-108', chapter: 'The Lion King', speaker: 'TIMON',
        agent: 'Timon advises Simba about the past. Say his wise line.',
        user: 'You gotta put your past behind you.',
        keywords: ['past'] },
      { id: 'movies-109', chapter: 'The Lion King', speaker: 'SIMBA',
        agent: 'Simba sings about love under the stars. Sing his sweet line.',
        user: 'Can you feel the love tonight?',
        keywords: ['feel', 'tonight'] },
      { id: 'movies-110', chapter: 'The Lion King', speaker: 'SIMBA',
        agent: 'Simba declares his future greatness. Sing it loudly.',
        user: "I'm gonna be a mighty king.",
        keywords: ['mighty', 'king'] },
      { id: 'movies-111', chapter: 'The Lion King', speaker: 'SIMBA',
        agent: 'Mufasa asks if Simba is ready. Answer your father.',
        user: "I'm ready, Father. Teach me everything.",
        keywords: ['ready', 'father'] },
      { id: 'movies-112', chapter: 'The Lion King', speaker: 'MUFASA',
        agent: 'Simba asks about the shadowy place. Warn him sternly.',
        user: 'You must never go there, Simba.',
        keywords: ['never'] },
      { id: 'movies-113', chapter: 'The Lion King', speaker: 'TIMON',
        agent: 'Simba asks what to eat in the jungle. Offer him grubs.',
        user: "Try the grubs! They're tasty and free!",
        keywords: ['grubs', 'tasty'] },
      { id: 'movies-114', chapter: 'The Lion King', speaker: 'PUMBAA',
        agent: 'Timon asks if Pumbaa is worried. Answer calmly.',
        user: "Don't worry. I never worry at all.",
        keywords: ['worry'] },
      { id: 'movies-115', chapter: 'The Lion King', speaker: 'SIMBA',
        agent: 'Nala asks Simba to come home. Refuse her sadly.',
        user: "I can't go back. Not now.",
        keywords: ['back'] },
      { id: 'movies-116', chapter: 'The Lion King', speaker: 'NALA',
        agent: 'Simba refuses to return. Convince him as Nala.',
        user: 'You are our only hope, Simba.',
        keywords: ['hope'] },
      { id: 'movies-117', chapter: 'The Lion King', speaker: 'SCAR',
        agent: 'The hyenas ask about food. Promise them plenty.',
        user: "Stick with me and you'll feast.",
        keywords: ['feast'] },
      { id: 'movies-118', chapter: 'The Lion King', speaker: 'MUFASA',
        agent: 'Simba feels guilty about the stampede. Comfort him.',
        user: 'It was an accident, my son.',
        keywords: ['accident'] },
      { id: 'movies-119', chapter: 'The Lion King', speaker: 'TIMON',
        agent: "Simba asks about the stars. Give Timon's funny answer.",
        user: "They're just fireflies in the sky.",
        keywords: ['fireflies'] },
      { id: 'movies-120', chapter: 'The Lion King', speaker: 'SIMBA',
        agent: 'Simba takes his place as king. Roar your proud line.',
        user: "It's the circle of life!",
        keywords: ['circle', 'life'] },
      // ---------- Chapter 7: More Classics ----------
      { id: 'movies-121', chapter: 'More Classics', speaker: 'RICK',
        agent: 'Rick says goodbye to Ilsa at the airport. Say his tender line.',
        user: "Here's looking at you, kid.",
        keywords: ['looking', 'kid'] },
      { id: 'movies-122', chapter: 'More Classics', speaker: 'RENAULT',
        agent: 'The police chief orders an arrest. Say his famous line.',
        user: 'Round up the usual suspects.',
        keywords: ['usual', 'suspects'] },
      { id: 'movies-123', chapter: 'More Classics', speaker: 'OBIWAN',
        agent: 'Obi-Wan blesses the rebels before battle. Say his Jedi line.',
        user: 'May the Force be with you.',
        keywords: ['force'] },
      { id: 'movies-124', chapter: 'More Classics', speaker: 'YODA',
        agent: 'Yoda trains Luke in the swamp. Say his wise line.',
        user: 'Do or do not. There is no try.',
        keywords: ['try'] },
      { id: 'movies-125', chapter: 'More Classics', speaker: 'TERMINATOR',
        agent: 'The Terminator is denied entry. Say his cold promise.',
        user: "I'll be back.",
        keywords: ['back'] },
      { id: 'movies-126', chapter: 'More Classics', speaker: 'KYLE',
        agent: 'Kyle begs Sarah to trust him. Say his urgent line.',
        user: 'Come with me if you want to live.',
        keywords: ['live'] },
      { id: 'movies-127', chapter: 'More Classics', speaker: 'RHETT',
        agent: 'Rhett finally leaves Scarlett. Say his brutal line.',
        user: "Frankly, my dear, I don't give a damn.",
        keywords: ['frankly', 'damn'] },
      { id: 'movies-128', chapter: 'More Classics', speaker: 'SCARLETT',
        agent: 'Rhett is walking out. Beg him as Scarlett.',
        user: "Rhett, please don't leave me now!",
        keywords: ['leave'] },
      { id: 'movies-129', chapter: 'More Classics', speaker: 'TRAVIS',
        agent: 'Travis talks to himself in the mirror. Say his edgy line.',
        user: "You talkin' to me?",
        keywords: ['talkin'] },
      { id: 'movies-130', chapter: 'More Classics', speaker: 'TRAVIS',
        agent: 'A passenger stares at Travis. Challenge him calmly.',
        user: "Are you talkin' to me, pal?",
        keywords: ['talkin', 'pal'] },
      { id: 'movies-131', chapter: 'More Classics', speaker: 'BUZZ',
        agent: 'Buzz shows off his space ranger pride. Shout his catchphrase.',
        user: 'To infinity and beyond!',
        keywords: ['infinity', 'beyond'] },
      { id: 'movies-132', chapter: 'More Classics', speaker: 'WOODY',
        agent: 'Woody explains his flying trick. Say his clever line.',
        user: "This isn't flying. This is falling with style.",
        keywords: ['flying', 'style'] },
      { id: 'movies-133', chapter: 'More Classics', speaker: 'DOROTHY',
        agent: 'Dorothy clicks her ruby slippers. Say her homesick line.',
        user: "There's no place like home.",
        keywords: ['place', 'home'] },
      { id: 'movies-134', chapter: 'More Classics', speaker: 'DOROTHY',
        agent: 'Dorothy sees the strange new land. Say her amazed line.',
        user: "Toto, I've a feeling we're not in Kansas anymore.",
        keywords: ['toto', 'kansas'] },
      { id: 'movies-135', chapter: 'More Classics', speaker: 'JERRY',
        agent: 'Jerry begs his client to stay. Shout his desperate line.',
        user: 'Show me the money!',
        keywords: ['money'] },
      { id: 'movies-136', chapter: 'More Classics', speaker: 'DOROTHY',
        agent: "Jerry gives his big speech. Stop him with Dorothy's famous reply.",
        user: 'You had me at hello.',
        keywords: ['hello'] },
      { id: 'movies-137', chapter: 'More Classics', speaker: 'MALCOLM',
        agent: "Dr. Malcolm warns about nature's power. Say his famous line.",
        user: 'Life finds a way.',
        keywords: ['life'] },
      { id: 'movies-138', chapter: 'More Classics', speaker: 'GRANT',
        agent: 'Hammond asks if the park is safe. Answer as Dr. Grant.',
        user: 'No fence can hold them forever.',
        keywords: ['fence'] },
      { id: 'movies-139', chapter: 'More Classics', speaker: 'BOND',
        agent: 'Bond introduces himself with style. Say his iconic line.',
        user: "The name's Bond. James Bond.",
        keywords: ['bond', 'james'] },
      { id: 'movies-140', chapter: 'More Classics', speaker: 'BOND',
        agent: 'Bond orders his favorite drink. Say it exactly.',
        user: 'Shaken, not stirred, please.',
        keywords: ['shaken', 'stirred'] },
    ]
  };
})();
