/* Speak or Boom — Restaurant v2 (rich, narrative) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.restaurant = {
    id: 'restaurant',
    title: 'Restaurant',
    tagline: 'Dinner Like a Local',
    speaker: 'WAITER',
    difficulty: 'Intermediate',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: Making a Reservation ----------
      { id: 1, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'Good evening, Bella Roma! This is Marco speaking. How may I make your evening special?',
        user: 'Good evening! I would like to book a table for two this Friday night.',
        keywords: ['evening', 'friday'] },
      { id: 2, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'Friday night, excellent choice! What time works best for your celebration plans?',
        user: 'Around seven thirty would be perfect. We like to savor dinner without rushing.',
        keywords: ['savor', 'rushing'] },
      { id: 3, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'Seven thirty it is. May I ask what occasion brings you to Bella Roma?',
        user: 'I got promoted at work, so we are celebrating with a proper Italian feast.',
        keywords: ['promoted', 'feast'] },
      { id: 4, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'Congratulations! A promotion deserves our finest table by the window, with candlelight.',
        user: 'That sounds absolutely wonderful. A window table would make the evening truly memorable.',
        keywords: ['wonderful', 'memorable'] },
      { id: 5, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'Consider it done. And may I have a name for this very special reservation?',
        user: 'Julia. Julia Bennett. My husband David will be joining me for dinner.',
        keywords: ['bennett', 'husband'] },
      { id: 6, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'Julia and David, what a lovely couple! I will personally ensure everything is perfect.',
        user: 'Thank you, Marco. Your enthusiasm already makes me excited for Friday night.',
        keywords: ['enthusiasm', 'excited'] },
      { id: 7, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'Enthusiasm is my specialty! Should I note any dietary restrictions or allergies beforehand?',
        user: 'No allergies, thankfully. We both love trying new flavors and culinary adventures.',
        keywords: ['allergies', 'culinary'] },
      { id: 8, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'Adventurous eaters are my favorite kind! Our chef loves surprising curious palates.',
        user: 'We are definitely curious. Surprise us with whatever the chef recommends most proudly.',
        keywords: ['curious', 'proudly'] },
      { id: 9, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'The chef will be thrilled! Is there anything else I can arrange for your celebration?',
        user: 'Could you keep the dessert a surprise? I want David to be completely delighted.',
        keywords: ['surprise', 'delighted'] },
      { id: 10, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'A surprise dessert, sealed with secrecy! Your table is booked for Friday at seven thirty.',
        user: 'Perfect. I really appreciate you making this reservation feel so personal and special.',
        keywords: ['appreciate', 'personal'] },
      { id: 11, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'Personal touches make all the difference. We will see you Friday, Julia! Congratulations again!',
        user: 'Thank you so much, Marco. We are already counting down the days until Friday.',
        keywords: ['counting', 'days'] },
      { id: 12, chapter: 'Making a Reservation', speaker: 'MARCO',
        agent: 'The countdown begins! Arrive hungry, leave happy — that is our promise at Bella Roma.',
        user: 'I have no doubt. Goodbye for now, and see you on Friday evening!',
        keywords: ['doubt', 'evening'] },
      // ---------- Chapter 2: Being Seated ----------
      { id: 13, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'Welcome back to Bella Roma! You must be Julia. I have been expecting you both.',
        user: 'Yes, that is us! The place looks even more beautiful than I had imagined.',
        keywords: ['beautiful', 'imagined'] },
      { id: 14, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'Thank you! We dimmed the lights specially and saved the finest window table for you.',
        user: 'The candlelight is lovely. David, is this not the most romantic spot in town?',
        keywords: ['candlelight', 'romantic'] },
      { id: 15, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'Romance is practically our second specialty, right after authentic Italian cuisine.',
        user: 'I can tell. The aroma from the kitchen is already making my mouth water.',
        keywords: ['aroma', 'kitchen'] },
      { id: 16, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'That aroma is our wood-fired oven working its magic on tonight’s special focaccia bread.',
        user: 'Wood-fired? No wonder it smells incredible. I feel like I am already in Italy.',
        keywords: ['incredible', 'woodfired'] },
      { id: 17, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'Close your eyes and you might hear the distant church bells of Rome, no?',
        user: 'You are quite the poet, Marco. Is everyone here as charming as you are?',
        keywords: ['poet', 'charming'] },
      { id: 18, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'Charm comes with the territory! Here are your menus, printed fresh this morning.',
        user: 'The menu is extensive. I might need your guidance to navigate these delicious options.',
        keywords: ['extensive', 'guidance'] },
      { id: 19, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'Guidance is what I do best! But first, can I bring you some sparkling water?',
        user: 'Sparkling water would be lovely. And perhaps some of that amazing focaccia bread?',
        keywords: ['sparkling', 'focaccia'] },
      { id: 20, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'Focaccia coming right up, warm from the oven with our house-made rosemary oil.',
        user: 'House-made rosemary oil? You really do pay attention to every delicious detail here.',
        keywords: ['rosemary', 'detail'] },
      { id: 21, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'Details are everything in Italian cooking. My grandmother taught me that lesson well.',
        user: 'Your grandmother sounds wise. Family recipes always carry the most love and tradition.',
        keywords: ['grandmother', 'tradition'] },
      { id: 22, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'She was the heart of our family kitchen. Many of tonight’s dishes come from her notebook.',
        user: 'What a beautiful legacy! I feel honored to taste recipes with such meaningful history.',
        keywords: ['legacy', 'honored'] },
      { id: 23, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'She would be delighted to hear that. Now, shall we talk about drinks to start?',
        user: 'Yes, please! David loves red wine, and I am open to your expert recommendation.',
        keywords: ['recommendation', 'expert'] },
      { id: 24, chapter: 'Being Seated', speaker: 'MARCO',
        agent: 'Expert recommendations coming right up! Let me fetch our wine list for you both.',
        user: 'Take your time. We are in absolutely no hurry on this special celebration night.',
        keywords: ['absolutely', 'celebration'] },
      // ---------- Chapter 3: Ordering Drinks ----------
      { id: 25, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Here is our wine list, featuring small vineyards from Tuscany to Sicily.',
        user: 'So many choices! I feel slightly overwhelmed by all these wonderful Italian regions.',
        keywords: ['overwhelmed', 'regions'] },
      { id: 26, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Overwhelmed is normal! Tell me what flavors you enjoy, and I will narrow it down.',
        user: 'We both prefer something bold and full-bodied, with a smooth, lingering finish.',
        keywords: ['bold', 'lingering'] },
      { id: 27, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Bold and full-bodied? Then you must try our Barolo — the king of Italian wines.',
        user: 'The king of wines sounds perfect for a promotion celebration. Tell us more.',
        keywords: ['king', 'celebration'] },
      { id: 28, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Barolo comes from Piedmont, aged for years in oak barrels until it becomes pure elegance.',
        user: 'Aged for years? I love the idea of drinking something with such patience.',
        keywords: ['something', 'drinking'] },
      { id: 29, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Patience is the secret ingredient! Shall I bring a bottle for the table to share?',
        user: 'Yes, a bottle would be lovely. David, are you as excited as I am?',
        keywords: ['bottle', 'excited'] },
      { id: 30, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Excellent choice! I will decant it properly so the flavors can fully blossom.',
        user: 'Decanting sounds so sophisticated. I had no idea wine needed to breathe like that.',
        keywords: ['sophisticated', 'decanting'] },
      { id: 31, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Breathing transforms it completely! While it decants, may I offer sparkling water refills?',
        user: 'Yes, please. And Marco, your passion for wine is genuinely contagious and inspiring.',
        keywords: ['passion', 'contagious'] },
      { id: 32, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Passion is impossible to hide when you truly love what you do every single day.',
        user: 'I completely agree. Finding work you love is the greatest professional blessing.',
        keywords: ['greatest', 'blessing'] },
      { id: 33, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Speaking of blessings, your Barolo is ready! Let me pour a small taste first.',
        user: 'The color is gorgeous — deep ruby with such remarkable clarity and depth.',
        keywords: ['gorgeous', 'clarity'] },
      { id: 34, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Remarkable indeed! Swirl it gently, then inhale deeply to catch the cherry aromas.',
        user: 'Cherries and... is that chocolate? This is far more complex than I expected.',
        keywords: ['cherries', 'complex'] },
      { id: 35, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Chocolate, cherries, even a hint of roses! Your palate is impressively discerning.',
        user: 'Thank you! I am learning so much tonight. This is already an unforgettable evening.',
        keywords: ['unforgettable', 'learning'] },
      { id: 36, chapter: 'Ordering Drinks', speaker: 'MARCO',
        agent: 'Unforgettable is exactly what we aim for! Now, shall we explore the starters menu?',
        user: 'Absolutely. Though after that wine lesson, my expectations are incredibly high now.',
        keywords: ['expectations', 'incredibly'] },
      // ---------- Chapter 4: Ordering Starters ----------
      { id: 37, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'For starters, I highly recommend our burrata — creamy, delicate, utterly unforgettable.',
        user: 'Burrata? I have heard wonderful things but never actually tasted the real thing.',
        keywords: ['wonderful', 'tasted'] },
      { id: 38, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'Then tonight is your lucky night! It arrives with heirloom tomatoes and fresh basil.',
        user: 'Heirloom tomatoes sound so much more interesting than the ordinary supermarket kind.',
        keywords: ['heirloom', 'ordinary'] },
      { id: 39, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'Infinitely more interesting! Each tomato variety tells a different story of Italian soil.',
        user: 'I love that philosophy — food as storytelling. What else would you suggest?',
        keywords: ['philosophy', 'storytelling'] },
      { id: 40, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'Our bruschetta is legendary — grilled bread rubbed with garlic and ripe tomatoes.',
        user: 'Legendary bruschetta and burrata? We might be too full for mains at this rate!',
        keywords: ['legendary', 'bruschetta'] },
      { id: 41, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'Pace yourself! In Italy, dinner is a marathon, not a sprint. Savor each course slowly.',
        user: 'A marathon, not a sprint — I need to remember that. We rush everything.',
        keywords: ['marathon', 'sprint'] },
      { id: 42, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'Rushing through dinner is the greatest tragedy! Food deserves your full attention and presence.',
        user: 'You are absolutely right. Tonight we will eat slowly and appreciate every single bite.',
        keywords: ['absolutely', 'appreciate'] },
      { id: 43, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'That is the spirit! So, burrata and bruschetta to start — an excellent adventurous combination.',
        user: 'Perfect. David, are you ready for this incredible Italian feast to begin?',
        keywords: ['incredible', 'italian'] },
      { id: 44, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'The feast begins! I will alert the kitchen that a celebration is officially underway.',
        user: 'Thank you, Marco. Your excitement makes everything feel even more festive and special.',
        keywords: ['festive', 'special'] },
      { id: 45, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'Festive is my middle name! Your starters will arrive in about ten minutes.',
        user: 'Ten minutes is perfect. It gives us time to enjoy this magnificent Barolo properly.',
        keywords: ['magnificent', 'properly'] },
      { id: 46, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'Enjoy every sip! And do not forget to save room — the best is yet to come.',
        user: 'We will try our best, though your descriptions make everything sound irresistible.',
        keywords: ['irresistible', 'descriptions'] },
      { id: 47, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'Irresistible is the goal! Here comes your burrata — look at that creamy center!',
        user: 'Oh my goodness, it is beautiful! The colors are so vibrant and appetizing.',
        keywords: ['vibrant', 'appetizing'] },
      { id: 48, chapter: 'Ordering Starters', speaker: 'MARCO',
        agent: 'Beautiful and delicious! Break it open and let the creamy heart flow onto the plate.',
        user: 'This is divine! The creaminess perfectly balances the acidity of those tomatoes.',
        keywords: ['divine', 'balances'] },
      // ---------- Chapter 5: Ordering Mains ----------
      { id: 49, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Now for the main event! Are you in the mood for pasta, seafood, or something hearty?',
        user: 'I am craving pasta — something authentic that I could never make at home.',
        keywords: ['craving', 'authentic'] },
      { id: 50, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Authentic pasta craving? Then you must try our handmade tagliatelle with wild mushrooms.',
        user: 'Handmade tagliatelle sounds incredible. Is it really made fresh here every day?',
        keywords: ['handmade', 'incredible'] },
      { id: 51, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Every single morning! Our pasta chef arrives at dawn to knead the dough by hand.',
        user: 'Dawn? That is true dedication. No wonder the texture is so remarkably silky.',
        keywords: ['dedication', 'silky'] },
      { id: 52, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Silky is the perfect word! The wild mushrooms are foraged from nearby forests.',
        user: 'Foraged mushrooms? That sounds wonderfully rustic and deeply connected to nature.',
        keywords: ['foraged', 'rustic'] },
      { id: 53, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Rustic yet refined — that is our philosophy! What about David? What is he craving?',
        user: 'David has been eyeing the osso buco. He loves slow-cooked meats that fall apart.',
        keywords: ['slowcooked', 'eyeing'] },
      { id: 54, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Osso buco is a masterpiece! The veal shank braises for four hours until meltingly tender.',
        user: 'Four hours? That level of patience is exactly what makes great food truly memorable.',
        keywords: ['memorable', 'patience'] },
      { id: 55, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Memorable is guaranteed! It comes with saffron risotto that will change your life.',
        user: 'Change my life? Bold claims, Marco. But I am starting to believe you.',
        keywords: ['claims', 'believe'] },
      { id: 56, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Believe me, I have never been wrong about osso buco! So, tagliatelle and osso buco?',
        user: 'Yes, exactly. Though I am already worried about having room for dessert later.',
        keywords: ['exactly', 'worried'] },
      { id: 57, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Worried about dessert? In Italy, there is always room — the stomach expands with joy!',
        user: 'The stomach expands with joy — I am using that line at future dinners.',
        keywords: ['expands', 'future'] },
      { id: 58, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Use it freely! Your mains will take about twenty minutes. Enjoy the anticipation!',
        user: 'Anticipation is half the pleasure. We will savor our wine while we wait patiently.',
        keywords: ['anticipation', 'pleasure'] },
      { id: 59, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Perfectly said! Here is your tagliatelle — notice how the sauce clings to every strand.',
        user: 'It looks stunning! The mushroom aroma is earthy and incredibly inviting right now.',
        keywords: ['stunning', 'inviting'] },
      { id: 60, chapter: 'Ordering Mains', speaker: 'MARCO',
        agent: 'Earthy and inviting, exactly! And David, your osso buco — be careful, it is falling apart!',
        user: 'This is extraordinary! The meat is so tender it practically melts in my mouth.',
        keywords: ['extraordinary', 'tender'] },
      // ---------- Chapter 6: Dietary Needs ----------
      { id: 61, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Before I forget — David mentioned a nut allergy earlier. I have alerted our kitchen.',
        user: 'Thank you for remembering! His allergy is serious, so we really appreciate your care.',
        keywords: ['allergy', 'appreciate'] },
      { id: 62, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Serious allergies deserve serious attention. Our chef personally oversees allergy orders.',
        user: 'That is so reassuring. Dining out can feel stressful when allergies are involved.',
        keywords: ['reassuring', 'stressful'] },
      { id: 63, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Stressful indeed, which is why we take it seriously. No nuts anywhere near your table.',
        user: 'Your thoroughness means the world to us. We can finally relax and enjoy ourselves.',
        keywords: ['thoroughness', 'relax'] },
      { id: 64, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Relaxation is the goal! Are there any other dietary preferences I should note?',
        user: 'I am trying to eat less dairy lately, though tonight is definitely an exception.',
        keywords: ['dairy', 'exception'] },
      { id: 65, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Celebrations are always exceptions! But I can suggest lighter options for next time.',
        user: 'I would love that. It is nice knowing you accommodate different needs so gracefully.',
        keywords: ['accommodate', 'gracefully'] },
      { id: 66, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Gracefully accommodating everyone is what hospitality truly means, in my humble opinion.',
        user: 'Humble and wise! You should write a book about the philosophy of great service.',
        keywords: ['philosophy', 'service'] },
      { id: 67, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'A book? Perhaps titled "The Art of Making Strangers Feel Like Family."',
        user: 'I would buy that book! You have certainly made us feel like family tonight.',
        keywords: ['certainly', 'tonight'] },
      { id: 68, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Family is exactly what Bella Roma is about! Now, how are those magnificent mains treating you?',
        user: 'Magnificent is an understatement. Every bite is better than the last one.',
        keywords: ['understatement', 'better'] },
      { id: 69, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Better with every bite — music to a waiter’s ears! Can I refresh your wine?',
        user: 'Yes, please. This Barolo pairs beautifully with both the pasta and the veal.',
        keywords: ['pairs', 'beautifully'] },
      { id: 70, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Beautifully indeed! A great wine elevates the entire meal to another level entirely.',
        user: 'It really does. I am learning that dining is about harmony between all elements.',
        keywords: ['elements', 'learning'] },
      { id: 71, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Harmony is the perfect word! You are thinking like a true Italian already.',
        user: 'High praise! Though I still have so much to learn about your delicious culture.',
        keywords: ['praise', 'culture'] },
      { id: 72, chapter: 'Dietary Needs', speaker: 'MARCO',
        agent: 'Learning is a lifelong feast! Speaking of which, are you ready to discuss dessert?',
        user: 'Dessert? After all this? You are ambitious, Marco. But I am intrigued...',
        keywords: ['ambitious', 'intrigued'] },
      // ---------- Chapter 7: Asking the Waiter ----------
      { id: 73, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Before dessert, you seem curious. Ask me anything about Bella Roma or Italian food!',
        user: 'How long has this restaurant been here? It feels full of history and character.',
        keywords: ['history', 'character'] },
      { id: 74, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Twenty-five years! My family opened it after emigrating from Naples with two suitcases.',
        user: 'Two suitcases and a dream? That is the most inspiring story I have heard.',
        keywords: ['inspiring', 'suitcases'] },
      { id: 75, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'A dream and my grandmother’s recipe notebook — that was our entire business plan!',
        user: 'A recipe notebook as a business plan? That is both brave and beautifully simple.',
        keywords: ['notebook', 'beautifully'] },
      { id: 76, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Beautifully simple indeed! Those handwritten recipes still guide our kitchen every day.',
        user: 'Handwritten recipes carry so much love. You can taste the difference, honestly.',
        keywords: ['handwritten', 'honestly'] },
      { id: 77, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Honestly, you can! Love is the invisible ingredient that no supermarket can sell.',
        user: 'The invisible ingredient — what a poetic way to describe what makes food special.',
        keywords: ['invisible', 'poetic'] },
      { id: 78, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Poetic but true! What else would you like to know about our little corner of Italy?',
        user: 'What is the most popular dish? I am curious what keeps people coming back.',
        keywords: ['popular', 'curious'] },
      { id: 79, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Our lasagna! It has twelve layers, each one spread with patience and parmesan.',
        user: 'Twelve layers? That sounds like an architectural masterpiece you can actually eat.',
        keywords: ['layers', 'architectural'] },
      { id: 80, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Edible architecture, exactly! It takes three hours to assemble and bake properly.',
        user: 'Three hours for one dish? That is commitment. I have new respect for lasagna.',
        keywords: ['commitment', 'lasagna'] },
      { id: 81, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Respect well earned! Shall I add a lasagna tasting portion to your dessert course?',
        user: 'A tasting portion sounds perfect. We can handle a small bite of that legend.',
        keywords: ['tasting', 'legend'] },
      { id: 82, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'A legendary bite coming up! Now, have I convinced you about dessert yet?',
        user: 'You had me at tiramisu. I have been dreaming about it since we arrived.',
        keywords: ['tiramisu', 'dreaming'] },
      { id: 83, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Dreaming of tiramisu? Then your dreams are about to come true in spectacular fashion!',
        user: 'Spectacular fashion? Now you are just teasing me, Marco. Bring on the dessert!',
        keywords: ['spectacular', 'teasing'] },
      { id: 84, chapter: 'Asking the Waiter', speaker: 'MARCO',
        agent: 'Teasing is part of the service! Our tiramisu recipe is older than I am.',
        user: 'Older than you? Now I absolutely must taste this piece of edible history.',
        keywords: ['absolutely', 'edible'] },
      // ---------- Chapter 8: Handling a Problem ----------
      { id: 85, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'Oh dear, I notice David pushing his risotto aside. Is something not quite right?',
        user: 'Honestly? It is too salty for him. But please do not make a fuss.',
        keywords: ['salty', 'fuss'] },
      { id: 86, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'No fuss at all, but I insist on fixing it! Your enjoyment matters more than my pride.',
        user: 'That is kind, but we do not want to trouble the kitchen staff.',
        keywords: ['kitchen', 'trouble'] },
      { id: 87, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'Trouble? Nonsense! A good restaurant welcomes the chance to make things right.',
        user: 'Your attitude is refreshing. Many places get defensive about any criticism.',
        keywords: ['refreshing', 'defensive'] },
      { id: 88, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'Defensive helps nobody! Let me have the chef prepare a fresh, perfectly seasoned portion.',
        user: 'Perfectly seasoned sounds wonderful. David, is that alright with you, dear?',
        keywords: ['seasoned', 'wonderful'] },
      { id: 89, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'While we wait, please enjoy some complimentary bruschetta on the house.',
        user: 'Complimentary bruschetta? You are turning a small problem into a delightful surprise.',
        keywords: ['complimentary', 'delightful'] },
      { id: 90, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'Delightful surprises are my specialty! Here is the new risotto — taste the difference.',
        user: 'Much better! The flavors are balanced and the saffron really shines through now.',
        keywords: ['balanced', 'shines'] },
      { id: 91, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'Balanced and shining — exactly as it should be! Thank you for your patience and grace.',
        user: 'Thank you for handling it so professionally. This is why we will definitely return.',
        keywords: ['professionally', 'definitely'] },
      { id: 92, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'Definitely returning? That is the greatest compliment a restaurant can ever receive!',
        user: 'Well deserved. You turned a minor issue into a memorable moment of care.',
        keywords: ['deserved', 'memorable'] },
      { id: 93, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'Memorable care is our mission! Now, shall we finally talk about that tiramisu?',
        user: 'Yes! After that excellent recovery, we have definitely earned our dessert.',
        keywords: ['recovery', 'earned'] },
      { id: 94, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'Earned and deserved! One tiramisu with a candle for the promotion celebration?',
        user: 'A candle would be perfect! David, are you ready for the grand finale?',
        keywords: ['candle', 'finale'] },
      { id: 95, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'The grand finale awaits! I will also bring that lasagna tasting portion we discussed.',
        user: 'You remembered! Your attention to detail is truly remarkable, Marco.',
        keywords: ['remembered', 'remarkable'] },
      { id: 96, chapter: 'Handling a Problem', speaker: 'MARCO',
        agent: 'Remarkable memory comes from genuinely caring about every guest who walks through our door.',
        user: 'We feel genuinely cared for. This is what dining should always feel like.',
        keywords: ['genuinely', 'cared'] },
      // ---------- Chapter 9: Dessert & Coffee ----------
      { id: 97, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Behold! Tiramisu with a candle, and a petite lasagna tasting portion on the side.',
        user: 'It looks stunning! The candlelight makes everything glow with such warmth.',
        keywords: ['stunning', 'glow'] },
      { id: 98, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Warmth and glow, perfect for a celebration! Make a wish before you blow it out.',
        user: 'I wish I could tell you! Let us say I am deeply grateful tonight.',
        keywords: ['grateful', 'wish'] },
      { id: 99, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Grateful is a wonderful wish! Now taste the tiramisu — coffee-soaked ladyfingers await.',
        user: 'Heavenly! The mascarpone is so light it practically floats off the spoon.',
        keywords: ['heavenly', 'mascarpone'] },
      { id: 100, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Floating mascarpone, what an image! Our secret is whipping it just enough, never too much.',
        user: 'Secrets worth keeping! I would love the recipe, though you will never share.',
        keywords: ['keeping', 'secrets'] },
      { id: 101, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Never sharing! Some mysteries make life more delicious. Try the lasagna bite now.',
        user: 'Twelve layers in one bite? The complexity is astonishing — rich, deep, comforting.',
        keywords: ['complexity', 'astonishing'] },
      { id: 102, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Astonishing complexity, beautifully described! You have the palate of a true food critic.',
        user: 'Food critic? Maybe I missed my calling. Though I prefer eating to writing reviews.',
        keywords: ['critic', 'calling'] },
      { id: 103, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Eating is definitely more fun! Would you like espresso to finish this perfect meal?',
        user: 'Espresso would be ideal. Something strong to balance all this wonderful sweetness.',
        keywords: ['espresso', 'ideal'] },
      { id: 104, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Ideal indeed! Two espressos, served the traditional Italian way — short and intense.',
        user: 'Short and intense, like the best moments in life. I love that philosophy.',
        keywords: ['intense', 'philosophy'] },
      { id: 105, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Philosophy in a demitasse! Here you are — drink it in one confident sip, like Italians do.',
        user: 'One confident sip... wow! Bitter, bold, and the perfect ending to this feast.',
        keywords: ['confident', 'perfect'] },
      { id: 106, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'The perfect ending to a perfect evening! Though I am sad to see it conclude.',
        user: 'All good things must end, unfortunately. But the memories will last much longer.',
        keywords: ['unfortunately', 'memories'] },
      { id: 107, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Memories last forever, especially delicious ones! Shall I bring the bill whenever you are ready?',
        user: 'Whenever ready, Marco. We are in no rush to leave this magical atmosphere.',
        keywords: ['magical', 'atmosphere'] },
      { id: 108, chapter: 'Dessert & Coffee', speaker: 'MARCO',
        agent: 'Magical atmosphere, lingering as long as you like! I will fetch the bill shortly.',
        user: 'Thank you. David and I need a moment to absorb how wonderful tonight is.',
        keywords: ['wonderful', 'tonight'] },
      // ---------- Chapter 10: The Bill ----------
      { id: 109, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'Here is your bill, no rush at all. Take your time reviewing every delicious detail.',
        user: 'Everything looks correct. Though I must say, the value here is absolutely exceptional.',
        keywords: ['correct', 'exceptional'] },
      { id: 110, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'Exceptional value for an exceptional evening! We believe great food should be accessible.',
        user: 'Accessible luxury — I love that concept. Too many fine restaurants feel intimidating.',
        keywords: ['accessible', 'intimidating'] },
      { id: 111, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'Intimidating is the opposite of hospitality! Everyone deserves to feel welcome at our table.',
        user: 'You have certainly made us feel welcome. This is worth every single penny.',
        keywords: ['welcome', 'penny'] },
      { id: 112, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'Every penny supports our family dream! Would you like to pay by card or cash?',
        user: 'Card, please. And Marco, please add a generous tip for your outstanding service.',
        keywords: ['generous', 'outstanding'] },
      { id: 113, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'Generous and kind! You have already given me the best tip — your genuine happiness.',
        user: 'Happiness is easy here. You have a real gift for making people feel special.',
        keywords: ['happiness', 'special'] },
      { id: 114, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'A gift I am grateful to share! Your card is processed. Here is your receipt.',
        user: 'Thank you. I will keep this receipt as a souvenir of our perfect night.',
        keywords: ['receipt', 'souvenir'] },
      { id: 115, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'A souvenir receipt? That is a first! I am truly honored by such a sweet gesture.',
        user: 'Honored is the right word. Tonight exceeded all our expectations in every way.',
        keywords: ['honored', 'exceeded'] },
      { id: 116, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'Exceeded expectations — the four most beautiful words in the restaurant business!',
        user: 'Beautiful words for a beautiful evening. We could not have asked for more.',
        keywords: ['beautiful', 'evening'] },
      { id: 117, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'More is always possible! Which brings me to — would you like anything for tomorrow?',
        user: 'Tomorrow? Are you suggesting we take some of this magic home with us?',
        keywords: ['suggesting', 'magic'] },
      { id: 118, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'Magic to go! Our takeaway boxes keep everything fresh and delicious for tomorrow.',
        user: 'Takeaway sounds wonderful. Though I doubt these leftovers will survive until morning.',
        keywords: ['takeaway', 'leftovers'] },
      { id: 119, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'Leftovers rarely survive! But let me pack that remaining osso buco for you anyway.',
        user: 'Yes, please. Midnight snacks of osso buco sound like pure luxury to me.',
        keywords: ['midnight', 'luxury'] },
      { id: 120, chapter: 'The Bill', speaker: 'MARCO',
        agent: 'Pure luxury indeed! I will pack it carefully with extra sauce on the side.',
        user: 'Extra sauce is essential. You think of everything, Marco. Truly impressive.',
        keywords: ['essential', 'impressive'] },
      // ---------- Chapter 11: Takeaway ----------
      { id: 121, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'Your takeaway is ready! I also tucked in some extra focaccia for tomorrow’s breakfast.',
        user: 'Extra focaccia? You are spoiling us! Tomorrow morning just got much more exciting.',
        keywords: ['spoiling', 'exciting'] },
      { id: 122, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'Exciting mornings start with good bread! Reheat it briefly for maximum crispiness.',
        user: 'Briefly reheated for crispiness — noted! You are full of useful culinary wisdom.',
        keywords: ['crispiness', 'wisdom'] },
      { id: 123, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'Culinary wisdom comes free with every takeaway box! Anything else for the road?',
        user: 'I think we are set. Though I am tempted to order the entire menu.',
        keywords: ['tempted', 'entire'] },
      { id: 124, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'The entire menu? Ambitious! But I admire your enthusiasm for our humble kitchen.',
        user: 'Humble? There is nothing humble about food this extraordinary and memorable.',
        keywords: ['extraordinary', 'memorable'] },
      { id: 125, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'Extraordinary yet humble — the perfect balance, just like our beloved grandmother taught us.',
        user: 'Your grandmother would be so proud of what you have built here, Marco.',
        keywords: ['grandmother', 'built'] },
      { id: 126, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'Proud indeed, I hope! She always said food tastes better when shared with love.',
        user: 'Shared with love — tonight proved her absolutely right in every delicious way.',
        keywords: ['shared', 'proved'] },
      { id: 127, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'Proved deliciously! Here is your bag, carefully packed and ready for midnight feasting.',
        user: 'Midnight feasting sounds perfect. Thank you for thinking of our future happiness.',
        keywords: ['feasting', 'happiness'] },
      { id: 128, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'Future happiness is my specialty! Now, before you go, one last thing...',
        user: 'One last thing? You have me intrigued, Marco. What surprise do you have now?',
        keywords: ['intrigued', 'surprise'] },
      { id: 129, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'A small limoncello, on the house! The traditional Italian farewell to a perfect meal.',
        user: 'Limoncello? What a thoughtful gesture! To Bella Roma and unforgettable evenings!',
        keywords: ['limoncello', 'thoughtful'] },
      { id: 130, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'To unforgettable evenings! Salute! May your promotion bring you endless joy and success.',
        user: 'Salute! Thank you for making this celebration more magical than we ever imagined.',
        keywords: ['salute', 'magical'] },
      { id: 131, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'Magical is what we do! Now, let me walk you to the door like proper Italian hosts.',
        user: 'Proper Italian hospitality until the very end. You never disappoint, Marco.',
        keywords: ['hospitality', 'disappoint'] },
      { id: 132, chapter: 'Takeaway', speaker: 'MARCO',
        agent: 'Disappointing you would disappoint my grandmother! And that is simply unforgivable.',
        user: 'Unforgivable indeed! Give our regards to the chef and your wonderful team.',
        keywords: ['unforgivable', 'regards'] },
      // ---------- Chapter 12: Complimenting the Meal ----------
      { id: 133, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'The chef sends his regards too! He says your appreciation made his entire evening.',
        user: 'Please tell him his food is art. Every dish was a masterpiece of flavor.',
        keywords: ['masterpiece', 'flavor'] },
      { id: 134, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Art on a plate! He will be thrilled. Compliments from happy guests fuel his creativity.',
        user: 'Creativity fueled by happiness — what a wonderful cycle of joy and deliciousness.',
        keywords: ['deliciousness', 'creativity'] },
      { id: 135, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Joy and deliciousness, the perfect recipe! Will we see you again sometime soon?',
        user: 'Absolutely! We are already planning our anniversary dinner here next month.',
        keywords: ['anniversary', 'planning'] },
      { id: 136, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Anniversary next month? I will reserve your favorite window table right now!',
        user: 'You are incredible! Though next time, I want to try that twelve-layer lasagna.',
        keywords: ['incredible', 'lasagna'] },
      { id: 137, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Twelve layers of happiness await! I will make sure the chef prepares something extraordinary.',
        user: 'Extraordinary is becoming your signature word, Marco. And you always deliver on it.',
        keywords: ['signature', 'deliver'] },
      { id: 138, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Delivering extraordinary is my life’s work! Thank you for letting me be part of tonight.',
        user: 'Thank you for turning dinner into an unforgettable story we will tell for years.',
        keywords: ['unforgettable', 'story'] },
      { id: 139, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Stories worth telling are the best souvenirs! Drive safely, and dream of tiramisu.',
        user: 'Dream of tiramisu? I absolutely will! Goodnight, Marco, and thank you again.',
        keywords: ['absolutely', 'goodnight'] },
      { id: 140, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Goodnight, Julia! Congratulations again on your promotion — you have earned every bit!',
        user: 'Thank you! Tonight was the perfect way to celebrate this exciting new chapter.',
        keywords: ['celebrate', 'exciting'] },
      { id: 141, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'New chapters deserve grand celebrations! May the next one be even more delicious.',
        user: 'More delicious? That seems impossible, but I trust Bella Roma to surprise us.',
        keywords: ['impossible', 'delicious'] },
      { id: 142, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Surprising you is our pleasure! Arrivederci, Julia and David — until next time!',
        user: 'Arrivederci, Marco! You have made us lifelong fans of Bella Roma.',
        keywords: ['arrivederci', 'lifelong'] },
      { id: 143, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Lifelong fans are the greatest reward! Your limoncello toast will stay with me.',
        user: 'And your hospitality will stay with us. This was truly dinner like a local.',
        keywords: ['hospitality', 'dinner'] },
      { id: 144, chapter: 'Complimenting the Meal', speaker: 'MARCO',
        agent: 'Dinner like a local, memories like family! Buonanotte, and thank you for everything.',
        user: 'Buonanotte, Marco! We will be back soon — that is a delicious promise.',
        keywords: ['buonanotte', 'promise'] }
    ]
  };
})();
