/* Speak or Boom — Restaurant scenario */
(function () {
'use strict';
window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
window.SPEAK_OR_BOOM_SCENARIOS.restaurant = {
  id: 'restaurant',
  title: 'Restaurant',
  tagline: 'Dinner Like a Local',
  speaker: 'WAITER',
  difficulty: 'Beginner',
  rounds: [
    // ---- Chapter 1: Making a Reservation ----
    { id: 'restaurant-001', chapter: 'Making a Reservation', agent: 'Good evening. Thank you for calling Bella Roma. How can I help?', user: "I'd like to book a table for two.", keywords: ['book', 'table'] },
    { id: 'restaurant-002', chapter: 'Making a Reservation', agent: 'Of course. Which day would you like to come?', user: "Friday evening, around seven o'clock.", keywords: ['friday', 'seven'] },
    { id: 'restaurant-003', chapter: 'Making a Reservation', agent: 'Friday at seven. How many people is that for?', user: 'Just two of us, please.', keywords: ['two'] },
    { id: 'restaurant-004', chapter: 'Making a Reservation', agent: 'Do you have a preference — inside or on the terrace?', user: 'Inside, near the window if possible.', keywords: ['inside', 'window'] },
    { id: 'restaurant-005', chapter: 'Making a Reservation', agent: "I'll note that down. A name for the reservation?", user: "It's under Li, L-I.", keywords: ['li'] },
    { id: 'restaurant-006', chapter: 'Making a Reservation', agent: 'Thank you. And a phone number, please?', user: "Sure, it's one three eight, eight eight eight eight.", keywords: ['eight'] },
    { id: 'restaurant-007', chapter: 'Making a Reservation', agent: 'Any special occasion we should know about?', user: "It's our anniversary, actually.", keywords: ['anniversary'] },
    { id: 'restaurant-008', chapter: 'Making a Reservation', agent: 'Wonderful! Would you like a quiet corner table?', user: 'That would be lovely, thanks.', keywords: ['lovely'] },
    { id: 'restaurant-009', chapter: 'Making a Reservation', agent: 'We hold tables for fifteen minutes. Is that okay?', user: "Yes, we'll be on time.", keywords: ['time'] },
    { id: 'restaurant-010', chapter: 'Making a Reservation', agent: 'One last thing — any allergies we should note?', user: 'No allergies, thank you.', keywords: ['allergies'] },
    { id: 'restaurant-011', chapter: 'Making a Reservation', agent: 'Perfect. Anything else I can do for you?', user: "No, that's everything. Thanks!", keywords: ['everything'] },
    { id: 'restaurant-012', chapter: 'Making a Reservation', agent: 'See you Friday at seven, Mr. Li. Goodbye.', user: 'Great, see you then. Bye!', keywords: ['bye'] },
    // ---- Chapter 2: Being Seated ----
    { id: 'restaurant-013', chapter: 'Being Seated', agent: 'Good evening! Welcome to Bella Roma. Do you have a reservation?', user: 'Yes, a table for two under Li.', keywords: ['table', 'two'] },
    { id: 'restaurant-014', chapter: 'Being Seated', agent: 'Mr. Li, right this way. How was your evening so far?', user: 'Pretty good, thank you. And yours?', keywords: ['yours'] },
    { id: 'restaurant-015', chapter: 'Being Seated', agent: "Busy but fun. Here's your table by the window.", user: 'This is perfect. Thank you.', keywords: ['perfect'] },
    { id: 'restaurant-016', chapter: 'Being Seated', agent: 'Can I take your coats for you?', user: 'Yes, please. Take our coats.', keywords: ['coats'] },
    { id: 'restaurant-017', chapter: 'Being Seated', agent: 'Your waiter will be with you in a moment.', user: "No rush. We're in no hurry.", keywords: ['hurry'] },
    { id: 'restaurant-018', chapter: 'Being Seated', agent: 'Here are the menus. The specials are on the back page.', user: "Thanks. We'll study the menus.", keywords: ['menus'] },
    { id: 'restaurant-019', chapter: 'Being Seated', agent: 'Would you like still or sparkling water to start?', user: 'Still water would be great.', keywords: ['still'] },
    { id: 'restaurant-020', chapter: 'Being Seated', agent: "Of course. I'll bring that right away.", user: 'Thank you very much.', keywords: ['thank'] },
    { id: 'restaurant-021', chapter: 'Being Seated', agent: 'Is this your first time dining with us?', user: 'Yes, our friends recommended this place.', keywords: ['recommended'] },
    { id: 'restaurant-022', chapter: 'Being Seated', agent: 'Lovely! I hope you enjoy your anniversary dinner.', user: "Thank you. We're really looking forward to it.", keywords: ['forward'] },
    { id: 'restaurant-023', chapter: 'Being Seated', agent: 'Enjoy your evening, and just wave if you need anything.', user: "Will do. I'll wave you down.", keywords: ['wave'] },
    { id: 'restaurant-024', chapter: 'Being Seated', agent: "Here's your water. Enjoy your evening!", user: 'Perfect timing, thanks. Cheers!', keywords: ['cheers'] },
    // ---- Chapter 3: Ordering Drinks ----
    { id: 'restaurant-025', chapter: 'Ordering Drinks', agent: "Good evening, I'm Marco. Can I start you with drinks?", user: "Yes, I'd like a glass of red wine.", keywords: ['wine', 'red'] },
    { id: 'restaurant-026', chapter: 'Ordering Drinks', agent: 'Any preference? We have a lovely house Chianti.', user: 'The house red sounds good.', keywords: ['house'] },
    { id: 'restaurant-027', chapter: 'Ordering Drinks', agent: 'And for you, madam? What would you like?', user: "I'll have a sparkling water with lime.", keywords: ['sparkling', 'lime'] },
    { id: 'restaurant-028', chapter: 'Ordering Drinks', agent: 'Would you like to see the cocktail menu?', user: 'Not tonight, thanks. Just the wine.', keywords: ['tonight'] },
    { id: 'restaurant-029', chapter: 'Ordering Drinks', agent: 'Red wine and sparkling water with lime. Anything else?', user: "That's all for now, thanks.", keywords: ['now'] },
    { id: 'restaurant-030', chapter: 'Ordering Drinks', agent: 'Your drinks will be right out.', user: 'Great. Could we have some bread too?', keywords: ['bread'] },
    { id: 'restaurant-031', chapter: 'Ordering Drinks', agent: 'Of course — our bread is baked fresh daily.', user: 'Wonderful. We love fresh bread.', keywords: ['fresh'] },
    { id: 'restaurant-032', chapter: 'Ordering Drinks', agent: 'Here are your drinks. Enjoy them!', user: 'Thank you. The drinks look great.', keywords: ['drinks'] },
    { id: 'restaurant-033', chapter: 'Ordering Drinks', agent: 'Can I get you anything else while you decide?', user: "We're still looking at the menu.", keywords: ['menu'] },
    { id: 'restaurant-034', chapter: 'Ordering Drinks', agent: "Take your time. I'll check back in a few minutes.", user: 'Sounds good. Thank you.', keywords: ['sounds'] },
    { id: 'restaurant-035', chapter: 'Ordering Drinks', agent: "How's the wine? Is it to your liking?", user: "It's excellent, really smooth.", keywords: ['excellent', 'smooth'] },
    { id: 'restaurant-036', chapter: 'Ordering Drinks', agent: 'Glad to hear it. Ready to order, or a few more minutes?', user: 'Give us five more minutes, please.', keywords: ['minutes'] },
    // ---- Chapter 4: Ordering Starters ----
    { id: 'restaurant-037', chapter: 'Ordering Starters', agent: 'Have you had a chance to look at the starters?', user: "Yes, we'll start with the bruschetta.", keywords: ['bruschetta'] },
    { id: 'restaurant-038', chapter: 'Ordering Starters', agent: 'Excellent choice. Would you like anything else to begin?', user: 'The garlic mushrooms as well, please.', keywords: ['mushrooms'] },
    { id: 'restaurant-039', chapter: 'Ordering Starters', agent: 'Would you like those to share, or one each?', user: "We'll share both, thanks.", keywords: ['share'] },
    { id: 'restaurant-040', chapter: 'Ordering Starters', agent: 'Lovely. And how about something to drink with those?', user: "We're fine with our drinks, thanks.", keywords: ['fine'] },
    { id: 'restaurant-041', chapter: 'Ordering Starters', agent: "Would you like to hear today's soup special?", user: "Sure, what's the soup today?", keywords: ['soup'] },
    { id: 'restaurant-042', chapter: 'Ordering Starters', agent: 'Creamy tomato basil, served with warm bread.', user: "Sounds nice, but we'll skip the soup.", keywords: ['skip'] },
    { id: 'restaurant-043', chapter: 'Ordering Starters', agent: 'No problem. Should I bring the starters together?', user: 'Yes, together is perfect.', keywords: ['together'] },
    { id: 'restaurant-044', chapter: 'Ordering Starters', agent: "I'll get those starters fired up right away.", user: 'Great, thank you very much.', keywords: ['great'] },
    { id: 'restaurant-045', chapter: 'Ordering Starters', agent: 'Here are your starters — bruschetta and garlic mushrooms.', user: 'They look delicious. Thank you!', keywords: ['delicious'] },
    { id: 'restaurant-046', chapter: 'Ordering Starters', agent: "Enjoy! I'll be back to take your main orders.", user: "Perfect. We'll keep looking at the menu.", keywords: ['menu'] },
    { id: 'restaurant-047', chapter: 'Ordering Starters', agent: 'How are the starters? Everything good?', user: 'Really tasty. The bruschetta is amazing.', keywords: ['amazing'] },
    { id: 'restaurant-048', chapter: 'Ordering Starters', agent: 'Wonderful. Ready for mains, or shall I give you time?', user: "We're ready when you are.", keywords: ['ready'] },
    // ---- Chapter 5: Ordering Mains ----
    { id: 'restaurant-049', chapter: 'Ordering Mains', agent: 'What can I get you for your main courses?', user: "I'll have the mushroom risotto, please.", keywords: ['risotto'] },
    { id: 'restaurant-050', chapter: 'Ordering Mains', agent: "And for you, sir? What's your choice?", user: 'The grilled salmon for me.', keywords: ['salmon'] },
    { id: 'restaurant-051', chapter: 'Ordering Mains', agent: 'How would you like your salmon cooked?', user: 'Medium, please. Not too dry.', keywords: ['medium'] },
    { id: 'restaurant-052', chapter: 'Ordering Mains', agent: 'Would you like any sides with that?', user: 'The roasted vegetables, please.', keywords: ['vegetables'] },
    { id: 'restaurant-053', chapter: 'Ordering Mains', agent: 'Anything for the lady — a side salad, perhaps?', user: 'A small green salad, please.', keywords: ['salad'] },
    { id: 'restaurant-054', chapter: 'Ordering Mains', agent: 'Dressing on the salad — oil and vinegar okay?', user: 'Just olive oil, please.', keywords: ['olive'] },
    { id: 'restaurant-055', chapter: 'Ordering Mains', agent: 'So: risotto, salmon, vegetables, and a green salad.', user: "That's exactly right. Thanks!", keywords: ['exactly'] },
    { id: 'restaurant-056', chapter: 'Ordering Mains', agent: "I'll fire those mains right away.", user: "Wonderful. We're looking forward to it.", keywords: ['forward'] },
    { id: 'restaurant-057', chapter: 'Ordering Mains', agent: 'Your mains are on the way — about fifteen minutes.', user: 'No rush at all. Thank you.', keywords: ['rush'] },
    { id: 'restaurant-058', chapter: 'Ordering Mains', agent: 'Can I top up your water while you wait?', user: "Yes, please. More water would be lovely.", keywords: ['water'] },
    { id: 'restaurant-059', chapter: 'Ordering Mains', agent: 'Here are your main courses. Enjoy your meal!', user: 'Thank you. Everything looks wonderful.', keywords: ['wonderful'] },
    { id: 'restaurant-060', chapter: 'Ordering Mains', agent: "I'll check back in a few minutes.", user: 'Great, thanks so much, Marco.', keywords: ['marco'] },
    // ---- Chapter 6: Dietary Needs ----
    { id: 'restaurant-061', chapter: 'Dietary Needs', agent: 'Before I go — any dietary requirements I should note?', user: "Actually, I'm a vegetarian.", keywords: ['vegetarian'] },
    { id: 'restaurant-062', chapter: 'Dietary Needs', agent: 'No problem. Several dishes can be made vegetarian.', user: 'Is the risotto made with chicken stock?', keywords: ['stock'] },
    { id: 'restaurant-063', chapter: 'Dietary Needs', agent: 'Good question — let me check with the kitchen.', user: "Thanks. I'd really appreciate that.", keywords: ['appreciate'] },
    { id: 'restaurant-064', chapter: 'Dietary Needs', agent: 'Good news — our risotto uses vegetable stock.', user: "Perfect. That's a relief!", keywords: ['relief'] },
    { id: 'restaurant-065', chapter: 'Dietary Needs', agent: 'And you, sir — any allergies I should know about?', user: "I'm allergic to peanuts.", keywords: ['peanuts'] },
    { id: 'restaurant-066', chapter: 'Dietary Needs', agent: "Thank you for telling me. I'll alert the kitchen.", user: "It's quite serious, so please be careful.", keywords: ['serious'] },
    { id: 'restaurant-067', chapter: 'Dietary Needs', agent: "Absolutely. We'll take every precaution in the kitchen.", user: 'Thank you. That means a lot.', keywords: ['lot'] },
    { id: 'restaurant-068', chapter: 'Dietary Needs', agent: 'The salmon is cooked separately — no nuts involved.', user: 'Good to know. Thank you.', keywords: ['know'] },
    { id: 'restaurant-069', chapter: 'Dietary Needs', agent: 'Would you like the allergen menu to double-check?', user: 'Yes, please. Better safe than sorry.', keywords: ['safe'] },
    { id: 'restaurant-070', chapter: 'Dietary Needs', agent: 'Here you go. Take your time reading it.', user: 'Thanks. This is very helpful.', keywords: ['helpful'] },
    { id: 'restaurant-071', chapter: 'Dietary Needs', agent: 'All set? Can I confirm your order as is?', user: 'Yes, everything looks good.', keywords: ['good'] },
    { id: 'restaurant-072', chapter: 'Dietary Needs', agent: 'Wonderful. The kitchen has all the notes.', user: 'Great. Thanks for checking.', keywords: ['checking'] },
    // ---- Chapter 7: Asking the Waiter ----
    { id: 'restaurant-073', chapter: 'Asking the Waiter', agent: 'Is everything alright with your meal so far?', user: 'Yes, lovely. Could I ask something?', keywords: ['ask'] },
    { id: 'restaurant-074', chapter: 'Asking the Waiter', agent: 'Of course! What would you like to know?', user: 'What wine goes well with salmon?', keywords: ['wine'] },
    { id: 'restaurant-075', chapter: 'Asking the Waiter', agent: 'A crisp white — our Pinot Grigio is perfect.', user: 'Could we try a glass each?', keywords: ['glass'] },
    { id: 'restaurant-076', chapter: 'Asking the Waiter', agent: "Certainly. I'll bring those right over.", user: "Thank you. You're very helpful.", keywords: ['helpful'] },
    { id: 'restaurant-077', chapter: 'Asking the Waiter', agent: 'How is everything tasting so far tonight?', user: "Delicious. What's in this sauce?", keywords: ['sauce'] },
    { id: 'restaurant-078', chapter: 'Asking the Waiter', agent: "It's a lemon butter sauce with fresh herbs.", user: "It's fantastic. I'll have to try making it.", keywords: ['fantastic'] },
    { id: 'restaurant-079', chapter: 'Asking the Waiter', agent: 'Can I get you anything else at the moment?', user: 'Could we have some more bread, please?', keywords: ['bread'] },
    { id: 'restaurant-080', chapter: 'Asking the Waiter', agent: 'Right away. White or whole wheat?', user: 'White, please. The warm kind.', keywords: ['white'] },
    { id: 'restaurant-081', chapter: 'Asking the Waiter', agent: 'Just so you know, the kitchen closes at ten.', user: "Good to know. We're in no rush.", keywords: ['rush'] },
    { id: 'restaurant-082', chapter: 'Asking the Waiter', agent: 'Would you like a peek at the dessert menu?', user: 'Yes, please. We love dessert.', keywords: ['dessert'] },
    { id: 'restaurant-083', chapter: 'Asking the Waiter', agent: 'Here it is. The tiramisu is famous here.', user: "We'll decide after the mains.", keywords: ['decide'] },
    { id: 'restaurant-084', chapter: 'Asking the Waiter', agent: "Take your time. I'm here if you need me.", user: "Thanks. You've been wonderful.", keywords: ['wonderful'] },
    // ---- Chapter 8: Handling a Problem ----
    { id: 'restaurant-085', chapter: 'Handling a Problem', agent: 'How is everything? Enjoying your mains?', user: 'Mostly, but my salmon is quite dry.', keywords: ['dry'] },
    { id: 'restaurant-086', chapter: 'Handling a Problem', agent: "Oh no, I'm so sorry to hear that.", user: "It's okay. These things happen.", keywords: ['happen'] },
    { id: 'restaurant-087', chapter: 'Handling a Problem', agent: 'Would you like me to have it remade?', user: 'Could you have it remade, please?', keywords: ['remade'] },
    { id: 'restaurant-088', chapter: 'Handling a Problem', agent: 'Of course. Medium, and nice and moist this time.', user: 'Exactly. Thank you for understanding.', keywords: ['understanding'] },
    { id: 'restaurant-089', chapter: 'Handling a Problem', agent: "I'll take this back and rush a fresh one.", user: "No hurry. I'll wait.", keywords: ['hurry'] },
    { id: 'restaurant-090', chapter: 'Handling a Problem', agent: 'Can I bring you something while you wait?', user: 'Maybe a small side salad.', keywords: ['salad'] },
    { id: 'restaurant-091', chapter: 'Handling a Problem', agent: 'On the house, of course. My apologies again.', user: "That's very kind. Thank you.", keywords: ['kind'] },
    { id: 'restaurant-092', chapter: 'Handling a Problem', agent: "Here's your fresh salmon. I hope it's better.", user: 'Much better. Thank you, Marco.', keywords: ['better'] },
    { id: 'restaurant-093', chapter: 'Handling a Problem', agent: 'I\'m glad. Please let me know if anything else comes up.', user: 'Will do. Thanks again.', keywords: ['thanks'] },
    { id: 'restaurant-094', chapter: 'Handling a Problem', agent: 'Is there anything else I can fix for you?', user: "No, everything's perfect now.", keywords: ['perfect'] },
    { id: 'restaurant-095', chapter: 'Handling a Problem', agent: 'Wonderful. Enjoy the rest of your meal.', user: 'We will. Thanks for sorting it out.', keywords: ['sorting'] },
    { id: 'restaurant-096', chapter: 'Handling a Problem', agent: "It's my pleasure. That's what I'm here for.", user: 'You handled that really well.', keywords: ['handled'] },
    // ---- Chapter 9: Dessert & Coffee ----
    { id: 'restaurant-097', chapter: 'Dessert & Coffee', agent: 'Would you like to see the dessert menu now?', user: "Yes, please. What's the best dessert here?", keywords: ['dessert'] },
    { id: 'restaurant-098', chapter: 'Dessert & Coffee', agent: 'The tiramisu is our signature — very popular.', user: 'One tiramisu, please. To share.', keywords: ['tiramisu'] },
    { id: 'restaurant-099', chapter: 'Dessert & Coffee', agent: 'And for you, madam? Something sweet?', user: 'The chocolate cake sounds tempting.', keywords: ['chocolate'] },
    { id: 'restaurant-100', chapter: 'Dessert & Coffee', agent: 'Two desserts. Any coffee to go with those?', user: "I'd love a cappuccino.", keywords: ['cappuccino'] },
    { id: 'restaurant-101', chapter: 'Dessert & Coffee', agent: 'Would you like regular or decaf coffee?', user: "Decaf, please. It's quite late.", keywords: ['decaf'] },
    { id: 'restaurant-102', chapter: 'Dessert & Coffee', agent: 'And for you, sir? Anything to drink?', user: 'Just an espresso for me.', keywords: ['espresso'] },
    { id: 'restaurant-103', chapter: 'Dessert & Coffee', agent: 'Tiramisu, chocolate cake, cappuccino, espresso. Correct?', user: 'Spot on. Thank you.', keywords: ['spot'] },
    { id: 'restaurant-104', chapter: 'Dessert & Coffee', agent: "I'll bring those desserts right out for you.", user: "Lovely. We can't wait.", keywords: ['wait'] },
    { id: 'restaurant-105', chapter: 'Dessert & Coffee', agent: 'Here are your desserts. Please enjoy them!', user: 'They look incredible. Thank you!', keywords: ['incredible'] },
    { id: 'restaurant-106', chapter: 'Dessert & Coffee', agent: "How's the tiramisu? Worth the hype?", user: "Absolutely divine. Best I've had.", keywords: ['divine'] },
    { id: 'restaurant-107', chapter: 'Dessert & Coffee', agent: "I'll tell the pastry chef — she'll be thrilled.", user: "Please do. It's outstanding.", keywords: ['outstanding'] },
    { id: 'restaurant-108', chapter: 'Dessert & Coffee', agent: 'Can I get you anything else?', user: "No, we're completely satisfied.", keywords: ['satisfied'] },
    // ---- Chapter 10: The Bill ----
    { id: 'restaurant-109', chapter: 'The Bill', agent: 'Was everything to your liking this evening?', user: 'Everything was wonderful. Thank you.', keywords: ['wonderful'] },
    { id: 'restaurant-110', chapter: 'The Bill', agent: 'Can I get you the bill?', user: "Yes, please. The bill, when you're ready.", keywords: ['bill'] },
    { id: 'restaurant-111', chapter: 'The Bill', agent: 'Here you go. No rush at all.', user: 'Could we split the bill, please?', keywords: ['split'] },
    { id: 'restaurant-112', chapter: 'The Bill', agent: 'Of course. Shall we do half and half?', user: 'Yes, fifty-fifty is perfect.', keywords: ['fifty'] },
    { id: 'restaurant-113', chapter: 'The Bill', agent: 'How would you like to pay — together or separately?', user: 'Separately, please. Two cards.', keywords: ['separately'] },
    { id: 'restaurant-114', chapter: 'The Bill', agent: 'Card or cash for the first half?', user: 'Card, please. Here you go.', keywords: ['card'] },
    { id: 'restaurant-115', chapter: 'The Bill', agent: 'Would you like to add a tip?', user: 'Yes, please add a ten percent tip.', keywords: ['tip'] },
    { id: 'restaurant-116', chapter: 'The Bill', agent: 'Very generous of you. Thank you so much.', user: "You've earned it. Great service.", keywords: ['earned'] },
    { id: 'restaurant-117', chapter: 'The Bill', agent: "Here's your receipt. All paid up.", user: 'Perfect. Thanks for the receipt.', keywords: ['receipt'] },
    { id: 'restaurant-118', chapter: 'The Bill', agent: 'Would you like a copy emailed to you?', user: "No need. The paper one's fine.", keywords: ['paper'] },
    { id: 'restaurant-119', chapter: 'The Bill', agent: 'Thank you for dining with us tonight.', user: 'Thank you. We had a lovely evening.', keywords: ['evening'] },
    { id: 'restaurant-120', chapter: 'The Bill', agent: 'We hope to see you again soon!', user: "Definitely. We'll be back.", keywords: ['definitely'] },
    // ---- Chapter 11: Takeaway ----
    { id: 'restaurant-121', chapter: 'Takeaway', agent: 'Would you like a box for the leftover cake?', user: 'Yes, please. A box would be great.', keywords: ['box'] },
    { id: 'restaurant-122', chapter: 'Takeaway', agent: "I'll pack that up for you right away.", user: 'Thank you. We hate to waste it.', keywords: ['waste'] },
    { id: 'restaurant-123', chapter: 'Takeaway', agent: 'Would you like anything else to take home?', user: 'Could we get the bread to go?', keywords: ['bread'] },
    { id: 'restaurant-124', chapter: 'Takeaway', agent: "Of course. I'll wrap up some fresh bread.", user: 'Lovely. Thank you so much.', keywords: ['lovely'] },
    { id: 'restaurant-125', chapter: 'Takeaway', agent: 'Do you need a bag for all of this?', user: 'Yes, one bag is enough.', keywords: ['bag'] },
    { id: 'restaurant-126', chapter: 'Takeaway', agent: 'Here are your takeaway boxes, all packed.', user: "Perfect. Everything is packed up nicely.", keywords: ['packed'] },
    { id: 'restaurant-127', chapter: 'Takeaway', agent: 'The tiramisu keeps well until tomorrow, by the way.', user: "Good to know. It won't last that long!", keywords: ['long'] },
    { id: 'restaurant-128', chapter: 'Takeaway', agent: 'Ha! I completely believe you on that.', user: "It's just too delicious.", keywords: ['delicious'] },
    { id: 'restaurant-129', chapter: 'Takeaway', agent: 'Is there anything else before you head out?', user: "No, I think we're all set.", keywords: ['set'] },
    { id: 'restaurant-130', chapter: 'Takeaway', agent: 'Let me walk you to the door.', user: "That's kind, but no need.", keywords: ['need'] },
    { id: 'restaurant-131', chapter: 'Takeaway', agent: 'Your coats — here you are.', user: 'Thank you. Have a good night!', keywords: ['night'] },
    { id: 'restaurant-132', chapter: 'Takeaway', agent: 'Goodnight! Thanks for coming to Bella Roma.', user: "Goodnight! We'll definitely return.", keywords: ['return'] },
    // ---- Chapter 12: Complimenting the Meal ----
    { id: 'restaurant-133', chapter: 'Complimenting the Meal', agent: 'Before you go — how was everything tonight?', user: 'Honestly, one of our best meals out.', keywords: ['best'] },
    { id: 'restaurant-134', chapter: 'Complimenting the Meal', agent: 'That means so much. Thank you!', user: 'The salmon was cooked perfectly.', keywords: ['perfectly'] },
    { id: 'restaurant-135', chapter: 'Complimenting the Meal', agent: "I'll pass that on to the chef.", user: 'And the tiramisu was unforgettable.', keywords: ['unforgettable'] },
    { id: 'restaurant-136', chapter: 'Complimenting the Meal', agent: 'Our pastry chef will be over the moon.', user: 'Please tell her we said thanks.', keywords: ['thanks'] },
    { id: 'restaurant-137', chapter: 'Complimenting the Meal', agent: 'Would you mind leaving us a quick review online?', user: "Of course. We'll leave a review tonight.", keywords: ['review'] },
    { id: 'restaurant-138', chapter: 'Complimenting the Meal', agent: 'It really helps a small place like ours.', user: 'We understand. Five stars for sure.', keywords: ['stars'] },
    { id: 'restaurant-139', chapter: 'Complimenting the Meal', agent: "You're too kind. Thank you so much!", user: "It's well deserved. Trust me.", keywords: ['deserved'] },
    { id: 'restaurant-140', chapter: 'Complimenting the Meal', agent: 'Will you be celebrating with us again?', user: "We'll be back for sure.", keywords: ['back'] },
    { id: 'restaurant-141', chapter: 'Complimenting the Meal', agent: "Ask for me next time — I'm Marco.", user: 'We will, Marco. Thanks for everything.', keywords: ['marco'] },
    { id: 'restaurant-142', chapter: 'Complimenting the Meal', agent: 'The pleasure was all mine tonight.', user: 'What a lovely evening this was.', keywords: ['lovely'] },
    { id: 'restaurant-143', chapter: 'Complimenting the Meal', agent: 'Happy anniversary once more, you two!', user: 'Thank you. You made it special.', keywords: ['special'] },
    { id: 'restaurant-144', chapter: 'Complimenting the Meal', agent: 'Goodnight, and safe travels home tonight!', user: 'Goodnight! Thanks again, Marco.', keywords: ['again'] },
  ]
};
})();
