/* Speak or Boom — Open Mic (shadow reading) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.shadow_comic = {
    id: 'shadow_comic',
    title: 'Open Mic',
    tagline: 'Shadowing · 听一句，跟读同一句',
    speaker: 'JENNY',
    difficulty: 'Advanced',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: The Stage ----------
      { id: 1, chapter: "The Stage", speaker: 'JENNY',
        agent: "Hi everyone. I am Jenny. I have never done this before, clearly.",
        user: "Hi everyone. I am Jenny. I have never done this before, clearly.",
        keywords: ["jenny", "clearly"] },
      { id: 2, chapter: "The Stage", speaker: 'JENNY',
        agent: "My hands are shaking. This microphone has seen braver people.",
        user: "My hands are shaking. This microphone has seen braver people.",
        keywords: ["shaking", "microphone"] },
      { id: 3, chapter: "The Stage", speaker: 'JENNY',
        agent: "I told my mother. She said break a leg, then actually worried.",
        user: "I told my mother. She said break a leg, then actually worried.",
        keywords: ["mother", "worried"] },
      { id: 4, chapter: "The Stage", speaker: 'JENNY',
        agent: "The host said be yourself. I am working on that part.",
        user: "The host said be yourself. I am working on that part.",
        keywords: ["host", "yourself"] },
      { id: 5, chapter: "The Stage", speaker: 'JENNY',
        agent: "Five minutes. That is all I get. No pressure at all.",
        user: "Five minutes. That is all I get. No pressure at all.",
        keywords: ["minutes", "pressure"] },
      { id: 6, chapter: "The Stage", speaker: 'JENNY',
        agent: "If this goes badly, I will deny everything tomorrow morning.",
        user: "If this goes badly, I will deny everything tomorrow morning.",
        keywords: ["badly", "deny", "morning"] },
      { id: 7, chapter: "The Stage", speaker: 'JENNY',
        agent: "Deep breath. Smile. Pretend the spotlight is a hug.",
        user: "Deep breath. Smile. Pretend the spotlight is a hug.",
        keywords: ["spotlight", "hug"] },
      { id: 8, chapter: "The Stage", speaker: 'JENNY',
        agent: "Okay. Here we go. Please laugh, or at least blink kindly.",
        user: "Okay. Here we go. Please laugh, or at least blink kindly.",
        keywords: ["laugh", "kindly"] },
      // ---------- Chapter 2: The Opener ----------
      { id: 9, chapter: "The Opener", speaker: 'JENNY',
        agent: "My plants died. At this point I am just watering guilt.",
        user: "My plants died. At this point I am just watering guilt.",
        keywords: ["plants", "watering", "guilt"] },
      { id: 10, chapter: "The Opener", speaker: 'JENNY',
        agent: "I bought a gym membership. It is now a monthly donation.",
        user: "I bought a gym membership. It is now a monthly donation.",
        keywords: ["membership", "donation"] },
      { id: 11, chapter: "The Opener", speaker: 'JENNY',
        agent: "My sleep schedule is just a rumor I heard about once.",
        user: "My sleep schedule is just a rumor I heard about once.",
        keywords: ["schedule", "rumor"] },
      { id: 12, chapter: "The Opener", speaker: 'JENNY',
        agent: "I meal-prepped on Sunday. By Tuesday I ordered pizza anyway.",
        user: "I meal-prepped on Sunday. By Tuesday I ordered pizza anyway.",
        keywords: ["sunday", "tuesday", "pizza"] },
      { id: 13, chapter: "The Opener", speaker: 'JENNY',
        agent: "My phone screen time report should come with a trigger warning.",
        user: "My phone screen time report should come with a trigger warning.",
        keywords: ["screen", "warning"] },
      { id: 14, chapter: "The Opener", speaker: 'JENNY',
        agent: "I tried meditation. My thoughts filed a noise complaint.",
        user: "I tried meditation. My thoughts filed a noise complaint.",
        keywords: ["meditation", "complaint"] },
      { id: 15, chapter: "The Opener", speaker: 'JENNY',
        agent: "Adulting is hard. I want a refund on these responsibilities.",
        user: "Adulting is hard. I want a refund on these responsibilities.",
        keywords: ["refund", "responsibilities"] },
      { id: 16, chapter: "The Opener", speaker: 'JENNY',
        agent: "My houseplants and I have the same survival strategy: barely.",
        user: "My houseplants and I have the same survival strategy: barely.",
        keywords: ["houseplants", "barely"] },
      // ---------- Chapter 3: Dating Life ----------
      { id: 17, chapter: "Dating Life", speaker: 'JENNY',
        agent: "Dating apps are just job interviews with worse lighting.",
        user: "Dating apps are just job interviews with worse lighting.",
        keywords: ["dating", "lighting"] },
      { id: 18, chapter: "Dating Life", speaker: 'JENNY',
        agent: "He said he was six feet tall. The elevator disagreed.",
        user: "He said he was six feet tall. The elevator disagreed.",
        keywords: ["tall", "elevator"] },
      { id: 19, chapter: "Dating Life", speaker: 'JENNY',
        agent: "My love life has more red flags than a parade.",
        user: "My love life has more red flags than a parade.",
        keywords: ["flags", "parade"] },
      { id: 20, chapter: "Dating Life", speaker: 'JENNY',
        agent: "He ghosted me. I am haunting his Instagram instead.",
        user: "He ghosted me. I am haunting his Instagram instead.",
        keywords: ["ghosted", "instagram"] },
      { id: 21, chapter: "Dating Life", speaker: 'JENNY',
        agent: "First dates are auditions. I keep forgetting my lines.",
        user: "First dates are auditions. I keep forgetting my lines.",
        keywords: ["auditions", "lines"] },
      { id: 22, chapter: "Dating Life", speaker: 'JENNY',
        agent: "My type is emotionally unavailable with good hair, apparently.",
        user: "My type is emotionally unavailable with good hair, apparently.",
        keywords: ["unavailable", "apparently"] },
      { id: 23, chapter: "Dating Life", speaker: 'JENNY',
        agent: "He said let's split the bill. I split, and left.",
        user: "He said let's split the bill. I split, and left.",
        keywords: ["split", "bill"] },
      { id: 24, chapter: "Dating Life", speaker: 'JENNY',
        agent: "Romance is dead. I checked. It left no forwarding address.",
        user: "Romance is dead. I checked. It left no forwarding address.",
        keywords: ["romance", "forwarding"] },
      // ---------- Chapter 4: My Parents ----------
      { id: 25, chapter: "My Parents", speaker: 'JENNY',
        agent: "My mother calls. I answer. That is the whole joke.",
        user: "My mother calls. I answer. That is the whole joke.",
        keywords: ["mother", "joke"] },
      { id: 26, chapter: "My Parents", speaker: 'JENNY',
        agent: "My dad texts in all caps. Everything feels urgent now.",
        user: "My dad texts in all caps. Everything feels urgent now.",
        keywords: ["caps", "urgent"] },
      { id: 27, chapter: "My Parents", speaker: 'JENNY',
        agent: "Mom saw my standup flyer. She asked if it pays rent.",
        user: "Mom saw my standup flyer. She asked if it pays rent.",
        keywords: ["flyer", "rent"] },
      { id: 28, chapter: "My Parents", speaker: 'JENNY',
        agent: "My parents wanted a doctor. They got a disappointment with jokes.",
        user: "My parents wanted a doctor. They got a disappointment with jokes.",
        keywords: ["doctor", "disappointment"] },
      { id: 29, chapter: "My Parents", speaker: 'JENNY',
        agent: "Dad's advice: marry rich. Mom's advice: also marry rich.",
        user: "Dad's advice: marry rich. Mom's advice: also marry rich.",
        keywords: ["marry", "rich"] },
      { id: 30, chapter: "My Parents", speaker: 'JENNY',
        agent: "My mother forwards chain messages. I forward her to voicemail.",
        user: "My mother forwards chain messages. I forward her to voicemail.",
        keywords: ["forwards", "voicemail"] },
      { id: 31, chapter: "My Parents", speaker: 'JENNY',
        agent: "Family dinners are just group therapy with better food.",
        user: "Family dinners are just group therapy with better food.",
        keywords: ["therapy", "food"] },
      { id: 32, chapter: "My Parents", speaker: 'JENNY',
        agent: "My parents' love language is comparing me to cousins.",
        user: "My parents' love language is comparing me to cousins.",
        keywords: ["comparing", "cousins"] },
      // ---------- Chapter 5: The Day Job ----------
      { id: 33, chapter: "The Day Job", speaker: 'JENNY',
        agent: "By day I file spreadsheets. By night I file complaints, comedically.",
        user: "By day I file spreadsheets. By night I file complaints, comedically.",
        keywords: ["spreadsheets", "comedically"] },
      { id: 34, chapter: "The Day Job", speaker: 'JENNY',
        agent: "My boss says think outside the box. The box has Wi-Fi.",
        user: "My boss says think outside the box. The box has Wi-Fi.",
        keywords: ["boss", "outside"] },
      { id: 35, chapter: "The Day Job", speaker: 'JENNY',
        agent: "Meetings could have been emails. Emails could have been silence.",
        user: "Meetings could have been emails. Emails could have been silence.",
        keywords: ["meetings", "silence"] },
      { id: 36, chapter: "The Day Job", speaker: 'JENNY',
        agent: "My coworker microwaves fish. That is my villain origin story.",
        user: "My coworker microwaves fish. That is my villain origin story.",
        keywords: ["microwaves", "villain"] },
      { id: 37, chapter: "The Day Job", speaker: 'JENNY',
        agent: "I asked for a raise. My boss laughed harder than you did.",
        user: "I asked for a raise. My boss laughed harder than you did.",
        keywords: ["raise", "laughed"] },
      { id: 38, chapter: "The Day Job", speaker: 'JENNY',
        agent: "The printer jams when it senses my deadlines approaching.",
        user: "The printer jams when it senses my deadlines approaching.",
        keywords: ["printer", "deadlines"] },
      { id: 39, chapter: "The Day Job", speaker: 'JENNY',
        agent: "Working from home means pajamas with a blazer on top.",
        user: "Working from home means pajamas with a blazer on top.",
        keywords: ["pajamas", "blazer"] },
      { id: 40, chapter: "The Day Job", speaker: 'JENNY',
        agent: "My job title is long. My paycheck is disappointingly short.",
        user: "My job title is long. My paycheck is disappointingly short.",
        keywords: ["title", "paycheck"] },
      // ---------- Chapter 6: The Bomb ----------
      { id: 41, chapter: "The Bomb", speaker: 'JENNY',
        agent: "That joke landed like my last relationship: nowhere good.",
        user: "That joke landed like my last relationship: nowhere good.",
        keywords: ["landed", "relationship"] },
      { id: 42, chapter: "The Bomb", speaker: 'JENNY',
        agent: "Tough crowd. I have seen warmer funerals, honestly.",
        user: "Tough crowd. I have seen warmer funerals, honestly.",
        keywords: ["crowd", "funerals"] },
      { id: 43, chapter: "The Bomb", speaker: 'JENNY',
        agent: "I will just wait here while that silence finishes.",
        user: "I will just wait here while that silence finishes.",
        keywords: ["silence", "finishes"] },
      { id: 44, chapter: "The Bomb", speaker: 'JENNY',
        agent: "My confidence just filed for unemployment, by the way.",
        user: "My confidence just filed for unemployment, by the way.",
        keywords: ["confidence", "unemployment"] },
      { id: 45, chapter: "The Bomb", speaker: 'JENNY',
        agent: "Note to self: that bit needs a funeral, not a rewrite.",
        user: "Note to self: that bit needs a funeral, not a rewrite.",
        keywords: ["funeral", "rewrite"] },
      { id: 46, chapter: "The Bomb", speaker: 'JENNY',
        agent: "You guys are great. This microphone disagrees with me.",
        user: "You guys are great. This microphone disagrees with me.",
        keywords: ["microphone", "disagrees"] },
      { id: 47, chapter: "The Bomb", speaker: 'JENNY',
        agent: "I can hear my own heartbeat. It is heckling me too.",
        user: "I can hear my own heartbeat. It is heckling me too.",
        keywords: ["heartbeat", "heckling"] },
      { id: 48, chapter: "The Bomb", speaker: 'JENNY',
        agent: "Okay, new plan. We pretend the last minute never happened.",
        user: "Okay, new plan. We pretend the last minute never happened.",
        keywords: ["pretend", "happened"] },
      // ---------- Chapter 7: The Recovery ----------
      { id: 49, chapter: "The Recovery", speaker: 'JENNY',
        agent: "Plot twist: the bombing was part of the act. Probably.",
        user: "Plot twist: the bombing was part of the act. Probably.",
        keywords: ["twist", "probably"] },
      { id: 50, chapter: "The Recovery", speaker: 'JENNY',
        agent: "I am like a phone at one percent: still going, barely.",
        user: "I am like a phone at one percent: still going, barely.",
        keywords: ["percent", "barely"] },
      { id: 51, chapter: "The Recovery", speaker: 'JENNY',
        agent: "Comedy is tragedy plus timing. I am heavy on tragedy.",
        user: "Comedy is tragedy plus timing. I am heavy on tragedy.",
        keywords: ["tragedy", "timing"] },
      { id: 52, chapter: "The Recovery", speaker: 'JENNY',
        agent: "Let's reset. Everybody laugh now, on the count of three.",
        user: "Let's reset. Everybody laugh now, on the count of three.",
        keywords: ["reset", "three"] },
      { id: 53, chapter: "The Recovery", speaker: 'JENNY',
        agent: "My therapist says embrace failure. So here we are, embracing.",
        user: "My therapist says embrace failure. So here we are, embracing.",
        keywords: ["therapist", "embracing"] },
      { id: 54, chapter: "The Recovery", speaker: 'JENNY',
        agent: "I survived that silence. I can survive anything tonight.",
        user: "I survived that silence. I can survive anything tonight.",
        keywords: ["survived", "tonight"] },
      { id: 55, chapter: "The Recovery", speaker: 'JENNY',
        agent: "New material incoming, folks. Lower your expectations, please.",
        user: "New material incoming, folks. Lower your expectations, please.",
        keywords: ["material", "expectations"] },
      { id: 56, chapter: "The Recovery", speaker: 'JENNY',
        agent: "We are in this together now. There is no escape, folks.",
        user: "We are in this together now. There is no escape, folks.",
        keywords: ["together", "escape"] },
      // ---------- Chapter 8: The Closer ----------
      { id: 57, chapter: "The Closer", speaker: 'JENNY',
        agent: "My grandmother gives better life advice than any podcast ever.",
        user: "My grandmother gives better life advice than any podcast ever.",
        keywords: ["grandmother", "podcast"] },
      { id: 58, chapter: "The Closer", speaker: 'JENNY',
        agent: "She said marry someone who laughs at your jokes. Still single.",
        user: "She said marry someone who laughs at your jokes. Still single.",
        keywords: ["marry", "single"] },
      { id: 59, chapter: "The Closer", speaker: 'JENNY',
        agent: "Wisdom comes with age. So does complaining about the weather.",
        user: "Wisdom comes with age. So does complaining about the weather.",
        keywords: ["wisdom", "weather"] },
      { id: 60, chapter: "The Closer", speaker: 'JENNY',
        agent: "Grandma's secret: dessert first, regrets never, naps always.",
        user: "Grandma's secret: dessert first, regrets never, naps always.",
        keywords: ["dessert", "regrets", "naps"] },
      { id: 61, chapter: "The Closer", speaker: 'JENNY',
        agent: "She lived through everything and still tips generously. Legend.",
        user: "She lived through everything and still tips generously. Legend.",
        keywords: ["generously", "legend"] },
      { id: 62, chapter: "The Closer", speaker: 'JENNY',
        agent: "My grandma arm-wrestled my uncle once. She won, obviously.",
        user: "My grandma arm-wrestled my uncle once. She won, obviously.",
        keywords: ["uncle", "obviously"] },
      { id: 63, chapter: "The Closer", speaker: 'JENNY',
        agent: "Ninety years old and funnier than everyone in this room.",
        user: "Ninety years old and funnier than everyone in this room.",
        keywords: ["ninety", "funnier"] },
      { id: 64, chapter: "The Closer", speaker: 'JENNY',
        agent: "If she were here, she would steal this whole show.",
        user: "If she were here, she would steal this whole show.",
        keywords: ["steal", "show"] },
      // ---------- Chapter 9: The Laugh ----------
      { id: 65, chapter: "The Laugh", speaker: 'JENNY',
        agent: "There it is! I knew you were awake back there.",
        user: "There it is! I knew you were awake back there.",
        keywords: ["awake"] },
      { id: 66, chapter: "The Laugh", speaker: 'JENNY',
        agent: "That laugh was worth every awkward second before it.",
        user: "That laugh was worth every awkward second before it.",
        keywords: ["worth", "awkward"] },
      { id: 67, chapter: "The Laugh", speaker: 'JENNY',
        agent: "See? We made it. Comedy is just survived embarrassment.",
        user: "See? We made it. Comedy is just survived embarrassment.",
        keywords: ["survived", "embarrassment"] },
      { id: 68, chapter: "The Laugh", speaker: 'JENNY',
        agent: "Your laughter is louder than my mother's disappointment. Finally.",
        user: "Your laughter is louder than my mother's disappointment. Finally.",
        keywords: ["louder", "disappointment"] },
      { id: 69, chapter: "The Laugh", speaker: 'JENNY',
        agent: "I am keeping this moment. Framing it. Living in it.",
        user: "I am keeping this moment. Framing it. Living in it.",
        keywords: ["keeping", "framing"] },
      { id: 70, chapter: "The Laugh", speaker: 'JENNY',
        agent: "Best sound in the world: strangers laughing at your pain.",
        user: "Best sound in the world: strangers laughing at your pain.",
        keywords: ["strangers", "pain"] },
      { id: 71, chapter: "The Laugh", speaker: 'JENNY',
        agent: "We did it, folks. From bombing to blooming in minutes.",
        user: "We did it, folks. From bombing to blooming in minutes.",
        keywords: ["bombing", "blooming"] },
      { id: 72, chapter: "The Laugh", speaker: 'JENNY',
        agent: "This is the part where I pretend I planned all of it.",
        user: "This is the part where I pretend I planned all of it.",
        keywords: ["pretend", "planned"] },
      // ---------- Chapter 10: Encore ----------
      { id: 73, chapter: "Encore", speaker: 'JENNY',
        agent: "You want more? My mother wants me to stop. Let's continue.",
        user: "You want more? My mother wants me to stop. Let's continue.",
        keywords: ["mother", "continue"] },
      { id: 74, chapter: "Encore", speaker: 'JENNY',
        agent: "Encore! I have peaked. It is all downhill, enjoy it.",
        user: "Encore! I have peaked. It is all downhill, enjoy it.",
        keywords: ["peaked", "downhill"] },
      { id: 75, chapter: "Encore", speaker: 'JENNY',
        agent: "One more story, then I return to spreadsheets forever.",
        user: "One more story, then I return to spreadsheets forever.",
        keywords: ["spreadsheets", "forever"] },
      { id: 76, chapter: "Encore", speaker: 'JENNY',
        agent: "Thank you for laughing. My ego needed this desperately.",
        user: "Thank you for laughing. My ego needed this desperately.",
        keywords: ["laughing", "desperately"] },
      { id: 77, chapter: "Encore", speaker: 'JENNY',
        agent: "Remember me when I am famous. Or at least employed.",
        user: "Remember me when I am famous. Or at least employed.",
        keywords: ["famous", "employed"] },
      { id: 78, chapter: "Encore", speaker: 'JENNY',
        agent: "Goodnight, everyone. Tip your servers, forgive your comedians.",
        user: "Goodnight, everyone. Tip your servers, forgive your comedians.",
        keywords: ["servers", "comedians"] },
      { id: 79, chapter: "Encore", speaker: 'JENNY',
        agent: "Jenny Park was here. The mic is still warm, probably.",
        user: "Jenny Park was here. The mic is still warm, probably.",
        keywords: ["warm", "probably"] },
      { id: 80, chapter: "Encore", speaker: 'JENNY',
        agent: "Dream big. Bomb bigger. Laugh loudest. Goodnight, folks.",
        user: "Dream big. Bomb bigger. Laugh loudest. Goodnight, folks.",
        keywords: ["dream", "goodnight"] }
    ]
  };
})();
