/* Speak or Boom — The Verdict (shadow reading) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.shadow_court = {
    id: 'shadow_court',
    title: 'The Verdict',
    tagline: 'Shadowing · 听一句，跟读同一句',
    speaker: 'COLE',
    difficulty: 'Advanced',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: The Courtroom ----------
      { id: 1, chapter: "The Courtroom", speaker: 'COLE',
        agent: "Ladies and gentlemen, the truth does not need a disguise.",
        user: "Ladies and gentlemen, the truth does not need a disguise.",
        keywords: ["truth", "disguise"] },
      { id: 2, chapter: "The Courtroom", speaker: 'COLE',
        agent: "You hold a man's future in your careful hands today.",
        user: "You hold a man's future in your careful hands today.",
        keywords: ["future", "careful"] },
      { id: 3, chapter: "The Courtroom", speaker: 'COLE',
        agent: "The prosecution has told you a story. Stories are not evidence.",
        user: "The prosecution has told you a story. Stories are not evidence.",
        keywords: ["prosecution", "evidence"] },
      { id: 4, chapter: "The Courtroom", speaker: 'COLE',
        agent: "Listen with your conscience, not with your fear, today.",
        user: "Listen with your conscience, not with your fear, today.",
        keywords: ["conscience", "fear"] },
      { id: 5, chapter: "The Courtroom", speaker: 'COLE',
        agent: "I ask only one thing: judge the facts, nothing else.",
        user: "I ask only one thing: judge the facts, nothing else.",
        keywords: ["facts"] },
      { id: 6, chapter: "The Courtroom", speaker: 'COLE',
        agent: "An innocent man sits behind me. Remember his face.",
        user: "An innocent man sits behind me. Remember his face.",
        keywords: ["innocent", "face"] },
      { id: 7, chapter: "The Courtroom", speaker: 'COLE',
        agent: "This trial is about evidence, not about headlines or rumors.",
        user: "This trial is about evidence, not about headlines or rumors.",
        keywords: ["headlines", "rumors"] },
      { id: 8, chapter: "The Courtroom", speaker: 'COLE',
        agent: "Let us walk through the facts together, step by step.",
        user: "Let us walk through the facts together, step by step.",
        keywords: ["facts", "together"] },
      // ---------- Chapter 2: The Accused ----------
      { id: 9, chapter: "The Accused", speaker: 'COLE',
        agent: "Thomas Hale drove a forklift for eleven faithful years.",
        user: "Thomas Hale drove a forklift for eleven faithful years.",
        keywords: ["forklift", "faithful"] },
      { id: 10, chapter: "The Accused", speaker: 'COLE',
        agent: "He coached his daughter's soccer team every single Saturday.",
        user: "He coached his daughter's soccer team every single Saturday.",
        keywords: ["coached", "saturday"] },
      { id: 11, chapter: "The Accused", speaker: 'COLE',
        agent: "Neighbors describe him as the man who always helps.",
        user: "Neighbors describe him as the man who always helps.",
        keywords: ["neighbors", "helps"] },
      { id: 12, chapter: "The Accused", speaker: 'COLE',
        agent: "He has no record, no debts, and no enemies anywhere.",
        user: "He has no record, no debts, and no enemies anywhere.",
        keywords: ["record", "enemies"] },
      { id: 13, chapter: "The Accused", speaker: 'COLE',
        agent: "Look at him. Really look. Is this the face of guilt?",
        user: "Look at him. Really look. Is this the face of guilt?",
        keywords: ["guilt", "face"] },
      { id: 14, chapter: "The Accused", speaker: 'COLE',
        agent: "He wept when they read the charges. Guilty men rarely weep.",
        user: "He wept when they read the charges. Guilty men rarely weep.",
        keywords: ["wept", "charges"] },
      { id: 15, chapter: "The Accused", speaker: 'COLE',
        agent: "His hands built shelves, not fires. Remember those hands.",
        user: "His hands built shelves, not fires. Remember those hands.",
        keywords: ["shelves", "fires"] },
      { id: 16, chapter: "The Accused", speaker: 'COLE',
        agent: "Eleven years of night shifts. That was his whole life.",
        user: "Eleven years of night shifts. That was his whole life.",
        keywords: ["shifts"] },
      // ---------- Chapter 3: The Evidence ----------
      { id: 17, chapter: "The Evidence", speaker: 'COLE',
        agent: "The prosecution's case rests on smoke, not on fire.",
        user: "The prosecution's case rests on smoke, not on fire.",
        keywords: ["smoke", "fire"] },
      { id: 18, chapter: "The Evidence", speaker: 'COLE',
        agent: "They found no fingerprints. Not one. Ask yourselves why.",
        user: "They found no fingerprints. Not one. Ask yourselves why.",
        keywords: ["fingerprints"] },
      { id: 19, chapter: "The Evidence", speaker: 'COLE',
        agent: "The gasoline can was never linked to my client.",
        user: "The gasoline can was never linked to my client.",
        keywords: ["gasoline", "client"] },
      { id: 20, chapter: "The Evidence", speaker: 'COLE',
        agent: "A footprint in mud proves nothing but muddy shoes.",
        user: "A footprint in mud proves nothing but muddy shoes.",
        keywords: ["footprint", "muddy"] },
      { id: 21, chapter: "The Evidence", speaker: 'COLE',
        agent: "Evidence should speak clearly. Theirs only whispers and guesses.",
        user: "Evidence should speak clearly. Theirs only whispers and guesses.",
        keywords: ["whispers", "guesses"] },
      { id: 22, chapter: "The Evidence", speaker: 'COLE',
        agent: "They tested the ashes twice. Both tests proved nothing.",
        user: "They tested the ashes twice. Both tests proved nothing.",
        keywords: ["ashes", "twice"] },
      { id: 23, chapter: "The Evidence", speaker: 'COLE',
        agent: "Where is the proof? I have waited three weeks to see it.",
        user: "Where is the proof? I have waited three weeks to see it.",
        keywords: ["proof", "waited"] },
      { id: 24, chapter: "The Evidence", speaker: 'COLE',
        agent: "Suspicion is cheap. Proof is expensive. They bought neither.",
        user: "Suspicion is cheap. Proof is expensive. They bought neither.",
        keywords: ["suspicion", "expensive"] },
      // ---------- Chapter 4: The Witness ----------
      { id: 25, chapter: "The Witness", speaker: 'COLE',
        agent: "Mr. Dalton swore he saw my client at midnight.",
        user: "Mr. Dalton swore he saw my client at midnight.",
        keywords: ["dalton", "midnight"] },
      { id: 26, chapter: "The Witness", speaker: 'COLE',
        agent: "Then he admitted the street was dark and rainy.",
        user: "Then he admitted the street was dark and rainy.",
        keywords: ["admitted", "rainy"] },
      { id: 27, chapter: "The Witness", speaker: 'COLE',
        agent: "First it was midnight. Then it was maybe eleven.",
        user: "First it was midnight. Then it was maybe eleven.",
        keywords: ["midnight", "eleven"] },
      { id: 28, chapter: "The Witness", speaker: 'COLE',
        agent: "A witness who cannot remember cannot be trusted, friends.",
        user: "A witness who cannot remember cannot be trusted, friends.",
        keywords: ["witness", "trusted"] },
      { id: 29, chapter: "The Witness", speaker: 'COLE',
        agent: "He changed his story three times under simple questions.",
        user: "He changed his story three times under simple questions.",
        keywords: ["changed", "story"] },
      { id: 30, chapter: "The Witness", speaker: 'COLE',
        agent: "Memory is fragile. His memory shattered on that stand.",
        user: "Memory is fragile. His memory shattered on that stand.",
        keywords: ["fragile", "shattered"] },
      { id: 31, chapter: "The Witness", speaker: 'COLE',
        agent: "Would you convict a man on such shifting sand?",
        user: "Would you convict a man on such shifting sand?",
        keywords: ["convict", "shifting"] },
      { id: 32, chapter: "The Witness", speaker: 'COLE',
        agent: "The truth does not change its clothes every hour.",
        user: "The truth does not change its clothes every hour.",
        keywords: ["truth", "clothes"] },
      // ---------- Chapter 5: The Motive ----------
      { id: 33, chapter: "The Motive", speaker: 'COLE',
        agent: "They claim he wanted revenge for a lost promotion.",
        user: "They claim he wanted revenge for a lost promotion.",
        keywords: ["revenge", "promotion"] },
      { id: 34, chapter: "The Motive", speaker: 'COLE',
        agent: "His supervisor called him the most loyal worker there.",
        user: "His supervisor called him the most loyal worker there.",
        keywords: ["supervisor", "loyal"] },
      { id: 35, chapter: "The Motive", speaker: 'COLE',
        agent: "Loyal men do not burn the places they love.",
        user: "Loyal men do not burn the places they love.",
        keywords: ["loyal", "burn"] },
      { id: 36, chapter: "The Motive", speaker: 'COLE',
        agent: "They found no debts, no threats, no angry letters.",
        user: "They found no debts, no threats, no angry letters.",
        keywords: ["debts", "threats"] },
      { id: 37, chapter: "The Motive", speaker: 'COLE',
        agent: "A motive must make sense. Theirs makes none at all.",
        user: "A motive must make sense. Theirs makes none at all.",
        keywords: ["motive", "sense"] },
      { id: 38, chapter: "The Motive", speaker: 'COLE',
        agent: "He was saving for his son's college, not for revenge.",
        user: "He was saving for his son's college, not for revenge.",
        keywords: ["saving", "revenge"] },
      { id: 39, chapter: "The Motive", speaker: 'COLE',
        agent: "Ask yourselves: what would he possibly gain from ashes?",
        user: "Ask yourselves: what would he possibly gain from ashes?",
        keywords: ["gain", "ashes"] },
      { id: 40, chapter: "The Motive", speaker: 'COLE',
        agent: "Without a motive, their story collapses like wet paper.",
        user: "Without a motive, their story collapses like wet paper.",
        keywords: ["collapses", "paper"] },
      // ---------- Chapter 6: The Timeline ----------
      { id: 41, chapter: "The Timeline", speaker: 'COLE',
        agent: "The fire started at ten. He clocked out at nine.",
        user: "The fire started at ten. He clocked out at nine.",
        keywords: ["clocked"] },
      { id: 42, chapter: "The Timeline", speaker: 'COLE',
        agent: "The bus camera shows him riding home at nine fifteen.",
        user: "The bus camera shows him riding home at nine fifteen.",
        keywords: ["camera", "riding"] },
      { id: 43, chapter: "The Timeline", speaker: 'COLE',
        agent: "You cannot be in two places at one time.",
        user: "You cannot be in two places at one time.",
        keywords: ["places"] },
      { id: 44, chapter: "The Timeline", speaker: 'COLE',
        agent: "The prosecution skipped that hour. I will not skip it.",
        user: "The prosecution skipped that hour. I will not skip it.",
        keywords: ["skipped", "hour"] },
      { id: 45, chapter: "The Timeline", speaker: 'COLE',
        agent: "Timelines are stubborn things. This one stubbornly clears him.",
        user: "Timelines are stubborn things. This one stubbornly clears him.",
        keywords: ["stubborn", "clears"] },
      { id: 46, chapter: "The Timeline", speaker: 'COLE',
        agent: "His wife made dinner at nine thirty. He was there.",
        user: "His wife made dinner at nine thirty. He was there.",
        keywords: ["dinner", "thirty"] },
      { id: 47, chapter: "The Timeline", speaker: 'COLE',
        agent: "Three witnesses confirm it. The prosecution called zero.",
        user: "Three witnesses confirm it. The prosecution called zero.",
        keywords: ["witnesses", "confirm"] },
      { id: 48, chapter: "The Timeline", speaker: 'COLE',
        agent: "An hour of his life, and they simply erased it.",
        user: "An hour of his life, and they simply erased it.",
        keywords: ["erased"] },
      // ---------- Chapter 7: Reasonable Doubt ----------
      { id: 49, chapter: "Reasonable Doubt", speaker: 'COLE',
        agent: "Doubt is not weakness. Doubt is your duty here.",
        user: "Doubt is not weakness. Doubt is your duty here.",
        keywords: ["doubt", "duty"] },
      { id: 50, chapter: "Reasonable Doubt", speaker: 'COLE',
        agent: "The law demands proof, not feelings, not hunches, not guesses.",
        user: "The law demands proof, not feelings, not hunches, not guesses.",
        keywords: ["demands", "proof"] },
      { id: 51, chapter: "Reasonable Doubt", speaker: 'COLE',
        agent: "If you hesitate, that hesitation is reasonable doubt itself.",
        user: "If you hesitate, that hesitation is reasonable doubt itself.",
        keywords: ["hesitate", "hesitation"] },
      { id: 52, chapter: "Reasonable Doubt", speaker: 'COLE',
        agent: "Beyond a reasonable doubt means beyond your honest doubt.",
        user: "Beyond a reasonable doubt means beyond your honest doubt.",
        keywords: ["reasonable", "honest"] },
      { id: 53, chapter: "Reasonable Doubt", speaker: 'COLE',
        agent: "They must prove guilt. He need not prove innocence.",
        user: "They must prove guilt. He need not prove innocence.",
        keywords: ["guilt", "innocence"] },
      { id: 54, chapter: "Reasonable Doubt", speaker: 'COLE',
        agent: "One unanswered question is enough to set him free.",
        user: "One unanswered question is enough to set him free.",
        keywords: ["unanswered", "free"] },
      { id: 55, chapter: "Reasonable Doubt", speaker: 'COLE',
        agent: "Justice is not speed. Justice is certainty, carefully earned.",
        user: "Justice is not speed. Justice is certainty, carefully earned.",
        keywords: ["certainty", "earned"] },
      { id: 56, chapter: "Reasonable Doubt", speaker: 'COLE',
        agent: "Hold the prosecution to the standard the law requires.",
        user: "Hold the prosecution to the standard the law requires.",
        keywords: ["standard", "requires"] },
      // ---------- Chapter 8: The Human Cost ----------
      { id: 57, chapter: "The Human Cost", speaker: 'COLE',
        agent: "Behind this case stands a family holding its breath.",
        user: "Behind this case stands a family holding its breath.",
        keywords: ["family", "breath"] },
      { id: 58, chapter: "The Human Cost", speaker: 'COLE',
        agent: "His daughter asks every night when Daddy comes home.",
        user: "His daughter asks every night when Daddy comes home.",
        keywords: ["daughter", "daddy"] },
      { id: 59, chapter: "The Human Cost", speaker: 'COLE',
        agent: "His son stopped playing soccer. He waits by the window.",
        user: "His son stopped playing soccer. He waits by the window.",
        keywords: ["soccer", "window"] },
      { id: 60, chapter: "The Human Cost", speaker: 'COLE',
        agent: "A wrong verdict does not end when the gavel falls.",
        user: "A wrong verdict does not end when the gavel falls.",
        keywords: ["verdict", "gavel"] },
      { id: 61, chapter: "The Human Cost", speaker: 'COLE',
        agent: "It follows a family for generations, like a shadow.",
        user: "It follows a family for generations, like a shadow.",
        keywords: ["generations", "shadow"] },
      { id: 62, chapter: "The Human Cost", speaker: 'COLE',
        agent: "You are not judging a file. You are judging lives.",
        user: "You are not judging a file. You are judging lives.",
        keywords: ["judging", "lives"] },
      { id: 63, chapter: "The Human Cost", speaker: 'COLE',
        agent: "Mercy and justice are not enemies. They are partners.",
        user: "Mercy and justice are not enemies. They are partners.",
        keywords: ["mercy", "partners"] },
      { id: 64, chapter: "The Human Cost", speaker: 'COLE',
        agent: "Send him home tonight. Let the children stop waiting.",
        user: "Send him home tonight. Let the children stop waiting.",
        keywords: ["children", "waiting"] },
      // ---------- Chapter 9: The Ask ----------
      { id: 65, chapter: "The Ask", speaker: 'COLE',
        agent: "I ask you for the bravest verdict: not guilty.",
        user: "I ask you for the bravest verdict: not guilty.",
        keywords: ["bravest", "verdict"] },
      { id: 66, chapter: "The Ask", speaker: 'COLE',
        agent: "Courage in this room means following the evidence home.",
        user: "Courage in this room means following the evidence home.",
        keywords: ["courage", "evidence"] },
      { id: 67, chapter: "The Ask", speaker: 'COLE',
        agent: "Do not send an innocent man to pay for shadows.",
        user: "Do not send an innocent man to pay for shadows.",
        keywords: ["innocent", "shadows"] },
      { id: 68, chapter: "The Ask", speaker: 'COLE',
        agent: "The easy verdict is guilty. The right one takes courage.",
        user: "The easy verdict is guilty. The right one takes courage.",
        keywords: ["courage"] },
      { id: 69, chapter: "The Ask", speaker: 'COLE',
        agent: "History remembers juries that chose truth over fear.",
        user: "History remembers juries that chose truth over fear.",
        keywords: ["juries", "fear"] },
      { id: 70, chapter: "The Ask", speaker: 'COLE',
        agent: "Give Thomas Hale back his name, his work, his life.",
        user: "Give Thomas Hale back his name, his work, his life.",
        keywords: ["thomas", "hale"] },
      { id: 71, chapter: "The Ask", speaker: 'COLE',
        agent: "Let the record show that justice was done today.",
        user: "Let the record show that justice was done today.",
        keywords: ["record", "justice"] },
      { id: 72, chapter: "The Ask", speaker: 'COLE',
        agent: "When you vote, vote with a clear and steady heart.",
        user: "When you vote, vote with a clear and steady heart.",
        keywords: ["steady", "heart"] },
      // ---------- Chapter 10: The Verdict ----------
      { id: 73, chapter: "The Verdict", speaker: 'COLE',
        agent: "Soon you will retire to decide a man's fate.",
        user: "Soon you will retire to decide a man's fate.",
        keywords: ["retire", "fate"] },
      { id: 74, chapter: "The Verdict", speaker: 'COLE',
        agent: "Take your time. Truth is patient with the careful.",
        user: "Take your time. Truth is patient with the careful.",
        keywords: ["patient", "careful"] },
      { id: 75, chapter: "The Verdict", speaker: 'COLE',
        agent: "Remember the bus camera. Remember the dark, rainy street.",
        user: "Remember the bus camera. Remember the dark, rainy street.",
        keywords: ["camera", "rainy"] },
      { id: 76, chapter: "The Verdict", speaker: 'COLE',
        agent: "Remember the children waiting by their quiet window.",
        user: "Remember the children waiting by their quiet window.",
        keywords: ["children", "quiet"] },
      { id: 77, chapter: "The Verdict", speaker: 'COLE',
        agent: "The gavel will fall. Make sure it falls justly.",
        user: "The gavel will fall. Make sure it falls justly.",
        keywords: ["gavel", "justly"] },
      { id: 78, chapter: "The Verdict", speaker: 'COLE',
        agent: "I rest my case, but I will never rest my faith.",
        user: "I rest my case, but I will never rest my faith.",
        keywords: ["faith"] },
      { id: 79, chapter: "The Verdict", speaker: 'COLE',
        agent: "Thank you for your attention, your patience, your conscience.",
        user: "Thank you for your attention, your patience, your conscience.",
        keywords: ["attention", "conscience"] },
      { id: 80, chapter: "The Verdict", speaker: 'COLE',
        agent: "Justice done today echoes far beyond this courtroom's walls.",
        user: "Justice done today echoes far beyond this courtroom's walls.",
        keywords: ["echoes", "courtroom"] }
    ]
  };
})();
