/* Speak or Boom — Starfall Protocol (shadow reading) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.shadow_space = {
    id: 'shadow_space',
    title: 'Starfall Protocol',
    tagline: 'Shadowing · 听一句，跟读同一句',
    speaker: 'REYES',
    difficulty: 'Intermediate',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: Captain's Log ----------
      { id: 1, chapter: "Captain's Log", speaker: 'REYES',
        agent: "This is Captain Reyes. We are going where no signal returns.",
        user: "This is Captain Reyes. We are going where no signal returns.",
        keywords: ["signal", "returns"] },
      { id: 2, chapter: "Captain's Log", speaker: 'REYES',
        agent: "The Meridian leaves orbit at dawn. All systems report ready.",
        user: "The Meridian leaves orbit at dawn. All systems report ready.",
        keywords: ["meridian", "orbit", "dawn"] },
      { id: 3, chapter: "Captain's Log", speaker: 'REYES',
        agent: "I have commanded this ship for six long years now.",
        user: "I have commanded this ship for six long years now.",
        keywords: ["commanded", "years"] },
      { id: 4, chapter: "Captain's Log", speaker: 'REYES',
        agent: "Two hundred souls sleep behind me, trusting my judgment.",
        user: "Two hundred souls sleep behind me, trusting my judgment.",
        keywords: ["souls", "judgment"] },
      { id: 5, chapter: "Captain's Log", speaker: 'REYES',
        agent: "The stars do not hurry. Neither do we.",
        user: "The stars do not hurry. Neither do we.",
        keywords: ["stars", "hurry"] },
      { id: 6, chapter: "Captain's Log", speaker: 'REYES',
        agent: "Space is patient. It rewards those who listen closely.",
        user: "Space is patient. It rewards those who listen closely.",
        keywords: ["patient", "listen"] },
      { id: 7, chapter: "Captain's Log", speaker: 'REYES',
        agent: "My first officer waits. The bridge is quiet and ready.",
        user: "My first officer waits. The bridge is quiet and ready.",
        keywords: ["officer", "bridge"] },
      { id: 8, chapter: "Captain's Log", speaker: 'REYES',
        agent: "Engines hum beneath us. Let the journey begin in earnest.",
        user: "Engines hum beneath us. Let the journey begin in earnest.",
        keywords: ["engines", "journey"] },
      // ---------- Chapter 2: The Signal ----------
      { id: 9, chapter: "The Signal", speaker: 'REYES',
        agent: "In the third hour, the silence finally broke open.",
        user: "In the third hour, the silence finally broke open.",
        keywords: ["silence", "broke"] },
      { id: 10, chapter: "The Signal", speaker: 'REYES',
        agent: "A signal arrived from the dark between the stars.",
        user: "A signal arrived from the dark between the stars.",
        keywords: ["signal", "arrived"] },
      { id: 11, chapter: "The Signal", speaker: 'REYES',
        agent: "No known language matches the pattern. It repeats every hour.",
        user: "No known language matches the pattern. It repeats every hour.",
        keywords: ["language", "pattern"] },
      { id: 12, chapter: "The Signal", speaker: 'REYES',
        agent: "My crew is awake now. Wonder replaced their sleep.",
        user: "My crew is awake now. Wonder replaced their sleep.",
        keywords: ["wonder", "sleep"] },
      { id: 13, chapter: "The Signal", speaker: 'REYES',
        agent: "The signal pulses like a heart. Something out there breathes.",
        user: "The signal pulses like a heart. Something out there breathes.",
        keywords: ["pulses", "breathes"] },
      { id: 14, chapter: "The Signal", speaker: 'REYES',
        agent: "Fear is data. We log it, and we move forward.",
        user: "Fear is data. We log it, and we move forward.",
        keywords: ["fear", "data"] },
      { id: 15, chapter: "The Signal", speaker: 'REYES',
        agent: "I ordered a full scan. The source is still moving.",
        user: "I ordered a full scan. The source is still moving.",
        keywords: ["scan", "source"] },
      { id: 16, chapter: "The Signal", speaker: 'REYES',
        agent: "Whatever waits ahead, we will meet it with open eyes.",
        user: "Whatever waits ahead, we will meet it with open eyes.",
        keywords: ["ahead", "eyes"] },
      // ---------- Chapter 3: Course Correction ----------
      { id: 17, chapter: "Course Correction", speaker: 'REYES',
        agent: "The signal comes from uncharted space. We change course now.",
        user: "The signal comes from uncharted space. We change course now.",
        keywords: ["uncharted", "course"] },
      { id: 18, chapter: "Course Correction", speaker: 'REYES',
        agent: "Charts mean nothing where we are going. Trust the instruments.",
        user: "Charts mean nothing where we are going. Trust the instruments.",
        keywords: ["charts", "instruments"] },
      { id: 19, chapter: "Course Correction", speaker: 'REYES',
        agent: "Some on the bridge doubted me. I heard their silence.",
        user: "Some on the bridge doubted me. I heard their silence.",
        keywords: ["doubted", "silence"] },
      { id: 20, chapter: "Course Correction", speaker: 'REYES',
        agent: "A captain does not explain every turn. She simply turns.",
        user: "A captain does not explain every turn. She simply turns.",
        keywords: ["captain", "turns"] },
      { id: 21, chapter: "Course Correction", speaker: 'REYES',
        agent: "The new heading is set. There is no going back now.",
        user: "The new heading is set. There is no going back now.",
        keywords: ["heading", "back"] },
      { id: 22, chapter: "Course Correction", speaker: 'REYES',
        agent: "Doubt is a passenger. It does not get the helm.",
        user: "Doubt is a passenger. It does not get the helm.",
        keywords: ["doubt", "passenger", "helm"] },
      { id: 23, chapter: "Course Correction", speaker: 'REYES',
        agent: "My navigator plotted a path through the quiet dark.",
        user: "My navigator plotted a path through the quiet dark.",
        keywords: ["navigator", "plotted"] },
      { id: 24, chapter: "Course Correction", speaker: 'REYES',
        agent: "We follow the signal. It is the only map we have.",
        user: "We follow the signal. It is the only map we have.",
        keywords: ["follow", "map"] },
      // ---------- Chapter 4: The Storm ----------
      { id: 25, chapter: "The Storm", speaker: 'REYES',
        agent: "The nebula ahead burns violet. It is beautiful and deadly.",
        user: "The nebula ahead burns violet. It is beautiful and deadly.",
        keywords: ["nebula", "violet", "deadly"] },
      { id: 26, chapter: "The Storm", speaker: 'REYES',
        agent: "Shields at full power. Strap in and hold your stations.",
        user: "Shields at full power. Strap in and hold your stations.",
        keywords: ["shields", "stations"] },
      { id: 27, chapter: "The Storm", speaker: 'REYES',
        agent: "The ship groans like an old tree in the wind.",
        user: "The ship groans like an old tree in the wind.",
        keywords: ["groans", "wind"] },
      { id: 28, chapter: "The Storm", speaker: 'REYES',
        agent: "Lightning without thunder rolls across the viewports now.",
        user: "Lightning without thunder rolls across the viewports now.",
        keywords: ["lightning", "thunder", "viewports"] },
      { id: 29, chapter: "The Storm", speaker: 'REYES',
        agent: "Stay calm, crew. Panic has never steered any ship.",
        user: "Stay calm, crew. Panic has never steered any ship.",
        keywords: ["calm", "panic"] },
      { id: 30, chapter: "The Storm", speaker: 'REYES',
        agent: "We ride the edge of the storm, not its heart.",
        user: "We ride the edge of the storm, not its heart.",
        keywords: ["storm", "heart"] },
      { id: 31, chapter: "The Storm", speaker: 'REYES',
        agent: "Damage reports are minor. The Meridian is tougher than rumors.",
        user: "Damage reports are minor. The Meridian is tougher than rumors.",
        keywords: ["damage", "tougher"] },
      { id: 32, chapter: "The Storm", speaker: 'REYES',
        agent: "The storm passes. Ahead, the signal grows even stronger.",
        user: "The storm passes. Ahead, the signal grows even stronger.",
        keywords: ["passes", "stronger"] },
      // ---------- Chapter 5: First Contact ----------
      { id: 33, chapter: "First Contact", speaker: 'REYES',
        agent: "Something massive waits beyond the dust. It is not a ship.",
        user: "Something massive waits beyond the dust. It is not a ship.",
        keywords: ["massive", "dust"] },
      { id: 34, chapter: "First Contact", speaker: 'REYES',
        agent: "It pulses in rhythm with our own signal now.",
        user: "It pulses in rhythm with our own signal now.",
        keywords: ["rhythm", "signal"] },
      { id: 35, chapter: "First Contact", speaker: 'REYES',
        agent: "Weapons stay cold. We came to listen, not to fight.",
        user: "Weapons stay cold. We came to listen, not to fight.",
        keywords: ["weapons", "listen"] },
      { id: 36, chapter: "First Contact", speaker: 'REYES',
        agent: "Open all channels. Let them hear a human voice first.",
        user: "Open all channels. Let them hear a human voice first.",
        keywords: ["channels", "voice"] },
      { id: 37, chapter: "First Contact", speaker: 'REYES',
        agent: "This is Captain Elena Reyes of the starship Meridian.",
        user: "This is Captain Elena Reyes of the starship Meridian.",
        keywords: ["captain", "meridian"] },
      { id: 38, chapter: "First Contact", speaker: 'REYES',
        agent: "We mean no harm. We followed your call across the void.",
        user: "We mean no harm. We followed your call across the void.",
        keywords: ["harm", "void"] },
      { id: 39, chapter: "First Contact", speaker: 'REYES',
        agent: "The bridge holds its breath. Even the engines seem quiet.",
        user: "The bridge holds its breath. Even the engines seem quiet.",
        keywords: ["breath", "quiet"] },
      { id: 40, chapter: "First Contact", speaker: 'REYES',
        agent: "Then the dark answered, in a voice made of light.",
        user: "Then the dark answered, in a voice made of light.",
        keywords: ["answered", "light"] },
      // ---------- Chapter 6: The Message ----------
      { id: 41, chapter: "The Message", speaker: 'REYES',
        agent: "The voice speaks in images, not words. We must interpret.",
        user: "The voice speaks in images, not words. We must interpret.",
        keywords: ["images", "interpret"] },
      { id: 42, chapter: "The Message", speaker: 'REYES',
        agent: "Our linguist wept. She said it sang of old sorrow.",
        user: "Our linguist wept. She said it sang of old sorrow.",
        keywords: ["linguist", "sorrow"] },
      { id: 43, chapter: "The Message", speaker: 'REYES',
        agent: "They are the Keepers, guardians of a dying star.",
        user: "They are the Keepers, guardians of a dying star.",
        keywords: ["keepers", "guardians"] },
      { id: 44, chapter: "The Message", speaker: 'REYES',
        agent: "Their sun fades. They asked if anyone was listening.",
        user: "Their sun fades. They asked if anyone was listening.",
        keywords: ["fades", "listening"] },
      { id: 45, chapter: "The Message", speaker: 'REYES',
        agent: "We were the first to answer in a thousand years.",
        user: "We were the first to answer in a thousand years.",
        keywords: ["answer", "thousand"] },
      { id: 46, chapter: "The Message", speaker: 'REYES',
        agent: "The message is simple: do not let our light die.",
        user: "The message is simple: do not let our light die.",
        keywords: ["message", "simple"] },
      { id: 47, chapter: "The Message", speaker: 'REYES',
        agent: "I promised we would carry their story home with us.",
        user: "I promised we would carry their story home with us.",
        keywords: ["promised", "story"] },
      { id: 48, chapter: "The Message", speaker: 'REYES',
        agent: "Some messages change the mission. This one changed us.",
        user: "Some messages change the mission. This one changed us.",
        keywords: ["mission", "changed"] },
      // ---------- Chapter 7: The Choice ----------
      { id: 49, chapter: "The Choice", speaker: 'REYES',
        agent: "Command will want the coordinates. I have not sent them.",
        user: "Command will want the coordinates. I have not sent them.",
        keywords: ["command", "coordinates"] },
      { id: 50, chapter: "The Choice", speaker: 'REYES',
        agent: "The Keepers trust us. Trust is not a resource to spend.",
        user: "The Keepers trust us. Trust is not a resource to spend.",
        keywords: ["trust", "spend"] },
      { id: 51, chapter: "The Choice", speaker: 'REYES',
        agent: "My officers argue through the night. Both sides are right.",
        user: "My officers argue through the night. Both sides are right.",
        keywords: ["officers", "argue"] },
      { id: 52, chapter: "The Choice", speaker: 'REYES',
        agent: "To reveal them is to save them. Or to doom them.",
        user: "To reveal them is to save them. Or to doom them.",
        keywords: ["reveal", "doom"] },
      { id: 53, chapter: "The Choice", speaker: 'REYES',
        agent: "I walked the empty decks until the answer found me.",
        user: "I walked the empty decks until the answer found me.",
        keywords: ["decks", "answer"] },
      { id: 54, chapter: "The Choice", speaker: 'REYES',
        agent: "We will help them quietly, asking nothing in return.",
        user: "We will help them quietly, asking nothing in return.",
        keywords: ["quietly", "return"] },
      { id: 55, chapter: "The Choice", speaker: 'REYES',
        agent: "A captain's hardest orders are the ones she withholds.",
        user: "A captain's hardest orders are the ones she withholds.",
        keywords: ["hardest", "withholds"] },
      { id: 56, chapter: "The Choice", speaker: 'REYES',
        agent: "The decision is logged. Let history judge it kindly.",
        user: "The decision is logged. Let history judge it kindly.",
        keywords: ["decision", "kindly"] },
      // ---------- Chapter 8: The Descent ----------
      { id: 57, chapter: "The Descent", speaker: 'REYES',
        agent: "We descend toward the Keeper world at first light.",
        user: "We descend toward the Keeper world at first light.",
        keywords: ["descend", "keeper"] },
      { id: 58, chapter: "The Descent", speaker: 'REYES',
        agent: "The surface glows silver beneath a violet sky.",
        user: "The surface glows silver beneath a violet sky.",
        keywords: ["surface", "silver"] },
      { id: 59, chapter: "The Descent", speaker: 'REYES',
        agent: "Gravity here is gentle, like being held, not pulled.",
        user: "Gravity here is gentle, like being held, not pulled.",
        keywords: ["gravity", "gentle"] },
      { id: 60, chapter: "The Descent", speaker: 'REYES',
        agent: "They gather to watch us land, silent and unafraid.",
        user: "They gather to watch us land, silent and unafraid.",
        keywords: ["gather", "unafraid"] },
      { id: 61, chapter: "The Descent", speaker: 'REYES',
        agent: "I step out first. A captain leads with her boots.",
        user: "I step out first. A captain leads with her boots.",
        keywords: ["boots", "leads"] },
      { id: 62, chapter: "The Descent", speaker: 'REYES',
        agent: "Their elder touches my hand. The contact feels like sunrise.",
        user: "Their elder touches my hand. The contact feels like sunrise.",
        keywords: ["elder", "sunrise"] },
      { id: 63, chapter: "The Descent", speaker: 'REYES',
        agent: "No words pass between us. None are needed at all.",
        user: "No words pass between us. None are needed at all.",
        keywords: ["words", "needed"] },
      { id: 64, chapter: "The Descent", speaker: 'REYES',
        agent: "We plant our flag beside theirs, as equals, as friends.",
        user: "We plant our flag beside theirs, as equals, as friends.",
        keywords: ["flag", "friends"] },
      // ---------- Chapter 9: The Discovery ----------
      { id: 65, chapter: "The Discovery", speaker: 'REYES',
        agent: "Beneath the surface sleeps an engine older than empires.",
        user: "Beneath the surface sleeps an engine older than empires.",
        keywords: ["engine", "empires"] },
      { id: 66, chapter: "The Discovery", speaker: 'REYES',
        agent: "It could reignite their sun, but it needs our help.",
        user: "It could reignite their sun, but it needs our help.",
        keywords: ["reignite", "help"] },
      { id: 67, chapter: "The Discovery", speaker: 'REYES',
        agent: "My engineers stare in wonder. Then they start to work.",
        user: "My engineers stare in wonder. Then they start to work.",
        keywords: ["engineers", "wonder"] },
      { id: 68, chapter: "The Discovery", speaker: 'REYES',
        agent: "Three days of labor. Three nights without proper sleep.",
        user: "Three days of labor. Three nights without proper sleep.",
        keywords: ["labor", "sleep"] },
      { id: 69, chapter: "The Discovery", speaker: 'REYES',
        agent: "Nobody complained. Purpose is stronger than any fatigue.",
        user: "Nobody complained. Purpose is stronger than any fatigue.",
        keywords: ["purpose", "fatigue"] },
      { id: 70, chapter: "The Discovery", speaker: 'REYES',
        agent: "On the fourth morning, the engine woke with a roar.",
        user: "On the fourth morning, the engine woke with a roar.",
        keywords: ["fourth", "roar"] },
      { id: 71, chapter: "The Discovery", speaker: 'REYES',
        agent: "Light returned to their sky. The Keepers wept openly.",
        user: "Light returned to their sky. The Keepers wept openly.",
        keywords: ["light", "wept"] },
      { id: 72, chapter: "The Discovery", speaker: 'REYES',
        agent: "We did not conquer anything. We simply kept a promise.",
        user: "We did not conquer anything. We simply kept a promise.",
        keywords: ["conquer", "promise"] },
      // ---------- Chapter 10: Homeward ----------
      { id: 73, chapter: "Homeward", speaker: 'REYES',
        agent: "The Meridian turns homeward. Our tanks are full of starlight.",
        user: "The Meridian turns homeward. Our tanks are full of starlight.",
        keywords: ["homeward", "starlight"] },
      { id: 74, chapter: "Homeward", speaker: 'REYES',
        agent: "We carry no treasure, only a story worth telling.",
        user: "We carry no treasure, only a story worth telling.",
        keywords: ["treasure", "story"] },
      { id: 75, chapter: "Homeward", speaker: 'REYES',
        agent: "The crew is quieter now, and somehow braver too.",
        user: "The crew is quieter now, and somehow braver too.",
        keywords: ["quieter", "braver"] },
      { id: 76, chapter: "Homeward", speaker: 'REYES',
        agent: "I log this final entry with a steady hand.",
        user: "I log this final entry with a steady hand.",
        keywords: ["final", "steady"] },
      { id: 77, chapter: "Homeward", speaker: 'REYES',
        agent: "We went seeking a signal. We found a responsibility.",
        user: "We went seeking a signal. We found a responsibility.",
        keywords: ["seeking", "responsibility"] },
      { id: 78, chapter: "Homeward", speaker: 'REYES',
        agent: "The void is vast, but no one need face it alone.",
        user: "The void is vast, but no one need face it alone.",
        keywords: ["vast", "alone"] },
      { id: 79, chapter: "Homeward", speaker: 'REYES',
        agent: "This is Captain Reyes, signing off. The stars keep watch.",
        user: "This is Captain Reyes, signing off. The stars keep watch.",
        keywords: ["signing", "watch"] },
      { id: 80, chapter: "Homeward", speaker: 'REYES',
        agent: "Until the next signal calls, we sail on in peace.",
        user: "Until the next signal calls, we sail on in peace.",
        keywords: ["signal", "peace"] }
    ]
  };
})();
