/* Speak or Boom — Codename: Nightfall (shadow reading) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.shadow_bond = {
    id: 'shadow_bond',
    title: 'Codename: Nightfall',
    tagline: 'Shadowing · 听一句，跟读同一句',
    speaker: 'CROSS',
    difficulty: 'Intermediate',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: Midnight Briefing ----------
      { id: 1, chapter: "Midnight Briefing", speaker: 'CROSS',
        agent: "The midnight call came. I never ignore that particular ringtone.",
        user: "The midnight call came. I never ignore that particular ringtone.",
        keywords: ["midnight", "ringtone"] },
      { id: 2, chapter: "Midnight Briefing", speaker: 'CROSS',
        agent: "Director Vale does not summon agents for small problems, ever.",
        user: "Director Vale does not summon agents for small problems, ever.",
        keywords: ["summon", "agents"] },
      { id: 3, chapter: "Midnight Briefing", speaker: 'CROSS',
        agent: "The file was thin. The best missions always start that way.",
        user: "The file was thin. The best missions always start that way.",
        keywords: ["missions", "thin"] },
      { id: 4, chapter: "Midnight Briefing", speaker: 'CROSS',
        agent: "A missing cipher. A dead courier. A casino in Monaco.",
        user: "A missing cipher. A dead courier. A casino in Monaco.",
        keywords: ["cipher", "courier", "monaco"] },
      { id: 5, chapter: "Midnight Briefing", speaker: 'CROSS',
        agent: "I asked for backup. She just smiled and said no.",
        user: "I asked for backup. She just smiled and said no.",
        keywords: ["backup", "smiled"] },
      { id: 6, chapter: "Midnight Briefing", speaker: 'CROSS',
        agent: "Forty-eight hours. That is all the time I have.",
        user: "Forty-eight hours. That is all the time I have.",
        keywords: ["hours"] },
      { id: 7, chapter: "Midnight Briefing", speaker: 'CROSS',
        agent: "I took the envelope and walked into the rain.",
        user: "I took the envelope and walked into the rain.",
        keywords: ["envelope", "rain"] },
      { id: 8, chapter: "Midnight Briefing", speaker: 'CROSS',
        agent: "Some assignments choose you. This one chose me twice.",
        user: "Some assignments choose you. This one chose me twice.",
        keywords: ["assignments", "twice"] },
      // ---------- Chapter 2: Gearing Up ----------
      { id: 9, chapter: "Gearing Up", speaker: 'CROSS',
        agent: "Fenwick handed me a watch. It does far more than tell time.",
        user: "Fenwick handed me a watch. It does far more than tell time.",
        keywords: ["fenwick", "watch"] },
      { id: 10, chapter: "Gearing Up", speaker: 'CROSS',
        agent: "The pen fires a tracker. Try not to lose this one.",
        user: "The pen fires a tracker. Try not to lose this one.",
        keywords: ["tracker", "fires"] },
      { id: 11, chapter: "Gearing Up", speaker: 'CROSS',
        agent: "These cufflinks are cameras. Smile for your enemies, he said.",
        user: "These cufflinks are cameras. Smile for your enemies, he said.",
        keywords: ["cufflinks", "cameras"] },
      { id: 12, chapter: "Gearing Up", speaker: 'CROSS',
        agent: "The car is fast. The ejector seat is faster, apparently.",
        user: "The car is fast. The ejector seat is faster, apparently.",
        keywords: ["ejector", "faster"] },
      { id: 13, chapter: "Gearing Up", speaker: 'CROSS',
        agent: "I signed for everything and promised to bring it back.",
        user: "I signed for everything and promised to bring it back.",
        keywords: ["signed", "promised"] },
      { id: 14, chapter: "Gearing Up", speaker: 'CROSS',
        agent: "He laughed. Nobody ever brings anything back, he said.",
        user: "He laughed. Nobody ever brings anything back, he said.",
        keywords: ["nobody", "laughed"] },
      { id: 15, chapter: "Gearing Up", speaker: 'CROSS',
        agent: "I pocketed the gadgets and headed for the airfield.",
        user: "I pocketed the gadgets and headed for the airfield.",
        keywords: ["gadgets", "airfield"] },
      { id: 16, chapter: "Gearing Up", speaker: 'CROSS',
        agent: "A good agent trusts his tools. A great one trusts himself.",
        user: "A good agent trusts his tools. A great one trusts himself.",
        keywords: ["trusts", "tools"] },
      // ---------- Chapter 3: Arrival in Monaco ----------
      { id: 17, chapter: "Arrival in Monaco", speaker: 'CROSS',
        agent: "Monaco at dawn. Even the sunlight here wears a tuxedo.",
        user: "Monaco at dawn. Even the sunlight here wears a tuxedo.",
        keywords: ["monaco", "tuxedo"] },
      { id: 18, chapter: "Arrival in Monaco", speaker: 'CROSS',
        agent: "The hotel knew my name before I showed my passport.",
        user: "The hotel knew my name before I showed my passport.",
        keywords: ["hotel", "passport"] },
      { id: 19, chapter: "Arrival in Monaco", speaker: 'CROSS',
        agent: "My room overlooks the harbor. Every yacht is a suspect.",
        user: "My room overlooks the harbor. Every yacht is a suspect.",
        keywords: ["overlooks", "suspect"] },
      { id: 20, chapter: "Arrival in Monaco", speaker: 'CROSS',
        agent: "I ordered coffee and studied the casino across the square.",
        user: "I ordered coffee and studied the casino across the square.",
        keywords: ["studied", "casino"] },
      { id: 21, chapter: "Arrival in Monaco", speaker: 'CROSS',
        agent: "The target arrives tonight. So does my opportunity.",
        user: "The target arrives tonight. So does my opportunity.",
        keywords: ["target", "opportunity"] },
      { id: 22, chapter: "Arrival in Monaco", speaker: 'CROSS',
        agent: "I pressed my suit and checked my reflection twice.",
        user: "I pressed my suit and checked my reflection twice.",
        keywords: ["pressed", "reflection"] },
      { id: 23, chapter: "Arrival in Monaco", speaker: 'CROSS',
        agent: "In this town, everyone is watching everyone else.",
        user: "In this town, everyone is watching everyone else.",
        keywords: ["watching", "town"] },
      { id: 24, chapter: "Arrival in Monaco", speaker: 'CROSS',
        agent: "Time to walk in like I own the place.",
        user: "Time to walk in like I own the place.",
        keywords: ["walk", "place"] },
      // ---------- Chapter 4: The Casino ----------
      { id: 25, chapter: "The Casino", speaker: 'CROSS',
        agent: "The casino floor smelled of money and bad decisions.",
        user: "The casino floor smelled of money and bad decisions.",
        keywords: ["smelled", "decisions"] },
      { id: 26, chapter: "The Casino", speaker: 'CROSS',
        agent: "I bought my chips and found the high-stakes table.",
        user: "I bought my chips and found the high-stakes table.",
        keywords: ["chips", "table"] },
      { id: 27, chapter: "The Casino", speaker: 'CROSS',
        agent: "Viktor Kaine sat across from me, smiling like a shark.",
        user: "Viktor Kaine sat across from me, smiling like a shark.",
        keywords: ["viktor", "shark"] },
      { id: 28, chapter: "The Casino", speaker: 'CROSS',
        agent: "I don't lose at cards. I simply choose when to win.",
        user: "I don't lose at cards. I simply choose when to win.",
        keywords: ["cards", "choose"] },
      { id: 29, chapter: "The Casino", speaker: 'CROSS',
        agent: "He raised. I called. The room went very quiet.",
        user: "He raised. I called. The room went very quiet.",
        keywords: ["raised", "quiet"] },
      { id: 30, chapter: "The Casino", speaker: 'CROSS',
        agent: "My hand was perfect. His face told me he knew.",
        user: "My hand was perfect. His face told me he knew.",
        keywords: ["perfect", "knew"] },
      { id: 31, chapter: "The Casino", speaker: 'CROSS',
        agent: "I took the pot and his attention in one move.",
        user: "I took the pot and his attention in one move.",
        keywords: ["pot", "attention"] },
      { id: 32, chapter: "The Casino", speaker: 'CROSS',
        agent: "He invited me for a drink. The game had begun.",
        user: "He invited me for a drink. The game had begun.",
        keywords: ["invited", "begun"] },
      // ---------- Chapter 5: Rooftop Chase ----------
      { id: 33, chapter: "Rooftop Chase", speaker: 'CROSS',
        agent: "His men moved in. I moved out through the kitchen.",
        user: "His men moved in. I moved out through the kitchen.",
        keywords: ["kitchen", "moved"] },
      { id: 34, chapter: "Rooftop Chase", speaker: 'CROSS',
        agent: "The back alley was dark. My legs were faster.",
        user: "The back alley was dark. My legs were faster.",
        keywords: ["alley", "faster"] },
      { id: 35, chapter: "Rooftop Chase", speaker: 'CROSS',
        agent: "A fire escape led up. I took it two steps at a time.",
        user: "A fire escape led up. I took it two steps at a time.",
        keywords: ["escape", "steps"] },
      { id: 36, chapter: "Rooftop Chase", speaker: 'CROSS',
        agent: "Across the rooftops, the whole city glittered below me.",
        user: "Across the rooftops, the whole city glittered below me.",
        keywords: ["rooftops", "glittered"] },
      { id: 37, chapter: "Rooftop Chase", speaker: 'CROSS',
        agent: "One of them grabbed my coat. He kept the coat.",
        user: "One of them grabbed my coat. He kept the coat.",
        keywords: ["grabbed", "coat"] },
      { id: 38, chapter: "Rooftop Chase", speaker: 'CROSS',
        agent: "I leapt the gap and landed running on the next roof.",
        user: "I leapt the gap and landed running on the next roof.",
        keywords: ["leapt", "landed"] },
      { id: 39, chapter: "Rooftop Chase", speaker: 'CROSS',
        agent: "The church bell rang midnight as I lost them.",
        user: "The church bell rang midnight as I lost them.",
        keywords: ["bell", "midnight"] },
      { id: 40, chapter: "Rooftop Chase", speaker: 'CROSS',
        agent: "Chase me again, gentlemen. I enjoy the exercise.",
        user: "Chase me again, gentlemen. I enjoy the exercise.",
        keywords: ["chase", "exercise"] },
      // ---------- Chapter 6: The Villa ----------
      { id: 41, chapter: "The Villa", speaker: 'CROSS',
        agent: "Kaine's villa sat on the cliff like a sleeping beast.",
        user: "Kaine's villa sat on the cliff like a sleeping beast.",
        keywords: ["villa", "beast"] },
      { id: 42, chapter: "The Villa", speaker: 'CROSS',
        agent: "The guards changed at two. I counted the seconds.",
        user: "The guards changed at two. I counted the seconds.",
        keywords: ["guards", "counted"] },
      { id: 43, chapter: "The Villa", speaker: 'CROSS',
        agent: "The tracker pen marked my path through the garden.",
        user: "The tracker pen marked my path through the garden.",
        keywords: ["tracker", "garden"] },
      { id: 44, chapter: "The Villa", speaker: 'CROSS',
        agent: "A window on the east side was slightly open.",
        user: "A window on the east side was slightly open.",
        keywords: ["window", "slightly"] },
      { id: 45, chapter: "The Villa", speaker: 'CROSS',
        agent: "Inside, the safe waited behind a painting of ships.",
        user: "Inside, the safe waited behind a painting of ships.",
        keywords: ["safe", "painting"] },
      { id: 46, chapter: "The Villa", speaker: 'CROSS',
        agent: "The cipher was there, exactly where Vale said it would be.",
        user: "The cipher was there, exactly where Vale said it would be.",
        keywords: ["cipher", "exactly"] },
      { id: 47, chapter: "The Villa", speaker: 'CROSS',
        agent: "I photographed every page and put it all back.",
        user: "I photographed every page and put it all back.",
        keywords: ["photographed", "page"] },
      { id: 48, chapter: "The Villa", speaker: 'CROSS',
        agent: "Then the lights came on. So much for stealth.",
        user: "Then the lights came on. So much for stealth.",
        keywords: ["lights", "stealth"] },
      // ---------- Chapter 7: The Trap ----------
      { id: 49, chapter: "The Trap", speaker: 'CROSS',
        agent: "Kaine clapped slowly from the doorway. Well done, Cross.",
        user: "Kaine clapped slowly from the doorway. Well done, Cross.",
        keywords: ["clapped", "doorway"] },
      { id: 50, chapter: "The Trap", speaker: 'CROSS',
        agent: "His men took my watch, my pen, and my dignity.",
        user: "His men took my watch, my pen, and my dignity.",
        keywords: ["dignity", "watch"] },
      { id: 51, chapter: "The Trap", speaker: 'CROSS',
        agent: "He offered me a job. I offered him a smile.",
        user: "He offered me a job. I offered him a smile.",
        keywords: ["offered", "smile"] },
      { id: 52, chapter: "The Trap", speaker: 'CROSS',
        agent: "You have thirty seconds to tell me where the files are.",
        user: "You have thirty seconds to tell me where the files are.",
        keywords: ["thirty", "seconds", "files"] },
      { id: 53, chapter: "The Trap", speaker: 'CROSS',
        agent: "That was his line, actually. I borrowed it back.",
        user: "That was his line, actually. I borrowed it back.",
        keywords: ["borrowed", "actually"] },
      { id: 54, chapter: "The Trap", speaker: 'CROSS',
        agent: "The chair was uncomfortable. The view was worse.",
        user: "The chair was uncomfortable. The view was worse.",
        keywords: ["uncomfortable", "worse"] },
      { id: 55, chapter: "The Trap", speaker: 'CROSS',
        agent: "I told him nothing. Silence is also an answer.",
        user: "I told him nothing. Silence is also an answer.",
        keywords: ["silence", "answer"] },
      { id: 56, chapter: "The Trap", speaker: 'CROSS',
        agent: "Then Fenwick's watch started beeping. Right on schedule.",
        user: "Then Fenwick's watch started beeping. Right on schedule.",
        keywords: ["beeping", "schedule"] },
      // ---------- Chapter 8: The Escape ----------
      { id: 57, chapter: "The Escape", speaker: 'CROSS',
        agent: "The watch was also a flash grenade. Surprise, gentlemen.",
        user: "The watch was also a flash grenade. Surprise, gentlemen.",
        keywords: ["grenade", "surprise"] },
      { id: 58, chapter: "The Escape", speaker: 'CROSS',
        agent: "I ran through the smoke toward the cliff path.",
        user: "I ran through the smoke toward the cliff path.",
        keywords: ["smoke", "cliff"] },
      { id: 59, chapter: "The Escape", speaker: 'CROSS',
        agent: "A speedboat waited below, engine running, just as planned.",
        user: "A speedboat waited below, engine running, just as planned.",
        keywords: ["speedboat", "planned"] },
      { id: 60, chapter: "The Escape", speaker: 'CROSS',
        agent: "Bullets hit the water behind me. They missed beautifully.",
        user: "Bullets hit the water behind me. They missed beautifully.",
        keywords: ["bullets", "beautifully"] },
      { id: 61, chapter: "The Escape", speaker: 'CROSS',
        agent: "I was never here. You never saw me. Understood?",
        user: "I was never here. You never saw me. Understood?",
        keywords: ["never", "understood"] },
      { id: 62, chapter: "The Escape", speaker: 'CROSS',
        agent: "The boat driver grinned. Nice evening for a ride, he said.",
        user: "The boat driver grinned. Nice evening for a ride, he said.",
        keywords: ["grinned", "ride"] },
      { id: 63, chapter: "The Escape", speaker: 'CROSS',
        agent: "Monaco's lights faded as we raced into the dark.",
        user: "Monaco's lights faded as we raced into the dark.",
        keywords: ["faded", "raced"] },
      { id: 64, chapter: "The Escape", speaker: 'CROSS',
        agent: "Phase one complete. Kaine knows my name now.",
        user: "Phase one complete. Kaine knows my name now.",
        keywords: ["phase", "complete"] },
      // ---------- Chapter 9: Showdown ----------
      { id: 65, chapter: "Showdown", speaker: 'CROSS',
        agent: "Kaine's yacht left at dawn. I was already aboard.",
        user: "Kaine's yacht left at dawn. I was already aboard.",
        keywords: ["yacht", "aboard"] },
      { id: 66, chapter: "Showdown", speaker: 'CROSS',
        agent: "We met on the deck, just the two of us.",
        user: "We met on the deck, just the two of us.",
        keywords: ["deck", "met"] },
      { id: 67, chapter: "Showdown", speaker: 'CROSS',
        agent: "He drew first. I had already won, politely.",
        user: "He drew first. I had already won, politely.",
        keywords: ["drew", "politely"] },
      { id: 68, chapter: "Showdown", speaker: 'CROSS',
        agent: "The cipher goes back to London. You go nowhere.",
        user: "The cipher goes back to London. You go nowhere.",
        keywords: ["cipher", "nowhere"] },
      { id: 69, chapter: "Showdown", speaker: 'CROSS',
        agent: "He laughed, but his hand was shaking slightly.",
        user: "He laughed, but his hand was shaking slightly.",
        keywords: ["laughed", "shaking"] },
      { id: 70, chapter: "Showdown", speaker: 'CROSS',
        agent: "I disarmed him with the pen. Fenwick would be proud.",
        user: "I disarmed him with the pen. Fenwick would be proud.",
        keywords: ["disarmed", "proud"] },
      { id: 71, chapter: "Showdown", speaker: 'CROSS',
        agent: "Game over, Viktor. The house always wins eventually.",
        user: "Game over, Viktor. The house always wins eventually.",
        keywords: ["game", "eventually"] },
      { id: 72, chapter: "Showdown", speaker: 'CROSS',
        agent: "I radioed Vale. One package ready for pickup.",
        user: "I radioed Vale. One package ready for pickup.",
        keywords: ["radioed", "pickup"] },
      // ---------- Chapter 10: Debrief ----------
      { id: 73, chapter: "Debrief", speaker: 'CROSS',
        agent: "London was gray. The debrief room was grayer.",
        user: "London was gray. The debrief room was grayer.",
        keywords: ["london", "grayer"] },
      { id: 74, chapter: "Debrief", speaker: 'CROSS',
        agent: "Vale read my report and almost smiled. Almost.",
        user: "Vale read my report and almost smiled. Almost.",
        keywords: ["report", "smiled"] },
      { id: 75, chapter: "Debrief", speaker: 'CROSS',
        agent: "The cipher is safe. Kaine is in custody.",
        user: "The cipher is safe. Kaine is in custody.",
        keywords: ["cipher", "custody"] },
      { id: 76, chapter: "Debrief", speaker: 'CROSS',
        agent: "Fenwick wants his watch back. I kept the pen.",
        user: "Fenwick wants his watch back. I kept the pen.",
        keywords: ["wants", "kept"] },
      { id: 77, chapter: "Debrief", speaker: 'CROSS',
        agent: "She offered me a week off. I asked for a mission.",
        user: "She offered me a week off. I asked for a mission.",
        keywords: ["offered", "mission"] },
      { id: 78, chapter: "Debrief", speaker: 'CROSS',
        agent: "There is always another cipher, another casino, another dawn.",
        user: "There is always another cipher, another casino, another dawn.",
        keywords: ["another", "dawn"] },
      { id: 79, chapter: "Debrief", speaker: 'CROSS',
        agent: "A martini, please. The evening is shaken enough already.",
        user: "A martini, please. The evening is shaken enough already.",
        keywords: ["martini", "shaken"] },
      { id: 80, chapter: "Debrief", speaker: 'CROSS',
        agent: "The name stays Cross. The work never ends.",
        user: "The name stays Cross. The work never ends.",
        keywords: ["stays", "ends"] }
    ]
  };
})();
