/* Speak or Boom — Fire & Thyme (shadow reading) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.shadow_chef = {
    id: 'shadow_chef',
    title: 'Fire & Thyme',
    tagline: 'Shadowing · 听一句，跟读同一句',
    speaker: 'ROSA',
    difficulty: 'Beginner',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: Welcome to My Kitchen ----------
      { id: 1, chapter: "Welcome to My Kitchen", speaker: 'ROSA',
        agent: "Welcome to my kitchen. Tonight we cook from the heart.",
        user: "Welcome to my kitchen. Tonight we cook from the heart.",
        keywords: ["kitchen", "heart"] },
      { id: 2, chapter: "Welcome to My Kitchen", speaker: 'ROSA',
        agent: "I am Rosa Bellini, and this stove is my happy place.",
        user: "I am Rosa Bellini, and this stove is my happy place.",
        keywords: ["bellini", "stove"] },
      { id: 3, chapter: "Welcome to My Kitchen", speaker: 'ROSA',
        agent: "Tonight we make my grandmother's Sunday ragu, slowly and lovingly.",
        user: "Tonight we make my grandmother's Sunday ragu, slowly and lovingly.",
        keywords: ["sunday", "ragu"] },
      { id: 4, chapter: "Welcome to My Kitchen", speaker: 'ROSA',
        agent: "No shortcuts. No rush. Just fire, patience, and good olive oil.",
        user: "No shortcuts. No rush. Just fire, patience, and good olive oil.",
        keywords: ["patience", "olive"] },
      { id: 5, chapter: "Welcome to My Kitchen", speaker: 'ROSA',
        agent: "Put your phone away. Cooking deserves your full attention.",
        user: "Put your phone away. Cooking deserves your full attention.",
        keywords: ["phone", "attention"] },
      { id: 6, chapter: "Welcome to My Kitchen", speaker: 'ROSA',
        agent: "Tie your apron tight. We are going on a delicious journey.",
        user: "Tie your apron tight. We are going on a delicious journey.",
        keywords: ["apron", "journey"] },
      { id: 7, chapter: "Welcome to My Kitchen", speaker: 'ROSA',
        agent: "Every great dish begins with a single brave onion.",
        user: "Every great dish begins with a single brave onion.",
        keywords: ["dish", "onion"] },
      { id: 8, chapter: "Welcome to My Kitchen", speaker: 'ROSA',
        agent: "Are you ready? Then let us begin this beautiful mess.",
        user: "Are you ready? Then let us begin this beautiful mess.",
        keywords: ["ready", "beautiful"] },
      // ---------- Chapter 2: The Ingredients ----------
      { id: 9, chapter: "The Ingredients", speaker: 'ROSA',
        agent: "Good cooking starts at the market, not at the stove.",
        user: "Good cooking starts at the market, not at the stove.",
        keywords: ["market", "stove"] },
      { id: 10, chapter: "The Ingredients", speaker: 'ROSA',
        agent: "These tomatoes smell like August sunshine in Sicily.",
        user: "These tomatoes smell like August sunshine in Sicily.",
        keywords: ["tomatoes", "sicily"] },
      { id: 11, chapter: "The Ingredients", speaker: 'ROSA',
        agent: "Good olive oil should smell like fresh-cut grass.",
        user: "Good olive oil should smell like fresh-cut grass.",
        keywords: ["olive", "grass"] },
      { id: 12, chapter: "The Ingredients", speaker: 'ROSA',
        agent: "Feel this basil. It should be soft like velvet.",
        user: "Feel this basil. It should be soft like velvet.",
        keywords: ["basil", "velvet"] },
      { id: 13, chapter: "The Ingredients", speaker: 'ROSA',
        agent: "The garlic must be firm, with tight papery skin.",
        user: "The garlic must be firm, with tight papery skin.",
        keywords: ["garlic", "papery"] },
      { id: 14, chapter: "The Ingredients", speaker: 'ROSA',
        agent: "Choose beef with beautiful marbling. Fat means flavor.",
        user: "Choose beef with beautiful marbling. Fat means flavor.",
        keywords: ["marbling", "flavor"] },
      { id: 15, chapter: "The Ingredients", speaker: 'ROSA',
        agent: "Fresh pasta needs only flour, eggs, and strong hands.",
        user: "Fresh pasta needs only flour, eggs, and strong hands.",
        keywords: ["flour", "hands"] },
      { id: 16, chapter: "The Ingredients", speaker: 'ROSA',
        agent: "Salt is a seasoning, but also a storyteller.",
        user: "Salt is a seasoning, but also a storyteller.",
        keywords: ["salt", "storyteller"] },
      // ---------- Chapter 3: First Cut ----------
      { id: 17, chapter: "First Cut", speaker: 'ROSA',
        agent: "A sharp knife is a cook's best friend. Respect it.",
        user: "A sharp knife is a cook's best friend. Respect it.",
        keywords: ["knife", "respect"] },
      { id: 18, chapter: "First Cut", speaker: 'ROSA',
        agent: "Slice the onion thin. Let it weep a little.",
        user: "Slice the onion thin. Let it weep a little.",
        keywords: ["onion", "weep"] },
      { id: 19, chapter: "First Cut", speaker: 'ROSA',
        agent: "Listen to the rhythm. Chop, chop, breathe, chop.",
        user: "Listen to the rhythm. Chop, chop, breathe, chop.",
        keywords: ["rhythm", "breathe"] },
      { id: 20, chapter: "First Cut", speaker: 'ROSA',
        agent: "Carrots first, then celery. Always in that order.",
        user: "Carrots first, then celery. Always in that order.",
        keywords: ["carrots", "celery"] },
      { id: 21, chapter: "First Cut", speaker: 'ROSA',
        agent: "Mince the garlic fine, but never crush its spirit.",
        user: "Mince the garlic fine, but never crush its spirit.",
        keywords: ["garlic", "spirit"] },
      { id: 22, chapter: "First Cut", speaker: 'ROSA',
        agent: "Keep your fingertips curled. The claw saves fingers.",
        user: "Keep your fingertips curled. The claw saves fingers.",
        keywords: ["fingertips", "claw"] },
      { id: 23, chapter: "First Cut", speaker: 'ROSA',
        agent: "Uniform pieces cook evenly. Patience starts with the knife.",
        user: "Uniform pieces cook evenly. Patience starts with the knife.",
        keywords: ["uniform", "patience"] },
      { id: 24, chapter: "First Cut", speaker: 'ROSA',
        agent: "Look at these colors. We eat with our eyes first.",
        user: "Look at these colors. We eat with our eyes first.",
        keywords: ["colors", "eyes"] },
      // ---------- Chapter 4: Fire ----------
      { id: 25, chapter: "Fire", speaker: 'ROSA',
        agent: "Now we wake the fire. Medium heat, never angry heat.",
        user: "Now we wake the fire. Medium heat, never angry heat.",
        keywords: ["fire", "angry"] },
      { id: 26, chapter: "Fire", speaker: 'ROSA',
        agent: "A heavy pot holds heat like a warm hug.",
        user: "A heavy pot holds heat like a warm hug.",
        keywords: ["heavy", "hug"] },
      { id: 27, chapter: "Fire", speaker: 'ROSA',
        agent: "The olive oil shimmers. That means it is ready.",
        user: "The olive oil shimmers. That means it is ready.",
        keywords: ["shimmers", "ready"] },
      { id: 28, chapter: "Fire", speaker: 'ROSA',
        agent: "Brown the beef in batches. Crowding steams, never sears.",
        user: "Brown the beef in batches. Crowding steams, never sears.",
        keywords: ["batches", "sears"] },
      { id: 29, chapter: "Fire", speaker: 'ROSA',
        agent: "Hear that crust forming? That is flavor being born.",
        user: "Hear that crust forming? That is flavor being born.",
        keywords: ["crust", "flavor"] },
      { id: 30, chapter: "Fire", speaker: 'ROSA',
        agent: "Do not touch it yet. Let the pan do its work.",
        user: "Do not touch it yet. Let the pan do its work.",
        keywords: ["touch", "pan"] },
      { id: 31, chapter: "Fire", speaker: 'ROSA',
        agent: "Golden brown on every side. That is the goal.",
        user: "Golden brown on every side. That is the goal.",
        keywords: ["golden", "goal"] },
      { id: 32, chapter: "Fire", speaker: 'ROSA',
        agent: "Deglaze with red wine. The sizzle is pure music.",
        user: "Deglaze with red wine. The sizzle is pure music.",
        keywords: ["deglaze", "music"] },
      // ---------- Chapter 5: The Sizzle ----------
      { id: 33, chapter: "The Sizzle", speaker: 'ROSA',
        agent: "Listen to that sizzle. That is the sound of patience.",
        user: "Listen to that sizzle. That is the sound of patience.",
        keywords: ["sizzle", "patience"] },
      { id: 34, chapter: "The Sizzle", speaker: 'ROSA',
        agent: "The onions are melting into sweet golden silk.",
        user: "The onions are melting into sweet golden silk.",
        keywords: ["melting", "silk"] },
      { id: 35, chapter: "The Sizzle", speaker: 'ROSA',
        agent: "Stir slowly. Rushing ruins what fire has built.",
        user: "Stir slowly. Rushing ruins what fire has built.",
        keywords: ["rushing", "built"] },
      { id: 36, chapter: "The Sizzle", speaker: 'ROSA',
        agent: "Add the tomatoes now. Watch them surrender to the heat.",
        user: "Add the tomatoes now. Watch them surrender to the heat.",
        keywords: ["surrender", "heat"] },
      { id: 37, chapter: "The Sizzle", speaker: 'ROSA',
        agent: "A pinch of salt wakes every sleepy flavor.",
        user: "A pinch of salt wakes every sleepy flavor.",
        keywords: ["pinch", "sleepy"] },
      { id: 38, chapter: "The Sizzle", speaker: 'ROSA',
        agent: "The sauce bubbles lazily, like a cat in sunshine.",
        user: "The sauce bubbles lazily, like a cat in sunshine.",
        keywords: ["bubbles", "sunshine"] },
      { id: 39, chapter: "The Sizzle", speaker: 'ROSA',
        agent: "Taste it. Then taste it again. Trust your tongue.",
        user: "Taste it. Then taste it again. Trust your tongue.",
        keywords: ["taste", "tongue"] },
      { id: 40, chapter: "The Sizzle", speaker: 'ROSA',
        agent: "It needs thyme. Fresh thyme, never the dusty jar.",
        user: "It needs thyme. Fresh thyme, never the dusty jar.",
        keywords: ["thyme", "dusty"] },
      // ---------- Chapter 6: Patience ----------
      { id: 41, chapter: "Patience", speaker: 'ROSA',
        agent: "Now we wait. Good ragu cannot be hurried, ever.",
        user: "Now we wait. Good ragu cannot be hurried, ever.",
        keywords: ["hurried", "ragu"] },
      { id: 42, chapter: "Patience", speaker: 'ROSA',
        agent: "Low and slow. Let time do the heavy lifting.",
        user: "Low and slow. Let time do the heavy lifting.",
        keywords: ["heavy", "lifting"] },
      { id: 43, chapter: "Patience", speaker: 'ROSA',
        agent: "Stir every twenty minutes. Visit it like an old friend.",
        user: "Stir every twenty minutes. Visit it like an old friend.",
        keywords: ["minutes", "friend"] },
      { id: 44, chapter: "Patience", speaker: 'ROSA',
        agent: "The kitchen smells like my childhood in Naples.",
        user: "The kitchen smells like my childhood in Naples.",
        keywords: ["childhood", "naples"] },
      { id: 45, chapter: "Patience", speaker: 'ROSA',
        agent: "Skim the fat gently. We want silk, not grease.",
        user: "Skim the fat gently. We want silk, not grease.",
        keywords: ["gently", "grease"] },
      { id: 46, chapter: "Patience", speaker: 'ROSA',
        agent: "Cooking is memory. Every single dish remembers someone dear.",
        user: "Cooking is memory. Every single dish remembers someone dear.",
        keywords: ["memory", "remembers"] },
      { id: 47, chapter: "Patience", speaker: 'ROSA',
        agent: "My grandmother stirred this same pot for fifty years.",
        user: "My grandmother stirred this same pot for fifty years.",
        keywords: ["grandmother", "fifty"] },
      { id: 48, chapter: "Patience", speaker: 'ROSA',
        agent: "Great flavor is just patience wearing an apron.",
        user: "Great flavor is just patience wearing an apron.",
        keywords: ["flavor", "apron"] },
      // ---------- Chapter 7: The Plate ----------
      { id: 49, chapter: "The Plate", speaker: 'ROSA',
        agent: "Time to plate. Warm plates keep everything happy.",
        user: "Time to plate. Warm plates keep everything happy.",
        keywords: ["plate", "happy"] },
      { id: 50, chapter: "The Plate", speaker: 'ROSA',
        agent: "Twirl the pasta high. Height makes it look alive.",
        user: "Twirl the pasta high. Height makes it look alive.",
        keywords: ["twirl", "alive"] },
      { id: 51, chapter: "The Plate", speaker: 'ROSA',
        agent: "Spoon the ragu generously. Do not be shy tonight.",
        user: "Spoon the ragu generously. Do not be shy tonight.",
        keywords: ["generously", "tonight"] },
      { id: 52, chapter: "The Plate", speaker: 'ROSA',
        agent: "A snowfall of parmesan over everything. Freshly grated, always.",
        user: "A snowfall of parmesan over everything. Freshly grated, always.",
        keywords: ["snowfall", "parmesan"] },
      { id: 53, chapter: "The Plate", speaker: 'ROSA',
        agent: "Wipe the rim clean. A tidy plate shows respect.",
        user: "Wipe the rim clean. A tidy plate shows respect.",
        keywords: ["wipe", "respect"] },
      { id: 54, chapter: "The Plate", speaker: 'ROSA',
        agent: "Basil leaves on top, like little green flags.",
        user: "Basil leaves on top, like little green flags.",
        keywords: ["basil", "flags"] },
      { id: 55, chapter: "The Plate", speaker: 'ROSA',
        agent: "A thread of olive oil to finish. Liquid gold.",
        user: "A thread of olive oil to finish. Liquid gold.",
        keywords: ["thread", "gold"] },
      { id: 56, chapter: "The Plate", speaker: 'ROSA',
        agent: "Step back and admire it. You made this.",
        user: "Step back and admire it. You made this.",
        keywords: ["admire", "made"] },
      // ---------- Chapter 8: The First Bite ----------
      { id: 57, chapter: "The First Bite", speaker: 'ROSA',
        agent: "Now the best moment. Take up your fork.",
        user: "Now the best moment. Take up your fork.",
        keywords: ["moment", "fork"] },
      { id: 58, chapter: "The First Bite", speaker: 'ROSA',
        agent: "Twirl, lift, and breathe in the steam first.",
        user: "Twirl, lift, and breathe in the steam first.",
        keywords: ["breathe", "steam"] },
      { id: 59, chapter: "The First Bite", speaker: 'ROSA',
        agent: "The first bite should be slow. Savor it.",
        user: "The first bite should be slow. Savor it.",
        keywords: ["savor", "slow"] },
      { id: 60, chapter: "The First Bite", speaker: 'ROSA',
        agent: "Taste the beef melting. Hours of patience in one bite.",
        user: "Taste the beef melting. Hours of patience in one bite.",
        keywords: ["melting", "patience"] },
      { id: 61, chapter: "The First Bite", speaker: 'ROSA',
        agent: "The pasta is silky. The sauce clings like velvet.",
        user: "The pasta is silky. The sauce clings like velvet.",
        keywords: ["silky", "velvet"] },
      { id: 62, chapter: "The First Bite", speaker: 'ROSA',
        agent: "Close your eyes. Let the flavors tell their story.",
        user: "Close your eyes. Let the flavors tell their story.",
        keywords: ["flavors", "story"] },
      { id: 63, chapter: "The First Bite", speaker: 'ROSA',
        agent: "That brightness? A squeeze of lemon at the end.",
        user: "That brightness? A squeeze of lemon at the end.",
        keywords: ["brightness", "lemon"] },
      { id: 64, chapter: "The First Bite", speaker: 'ROSA',
        agent: "Mmm. That sound means you cooked with love.",
        user: "Mmm. That sound means you cooked with love.",
        keywords: ["cooked", "love"] },
      // ---------- Chapter 9: The Secret ----------
      { id: 65, chapter: "The Secret", speaker: 'ROSA',
        agent: "Everyone asks for my secret. Tonight I will share it.",
        user: "Everyone asks for my secret. Tonight I will share it.",
        keywords: ["secret", "share"] },
      { id: 66, chapter: "The Secret", speaker: 'ROSA',
        agent: "My grandmother added a spoonful of honey to the ragu.",
        user: "My grandmother added a spoonful of honey to the ragu.",
        keywords: ["spoonful", "honey"] },
      { id: 67, chapter: "The Secret", speaker: 'ROSA',
        agent: "Just a spoonful. It tames the tomato's sharp edges.",
        user: "Just a spoonful. It tames the tomato's sharp edges.",
        keywords: ["tames", "edges"] },
      { id: 68, chapter: "The Secret", speaker: 'ROSA',
        agent: "She learned it from her mother in the old village.",
        user: "She learned it from her mother in the old village.",
        keywords: ["mother", "village"] },
      { id: 69, chapter: "The Secret", speaker: 'ROSA',
        agent: "Secrets are meant to be shared, or they die hungry.",
        user: "Secrets are meant to be shared, or they die hungry.",
        keywords: ["secrets", "hungry"] },
      { id: 70, chapter: "The Secret", speaker: 'ROSA',
        agent: "Write it down, but cook it from your heart.",
        user: "Write it down, but cook it from your heart.",
        keywords: ["cook", "heart"] },
      { id: 71, chapter: "The Secret", speaker: 'ROSA',
        agent: "Recipes are maps. Your hands must walk the road.",
        user: "Recipes are maps. Your hands must walk the road.",
        keywords: ["recipes", "hands"] },
      { id: 72, chapter: "The Secret", speaker: 'ROSA',
        agent: "Now this secret belongs to you too. Guard it well.",
        user: "Now this secret belongs to you too. Guard it well.",
        keywords: ["belongs", "guard"] },
      // ---------- Chapter 10: Mangia! ----------
      { id: 73, chapter: "Mangia!", speaker: 'ROSA',
        agent: "Mangia! That means eat, and eat with joy.",
        user: "Mangia! That means eat, and eat with joy.",
        keywords: ["mangia", "joy"] },
      { id: 74, chapter: "Mangia!", speaker: 'ROSA',
        agent: "Call your people to the table. Food loves company.",
        user: "Call your people to the table. Food loves company.",
        keywords: ["table", "company"] },
      { id: 75, chapter: "Mangia!", speaker: 'ROSA',
        agent: "Pour the wine generously. Tonight is a celebration.",
        user: "Pour the wine generously. Tonight is a celebration.",
        keywords: ["wine", "celebration"] },
      { id: 76, chapter: "Mangia!", speaker: 'ROSA',
        agent: "There are no strangers here, only future dinner guests.",
        user: "There are no strangers here, only future dinner guests.",
        keywords: ["strangers", "guests"] },
      { id: 77, chapter: "Mangia!", speaker: 'ROSA',
        agent: "Thank you for cooking beside me tonight, my friend.",
        user: "Thank you for cooking beside me tonight, my friend.",
        keywords: ["cooking", "friend"] },
      { id: 78, chapter: "Mangia!", speaker: 'ROSA',
        agent: "Remember: a recipe shared is a love multiplied.",
        user: "Remember: a recipe shared is a love multiplied.",
        keywords: ["shared", "multiplied"] },
      { id: 79, chapter: "Mangia!", speaker: 'ROSA',
        agent: "Until next time, keep your knives sharp and heart soft.",
        user: "Until next time, keep your knives sharp and heart soft.",
        keywords: ["knives", "soft"] },
      { id: 80, chapter: "Mangia!", speaker: 'ROSA',
        agent: "From my kitchen to yours. Buon appetito, always.",
        user: "From my kitchen to yours. Buon appetito, always.",
        keywords: ["kitchen", "appetito"] }
    ]
  };
})();
