/* Speak or Boom — Midnight Alibi (shadow reading) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.shadow_noir = {
    id: 'shadow_noir',
    title: 'Midnight Alibi',
    tagline: 'Shadowing · 听一句，跟读同一句',
    speaker: 'MARLOWE',
    difficulty: 'Intermediate',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: The Client ----------
      { id: 1, chapter: "The Client", speaker: 'MARLOWE',
        agent: "The knock came at midnight. Nobody knocks at midnight innocently.",
        user: "The knock came at midnight. Nobody knocks at midnight innocently.",
        keywords: ["midnight", "knocks"] },
      { id: 2, chapter: "The Client", speaker: 'MARLOWE',
        agent: "She walked in like trouble wearing a red dress.",
        user: "She walked in like trouble wearing a red dress.",
        keywords: ["trouble", "dress"] },
      { id: 3, chapter: "The Client", speaker: 'MARLOWE',
        agent: "Her eyes had seen things no eyes should ever see.",
        user: "Her eyes had seen things no eyes should ever see.",
        keywords: ["eyes", "seen"] },
      { id: 4, chapter: "The Client", speaker: 'MARLOWE',
        agent: "I find people, lady. Sometimes I wish I did not.",
        user: "I find people, lady. Sometimes I wish I did not.",
        keywords: ["people", "wish"] },
      { id: 5, chapter: "The Client", speaker: 'MARLOWE',
        agent: "She slid a photograph across my desk. Face down, of course.",
        user: "She slid a photograph across my desk. Face down, of course.",
        keywords: ["photograph", "desk"] },
      { id: 6, chapter: "The Client", speaker: 'MARLOWE',
        agent: "My husband is missing, she said. Her voice never shook once.",
        user: "My husband is missing, she said. Her voice never shook once.",
        keywords: ["husband", "missing", "shook"] },
      { id: 7, chapter: "The Client", speaker: 'MARLOWE',
        agent: "In my business, everybody lies. The trick is knowing why.",
        user: "In my business, everybody lies. The trick is knowing why.",
        keywords: ["business", "lies", "trick"] },
      { id: 8, chapter: "The Client", speaker: 'MARLOWE',
        agent: "I took the case. I always take the dangerous ones.",
        user: "I took the case. I always take the dangerous ones.",
        keywords: ["case", "dangerous"] },
      // ---------- Chapter 2: The Photograph ----------
      { id: 9, chapter: "The Photograph", speaker: 'MARLOWE',
        agent: "The photograph showed a man I had buried last spring.",
        user: "The photograph showed a man I had buried last spring.",
        keywords: ["photograph", "buried", "spring"] },
      { id: 10, chapter: "The Photograph", speaker: 'MARLOWE',
        agent: "Dead men do not smile. This one was grinning widely.",
        user: "Dead men do not smile. This one was grinning widely.",
        keywords: ["dead", "grinning"] },
      { id: 11, chapter: "The Photograph", speaker: 'MARLOWE',
        agent: "The date stamp read March. He died in cold February.",
        user: "The date stamp read March. He died in cold February.",
        keywords: ["stamp", "february"] },
      { id: 12, chapter: "The Photograph", speaker: 'MARLOWE',
        agent: "Somebody wanted me to see this. Somebody wanted confusion.",
        user: "Somebody wanted me to see this. Somebody wanted confusion.",
        keywords: ["somebody", "confusion"] },
      { id: 13, chapter: "The Photograph", speaker: 'MARLOWE',
        agent: "I held it to the lamp. The shadows told another story.",
        user: "I held it to the lamp. The shadows told another story.",
        keywords: ["lamp", "shadows"] },
      { id: 14, chapter: "The Photograph", speaker: 'MARLOWE',
        agent: "A reflection in the window. A second face, half hidden.",
        user: "A reflection in the window. A second face, half hidden.",
        keywords: ["reflection", "hidden"] },
      { id: 15, chapter: "The Photograph", speaker: 'MARLOWE',
        agent: "The lady in red knew more than she admitted.",
        user: "The lady in red knew more than she admitted.",
        keywords: ["lady", "admitted"] },
      { id: 16, chapter: "The Photograph", speaker: 'MARLOWE',
        agent: "I poured a drink. The case was already getting complicated.",
        user: "I poured a drink. The case was already getting complicated.",
        keywords: ["poured", "complicated"] },
      // ---------- Chapter 3: Rain on Fifth Street ----------
      { id: 17, chapter: "Rain on Fifth Street", speaker: 'MARLOWE',
        agent: "The rain washed the street clean. It could not wash her.",
        user: "The rain washed the street clean. It could not wash her.",
        keywords: ["rain", "street", "wash"] },
      { id: 18, chapter: "Rain on Fifth Street", speaker: 'MARLOWE',
        agent: "I followed her through the neon and the puddles.",
        user: "I followed her through the neon and the puddles.",
        keywords: ["followed", "neon", "puddles"] },
      { id: 19, chapter: "Rain on Fifth Street", speaker: 'MARLOWE',
        agent: "Fifth Street at midnight belongs to ghosts and gamblers.",
        user: "Fifth Street at midnight belongs to ghosts and gamblers.",
        keywords: ["fifth", "ghosts", "gamblers"] },
      { id: 20, chapter: "Rain on Fifth Street", speaker: 'MARLOWE',
        agent: "Her heels clicked a rhythm only the guilty understand.",
        user: "Her heels clicked a rhythm only the guilty understand.",
        keywords: ["heels", "rhythm", "guilty"] },
      { id: 21, chapter: "Rain on Fifth Street", speaker: 'MARLOWE',
        agent: "She stopped twice. She never once looked back.",
        user: "She stopped twice. She never once looked back.",
        keywords: ["stopped", "twice"] },
      { id: 22, chapter: "Rain on Fifth Street", speaker: 'MARLOWE',
        agent: "A black sedan waited at the corner, engine running softly.",
        user: "A black sedan waited at the corner, engine running softly.",
        keywords: ["sedan", "corner", "softly"] },
      { id: 23, chapter: "Rain on Fifth Street", speaker: 'MARLOWE',
        agent: "I memorized the plate. Old habits never truly die.",
        user: "I memorized the plate. Old habits never truly die.",
        keywords: ["memorized", "habits"] },
      { id: 24, chapter: "Rain on Fifth Street", speaker: 'MARLOWE',
        agent: "The car pulled away. So did my last good theory.",
        user: "The car pulled away. So did my last good theory.",
        keywords: ["theory", "pulled"] },
      // ---------- Chapter 4: The Bar ----------
      { id: 25, chapter: "The Bar", speaker: 'MARLOWE',
        agent: "The bar smells of whiskey and broken promises.",
        user: "The bar smells of whiskey and broken promises.",
        keywords: ["whiskey", "promises"] },
      { id: 26, chapter: "The Bar", speaker: 'MARLOWE',
        agent: "The bartender owed me a favor. Tonight I collected.",
        user: "The bartender owed me a favor. Tonight I collected.",
        keywords: ["bartender", "favor"] },
      { id: 27, chapter: "The Bar", speaker: 'MARLOWE',
        agent: "Red dress, I said. She was here an hour ago.",
        user: "Red dress, I said. She was here an hour ago.",
        keywords: ["dress", "hour"] },
      { id: 28, chapter: "The Bar", speaker: 'MARLOWE',
        agent: "He nodded toward the back booth. Somebody was waiting.",
        user: "He nodded toward the back booth. Somebody was waiting.",
        keywords: ["nodded", "booth"] },
      { id: 29, chapter: "The Bar", speaker: 'MARLOWE',
        agent: "A man with a scarred hand dealt cards alone.",
        user: "A man with a scarred hand dealt cards alone.",
        keywords: ["scarred", "cards"] },
      { id: 30, chapter: "The Bar", speaker: 'MARLOWE',
        agent: "I bought him a drink. Information loves good whiskey.",
        user: "I bought him a drink. Information loves good whiskey.",
        keywords: ["information", "whiskey"] },
      { id: 31, chapter: "The Bar", speaker: 'MARLOWE',
        agent: "Her husband owed money to people who collect painfully.",
        user: "Her husband owed money to people who collect painfully.",
        keywords: ["husband", "painfully"] },
      { id: 32, chapter: "The Bar", speaker: 'MARLOWE',
        agent: "The scarred man smiled. Smiles like that cost extra.",
        user: "The scarred man smiled. Smiles like that cost extra.",
        keywords: ["scarred", "smiles", "extra"] },
      // ---------- Chapter 5: The Lie ----------
      { id: 33, chapter: "The Lie", speaker: 'MARLOWE',
        agent: "I confronted her at dawn. Dawn makes liars nervous.",
        user: "I confronted her at dawn. Dawn makes liars nervous.",
        keywords: ["confronted", "dawn", "liars"] },
      { id: 34, chapter: "The Lie", speaker: 'MARLOWE',
        agent: "Your husband is not missing, I said. He is hiding.",
        user: "Your husband is not missing, I said. He is hiding.",
        keywords: ["husband", "hiding"] },
      { id: 35, chapter: "The Lie", speaker: 'MARLOWE',
        agent: "Her red dress suddenly looked like a warning flag.",
        user: "Her red dress suddenly looked like a warning flag.",
        keywords: ["dress", "warning"] },
      { id: 36, chapter: "The Lie", speaker: 'MARLOWE',
        agent: "The photograph was staged. The dead man was alive.",
        user: "The photograph was staged. The dead man was alive.",
        keywords: ["photograph", "staged", "alive"] },
      { id: 37, chapter: "The Lie", speaker: 'MARLOWE',
        agent: "Tears came fast. Too fast for honest grief.",
        user: "Tears came fast. Too fast for honest grief.",
        keywords: ["tears", "grief"] },
      { id: 38, chapter: "The Lie", speaker: 'MARLOWE',
        agent: "You hired me to find him, I said. Or bury him?",
        user: "You hired me to find him, I said. Or bury him?",
        keywords: ["hired", "bury"] },
      { id: 39, chapter: "The Lie", speaker: 'MARLOWE',
        agent: "Silence filled the room like smoke from my cigarette.",
        user: "Silence filled the room like smoke from my cigarette.",
        keywords: ["silence", "smoke"] },
      { id: 40, chapter: "The Lie", speaker: 'MARLOWE',
        agent: "She reached for the photograph. I reached it first.",
        user: "She reached for the photograph. I reached it first.",
        keywords: ["reached", "photograph"] },
      // ---------- Chapter 6: The Partner ----------
      { id: 41, chapter: "The Partner", speaker: 'MARLOWE',
        agent: "Sam was my partner once. Now he sells insurance.",
        user: "Sam was my partner once. Now he sells insurance.",
        keywords: ["partner", "insurance"] },
      { id: 42, chapter: "The Partner", speaker: 'MARLOWE',
        agent: "He warned me over coffee. Walk away, Jack, he said.",
        user: "He warned me over coffee. Walk away, Jack, he said.",
        keywords: ["warned", "coffee"] },
      { id: 43, chapter: "The Partner", speaker: 'MARLOWE',
        agent: "The husband worked for Kaine. That name means trouble.",
        user: "The husband worked for Kaine. That name means trouble.",
        keywords: ["kaine", "trouble"] },
      { id: 44, chapter: "The Partner", speaker: 'MARLOWE',
        agent: "Victor Kaine owns half the docks and all the judges.",
        user: "Victor Kaine owns half the docks and all the judges.",
        keywords: ["victor", "docks", "judges"] },
      { id: 45, chapter: "The Partner", speaker: 'MARLOWE',
        agent: "Sam slid a folder over. Do not open it here.",
        user: "Sam slid a folder over. Do not open it here.",
        keywords: ["folder", "open"] },
      { id: 46, chapter: "The Partner", speaker: 'MARLOWE',
        agent: "Old partners remember the debts. They forget the dangers.",
        user: "Old partners remember the debts. They forget the dangers.",
        keywords: ["partners", "debts", "dangers"] },
      { id: 47, chapter: "The Partner", speaker: 'MARLOWE',
        agent: "I promised to be careful. We both knew I lied.",
        user: "I promised to be careful. We both knew I lied.",
        keywords: ["promised", "careful", "lied"] },
      { id: 48, chapter: "The Partner", speaker: 'MARLOWE',
        agent: "The rain started again. It always rains on bad decisions.",
        user: "The rain started again. It always rains on bad decisions.",
        keywords: ["rain", "decisions"] },
      // ---------- Chapter 7: The Warehouse ----------
      { id: 49, chapter: "The Warehouse", speaker: 'MARLOWE',
        agent: "The warehouse sat by the river, dark and waiting.",
        user: "The warehouse sat by the river, dark and waiting.",
        keywords: ["warehouse", "river"] },
      { id: 50, chapter: "The Warehouse", speaker: 'MARLOWE',
        agent: "A single bulb burned above the rusted metal door.",
        user: "A single bulb burned above the rusted metal door.",
        keywords: ["bulb", "rusted"] },
      { id: 51, chapter: "The Warehouse", speaker: 'MARLOWE',
        agent: "I heard voices inside. One of them was hers.",
        user: "I heard voices inside. One of them was hers.",
        keywords: ["voices", "hers"] },
      { id: 52, chapter: "The Warehouse", speaker: 'MARLOWE',
        agent: "The husband stood beside Kaine, very much alive indeed.",
        user: "The husband stood beside Kaine, very much alive indeed.",
        keywords: ["husband", "kaine", "alive"] },
      { id: 53, chapter: "The Warehouse", speaker: 'MARLOWE',
        agent: "Well, Marlowe, Kaine said. You were never invited.",
        user: "Well, Marlowe, Kaine said. You were never invited.",
        keywords: ["marlowe", "invited"] },
      { id: 54, chapter: "The Warehouse", speaker: 'MARLOWE',
        agent: "Guns make conversations short. I kept mine holstered.",
        user: "Guns make conversations short. I kept mine holstered.",
        keywords: ["guns", "holstered"] },
      { id: 55, chapter: "The Warehouse", speaker: 'MARLOWE',
        agent: "The lady in red would not meet my eyes.",
        user: "The lady in red would not meet my eyes.",
        keywords: ["lady", "eyes"] },
      { id: 56, chapter: "The Warehouse", speaker: 'MARLOWE',
        agent: "Everybody in that room was lying about something important.",
        user: "Everybody in that room was lying about something important.",
        keywords: ["everybody", "lying", "important"] },
      // ---------- Chapter 8: The Confession ----------
      { id: 57, chapter: "The Confession", speaker: 'MARLOWE',
        agent: "She found me later, alone, by the cold river.",
        user: "She found me later, alone, by the cold river.",
        keywords: ["river", "alone"] },
      { id: 58, chapter: "The Confession", speaker: 'MARLOWE',
        agent: "He forced me, she whispered. Kaine owns my brother's debt.",
        user: "He forced me, she whispered. Kaine owns my brother's debt.",
        keywords: ["forced", "whispered", "debt"] },
      { id: 59, chapter: "The Confession", speaker: 'MARLOWE',
        agent: "The photograph was his idea. Lure the detective, trap him.",
        user: "The photograph was his idea. Lure the detective, trap him.",
        keywords: ["photograph", "lure", "trap"] },
      { id: 60, chapter: "The Confession", speaker: 'MARLOWE',
        agent: "Her tears were real this time. I have learned the difference.",
        user: "Her tears were real this time. I have learned the difference.",
        keywords: ["tears", "difference"] },
      { id: 61, chapter: "The Confession", speaker: 'MARLOWE',
        agent: "I wanted to believe her. Wanting is my weakness.",
        user: "I wanted to believe her. Wanting is my weakness.",
        keywords: ["believe", "weakness"] },
      { id: 62, chapter: "The Confession", speaker: 'MARLOWE',
        agent: "Kaine plans to burn the warehouse with the evidence.",
        user: "Kaine plans to burn the warehouse with the evidence.",
        keywords: ["kaine", "burn", "evidence"] },
      { id: 63, chapter: "The Confession", speaker: 'MARLOWE',
        agent: "Midnight tomorrow, she said. After that, nothing remains.",
        user: "Midnight tomorrow, she said. After that, nothing remains.",
        keywords: ["midnight", "remains"] },
      { id: 64, chapter: "The Confession", speaker: 'MARLOWE',
        agent: "I lit a cigarette. The truth always tastes like smoke.",
        user: "I lit a cigarette. The truth always tastes like smoke.",
        keywords: ["cigarette", "truth", "smoke"] },
      // ---------- Chapter 9: The Choice ----------
      { id: 65, chapter: "The Choice", speaker: 'MARLOWE',
        agent: "The evidence could hang Kaine. It could also hang her.",
        user: "The evidence could hang Kaine. It could also hang her.",
        keywords: ["evidence", "hang"] },
      { id: 66, chapter: "The Choice", speaker: 'MARLOWE',
        agent: "The law is blind, Sam said. It is also merciless.",
        user: "The law is blind, Sam said. It is also merciless.",
        keywords: ["blind", "merciless"] },
      { id: 67, chapter: "The Choice", speaker: 'MARLOWE',
        agent: "I held the folder all night, watching the rain.",
        user: "I held the folder all night, watching the rain.",
        keywords: ["folder", "watching"] },
      { id: 68, chapter: "The Choice", speaker: 'MARLOWE',
        agent: "A detective sells the truth. Tonight I considered theft.",
        user: "A detective sells the truth. Tonight I considered theft.",
        keywords: ["detective", "theft"] },
      { id: 69, chapter: "The Choice", speaker: 'MARLOWE',
        agent: "Her brother is innocent. She is only half guilty.",
        user: "Her brother is innocent. She is only half guilty.",
        keywords: ["brother", "innocent", "guilty"] },
      { id: 70, chapter: "The Choice", speaker: 'MARLOWE',
        agent: "Justice wears a blindfold. I decided to peek.",
        user: "Justice wears a blindfold. I decided to peek.",
        keywords: ["justice", "blindfold", "peek"] },
      { id: 71, chapter: "The Choice", speaker: 'MARLOWE',
        agent: "I copied the pages that freed her brother.",
        user: "I copied the pages that freed her brother.",
        keywords: ["copied", "freed"] },
      { id: 72, chapter: "The Choice", speaker: 'MARLOWE',
        agent: "The rest I mailed to the district attorney.",
        user: "The rest I mailed to the district attorney.",
        keywords: ["mailed", "attorney"] },
      // ---------- Chapter 10: Last Cigarette ----------
      { id: 73, chapter: "Last Cigarette", speaker: 'MARLOWE',
        agent: "Kaine fled the city before the sun came up.",
        user: "Kaine fled the city before the sun came up.",
        keywords: ["fled", "city"] },
      { id: 74, chapter: "Last Cigarette", speaker: 'MARLOWE',
        agent: "The lady in red left no forwarding address.",
        user: "The lady in red left no forwarding address.",
        keywords: ["lady", "forwarding", "address"] },
      { id: 75, chapter: "Last Cigarette", speaker: 'MARLOWE',
        agent: "Sam says I am a fool. He is usually right.",
        user: "Sam says I am a fool. He is usually right.",
        keywords: ["fool", "usually"] },
      { id: 76, chapter: "Last Cigarette", speaker: 'MARLOWE',
        agent: "The office is quiet now. The rain has finally stopped.",
        user: "The office is quiet now. The rain has finally stopped.",
        keywords: ["office", "quiet", "stopped"] },
      { id: 77, chapter: "Last Cigarette", speaker: 'MARLOWE',
        agent: "Some cases you solve. Some cases you survive.",
        user: "Some cases you solve. Some cases you survive.",
        keywords: ["cases", "survive"] },
      { id: 78, chapter: "Last Cigarette", speaker: 'MARLOWE',
        agent: "I kept the photograph. A reminder of red dresses.",
        user: "I kept the photograph. A reminder of red dresses.",
        keywords: ["photograph", "reminder"] },
      { id: 79, chapter: "Last Cigarette", speaker: 'MARLOWE',
        agent: "The city forgets quickly. Detectives are paid to remember.",
        user: "The city forgets quickly. Detectives are paid to remember.",
        keywords: ["city", "detectives", "remember"] },
      { id: 80, chapter: "Last Cigarette", speaker: 'MARLOWE',
        agent: "I lit my last cigarette. Tomorrow is another case.",
        user: "I lit my last cigarette. Tomorrow is another case.",
        keywords: ["cigarette", "tomorrow", "case"] }
    ]
  };
})();
