/* Speak or Boom — Fourth Quarter (shadow reading) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.shadow_coach = {
    id: 'shadow_coach',
    title: 'Fourth Quarter',
    tagline: 'Shadowing · 听一句，跟读同一句',
    speaker: 'WEBB',
    difficulty: 'Beginner',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: The Locker Room ----------
      { id: 1, chapter: "The Locker Room", speaker: 'WEBB',
        agent: "Sit down. Look at me. We are not done here.",
        user: "Sit down. Look at me. We are not done here.",
        keywords: ["done"] },
      { id: 2, chapter: "The Locker Room", speaker: 'WEBB',
        agent: "The door is closed. The world can wait outside.",
        user: "The door is closed. The world can wait outside.",
        keywords: ["closed", "wait"] },
      { id: 3, chapter: "The Locker Room", speaker: 'WEBB',
        agent: "I see tired eyes. I also see unfinished business.",
        user: "I see tired eyes. I also see unfinished business.",
        keywords: ["tired", "unfinished"] },
      { id: 4, chapter: "The Locker Room", speaker: 'WEBB',
        agent: "Breathe in deep. Let the noise stay in the hallway.",
        user: "Breathe in deep. Let the noise stay in the hallway.",
        keywords: ["breathe", "hallway"] },
      { id: 5, chapter: "The Locker Room", speaker: 'WEBB',
        agent: "This room built champions. It does not build quitters.",
        user: "This room built champions. It does not build quitters.",
        keywords: ["champions", "quitters"] },
      { id: 6, chapter: "The Locker Room", speaker: 'WEBB',
        agent: "Your jerseys are heavy. That weight is called pride.",
        user: "Your jerseys are heavy. That weight is called pride.",
        keywords: ["jerseys", "pride"] },
      { id: 7, chapter: "The Locker Room", speaker: 'WEBB',
        agent: "I am not here to scold. I am here to wake you.",
        user: "I am not here to scold. I am here to wake you.",
        keywords: ["scold", "wake"] },
      { id: 8, chapter: "The Locker Room", speaker: 'WEBB',
        agent: "Listen close. What I say next changes everything.",
        user: "Listen close. What I say next changes everything.",
        keywords: ["listen", "changes"] },
      // ---------- Chapter 2: The Score ----------
      { id: 9, chapter: "The Score", speaker: 'WEBB',
        agent: "Fourteen points down. The clock does not care.",
        user: "Fourteen points down. The clock does not care.",
        keywords: ["fourteen", "clock"] },
      { id: 10, chapter: "The Score", speaker: 'WEBB',
        agent: "The scoreboard is honest. It never lies to anyone.",
        user: "The scoreboard is honest. It never lies to anyone.",
        keywords: ["scoreboard", "honest"] },
      { id: 11, chapter: "The Score", speaker: 'WEBB',
        agent: "They scored fast. We answered slow. That ends now.",
        user: "They scored fast. We answered slow. That ends now.",
        keywords: ["scored", "answered"] },
      { id: 12, chapter: "The Score", speaker: 'WEBB',
        agent: "Numbers on a wall do not decide who we are.",
        user: "Numbers on a wall do not decide who we are.",
        keywords: ["numbers", "decide"] },
      { id: 13, chapter: "The Score", speaker: 'WEBB',
        agent: "One quarter left. Fifteen minutes to rewrite the story.",
        user: "One quarter left. Fifteen minutes to rewrite the story.",
        keywords: ["quarter", "rewrite"] },
      { id: 14, chapter: "The Score", speaker: 'WEBB',
        agent: "Forget the first half. It is already buried and gone.",
        user: "Forget the first half. It is already buried and gone.",
        keywords: ["forget", "buried"] },
      { id: 15, chapter: "The Score", speaker: 'WEBB',
        agent: "The deficit is real. So is the fire in you.",
        user: "The deficit is real. So is the fire in you.",
        keywords: ["deficit", "fire"] },
      { id: 16, chapter: "The Score", speaker: 'WEBB',
        agent: "Chase the lead. Do not chase the clock, ever.",
        user: "Chase the lead. Do not chase the clock, ever.",
        keywords: ["chase", "lead"] },
      // ---------- Chapter 3: No Excuses ----------
      { id: 17, chapter: "No Excuses", speaker: 'WEBB',
        agent: "No excuses. Excuses never scored a single point.",
        user: "No excuses. Excuses never scored a single point.",
        keywords: ["excuses", "scored"] },
      { id: 18, chapter: "No Excuses", speaker: 'WEBB',
        agent: "The refs missed calls. Champions play through bad calls.",
        user: "The refs missed calls. Champions play through bad calls.",
        keywords: ["refs", "champions"] },
      { id: 19, chapter: "No Excuses", speaker: 'WEBB',
        agent: "Tired is temporary. Quitting is forever. Choose wisely.",
        user: "Tired is temporary. Quitting is forever. Choose wisely.",
        keywords: ["tired", "quitting"] },
      { id: 20, chapter: "No Excuses", speaker: 'WEBB',
        agent: "Your legs hurt. Good. That means they still work.",
        user: "Your legs hurt. Good. That means they still work.",
        keywords: ["legs", "hurt"] },
      { id: 21, chapter: "No Excuses", speaker: 'WEBB',
        agent: "Rain, mud, noise. None of it wears our colors.",
        user: "Rain, mud, noise. None of it wears our colors.",
        keywords: ["rain", "colors"] },
      { id: 22, chapter: "No Excuses", speaker: 'WEBB',
        agent: "Blame the field, blame the wind, blame the night.",
        user: "Blame the field, blame the wind, blame the night.",
        keywords: ["blame", "field"] },
      { id: 23, chapter: "No Excuses", speaker: 'WEBB',
        agent: "Winners adjust. Losers explain. Which one are you?",
        user: "Winners adjust. Losers explain. Which one are you?",
        keywords: ["winners", "losers"] },
      { id: 24, chapter: "No Excuses", speaker: 'WEBB',
        agent: "Pain is just weakness leaving. Let it leave loudly.",
        user: "Pain is just weakness leaving. Let it leave loudly.",
        keywords: ["pain", "weakness"] },
      // ---------- Chapter 4: Remember Why ----------
      { id: 25, chapter: "Remember Why", speaker: 'WEBB',
        agent: "Remember the kid who dreamed of this exact moment.",
        user: "Remember the kid who dreamed of this exact moment.",
        keywords: ["remember", "dreamed"] },
      { id: 26, chapter: "Remember Why", speaker: 'WEBB',
        agent: "Your mother drove you to practice in the snow.",
        user: "Your mother drove you to practice in the snow.",
        keywords: ["mother", "practice"] },
      { id: 27, chapter: "Remember Why", speaker: 'WEBB',
        agent: "Your father taught you to never drop the ball.",
        user: "Your father taught you to never drop the ball.",
        keywords: ["father", "taught"] },
      { id: 28, chapter: "Remember Why", speaker: 'WEBB',
        agent: "Play for the name on the front, not the back.",
        user: "Play for the name on the front, not the back.",
        keywords: ["front", "back"] },
      { id: 29, chapter: "Remember Why", speaker: 'WEBB',
        agent: "Some kid in the stands wears your number tonight.",
        user: "Some kid in the stands wears your number tonight.",
        keywords: ["stands", "number"] },
      { id: 30, chapter: "Remember Why", speaker: 'WEBB',
        agent: "Make him proud. Make every kid out there proud.",
        user: "Make him proud. Make every kid out there proud.",
        keywords: ["proud"] },
      { id: 31, chapter: "Remember Why", speaker: 'WEBB',
        agent: "This game will end. The memory of it will not.",
        user: "This game will end. The memory of it will not.",
        keywords: ["memory"] },
      { id: 32, chapter: "Remember Why", speaker: 'WEBB',
        agent: "Years from now, you will thank this very moment.",
        user: "Years from now, you will thank this very moment.",
        keywords: ["years", "thank"] },
      // ---------- Chapter 5: One Play ----------
      { id: 33, chapter: "One Play", speaker: 'WEBB',
        agent: "Forget the score. Win the very next play.",
        user: "Forget the score. Win the very next play.",
        keywords: ["forget", "next"] },
      { id: 34, chapter: "One Play", speaker: 'WEBB',
        agent: "One snap. One block. One tackle. One heartbeat.",
        user: "One snap. One block. One tackle. One heartbeat.",
        keywords: ["snap", "tackle"] },
      { id: 35, chapter: "One Play", speaker: 'WEBB',
        agent: "Shrink the game. Make it small enough to own.",
        user: "Shrink the game. Make it small enough to own.",
        keywords: ["shrink", "own"] },
      { id: 36, chapter: "One Play", speaker: 'WEBB',
        agent: "Eyes on the ball. Nothing else exists right now.",
        user: "Eyes on the ball. Nothing else exists right now.",
        keywords: ["eyes", "exists"] },
      { id: 37, chapter: "One Play", speaker: 'WEBB',
        agent: "Do your job. Just your job. Nothing more, nothing less.",
        user: "Do your job. Just your job. Nothing more, nothing less.",
        keywords: ["job"] },
      { id: 38, chapter: "One Play", speaker: 'WEBB',
        agent: "The next play is the only play that matters.",
        user: "The next play is the only play that matters.",
        keywords: ["next", "matters"] },
      { id: 39, chapter: "One Play", speaker: 'WEBB',
        agent: "Slow the mind. Speed the feet. Trust the plan.",
        user: "Slow the mind. Speed the feet. Trust the plan.",
        keywords: ["slow", "speed"] },
      { id: 40, chapter: "One Play", speaker: 'WEBB',
        agent: "Stack small wins. They become avalanches by midnight.",
        user: "Stack small wins. They become avalanches by midnight.",
        keywords: ["stack", "avalanches"] },
      // ---------- Chapter 6: Trust ----------
      { id: 41, chapter: "Trust", speaker: 'WEBB',
        agent: "Look left. Look right. Those are your brothers.",
        user: "Look left. Look right. Those are your brothers.",
        keywords: ["left", "brothers"] },
      { id: 42, chapter: "Trust", speaker: 'WEBB',
        agent: "No hero ball. We win as eleven, not one.",
        user: "No hero ball. We win as eleven, not one.",
        keywords: ["hero", "eleven"] },
      { id: 43, chapter: "Trust", speaker: 'WEBB',
        agent: "Trust the man beside you with your whole heart.",
        user: "Trust the man beside you with your whole heart.",
        keywords: ["trust", "beside"] },
      { id: 44, chapter: "Trust", speaker: 'WEBB',
        agent: "He will block for you. You will run for him.",
        user: "He will block for you. You will run for him.",
        keywords: ["block", "run"] },
      { id: 45, chapter: "Trust", speaker: 'WEBB',
        agent: "Call it loud. Then back it up louder.",
        user: "Call it loud. Then back it up louder.",
        keywords: ["call", "louder"] },
      { id: 46, chapter: "Trust", speaker: 'WEBB',
        agent: "Pick each other up. Every single time, no exceptions.",
        user: "Pick each other up. Every single time, no exceptions.",
        keywords: ["pick", "exceptions"] },
      { id: 47, chapter: "Trust", speaker: 'WEBB',
        agent: "One heartbeat. One breath. One team. One mission.",
        user: "One heartbeat. One breath. One team. One mission.",
        keywords: ["heartbeat", "mission"] },
      { id: 48, chapter: "Trust", speaker: 'WEBB',
        agent: "Alone we are loud. Together we are thunder.",
        user: "Alone we are loud. Together we are thunder.",
        keywords: ["alone", "thunder"] },
      // ---------- Chapter 7: The Stand ----------
      { id: 49, chapter: "The Stand", speaker: 'WEBB',
        agent: "Stand up. Champions are not built sitting down.",
        user: "Stand up. Champions are not built sitting down.",
        keywords: ["stand", "champions"] },
      { id: 50, chapter: "The Stand", speaker: 'WEBB',
        agent: "On your feet. Let them hear you coming.",
        user: "On your feet. Let them hear you coming.",
        keywords: ["feet", "hear"] },
      { id: 51, chapter: "The Stand", speaker: 'WEBB',
        agent: "Rise like the fourth quarter owes you money.",
        user: "Rise like the fourth quarter owes you money.",
        keywords: ["rise", "owes"] },
      { id: 52, chapter: "The Stand", speaker: 'WEBB',
        agent: "Shake off the doubt. Wear the confidence instead.",
        user: "Shake off the doubt. Wear the confidence instead.",
        keywords: ["shake", "confidence"] },
      { id: 53, chapter: "The Stand", speaker: 'WEBB',
        agent: "Your moment is knocking. Answer it with everything.",
        user: "Your moment is knocking. Answer it with everything.",
        keywords: ["knocking", "everything"] },
      { id: 54, chapter: "The Stand", speaker: 'WEBB',
        agent: "Stand tall. The cameras love a comeback story.",
        user: "Stand tall. The cameras love a comeback story.",
        keywords: ["tall", "comeback"] },
      { id: 55, chapter: "The Stand", speaker: 'WEBB',
        agent: "Dig deeper than you ever thought you could.",
        user: "Dig deeper than you ever thought you could.",
        keywords: ["dig", "deeper"] },
      { id: 56, chapter: "The Stand", speaker: 'WEBB',
        agent: "Leave the doubt in this room. Take the fire out.",
        user: "Leave the doubt in this room. Take the fire out.",
        keywords: ["leave", "fire"] },
      // ---------- Chapter 8: The Roar ----------
      { id: 57, chapter: "The Roar", speaker: 'WEBB',
        agent: "Let me hear it. Let the whole stadium hear it.",
        user: "Let me hear it. Let the whole stadium hear it.",
        keywords: ["hear", "stadium"] },
      { id: 58, chapter: "The Roar", speaker: 'WEBB',
        agent: "Roar like the roof is about to come down.",
        user: "Roar like the roof is about to come down.",
        keywords: ["roar", "roof"] },
      { id: 59, chapter: "The Roar", speaker: 'WEBB',
        agent: "Scream until your throat reminds you you are alive.",
        user: "Scream until your throat reminds you you are alive.",
        keywords: ["scream", "alive"] },
      { id: 60, chapter: "The Roar", speaker: 'WEBB',
        agent: "Noise is our twelfth player. Wake him up now.",
        user: "Noise is our twelfth player. Wake him up now.",
        keywords: ["noise", "twelfth"] },
      { id: 61, chapter: "The Roar", speaker: 'WEBB',
        agent: "Hit somebody. Hit them clean. Hit them again.",
        user: "Hit somebody. Hit them clean. Hit them again.",
        keywords: ["hit", "clean"] },
      { id: 62, chapter: "The Roar", speaker: 'WEBB',
        agent: "Bring the thunder. Bring the lightning. Bring everything.",
        user: "Bring the thunder. Bring the lightning. Bring everything.",
        keywords: ["thunder", "lightning"] },
      { id: 63, chapter: "The Roar", speaker: 'WEBB',
        agent: "Make their quarterback hear footsteps all night long.",
        user: "Make their quarterback hear footsteps all night long.",
        keywords: ["quarterback", "footsteps"] },
      { id: 64, chapter: "The Roar", speaker: 'WEBB',
        agent: "Unleash it. Everything you saved is spent tonight.",
        user: "Unleash it. Everything you saved is spent tonight.",
        keywords: ["unleash", "spent"] },
      // ---------- Chapter 9: Back Out ----------
      { id: 65, chapter: "Back Out", speaker: 'WEBB',
        agent: "Helmets on. The tunnel is calling your names.",
        user: "Helmets on. The tunnel is calling your names.",
        keywords: ["helmets", "tunnel"] },
      { id: 66, chapter: "Back Out", speaker: 'WEBB',
        agent: "Run out like the field owes you an apology.",
        user: "Run out like the field owes you an apology.",
        keywords: ["run", "apology"] },
      { id: 67, chapter: "Back Out", speaker: 'WEBB',
        agent: "The crowd is waiting. Do not keep them waiting.",
        user: "The crowd is waiting. Do not keep them waiting.",
        keywords: ["crowd", "waiting"] },
      { id: 68, chapter: "Back Out", speaker: 'WEBB',
        agent: "Walk tall through that tunnel. Run tall onto that field.",
        user: "Walk tall through that tunnel. Run tall onto that field.",
        keywords: ["tunnel", "field"] },
      { id: 69, chapter: "Back Out", speaker: 'WEBB',
        agent: "First snap sets the tone. Make it violent and clean.",
        user: "First snap sets the tone. Make it violent and clean.",
        keywords: ["snap", "violent"] },
      { id: 70, chapter: "Back Out", speaker: 'WEBB',
        agent: "They think the game is over. Prove them wrong.",
        user: "They think the game is over. Prove them wrong.",
        keywords: ["think", "prove"] },
      { id: 71, chapter: "Back Out", speaker: 'WEBB',
        agent: "Take the field. Take the momentum. Take it all.",
        user: "Take the field. Take the momentum. Take it all.",
        keywords: ["momentum"] },
      { id: 72, chapter: "Back Out", speaker: 'WEBB',
        agent: "Now go. The fourth quarter belongs to the brave.",
        user: "Now go. The fourth quarter belongs to the brave.",
        keywords: ["quarter", "brave"] },
      // ---------- Chapter 10: The Whistle ----------
      { id: 73, chapter: "The Whistle", speaker: 'WEBB',
        agent: "Play until the whistle. Not a second before it.",
        user: "Play until the whistle. Not a second before it.",
        keywords: ["whistle", "second"] },
      { id: 74, chapter: "The Whistle", speaker: 'WEBB',
        agent: "Sixty minutes of war. Leave nothing in the tank.",
        user: "Sixty minutes of war. Leave nothing in the tank.",
        keywords: ["sixty", "tank"] },
      { id: 75, chapter: "The Whistle", speaker: 'WEBB',
        agent: "Nobody remembers the team that almost won. Finish it.",
        user: "Nobody remembers the team that almost won. Finish it.",
        keywords: ["remembers", "finish"] },
      { id: 76, chapter: "The Whistle", speaker: 'WEBB',
        agent: "When the whistle blows, you will know you gave all.",
        user: "When the whistle blows, you will know you gave all.",
        keywords: ["blows", "gave"] },
      { id: 77, chapter: "The Whistle", speaker: 'WEBB',
        agent: "Champions are made when the lights burn brightest.",
        user: "Champions are made when the lights burn brightest.",
        keywords: ["champions", "brightest"] },
      { id: 78, chapter: "The Whistle", speaker: 'WEBB',
        agent: "One team. One dream. One unforgettable fourth quarter.",
        user: "One team. One dream. One unforgettable fourth quarter.",
        keywords: ["unforgettable", "quarter"] },
      { id: 79, chapter: "The Whistle", speaker: 'WEBB',
        agent: "Now bring it in. Hands together. Family on three.",
        user: "Now bring it in. Hands together. Family on three.",
        keywords: ["hands", "family"] },
      { id: 80, chapter: "The Whistle", speaker: 'WEBB',
        agent: "Family on three. One, two, three. Family!",
        user: "Family on three. One, two, three. Family!",
        keywords: ["family"] },
    ]
  };
})();
