/* Speak or Boom — Coffee Shop v2 (rich, narrative) */
(function () {
  'use strict';
  window.SPEAK_OR_BOOM_SCENARIOS = window.SPEAK_OR_BOOM_SCENARIOS || {};
  window.SPEAK_OR_BOOM_SCENARIOS.coffee = {
    id: 'coffee',
    title: 'Coffee Shop',
    tagline: 'Order Like a Regular',
    speaker: 'BARISTA',
    difficulty: 'Intermediate',
    ordered: true,
    rounds: [
      // ---------- Chapter 1: Walking In ----------
      { id: 1, chapter: 'Walking In', speaker: 'SAM',
        agent: 'Welcome to The Daily Grind! You look like you need something strong today.',
        user: 'You read my mind. It has been one of those endless Monday mornings.',
        keywords: ['endless', 'mornings'] },
      { id: 2, chapter: 'Walking In', speaker: 'SAM',
        agent: 'I am Sam, by the way. I just started here last week and still learning names.',
        user: 'Nice to meet you, Sam. I am Alex, a regular who practically lives here.',
        keywords: ['regular', 'practically'] },
      { id: 3, chapter: 'Walking In', speaker: 'SAM',
        agent: 'A regular! Then you must have a usual order that I should memorize quickly.',
        user: 'I do, but I am feeling adventurous today. Surprise me with something new.',
        keywords: ['adventurous', 'surprise'] },
      { id: 4, chapter: 'Walking In', speaker: 'SAM',
        agent: 'Adventurous on a Monday? That is brave. Any flavors you absolutely cannot stand?',
        user: 'I cannot stand anything too sweet. Bitter and bold is more my style.',
        keywords: ['bitter', 'bold'] },
      { id: 5, chapter: 'Walking In', speaker: 'SAM',
        agent: 'Bitter and bold, got it. Are you in a hurry, or can you savor it here?',
        user: 'I have about twenty minutes before my meeting across the street starts.',
        keywords: ['twenty', 'meeting'] },
      { id: 6, chapter: 'Walking In', speaker: 'SAM',
        agent: 'Twenty minutes is perfect. I will make you something worth slowing down for.',
        user: 'I like your confidence. Most baristas just rush through the morning crowd.',
        keywords: ['confidence', 'crowd'] },
      { id: 7, chapter: 'Walking In', speaker: 'SAM',
        agent: 'Rushing ruins the crema. Good coffee deserves at least a little patience and care.',
        user: 'You sound like a true coffee lover, not just someone working for tips.',
        keywords: ['someone', 'working'] },
      { id: 8, chapter: 'Walking In', speaker: 'SAM',
        agent: 'Guilty as charged. So, what direction should we take this adventure today?',
        user: 'Let us start with your signature drink, whatever you are most proud of.',
        keywords: ['signature', 'proud'] },
      // ---------- Chapter 2: Customizing ----------
      { id: 9, chapter: 'Customizing', speaker: 'SAM',
        agent: 'My signature is a honey oat milk latte with a double shot of our darkest roast.',
        user: 'That sounds intriguing, though I usually skip sweeteners in my coffee entirely.',
        keywords: ['intriguing', 'sweeteners'] },
      { id: 10, chapter: 'Customizing', speaker: 'SAM',
        agent: 'The honey is subtle, I promise. It just smooths out the bitterness without overpowering it.',
        user: 'Alright, I trust your expertise. But go easy on the honey, please.',
        keywords: ['expertise', 'alright'] },
      { id: 11, chapter: 'Customizing', speaker: 'SAM',
        agent: 'Easy on the honey, noted. What size are we thinking for this masterpiece?',
        user: 'Medium is perfect. Large just makes me jittery for the rest of the afternoon.',
        keywords: ['jittery', 'afternoon'] },
      { id: 12, chapter: 'Customizing', speaker: 'SAM',
        agent: 'Medium it is. Hot or iced? Though on a chilly morning like this, I recommend hot.',
        user: 'Hot, definitely. I need something warm to wrap my hands around right now.',
        keywords: ['definitely', 'something'] },
      { id: 13, chapter: 'Customizing', speaker: 'SAM',
        agent: 'Hot medium honey oat latte, light on the honey. Anything else to customize?',
        user: 'Could you add an extra shot? I need all the help I can get.',
        keywords: ['extra', 'shot'] },
      { id: 14, chapter: 'Customizing', speaker: 'SAM',
        agent: 'Triple shot coming right up. You must really need to conquer this Monday.',
        user: 'Conquer is the right word. My inbox is already overflowing with urgent emails.',
        keywords: ['conquer', 'overflowing'] },
      { id: 15, chapter: 'Customizing', speaker: 'SAM',
        agent: 'Urgent emails on a Monday should be illegal. Consider this latte your armor.',
        user: 'I like that philosophy. Coffee as armor against the chaos of modern work.',
        keywords: ['armor', 'philosophy'] },
      { id: 16, chapter: 'Customizing', speaker: 'SAM',
        agent: 'Exactly! Now, should I write your name on the cup, or prefer to stay mysterious?',
        user: 'Write Alex. Though everyone here already knows my ridiculously complicated order.',
        keywords: ['ridiculously', 'complicated'] },
      // ---------- Chapter 3: Changing the Order ----------
      { id: 17, chapter: 'Changing the Order', speaker: 'SAM',
        agent: 'Wait, before I start — are you absolutely sure about the oat milk today?',
        user: 'Hmm, now you have me second-guessing. What would you recommend instead?',
        keywords: ['secondguessing', 'recommend'] },
      { id: 18, chapter: 'Changing the Order', speaker: 'SAM',
        agent: 'Our almond milk is fantastic, but it can overpower delicate flavors if you are not careful.',
        user: 'I appreciate the honesty. Let us stick with oat milk, my original instinct.',
        keywords: ['appreciate', 'instinct'] },
      { id: 19, chapter: 'Changing the Order', speaker: 'SAM',
        agent: 'Good call. Oat milk is creamier and lets the espresso shine through beautifully.',
        user: 'I think I will skip the honey after all. Keep it pure.',
        keywords: ['after', 'honey'] },
      { id: 20, chapter: 'Changing the Order', speaker: 'SAM',
        agent: 'No honey at all? Bold move! A purist after my own heart, I respect that.',
        user: 'I have decided to embrace the bitterness. It matches my Monday mood perfectly.',
        keywords: ['bitterness', 'perfectly'] },
      { id: 21, chapter: 'Changing the Order', speaker: 'SAM',
        agent: 'Embracing bitterness on a Monday is practically a survival strategy around here.',
        user: 'It really is. Though I hope the rest of my week turns out sweeter.',
        keywords: ['sweeter', 'though'] },
      { id: 22, chapter: 'Changing the Order', speaker: 'SAM',
        agent: 'It will. And if not, you know exactly where to find your bitter refuge.',
        user: 'This place has saved many of my mornings. I am genuinely grateful for it.',
        keywords: ['genuinely', 'grateful'] },
      { id: 23, chapter: 'Changing the Order', speaker: 'SAM',
        agent: 'That means a lot to hear. So final order: triple shot oat milk latte, no honey?',
        user: 'Final answer, yes. Hot, medium, triple shot, oat milk, absolutely no honey.',
        keywords: ['final', 'absolutely'] },
      { id: 24, chapter: 'Changing the Order', speaker: 'SAM',
        agent: 'Locked in! I admire someone who knows what they want and is not afraid to change their mind.',
        user: 'Changing my mind is my specialty. Committing to decisions is the hard part.',
        keywords: ['specialty', 'committing'] },
      // ---------- Chapter 4: Paying ----------
      { id: 25, chapter: 'Paying', speaker: 'SAM',
        agent: 'That will be six fifty. Do you have our loyalty card, or should I get you one?',
        user: 'I have one somewhere in my wallet. It is probably buried under old receipts.',
        keywords: ['somewhere', 'probably'] },
      { id: 26, chapter: 'Paying', speaker: 'SAM',
        agent: 'Buried under receipts is basically a rite of passage for all our regulars here.',
        user: 'Found it! It is worn out, but it still scans after all these years.',
        keywords: ['after', 'found'] },
      { id: 27, chapter: 'Paying', speaker: 'SAM',
        agent: 'Wow, this card is practically vintage! You must have been coming here for ages.',
        user: 'Three years and counting. This place has been my second office for ages.',
        keywords: ['counting', 'office'] },
      { id: 28, chapter: 'Paying', speaker: 'SAM',
        agent: 'Three years of loyalty deserves a reward. This one is on the house, Alex.',
        user: 'Are you serious? You do not have to do that on your second week.',
        keywords: ['serious', 'second'] },
      { id: 29, chapter: 'Paying', speaker: 'SAM',
        agent: 'I insist. Consider it a welcome gift from the new barista to a valued regular.',
        user: 'That is incredibly kind. I will definitely be tipping extra generously today.',
        keywords: ['incredibly', 'generously'] },
      { id: 30, chapter: 'Paying', speaker: 'SAM',
        agent: 'No need for extra tips, honestly. Just keep coming back and bringing good energy.',
        user: 'Deal. Though I should warn you, my Monday energy is not always this charming.',
        keywords: ['energy', 'charming'] },
      // ---------- Chapter 5: Waiting ----------
      { id: 31, chapter: 'Waiting', speaker: 'SAM',
        agent: 'Your drink will be ready in about three minutes. Feel free to watch me work my magic.',
        user: 'I love watching the process. There is something meditative about making coffee properly.',
        keywords: ['meditative', 'properly'] },
      { id: 32, chapter: 'Waiting', speaker: 'SAM',
        agent: 'It really is meditative. The grinding, the tamping, the slow extraction — it demands focus.',
        user: 'I never thought about it that way. I usually just wait impatiently for caffeine.',
        keywords: ['impatiently', 'caffeine'] },
      { id: 33, chapter: 'Waiting', speaker: 'SAM',
        agent: 'Most people do. But slowing down to appreciate the craft makes it taste even better.',
        user: 'You are making me rethink my entire rushed relationship with morning coffee.',
        keywords: ['relationship', 'morning'] },
      { id: 34, chapter: 'Waiting', speaker: 'SAM',
        agent: 'That is the goal! Coffee is not just fuel; it is a small daily ritual worth savoring.',
        user: 'A ritual worth savoring — I will remember that phrase for my next meeting.',
        keywords: ['ritual', 'savoring'] },
      { id: 35, chapter: 'Waiting', speaker: 'SAM',
        agent: 'Use it wisely. Now watch this — I am about to pour the perfect rosetta on top.',
        user: 'A rosetta? You are really showing off for the new regular, are you not?',
        keywords: ['rosetta', 'showing'] },
      { id: 36, chapter: 'Waiting', speaker: 'SAM',
        agent: 'Maybe a little. But you deserve beautiful latte art after that chaotic Monday morning.',
        user: 'Flattery and latte art — you are definitely going to survive in this business.',
        keywords: ['flattery', 'survive'] },
      { id: 37, chapter: 'Waiting', speaker: 'SAM',
        agent: 'That is the plan. And... done! Behold, your triple shot oat milk masterpiece.',
        user: 'It looks almost too beautiful to drink. Almost being the key word here.',
        keywords: ['beautiful', 'almost'] },
      { id: 38, chapter: 'Waiting', speaker: 'SAM',
        agent: 'Drink it while it is hot! The flavors are at their peak in the first few minutes.',
        user: 'One sip... wow. The bitterness is bold but incredibly smooth going down.',
        keywords: ['bitterness', 'incredibly'] },
      // ---------- Chapter 6: Finding a Seat ----------
      { id: 39, chapter: 'Finding a Seat', speaker: 'SAM',
        agent: 'Glad you love it! The corner table by the window just opened up, if you want it.',
        user: 'That is my favorite spot! I can people-watch while pretending to check emails.',
        keywords: ['peoplewatch', 'pretending'] },
      { id: 40, chapter: 'Finding a Seat', speaker: 'SAM',
        agent: 'People-watching is an underrated art form. This window has the best view in the neighborhood.',
        user: 'It really does. I have witnessed countless fascinating street dramas from that chair.',
        keywords: ['fascinating', 'countless'] },
      { id: 41, chapter: 'Finding a Seat', speaker: 'SAM',
        agent: 'Oh, I bet! What is the most memorable thing you have seen from that window?',
        user: 'Once I saw a proposal happen right across the street. She said yes, thankfully.',
        keywords: ['proposal', 'thankfully'] },
      { id: 42, chapter: 'Finding a Seat', speaker: 'SAM',
        agent: 'Thankfully indeed! That would have been awkward to witness over a morning latte.',
        user: 'Extremely awkward. I pretended to be deeply absorbed in my laptop screen.',
        keywords: ['awkward', 'absorbed'] },
      { id: 43, chapter: 'Finding a Seat', speaker: 'SAM',
        agent: 'The universal signal for "I am definitely not watching your personal moment unfold."',
        user: 'Exactly! Though I was absolutely watching through the reflection in my screen.',
        keywords: ['reflection', 'absolutely'] },
      { id: 44, chapter: 'Finding a Seat', speaker: 'SAM',
        agent: 'We have all been there. Enjoy your seat, and let me know if you need anything else.',
        user: 'Will do. Though I might just stay here all day avoiding my responsibilities.',
        keywords: ['responsibilities', 'avoiding'] },
      { id: 45, chapter: 'Finding a Seat', speaker: 'SAM',
        agent: 'Avoiding responsibilities is a time-honored coffee shop tradition. No judgment here.',
        user: 'Good to know. This place has always been my favorite productive procrastination spot.',
        keywords: ['procrastination', 'productive'] },
      { id: 46, chapter: 'Finding a Seat', speaker: 'SAM',
        agent: 'Productive procrastination — I love that contradiction. It describes half our customers perfectly.',
        user: 'We come here to feel productive while expertly avoiding actual work. It is genius.',
        keywords: ['productive', 'avoiding'] },
      // ---------- Chapter 7: Small Talk ----------
      { id: 47, chapter: 'Small Talk', speaker: 'SAM',
        agent: 'So Alex, what do you do when you are not expertly avoiding work in coffee shops?',
        user: 'I am a graphic designer. I stare at screens and argue about fonts.',
        keywords: ['graphic', 'fonts'] },
      { id: 48, chapter: 'Small Talk', speaker: 'SAM',
        agent: 'Arguing about fonts sounds oddly intense. Are you team serif or team sans-serif?',
        user: 'Sans-serif all the way. Serifs feel like they belong in old history textbooks.',
        keywords: ['sansserif', 'textbooks'] },
      { id: 49, chapter: 'Small Talk', speaker: 'SAM',
        agent: 'Bold statement! I will try not to hold your questionable taste against you.',
        user: 'Questionable? My taste is impeccable. Lovely latte art, but typography is my domain.',
        keywords: ['impeccable', 'typography'] },
      { id: 50, chapter: 'Small Talk', speaker: 'SAM',
        agent: 'Fair enough, I will stay in my lane. What brought you to graphic design originally?',
        user: 'I have always loved visual storytelling. A single image can communicate entire narratives.',
        keywords: ['storytelling', 'narratives'] },
      { id: 51, chapter: 'Small Talk', speaker: 'SAM',
        agent: 'That is beautiful. Kind of like latte art — fleeting, but it tells a story.',
        user: 'I never made that connection before, but you are absolutely right about it.',
        keywords: ['absolutely', 'connection'] },
      { id: 52, chapter: 'Small Talk', speaker: 'SAM',
        agent: 'What about you — what made you trade a stable career for the chaos of coffee?',
        user: 'Wait, I asked first! But I am curious too. What is your story, Sam?',
        keywords: ['curious', 'asked'] },
      { id: 53, chapter: 'Small Talk', speaker: 'SAM',
        agent: 'I was an accountant for five years. Then I realized spreadsheets were slowly draining my soul.',
        user: 'From spreadsheets to espresso shots — that is quite a dramatic career pivot.',
        keywords: ['spreadsheets', 'dramatic'] },
      { id: 54, chapter: 'Small Talk', speaker: 'SAM',
        agent: 'Dramatic but necessary. I would rather create joy in a cup than balance lifeless numbers.',
        user: 'I completely understand. Creative fulfillment beats a bigger paycheck any day.',
        keywords: ['fulfillment', 'paycheck'] },
      // ---------- Chapter 8: Drink Made Incorrectly ----------
      { id: 55, chapter: 'Drink Made Incorrectly', speaker: 'SAM',
        agent: 'Oh no, I just realized — I think I accidentally used whole milk instead of oat milk!',
        user: 'Really? I did not even notice. It tasted fantastic, to be honest with you.',
        keywords: ['fantastic', 'honest'] },
      { id: 56, chapter: 'Drink Made Incorrectly', speaker: 'SAM',
        agent: 'You are too kind, but I insist on remaking it. A promise is a promise, after all.',
        user: 'That is very professional of you, though I genuinely enjoyed every single sip.',
        keywords: ['professional', 'genuinely'] },
      { id: 57, chapter: 'Drink Made Incorrectly', speaker: 'SAM',
        agent: 'I appreciate that, but my integrity as a barista demands a perfect remake right now.',
        user: 'Your integrity is admirable. Most places would just hope the customer never notices.',
        keywords: ['integrity', 'admirable'] },
      { id: 58, chapter: 'Drink Made Incorrectly', speaker: 'SAM',
        agent: 'Noticing is the whole point of craft. Give me two minutes to make it right.',
        user: 'Take your time. I am in no rush, and the people-watching is excellent today.',
        keywords: ['peoplewatching', 'excellent'] },
      { id: 59, chapter: 'Drink Made Incorrectly', speaker: 'SAM',
        agent: 'And... here is the corrected version. Triple shot, oat milk, no honey, extra care.',
        user: 'The rosetta is even more beautiful this time. You are definitely showing off now.',
        keywords: ['definitely', 'beautiful'] },
      { id: 60, chapter: 'Drink Made Incorrectly', speaker: 'SAM',
        agent: 'Guilty again! But seriously, thank you for being so gracious about my mistake.',
        user: 'Mistakes happen in your second week. It is how you handle them that matters.',
        keywords: ['mistakes', 'matters'] },
      // ---------- Chapter 9: Ordering Another Drink ----------
      { id: 61, chapter: 'Ordering Another Drink', speaker: 'SAM',
        agent: 'You know what? That remake was so good, I think I deserve a second cup myself.',
        user: 'I was just thinking the same thing. What would you recommend for round two?',
        keywords: ['recommend', 'round'] },
      { id: 62, chapter: 'Ordering Another Drink', speaker: 'SAM',
        agent: 'For round two, I would suggest something completely different — our lavender honey cappuccino.',
        user: 'Lavender in coffee? That sounds either brilliant or absolutely terrible, no middle ground.',
        keywords: ['lavender', 'brilliant'] },
      { id: 63, chapter: 'Ordering Another Drink', speaker: 'SAM',
        agent: 'It is surprisingly brilliant, I promise. The floral notes complement the espresso beautifully.',
        user: 'You earned my trust after the oat milk incident. I will take a chance.',
        keywords: ['incident', 'chance'] },
      { id: 64, chapter: 'Ordering Another Drink', speaker: 'SAM',
        agent: 'That is the spirit! Adventurous Alex is back. Small size, since it is quite rich?',
        user: 'Small is perfect. I still have that meeting, and I should probably stay focused.',
        keywords: ['probably', 'focused'] },
      { id: 65, chapter: 'Ordering Another Drink', speaker: 'SAM',
        agent: 'Smart thinking. Though I suspect the lavender might make you too relaxed for urgent emails.',
        user: 'Relaxed is good. Maybe I will handle those emails with newfound calm and wisdom.',
        keywords: ['newfound', 'relaxed'] },
      { id: 66, chapter: 'Ordering Another Drink', speaker: 'SAM',
        agent: 'Newfound calm and wisdom, courtesy of The Daily Grind. That should be our new slogan.',
        user: 'It is definitely better than "Coffee as armor." Though I liked that one too.',
        keywords: ['definitely', 'better'] },
      { id: 67, chapter: 'Ordering Another Drink', speaker: 'SAM',
        agent: 'We are on a roll with slogans today. Here is your lavender cappuccino, made with love.',
        user: 'The aroma is incredible. Floral and warm, like a garden in spring.',
        keywords: ['aroma', 'incredible'] },
      { id: 68, chapter: 'Ordering Another Drink', speaker: 'SAM',
        agent: 'A garden in spring, exactly! Take a sip and tell me if I have converted you.',
        user: 'One sip... okay, I am converted. This is unexpectedly sophisticated and delightful.',
        keywords: ['converted', 'sophisticated'] },
      // ---------- Chapter 10: Chatting with a Customer ----------
      { id: 69, chapter: 'Chatting with a Customer', speaker: 'SAM',
        agent: 'Oh, here comes Mrs. Chen, our most opinionated regular. She has strong feelings about everything.',
        user: 'Mrs. Chen! I have not seen her in weeks. She has the best stories.',
        keywords: ['stories', 'weeks'] },
      { id: 70, chapter: 'Chatting with a Customer', speaker: 'SAM',
        agent: 'She was traveling, I think. She just ordered her usual — black coffee, no nonsense.',
        user: 'No nonsense is right. Mrs. Chen does not have time for fussy latte art.',
        keywords: ['nonsense', 'fussy'] },
      { id: 71, chapter: 'Chatting with a Customer', speaker: 'SAM',
        agent: 'She is waving you over! I think she wants to join your philosophical coffee discussion.',
        user: 'I would love that. Mrs. Chen, come share our corner of wisdom and caffeine.',
        keywords: ['caffeine', 'corner'] },
      { id: 72, chapter: 'Chatting with a Customer', speaker: 'SAM',
        agent: 'She says your generation overthinks coffee. In her day, it was just strong and hot.',
        user: 'She has a point. We turned a simple beverage into an elaborate art form.',
        keywords: ['elaborate', 'beverage'] },
      { id: 73, chapter: 'Chatting with a Customer', speaker: 'SAM',
        agent: 'But there is beauty in the elaboration, do you not think? Craft matters, even in simplicity.',
        user: 'Absolutely. Though Mrs. Chen would argue that simplicity itself is the highest craft.',
        keywords: ['absolutely', 'simplicity'] },
      { id: 74, chapter: 'Chatting with a Customer', speaker: 'SAM',
        agent: 'She is nodding! I think you just earned her respect, which is no small achievement.',
        user: 'Earning Mrs. Chen’s respect feels like winning a prestigious lifetime achievement award.',
        keywords: ['prestigious', 'achievement'] },
      { id: 75, chapter: 'Chatting with a Customer', speaker: 'SAM',
        agent: 'It really does. She is now telling me about coffee houses in Taipei from forty years ago.',
        user: 'Forty years ago! I bet those places had incredible character and even better stories.',
        keywords: ['incredible', 'character'] },
      { id: 76, chapter: 'Chatting with a Customer', speaker: 'SAM',
        agent: 'She says the best conversations happen over simple black coffee, no distractions needed.',
        user: 'Wise words. Next time I will try her approach — just black, no complications.',
        keywords: ['complications', 'approach'] },
      // ---------- Chapter 11: Wrapping Up ----------
      { id: 77, chapter: 'Wrapping Up', speaker: 'SAM',
        agent: 'I hate to interrupt this wonderful gathering, but I notice you keep glancing at the clock.',
        user: 'You caught me. My meeting starts in five minutes, and I am not ready.',
        keywords: ['meeting', 'minutes'] },
      { id: 78, chapter: 'Wrapping Up', speaker: 'SAM',
        agent: 'Five minutes! Then you should definitely take that lavender cappuccino to go, my friend.',
        user: 'Good idea. Though I am worried the lid will ruin your beautiful latte art.',
        keywords: ['beautiful', 'worried'] },
      { id: 79, chapter: 'Wrapping Up', speaker: 'SAM',
        agent: 'Art is fleeting, but the memory lasts. Besides, I can make you another masterpiece tomorrow.',
        user: 'Tomorrow? You assume I will be back. You know me too well already, Sam.',
        keywords: ['tomorrow', 'assume'] },
      { id: 80, chapter: 'Wrapping Up', speaker: 'SAM',
        agent: 'Three-year regulars always come back. It is practically a law of nature at this point.',
        user: 'A law of nature indeed. This place is an essential part of my routine.',
        keywords: ['essential', 'routine'] },
      // ---------- Chapter 12: Leaving ----------
      { id: 81, chapter: 'Leaving', speaker: 'SAM',
        agent: 'Here is your to-go cup. And I threw in a complimentary biscotti for the road.',
        user: 'A complimentary biscotti? You are spoiling me, Sam. This is above and beyond.',
        keywords: ['complimentary', 'spoiling'] },
      { id: 82, chapter: 'Leaving', speaker: 'SAM',
        agent: 'You deserve it after surviving Monday morning and my oat milk mishap with such grace.',
        user: 'Surviving is the right word. Though today felt more like thriving, honestly.',
        keywords: ['surviving', 'thriving'] },
      { id: 83, chapter: 'Leaving', speaker: 'SAM',
        agent: 'Thriving on a Monday — that is the real achievement. Go conquer those emails now!',
        user: 'I will, armed with lavender calm and your excellent coffee. Wish me luck!',
        keywords: ['excellent', 'lavender'] },
      { id: 84, chapter: 'Leaving', speaker: 'SAM',
        agent: 'Good luck, Alex! And remember — bitterness is a choice, but so is sweetness.',
        user: 'Profound words to end on. See you tomorrow, Sam. Keep the magic brewing!',
        keywords: ['profound', 'brewing'] },
      { id: 85, chapter: 'Leaving', speaker: 'SAM',
        agent: 'I will! And Alex — thanks for making my second week here absolutely unforgettable.',
        user: 'Thanks for the best Monday coffee in months. You are a natural.',
        keywords: ['natural', 'coffee'] },
      { id: 86, chapter: 'Leaving', speaker: 'SAM',
        agent: 'That means the world coming from a three-year regular. Now go, before you are late!',
        user: 'Going! Though part of me wishes I could stay in this cozy corner forever.',
        keywords: ['forever', 'corner'] },
      { id: 87, chapter: 'Leaving', speaker: 'SAM',
        agent: 'Forever is a long time, but tomorrow morning works perfectly. Same time, same place?',
        user: 'Same time, same place. Though tomorrow I might actually try something simple.',
        keywords: ['something', 'actually'] },
      { id: 88, chapter: 'Leaving', speaker: 'SAM',
        agent: 'Simple? From adventurous Alex? I will believe it when I see it. Have a great day!',
        user: 'You too, Sam! Remember — Mrs. Chen is always right about black coffee.',
        keywords: ['remember', 'coffee'] },
    ]
  };
})();
